/**
 * Dashboard Test Cases
 * Real-world dashboard UI configurations
 */

import type { UITree, UIElement } from '@json-render/core';
import type { TestCase } from './test-cases';

function el(key: string, type: string, props: Record<string, unknown>, children?: string[]): UIElement {
  return { key, type, props, children };
}

export const dashboardTestCases: TestCase[] = [
  {
    id: 'dashboard-analytics',
    name: 'Analytics Dashboard',
    description: 'Website analytics with stats, charts, tables, and filters',
    category: 'dashboards',
    tags: ['dashboard', 'analytics', 'stats', 'charts', 'metrics'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'filters', 'stats', 'charts', 'table']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'actions']),
        title: el('title', 'Heading', { level: '1', text: 'Analytics Dashboard' }),
        actions: el('actions', 'Row', { gap: 'sm' }, ['exportBtn', 'refreshBtn']),
        exportBtn: el('exportBtn', 'Button', { label: 'Export', variant: 'outline' }),
        refreshBtn: el('refreshBtn', 'Button', { label: 'Refresh', variant: 'solid' }),
        filters: el('filters', 'Card', { variant: 'outlined' }, ['filtersContent']),
        filtersContent: el('filtersContent', 'Row', { gap: 'md', align: 'end' }, ['dateRange', 'channelFilter', 'applyBtn']),
        dateRange: el('dateRange', 'Select', { label: 'Date Range', options: [{ value: '7d', label: 'Last 7 Days' }, { value: '30d', label: 'Last 30 Days' }, { value: '90d', label: 'Last 90 Days' }] }),
        channelFilter: el('channelFilter', 'Select', { label: 'Channel', options: [{ value: 'all', label: 'All Channels' }, { value: 'organic', label: 'Organic' }, { value: 'paid', label: 'Paid' }, { value: 'social', label: 'Social' }] }),
        applyBtn: el('applyBtn', 'Button', { label: 'Apply', variant: 'solid' }),
        stats: el('stats', 'Grid', { columns: 4, gap: 'md' }, ['stat1', 'stat2', 'stat3', 'stat4']),
        stat1: el('stat1', 'Card', { variant: 'elevated' }, ['metric1']),
        stat2: el('stat2', 'Card', { variant: 'elevated' }, ['metric2']),
        stat3: el('stat3', 'Card', { variant: 'elevated' }, ['metric3']),
        stat4: el('stat4', 'Card', { variant: 'elevated' }, ['metric4']),
        metric1: el('metric1', 'Metric', { label: 'Page Views', value: '2.4M', change: '+12.5%', changeType: 'positive' }),
        metric2: el('metric2', 'Metric', { label: 'Unique Visitors', value: '847K', change: '+8.2%', changeType: 'positive' }),
        metric3: el('metric3', 'Metric', { label: 'Bounce Rate', value: '42.3%', change: '-3.1%', changeType: 'positive' }),
        metric4: el('metric4', 'Metric', { label: 'Avg. Session', value: '4m 23s', change: '+15.4%', changeType: 'positive' }),
        charts: el('charts', 'Grid', { columns: 2, gap: 'lg' }, ['trafficChart', 'sourceChart']),
        trafficChart: el('trafficChart', 'Card', { title: 'Traffic Over Time' }, ['trafficPlaceholder']),
        sourceChart: el('sourceChart', 'Card', { title: 'Traffic by Source' }, ['sourcePlaceholder']),
        trafficPlaceholder: el('trafficPlaceholder', 'Text', { content: '[Line Chart: Daily traffic over selected period]', color: 'muted', align: 'center' }),
        sourcePlaceholder: el('sourcePlaceholder', 'Text', { content: '[Pie Chart: Organic 45%, Direct 30%, Social 15%, Referral 10%]', color: 'muted', align: 'center' }),
        table: el('table', 'Card', { title: 'Top Pages' }, ['tableContent']),
        tableContent: el('tableContent', 'Column', { gap: 'sm' }, ['tableHeader', 'tableRow1', 'tableRow2', 'tableRow3', 'tableRow4', 'tableRow5']),
        tableHeader: el('tableHeader', 'Row', { gap: 'md' }, ['thPage', 'thViews', 'thBounce', 'thTime']),
        thPage: el('thPage', 'Text', { content: 'Page', size: 'sm' }),
        thViews: el('thViews', 'Text', { content: 'Views', size: 'sm' }),
        thBounce: el('thBounce', 'Text', { content: 'Bounce Rate', size: 'sm' }),
        thTime: el('thTime', 'Text', { content: 'Avg. Time', size: 'sm' }),
        tableRow1: el('tableRow1', 'Row', { gap: 'md' }, ['tr1Page', 'tr1Views', 'tr1Bounce', 'tr1Time']),
        tableRow2: el('tableRow2', 'Row', { gap: 'md' }, ['tr2Page', 'tr2Views', 'tr2Bounce', 'tr2Time']),
        tableRow3: el('tableRow3', 'Row', { gap: 'md' }, ['tr3Page', 'tr3Views', 'tr3Bounce', 'tr3Time']),
        tableRow4: el('tableRow4', 'Row', { gap: 'md' }, ['tr4Page', 'tr4Views', 'tr4Bounce', 'tr4Time']),
        tableRow5: el('tableRow5', 'Row', { gap: 'md' }, ['tr5Page', 'tr5Views', 'tr5Bounce', 'tr5Time']),
        tr1Page: el('tr1Page', 'Text', { content: '/home' }),
        tr1Views: el('tr1Views', 'Text', { content: '524,892' }),
        tr1Bounce: el('tr1Bounce', 'Text', { content: '38.2%' }),
        tr1Time: el('tr1Time', 'Text', { content: '3m 45s' }),
        tr2Page: el('tr2Page', 'Text', { content: '/products' }),
        tr2Views: el('tr2Views', 'Text', { content: '312,456' }),
        tr2Bounce: el('tr2Bounce', 'Text', { content: '42.1%' }),
        tr2Time: el('tr2Time', 'Text', { content: '5m 12s' }),
        tr3Page: el('tr3Page', 'Text', { content: '/pricing' }),
        tr3Views: el('tr3Views', 'Text', { content: '198,234' }),
        tr3Bounce: el('tr3Bounce', 'Text', { content: '35.8%' }),
        tr3Time: el('tr3Time', 'Text', { content: '4m 28s' }),
        tr4Page: el('tr4Page', 'Text', { content: '/about' }),
        tr4Views: el('tr4Views', 'Text', { content: '156,789' }),
        tr4Bounce: el('tr4Bounce', 'Text', { content: '52.3%' }),
        tr4Time: el('tr4Time', 'Text', { content: '2m 15s' }),
        tr5Page: el('tr5Page', 'Text', { content: '/blog' }),
        tr5Views: el('tr5Views', 'Text', { content: '134,567' }),
        tr5Bounce: el('tr5Bounce', 'Text', { content: '28.9%' }),
        tr5Time: el('tr5Time', 'Text', { content: '6m 42s' }),
      },
    },
  },
  {
    id: 'dashboard-project',
    name: 'Project Management Dashboard',
    description: 'Project tracking with task lists, progress, and team view',
    category: 'dashboards',
    tags: ['dashboard', 'project', 'tasks', 'kanban', 'team'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'stats', 'content']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['titleSection', 'headerActions']),
        titleSection: el('titleSection', 'Column', { gap: 'xs' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '1', text: 'Project Alpha' }),
        subtitle: el('subtitle', 'Text', { content: 'Website Redesign | Due: March 15, 2024', color: 'muted' }),
        headerActions: el('headerActions', 'Row', { gap: 'sm' }, ['addTaskBtn', 'settingsBtn']),
        addTaskBtn: el('addTaskBtn', 'Button', { label: 'Add Task', variant: 'solid' }),
        settingsBtn: el('settingsBtn', 'Button', { label: 'Settings', variant: 'outline' }),
        stats: el('stats', 'Grid', { columns: 4, gap: 'md' }, ['statTotal', 'statProgress', 'statCompleted', 'statOverdue']),
        statTotal: el('statTotal', 'Card', { variant: 'outlined' }, ['metricTotal']),
        statProgress: el('statProgress', 'Card', { variant: 'outlined' }, ['metricProgress']),
        statCompleted: el('statCompleted', 'Card', { variant: 'outlined' }, ['metricCompleted']),
        statOverdue: el('statOverdue', 'Card', { variant: 'outlined' }, ['metricOverdue']),
        metricTotal: el('metricTotal', 'Metric', { label: 'Total Tasks', value: '48' }),
        metricProgress: el('metricProgress', 'Metric', { label: 'In Progress', value: '12' }),
        metricCompleted: el('metricCompleted', 'Metric', { label: 'Completed', value: '32' }),
        metricOverdue: el('metricOverdue', 'Metric', { label: 'Overdue', value: '4', change: 'Needs attention', changeType: 'negative' }),
        content: el('content', 'Row', { gap: 'lg' }, ['tasksSection', 'teamSection']),
        tasksSection: el('tasksSection', 'Column', { gap: 'md' }, ['tasksTodo', 'tasksInProgress', 'tasksDone']),
        tasksTodo: el('tasksTodo', 'Card', { title: 'To Do (8)' }, ['todoList']),
        tasksInProgress: el('tasksInProgress', 'Card', { title: 'In Progress (12)' }, ['progressList']),
        tasksDone: el('tasksDone', 'Card', { title: 'Done (32)' }, ['doneList']),
        todoList: el('todoList', 'Column', { gap: 'sm' }, ['todo1', 'todo2', 'todo3']),
        todo1: el('todo1', 'Card', { variant: 'outlined' }, ['todo1Content']),
        todo2: el('todo2', 'Card', { variant: 'outlined' }, ['todo2Content']),
        todo3: el('todo3', 'Card', { variant: 'outlined' }, ['todo3Content']),
        todo1Content: el('todo1Content', 'Column', { gap: 'xs' }, ['todo1Title', 'todo1Meta']),
        todo2Content: el('todo2Content', 'Column', { gap: 'xs' }, ['todo2Title', 'todo2Meta']),
        todo3Content: el('todo3Content', 'Column', { gap: 'xs' }, ['todo3Title', 'todo3Meta']),
        todo1Title: el('todo1Title', 'Text', { content: 'Design homepage mockup' }),
        todo1Meta: el('todo1Meta', 'Row', { gap: 'sm' }, ['todo1Priority', 'todo1Due']),
        todo1Priority: el('todo1Priority', 'Badge', { text: 'High', color: 'error' }),
        todo1Due: el('todo1Due', 'Text', { content: 'Due Feb 28', color: 'muted', size: 'sm' }),
        todo2Title: el('todo2Title', 'Text', { content: 'Write API documentation' }),
        todo2Meta: el('todo2Meta', 'Row', { gap: 'sm' }, ['todo2Priority', 'todo2Due']),
        todo2Priority: el('todo2Priority', 'Badge', { text: 'Medium', color: 'warning' }),
        todo2Due: el('todo2Due', 'Text', { content: 'Due Mar 5', color: 'muted', size: 'sm' }),
        todo3Title: el('todo3Title', 'Text', { content: 'Set up CI/CD pipeline' }),
        todo3Meta: el('todo3Meta', 'Row', { gap: 'sm' }, ['todo3Priority', 'todo3Due']),
        todo3Priority: el('todo3Priority', 'Badge', { text: 'Low', variant: 'outline' }),
        todo3Due: el('todo3Due', 'Text', { content: 'Due Mar 10', color: 'muted', size: 'sm' }),
        progressList: el('progressList', 'Column', { gap: 'sm' }, ['prog1', 'prog2']),
        prog1: el('prog1', 'Card', { variant: 'outlined' }, ['prog1Content']),
        prog2: el('prog2', 'Card', { variant: 'outlined' }, ['prog2Content']),
        prog1Content: el('prog1Content', 'Column', { gap: 'xs' }, ['prog1Title', 'prog1Bar', 'prog1Meta']),
        prog2Content: el('prog2Content', 'Column', { gap: 'xs' }, ['prog2Title', 'prog2Bar', 'prog2Meta']),
        prog1Title: el('prog1Title', 'Text', { content: 'Implement user auth' }),
        prog1Bar: el('prog1Bar', 'Progress', { value: 75, max: 100, showValue: true }),
        prog1Meta: el('prog1Meta', 'Row', { gap: 'sm', align: 'center' }, ['prog1Assignee', 'prog1Due']),
        prog1Assignee: el('prog1Assignee', 'Avatar', { name: 'John D.', size: 'sm' }),
        prog1Due: el('prog1Due', 'Text', { content: 'Due Mar 1', color: 'muted', size: 'sm' }),
        prog2Title: el('prog2Title', 'Text', { content: 'Database migration' }),
        prog2Bar: el('prog2Bar', 'Progress', { value: 40, max: 100, showValue: true }),
        prog2Meta: el('prog2Meta', 'Row', { gap: 'sm', align: 'center' }, ['prog2Assignee', 'prog2Due']),
        prog2Assignee: el('prog2Assignee', 'Avatar', { name: 'Sarah M.', size: 'sm' }),
        prog2Due: el('prog2Due', 'Text', { content: 'Due Mar 3', color: 'muted', size: 'sm' }),
        doneList: el('doneList', 'Column', { gap: 'sm' }, ['done1', 'done2']),
        done1: el('done1', 'Card', { variant: 'outlined' }, ['done1Content']),
        done2: el('done2', 'Card', { variant: 'outlined' }, ['done2Content']),
        done1Content: el('done1Content', 'Row', { gap: 'sm', align: 'center' }, ['done1Check', 'done1Title']),
        done2Content: el('done2Content', 'Row', { gap: 'sm', align: 'center' }, ['done2Check', 'done2Title']),
        done1Check: el('done1Check', 'Badge', { text: '✓', color: 'success' }),
        done1Title: el('done1Title', 'Text', { content: 'Set up project repository' }),
        done2Check: el('done2Check', 'Badge', { text: '✓', color: 'success' }),
        done2Title: el('done2Title', 'Text', { content: 'Create wireframes' }),
        teamSection: el('teamSection', 'Card', { title: 'Team Members' }, ['teamList']),
        teamList: el('teamList', 'Column', { gap: 'md' }, ['member1', 'member2', 'member3']),
        member1: el('member1', 'Row', { gap: 'md', align: 'center' }, ['member1Avatar', 'member1Info']),
        member2: el('member2', 'Row', { gap: 'md', align: 'center' }, ['member2Avatar', 'member2Info']),
        member3: el('member3', 'Row', { gap: 'md', align: 'center' }, ['member3Avatar', 'member3Info']),
        member1Avatar: el('member1Avatar', 'Avatar', { name: 'John Doe', size: 'md' }),
        member1Info: el('member1Info', 'Column', { gap: 'xs' }, ['member1Name', 'member1Role', 'member1Tasks']),
        member1Name: el('member1Name', 'Text', { content: 'John Doe' }),
        member1Role: el('member1Role', 'Text', { content: 'Lead Developer', color: 'muted', size: 'sm' }),
        member1Tasks: el('member1Tasks', 'Text', { content: '5 tasks assigned', color: 'muted', size: 'sm' }),
        member2Avatar: el('member2Avatar', 'Avatar', { name: 'Sarah Miller', size: 'md' }),
        member2Info: el('member2Info', 'Column', { gap: 'xs' }, ['member2Name', 'member2Role', 'member2Tasks']),
        member2Name: el('member2Name', 'Text', { content: 'Sarah Miller' }),
        member2Role: el('member2Role', 'Text', { content: 'UI/UX Designer', color: 'muted', size: 'sm' }),
        member2Tasks: el('member2Tasks', 'Text', { content: '3 tasks assigned', color: 'muted', size: 'sm' }),
        member3Avatar: el('member3Avatar', 'Avatar', { name: 'Mike Chen', size: 'md' }),
        member3Info: el('member3Info', 'Column', { gap: 'xs' }, ['member3Name', 'member3Role', 'member3Tasks']),
        member3Name: el('member3Name', 'Text', { content: 'Mike Chen' }),
        member3Role: el('member3Role', 'Text', { content: 'Backend Developer', color: 'muted', size: 'sm' }),
        member3Tasks: el('member3Tasks', 'Text', { content: '4 tasks assigned', color: 'muted', size: 'sm' }),
      },
    },
  },
  {
    id: 'dashboard-sales',
    name: 'Sales Dashboard',
    description: 'Sales metrics with KPIs, pipeline, and recent deals',
    category: 'dashboards',
    tags: ['dashboard', 'sales', 'crm', 'pipeline', 'revenue'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'kpis', 'content']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'periodSelect']),
        title: el('title', 'Heading', { level: '1', text: 'Sales Dashboard' }),
        periodSelect: el('periodSelect', 'Select', { options: [{ value: 'mtd', label: 'Month to Date' }, { value: 'qtd', label: 'Quarter to Date' }, { value: 'ytd', label: 'Year to Date' }] }),
        kpis: el('kpis', 'Grid', { columns: 4, gap: 'md' }, ['kpi1', 'kpi2', 'kpi3', 'kpi4']),
        kpi1: el('kpi1', 'Card', { variant: 'elevated' }, ['kpiRevenue']),
        kpi2: el('kpi2', 'Card', { variant: 'elevated' }, ['kpiDeals']),
        kpi3: el('kpi3', 'Card', { variant: 'elevated' }, ['kpiAvgDeal']),
        kpi4: el('kpi4', 'Card', { variant: 'elevated' }, ['kpiWinRate']),
        kpiRevenue: el('kpiRevenue', 'Metric', { label: 'Total Revenue', value: '$1.24M', change: '+18.5%', changeType: 'positive' }),
        kpiDeals: el('kpiDeals', 'Metric', { label: 'Closed Deals', value: '47', change: '+12', changeType: 'positive' }),
        kpiAvgDeal: el('kpiAvgDeal', 'Metric', { label: 'Avg. Deal Size', value: '$26.4K', change: '+5.2%', changeType: 'positive' }),
        kpiWinRate: el('kpiWinRate', 'Metric', { label: 'Win Rate', value: '34%', change: '-2.1%', changeType: 'negative' }),
        content: el('content', 'Grid', { columns: 2, gap: 'lg' }, ['pipeline', 'recentDeals']),
        pipeline: el('pipeline', 'Card', { title: 'Sales Pipeline' }, ['pipelineContent']),
        pipelineContent: el('pipelineContent', 'Column', { gap: 'md' }, ['pipeStage1', 'pipeStage2', 'pipeStage3', 'pipeStage4']),
        pipeStage1: el('pipeStage1', 'Column', { gap: 'xs' }, ['stage1Header', 'stage1Bar']),
        pipeStage2: el('pipeStage2', 'Column', { gap: 'xs' }, ['stage2Header', 'stage2Bar']),
        pipeStage3: el('pipeStage3', 'Column', { gap: 'xs' }, ['stage3Header', 'stage3Bar']),
        pipeStage4: el('pipeStage4', 'Column', { gap: 'xs' }, ['stage4Header', 'stage4Bar']),
        stage1Header: el('stage1Header', 'Row', { justify: 'between' }, ['stage1Name', 'stage1Value']),
        stage1Name: el('stage1Name', 'Text', { content: 'Qualified' }),
        stage1Value: el('stage1Value', 'Text', { content: '$2.1M (45 deals)' }),
        stage1Bar: el('stage1Bar', 'Progress', { value: 100, max: 100, color: 'info' }),
        stage2Header: el('stage2Header', 'Row', { justify: 'between' }, ['stage2Name', 'stage2Value']),
        stage2Name: el('stage2Name', 'Text', { content: 'Proposal' }),
        stage2Value: el('stage2Value', 'Text', { content: '$1.5M (28 deals)' }),
        stage2Bar: el('stage2Bar', 'Progress', { value: 71, max: 100, color: 'info' }),
        stage3Header: el('stage3Header', 'Row', { justify: 'between' }, ['stage3Name', 'stage3Value']),
        stage3Name: el('stage3Name', 'Text', { content: 'Negotiation' }),
        stage3Value: el('stage3Value', 'Text', { content: '$890K (15 deals)' }),
        stage3Bar: el('stage3Bar', 'Progress', { value: 42, max: 100, color: 'warning' }),
        stage4Header: el('stage4Header', 'Row', { justify: 'between' }, ['stage4Name', 'stage4Value']),
        stage4Name: el('stage4Name', 'Text', { content: 'Closing' }),
        stage4Value: el('stage4Value', 'Text', { content: '$450K (8 deals)' }),
        stage4Bar: el('stage4Bar', 'Progress', { value: 21, max: 100, color: 'success' }),
        recentDeals: el('recentDeals', 'Card', { title: 'Recent Deals' }, ['dealsList']),
        dealsList: el('dealsList', 'Column', { gap: 'sm' }, ['deal1', 'deal2', 'deal3', 'deal4']),
        deal1: el('deal1', 'Row', { justify: 'between', align: 'center' }, ['deal1Info', 'deal1Amount']),
        deal2: el('deal2', 'Row', { justify: 'between', align: 'center' }, ['deal2Info', 'deal2Amount']),
        deal3: el('deal3', 'Row', { justify: 'between', align: 'center' }, ['deal3Info', 'deal3Amount']),
        deal4: el('deal4', 'Row', { justify: 'between', align: 'center' }, ['deal4Info', 'deal4Amount']),
        deal1Info: el('deal1Info', 'Column', { gap: 'xs' }, ['deal1Company', 'deal1Meta']),
        deal1Company: el('deal1Company', 'Text', { content: 'Acme Corporation' }),
        deal1Meta: el('deal1Meta', 'Row', { gap: 'sm' }, ['deal1Status', 'deal1Date']),
        deal1Status: el('deal1Status', 'Badge', { text: 'Won', color: 'success' }),
        deal1Date: el('deal1Date', 'Text', { content: 'Today', color: 'muted', size: 'sm' }),
        deal1Amount: el('deal1Amount', 'Text', { content: '$85,000' }),
        deal2Info: el('deal2Info', 'Column', { gap: 'xs' }, ['deal2Company', 'deal2Meta']),
        deal2Company: el('deal2Company', 'Text', { content: 'TechStart Inc.' }),
        deal2Meta: el('deal2Meta', 'Row', { gap: 'sm' }, ['deal2Status', 'deal2Date']),
        deal2Status: el('deal2Status', 'Badge', { text: 'Won', color: 'success' }),
        deal2Date: el('deal2Date', 'Text', { content: 'Yesterday', color: 'muted', size: 'sm' }),
        deal2Amount: el('deal2Amount', 'Text', { content: '$42,500' }),
        deal3Info: el('deal3Info', 'Column', { gap: 'xs' }, ['deal3Company', 'deal3Meta']),
        deal3Company: el('deal3Company', 'Text', { content: 'Global Systems' }),
        deal3Meta: el('deal3Meta', 'Row', { gap: 'sm' }, ['deal3Status', 'deal3Date']),
        deal3Status: el('deal3Status', 'Badge', { text: 'Lost', color: 'error' }),
        deal3Date: el('deal3Date', 'Text', { content: '2 days ago', color: 'muted', size: 'sm' }),
        deal3Amount: el('deal3Amount', 'Text', { content: '$120,000', color: 'muted' }),
        deal4Info: el('deal4Info', 'Column', { gap: 'xs' }, ['deal4Company', 'deal4Meta']),
        deal4Company: el('deal4Company', 'Text', { content: 'MegaCorp Ltd.' }),
        deal4Meta: el('deal4Meta', 'Row', { gap: 'sm' }, ['deal4Status', 'deal4Date']),
        deal4Status: el('deal4Status', 'Badge', { text: 'Negotiation', color: 'warning' }),
        deal4Date: el('deal4Date', 'Text', { content: 'In progress', color: 'muted', size: 'sm' }),
        deal4Amount: el('deal4Amount', 'Text', { content: '$250,000' }),
      },
    },
  },
  {
    id: 'dashboard-user-admin',
    name: 'User Admin Panel',
    description: 'User management with table, filters, and bulk actions',
    category: 'dashboards',
    tags: ['dashboard', 'admin', 'users', 'management', 'table'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'filters', 'userTable', 'pagination']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'addUserBtn']),
        title: el('title', 'Heading', { level: '1', text: 'User Management' }),
        addUserBtn: el('addUserBtn', 'Button', { label: 'Add User', variant: 'solid' }),
        filters: el('filters', 'Card', { variant: 'outlined' }, ['filterContent']),
        filterContent: el('filterContent', 'Row', { gap: 'md', align: 'end' }, ['searchInput', 'roleFilter', 'statusFilter', 'searchBtn']),
        searchInput: el('searchInput', 'Input', { label: 'Search', placeholder: 'Search users...' }),
        roleFilter: el('roleFilter', 'Select', { label: 'Role', options: [{ value: 'all', label: 'All Roles' }, { value: 'admin', label: 'Admin' }, { value: 'editor', label: 'Editor' }, { value: 'viewer', label: 'Viewer' }] }),
        statusFilter: el('statusFilter', 'Select', { label: 'Status', options: [{ value: 'all', label: 'All Status' }, { value: 'active', label: 'Active' }, { value: 'inactive', label: 'Inactive' }, { value: 'pending', label: 'Pending' }] }),
        searchBtn: el('searchBtn', 'Button', { label: 'Search', variant: 'solid' }),
        userTable: el('userTable', 'Card', {}, ['tableContent']),
        tableContent: el('tableContent', 'Column', { gap: 'none' }, ['tableHeader', 'tableBody']),
        tableHeader: el('tableHeader', 'Row', { gap: 'md' }, ['thCheck', 'thUser', 'thEmail', 'thRole', 'thStatus', 'thJoined', 'thActions']),
        thCheck: el('thCheck', 'Checkbox', {}),
        thUser: el('thUser', 'Text', { content: 'User', size: 'sm' }),
        thEmail: el('thEmail', 'Text', { content: 'Email', size: 'sm' }),
        thRole: el('thRole', 'Text', { content: 'Role', size: 'sm' }),
        thStatus: el('thStatus', 'Text', { content: 'Status', size: 'sm' }),
        thJoined: el('thJoined', 'Text', { content: 'Joined', size: 'sm' }),
        thActions: el('thActions', 'Text', { content: 'Actions', size: 'sm' }),
        tableBody: el('tableBody', 'Column', { gap: 'sm' }, ['userRow1', 'userRow2', 'userRow3', 'userRow4', 'userRow5']),
        userRow1: el('userRow1', 'Row', { gap: 'md', align: 'center' }, ['u1Check', 'u1User', 'u1Email', 'u1Role', 'u1Status', 'u1Joined', 'u1Actions']),
        userRow2: el('userRow2', 'Row', { gap: 'md', align: 'center' }, ['u2Check', 'u2User', 'u2Email', 'u2Role', 'u2Status', 'u2Joined', 'u2Actions']),
        userRow3: el('userRow3', 'Row', { gap: 'md', align: 'center' }, ['u3Check', 'u3User', 'u3Email', 'u3Role', 'u3Status', 'u3Joined', 'u3Actions']),
        userRow4: el('userRow4', 'Row', { gap: 'md', align: 'center' }, ['u4Check', 'u4User', 'u4Email', 'u4Role', 'u4Status', 'u4Joined', 'u4Actions']),
        userRow5: el('userRow5', 'Row', { gap: 'md', align: 'center' }, ['u5Check', 'u5User', 'u5Email', 'u5Role', 'u5Status', 'u5Joined', 'u5Actions']),
        u1Check: el('u1Check', 'Checkbox', {}),
        u1User: el('u1User', 'Row', { gap: 'sm', align: 'center' }, ['u1Avatar', 'u1Name']),
        u1Avatar: el('u1Avatar', 'Avatar', { name: 'John Doe', size: 'sm' }),
        u1Name: el('u1Name', 'Text', { content: 'John Doe' }),
        u1Email: el('u1Email', 'Text', { content: 'john@example.com' }),
        u1Role: el('u1Role', 'Badge', { text: 'Admin', color: 'info' }),
        u1Status: el('u1Status', 'Badge', { text: 'Active', color: 'success' }),
        u1Joined: el('u1Joined', 'Text', { content: 'Jan 15, 2024' }),
        u1Actions: el('u1Actions', 'Row', { gap: 'xs' }, ['u1Edit', 'u1Delete']),
        u1Edit: el('u1Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        u1Delete: el('u1Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
        u2Check: el('u2Check', 'Checkbox', {}),
        u2User: el('u2User', 'Row', { gap: 'sm', align: 'center' }, ['u2Avatar', 'u2Name']),
        u2Avatar: el('u2Avatar', 'Avatar', { name: 'Jane Smith', size: 'sm' }),
        u2Name: el('u2Name', 'Text', { content: 'Jane Smith' }),
        u2Email: el('u2Email', 'Text', { content: 'jane@example.com' }),
        u2Role: el('u2Role', 'Badge', { text: 'Editor', variant: 'outline' }),
        u2Status: el('u2Status', 'Badge', { text: 'Active', color: 'success' }),
        u2Joined: el('u2Joined', 'Text', { content: 'Jan 20, 2024' }),
        u2Actions: el('u2Actions', 'Row', { gap: 'xs' }, ['u2Edit', 'u2Delete']),
        u2Edit: el('u2Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        u2Delete: el('u2Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
        u3Check: el('u3Check', 'Checkbox', {}),
        u3User: el('u3User', 'Row', { gap: 'sm', align: 'center' }, ['u3Avatar', 'u3Name']),
        u3Avatar: el('u3Avatar', 'Avatar', { name: 'Bob Wilson', size: 'sm' }),
        u3Name: el('u3Name', 'Text', { content: 'Bob Wilson' }),
        u3Email: el('u3Email', 'Text', { content: 'bob@example.com' }),
        u3Role: el('u3Role', 'Badge', { text: 'Viewer', variant: 'outline' }),
        u3Status: el('u3Status', 'Badge', { text: 'Pending', color: 'warning' }),
        u3Joined: el('u3Joined', 'Text', { content: 'Feb 1, 2024' }),
        u3Actions: el('u3Actions', 'Row', { gap: 'xs' }, ['u3Edit', 'u3Delete']),
        u3Edit: el('u3Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        u3Delete: el('u3Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
        u4Check: el('u4Check', 'Checkbox', {}),
        u4User: el('u4User', 'Row', { gap: 'sm', align: 'center' }, ['u4Avatar', 'u4Name']),
        u4Avatar: el('u4Avatar', 'Avatar', { name: 'Alice Brown', size: 'sm' }),
        u4Name: el('u4Name', 'Text', { content: 'Alice Brown' }),
        u4Email: el('u4Email', 'Text', { content: 'alice@example.com' }),
        u4Role: el('u4Role', 'Badge', { text: 'Editor', variant: 'outline' }),
        u4Status: el('u4Status', 'Badge', { text: 'Inactive', color: 'error' }),
        u4Joined: el('u4Joined', 'Text', { content: 'Dec 10, 2023' }),
        u4Actions: el('u4Actions', 'Row', { gap: 'xs' }, ['u4Edit', 'u4Delete']),
        u4Edit: el('u4Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        u4Delete: el('u4Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
        u5Check: el('u5Check', 'Checkbox', {}),
        u5User: el('u5User', 'Row', { gap: 'sm', align: 'center' }, ['u5Avatar', 'u5Name']),
        u5Avatar: el('u5Avatar', 'Avatar', { name: 'Charlie Davis', size: 'sm' }),
        u5Name: el('u5Name', 'Text', { content: 'Charlie Davis' }),
        u5Email: el('u5Email', 'Text', { content: 'charlie@example.com' }),
        u5Role: el('u5Role', 'Badge', { text: 'Admin', color: 'info' }),
        u5Status: el('u5Status', 'Badge', { text: 'Active', color: 'success' }),
        u5Joined: el('u5Joined', 'Text', { content: 'Nov 5, 2023' }),
        u5Actions: el('u5Actions', 'Row', { gap: 'xs' }, ['u5Edit', 'u5Delete']),
        u5Edit: el('u5Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        u5Delete: el('u5Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
        pagination: el('pagination', 'Row', { justify: 'between', align: 'center' }, ['pageInfo', 'pageControls']),
        pageInfo: el('pageInfo', 'Text', { content: 'Showing 1-5 of 127 users', color: 'muted' }),
        pageControls: el('pageControls', 'Row', { gap: 'sm' }, ['prevBtn', 'page1', 'page2', 'page3', 'nextBtn']),
        prevBtn: el('prevBtn', 'Button', { label: 'Previous', variant: 'outline', disabled: true }),
        page1: el('page1', 'Button', { label: '1', variant: 'solid' }),
        page2: el('page2', 'Button', { label: '2', variant: 'outline' }),
        page3: el('page3', 'Button', { label: '3', variant: 'outline' }),
        nextBtn: el('nextBtn', 'Button', { label: 'Next', variant: 'outline' }),
      },
    },
  },
  {
    id: 'dashboard-financial',
    name: 'Financial Dashboard',
    description: 'Financial overview with revenue, expenses, and trends',
    category: 'dashboards',
    tags: ['dashboard', 'finance', 'revenue', 'expenses', 'accounting'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'summary', 'charts', 'transactions']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['titleSection', 'headerActions']),
        titleSection: el('titleSection', 'Column', { gap: 'xs' }, ['title', 'lastUpdated']),
        title: el('title', 'Heading', { level: '1', text: 'Financial Overview' }),
        lastUpdated: el('lastUpdated', 'Text', { content: 'Last updated: February 1, 2024', color: 'muted', size: 'sm' }),
        headerActions: el('headerActions', 'Row', { gap: 'sm' }, ['periodSelect', 'exportBtn']),
        periodSelect: el('periodSelect', 'Select', { options: [{ value: 'jan', label: 'January 2024' }, { value: 'q4', label: 'Q4 2023' }, { value: 'year', label: 'Full Year 2023' }] }),
        exportBtn: el('exportBtn', 'Button', { label: 'Export Report', variant: 'outline' }),
        summary: el('summary', 'Grid', { columns: 4, gap: 'md' }, ['sumRevenue', 'sumExpenses', 'sumProfit', 'sumCash']),
        sumRevenue: el('sumRevenue', 'Card', { variant: 'elevated' }, ['metricRevenue']),
        sumExpenses: el('sumExpenses', 'Card', { variant: 'elevated' }, ['metricExpenses']),
        sumProfit: el('sumProfit', 'Card', { variant: 'elevated' }, ['metricProfit']),
        sumCash: el('sumCash', 'Card', { variant: 'elevated' }, ['metricCash']),
        metricRevenue: el('metricRevenue', 'Metric', { label: 'Total Revenue', value: '$2.45M', change: '+23.5%', changeType: 'positive' }),
        metricExpenses: el('metricExpenses', 'Metric', { label: 'Total Expenses', value: '$1.82M', change: '+12.3%', changeType: 'negative' }),
        metricProfit: el('metricProfit', 'Metric', { label: 'Net Profit', value: '$630K', change: '+45.2%', changeType: 'positive' }),
        metricCash: el('metricCash', 'Metric', { label: 'Cash Flow', value: '$412K', change: '+8.7%', changeType: 'positive' }),
        charts: el('charts', 'Grid', { columns: 2, gap: 'lg' }, ['revenueChart', 'expenseBreakdown']),
        revenueChart: el('revenueChart', 'Card', { title: 'Revenue vs Expenses' }, ['revenueChartContent']),
        revenueChartContent: el('revenueChartContent', 'Column', { gap: 'md' }, ['chartPlaceholder', 'chartLegend']),
        chartPlaceholder: el('chartPlaceholder', 'Text', { content: '[Bar Chart: Monthly revenue and expenses comparison]', color: 'muted', align: 'center' }),
        chartLegend: el('chartLegend', 'Row', { gap: 'md', justify: 'center' }, ['legendRevenue', 'legendExpenses']),
        legendRevenue: el('legendRevenue', 'Row', { gap: 'xs', align: 'center' }, ['legendRevDot', 'legendRevText']),
        legendExpenses: el('legendExpenses', 'Row', { gap: 'xs', align: 'center' }, ['legendExpDot', 'legendExpText']),
        legendRevDot: el('legendRevDot', 'Badge', { text: '●', color: 'success' }),
        legendRevText: el('legendRevText', 'Text', { content: 'Revenue', size: 'sm' }),
        legendExpDot: el('legendExpDot', 'Badge', { text: '●', color: 'error' }),
        legendExpText: el('legendExpText', 'Text', { content: 'Expenses', size: 'sm' }),
        expenseBreakdown: el('expenseBreakdown', 'Card', { title: 'Expense Breakdown' }, ['expenseList']),
        expenseList: el('expenseList', 'Column', { gap: 'sm' }, ['exp1', 'exp2', 'exp3', 'exp4', 'exp5']),
        exp1: el('exp1', 'Column', { gap: 'xs' }, ['exp1Header', 'exp1Bar']),
        exp2: el('exp2', 'Column', { gap: 'xs' }, ['exp2Header', 'exp2Bar']),
        exp3: el('exp3', 'Column', { gap: 'xs' }, ['exp3Header', 'exp3Bar']),
        exp4: el('exp4', 'Column', { gap: 'xs' }, ['exp4Header', 'exp4Bar']),
        exp5: el('exp5', 'Column', { gap: 'xs' }, ['exp5Header', 'exp5Bar']),
        exp1Header: el('exp1Header', 'Row', { justify: 'between' }, ['exp1Name', 'exp1Amount']),
        exp1Name: el('exp1Name', 'Text', { content: 'Payroll' }),
        exp1Amount: el('exp1Amount', 'Text', { content: '$980,000 (54%)' }),
        exp1Bar: el('exp1Bar', 'Progress', { value: 54, max: 100 }),
        exp2Header: el('exp2Header', 'Row', { justify: 'between' }, ['exp2Name', 'exp2Amount']),
        exp2Name: el('exp2Name', 'Text', { content: 'Operations' }),
        exp2Amount: el('exp2Amount', 'Text', { content: '$340,000 (19%)' }),
        exp2Bar: el('exp2Bar', 'Progress', { value: 19, max: 100 }),
        exp3Header: el('exp3Header', 'Row', { justify: 'between' }, ['exp3Name', 'exp3Amount']),
        exp3Name: el('exp3Name', 'Text', { content: 'Marketing' }),
        exp3Amount: el('exp3Amount', 'Text', { content: '$250,000 (14%)' }),
        exp3Bar: el('exp3Bar', 'Progress', { value: 14, max: 100 }),
        exp4Header: el('exp4Header', 'Row', { justify: 'between' }, ['exp4Name', 'exp4Amount']),
        exp4Name: el('exp4Name', 'Text', { content: 'Technology' }),
        exp4Amount: el('exp4Amount', 'Text', { content: '$180,000 (10%)' }),
        exp4Bar: el('exp4Bar', 'Progress', { value: 10, max: 100 }),
        exp5Header: el('exp5Header', 'Row', { justify: 'between' }, ['exp5Name', 'exp5Amount']),
        exp5Name: el('exp5Name', 'Text', { content: 'Other' }),
        exp5Amount: el('exp5Amount', 'Text', { content: '$70,000 (3%)' }),
        exp5Bar: el('exp5Bar', 'Progress', { value: 3, max: 100 }),
        transactions: el('transactions', 'Card', { title: 'Recent Transactions' }, ['transactionList']),
        transactionList: el('transactionList', 'Column', { gap: 'sm' }, ['trans1', 'trans2', 'trans3', 'trans4']),
        trans1: el('trans1', 'Row', { justify: 'between', align: 'center' }, ['trans1Info', 'trans1Amount']),
        trans2: el('trans2', 'Row', { justify: 'between', align: 'center' }, ['trans2Info', 'trans2Amount']),
        trans3: el('trans3', 'Row', { justify: 'between', align: 'center' }, ['trans3Info', 'trans3Amount']),
        trans4: el('trans4', 'Row', { justify: 'between', align: 'center' }, ['trans4Info', 'trans4Amount']),
        trans1Info: el('trans1Info', 'Column', { gap: 'xs' }, ['trans1Desc', 'trans1Date']),
        trans1Desc: el('trans1Desc', 'Text', { content: 'Client Payment - Acme Corp' }),
        trans1Date: el('trans1Date', 'Text', { content: 'Feb 1, 2024', color: 'muted', size: 'sm' }),
        trans1Amount: el('trans1Amount', 'Text', { content: '+$45,000', color: 'success' }),
        trans2Info: el('trans2Info', 'Column', { gap: 'xs' }, ['trans2Desc', 'trans2Date']),
        trans2Desc: el('trans2Desc', 'Text', { content: 'AWS Infrastructure' }),
        trans2Date: el('trans2Date', 'Text', { content: 'Jan 31, 2024', color: 'muted', size: 'sm' }),
        trans2Amount: el('trans2Amount', 'Text', { content: '-$12,500', color: 'error' }),
        trans3Info: el('trans3Info', 'Column', { gap: 'xs' }, ['trans3Desc', 'trans3Date']),
        trans3Desc: el('trans3Desc', 'Text', { content: 'Client Payment - TechStart' }),
        trans3Date: el('trans3Date', 'Text', { content: 'Jan 30, 2024', color: 'muted', size: 'sm' }),
        trans3Amount: el('trans3Amount', 'Text', { content: '+$28,750', color: 'success' }),
        trans4Info: el('trans4Info', 'Column', { gap: 'xs' }, ['trans4Desc', 'trans4Date']),
        trans4Desc: el('trans4Desc', 'Text', { content: 'Payroll - January' }),
        trans4Date: el('trans4Date', 'Text', { content: 'Jan 28, 2024', color: 'muted', size: 'sm' }),
        trans4Amount: el('trans4Amount', 'Text', { content: '-$85,000', color: 'error' }),
      },
    },
  },
  {
    id: 'dashboard-social-media',
    name: 'Social Media Dashboard',
    description: 'Social media metrics with engagement, posts, and scheduling',
    category: 'dashboards',
    tags: ['dashboard', 'social', 'media', 'engagement', 'posts'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'platforms', 'content']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'newPostBtn']),
        title: el('title', 'Heading', { level: '1', text: 'Social Media Dashboard' }),
        newPostBtn: el('newPostBtn', 'Button', { label: 'Create Post', variant: 'solid' }),
        platforms: el('platforms', 'Grid', { columns: 4, gap: 'md' }, ['twitter', 'instagram', 'facebook', 'linkedin']),
        twitter: el('twitter', 'Card', { variant: 'outlined' }, ['twitterContent']),
        instagram: el('instagram', 'Card', { variant: 'outlined' }, ['instagramContent']),
        facebook: el('facebook', 'Card', { variant: 'outlined' }, ['facebookContent']),
        linkedin: el('linkedin', 'Card', { variant: 'outlined' }, ['linkedinContent']),
        twitterContent: el('twitterContent', 'Column', { gap: 'sm' }, ['twitterHeader', 'twitterStats']),
        twitterHeader: el('twitterHeader', 'Row', { gap: 'sm', align: 'center' }, ['twitterIcon', 'twitterName']),
        twitterIcon: el('twitterIcon', 'Badge', { text: 'X', variant: 'solid' }),
        twitterName: el('twitterName', 'Text', { content: 'Twitter/X' }),
        twitterStats: el('twitterStats', 'Column', { gap: 'xs' }, ['twitterFollowers', 'twitterEngagement']),
        twitterFollowers: el('twitterFollowers', 'Text', { content: '45.2K followers', size: 'lg' }),
        twitterEngagement: el('twitterEngagement', 'Text', { content: '+2.3% this week', color: 'success', size: 'sm' }),
        instagramContent: el('instagramContent', 'Column', { gap: 'sm' }, ['instagramHeader', 'instagramStats']),
        instagramHeader: el('instagramHeader', 'Row', { gap: 'sm', align: 'center' }, ['instagramIcon', 'instagramName']),
        instagramIcon: el('instagramIcon', 'Badge', { text: 'IG', variant: 'solid', color: 'error' }),
        instagramName: el('instagramName', 'Text', { content: 'Instagram' }),
        instagramStats: el('instagramStats', 'Column', { gap: 'xs' }, ['instagramFollowers', 'instagramEngagement']),
        instagramFollowers: el('instagramFollowers', 'Text', { content: '128K followers', size: 'lg' }),
        instagramEngagement: el('instagramEngagement', 'Text', { content: '+5.8% this week', color: 'success', size: 'sm' }),
        facebookContent: el('facebookContent', 'Column', { gap: 'sm' }, ['facebookHeader', 'facebookStats']),
        facebookHeader: el('facebookHeader', 'Row', { gap: 'sm', align: 'center' }, ['facebookIcon', 'facebookName']),
        facebookIcon: el('facebookIcon', 'Badge', { text: 'FB', variant: 'solid', color: 'info' }),
        facebookName: el('facebookName', 'Text', { content: 'Facebook' }),
        facebookStats: el('facebookStats', 'Column', { gap: 'xs' }, ['facebookFollowers', 'facebookEngagement']),
        facebookFollowers: el('facebookFollowers', 'Text', { content: '89.5K followers', size: 'lg' }),
        facebookEngagement: el('facebookEngagement', 'Text', { content: '-0.5% this week', color: 'error', size: 'sm' }),
        linkedinContent: el('linkedinContent', 'Column', { gap: 'sm' }, ['linkedinHeader', 'linkedinStats']),
        linkedinHeader: el('linkedinHeader', 'Row', { gap: 'sm', align: 'center' }, ['linkedinIcon', 'linkedinName']),
        linkedinIcon: el('linkedinIcon', 'Badge', { text: 'LI', variant: 'solid', color: 'info' }),
        linkedinName: el('linkedinName', 'Text', { content: 'LinkedIn' }),
        linkedinStats: el('linkedinStats', 'Column', { gap: 'xs' }, ['linkedinFollowers', 'linkedinEngagement']),
        linkedinFollowers: el('linkedinFollowers', 'Text', { content: '23.1K followers', size: 'lg' }),
        linkedinEngagement: el('linkedinEngagement', 'Text', { content: '+8.2% this week', color: 'success', size: 'sm' }),
        content: el('content', 'Grid', { columns: 2, gap: 'lg' }, ['recentPosts', 'scheduled']),
        recentPosts: el('recentPosts', 'Card', { title: 'Recent Posts' }, ['postsList']),
        postsList: el('postsList', 'Column', { gap: 'md' }, ['post1', 'post2', 'post3']),
        post1: el('post1', 'Card', { variant: 'outlined' }, ['post1Content']),
        post2: el('post2', 'Card', { variant: 'outlined' }, ['post2Content']),
        post3: el('post3', 'Card', { variant: 'outlined' }, ['post3Content']),
        post1Content: el('post1Content', 'Column', { gap: 'sm' }, ['post1Header', 'post1Text', 'post1Stats']),
        post1Header: el('post1Header', 'Row', { justify: 'between', align: 'center' }, ['post1Platform', 'post1Date']),
        post1Platform: el('post1Platform', 'Badge', { text: 'Instagram', color: 'error' }),
        post1Date: el('post1Date', 'Text', { content: '2 hours ago', color: 'muted', size: 'sm' }),
        post1Text: el('post1Text', 'Text', { content: 'Excited to announce our new product launch! Stay tuned for more details...' }),
        post1Stats: el('post1Stats', 'Row', { gap: 'md' }, ['post1Likes', 'post1Comments', 'post1Shares']),
        post1Likes: el('post1Likes', 'Text', { content: '1.2K likes', color: 'muted', size: 'sm' }),
        post1Comments: el('post1Comments', 'Text', { content: '89 comments', color: 'muted', size: 'sm' }),
        post1Shares: el('post1Shares', 'Text', { content: '45 shares', color: 'muted', size: 'sm' }),
        post2Content: el('post2Content', 'Column', { gap: 'sm' }, ['post2Header', 'post2Text', 'post2Stats']),
        post2Header: el('post2Header', 'Row', { justify: 'between', align: 'center' }, ['post2Platform', 'post2Date']),
        post2Platform: el('post2Platform', 'Badge', { text: 'Twitter/X', variant: 'solid' }),
        post2Date: el('post2Date', 'Text', { content: '5 hours ago', color: 'muted', size: 'sm' }),
        post2Text: el('post2Text', 'Text', { content: 'Just published our latest blog post on AI trends in 2024. Link in bio!' }),
        post2Stats: el('post2Stats', 'Row', { gap: 'md' }, ['post2Likes', 'post2Comments', 'post2Shares']),
        post2Likes: el('post2Likes', 'Text', { content: '342 likes', color: 'muted', size: 'sm' }),
        post2Comments: el('post2Comments', 'Text', { content: '28 replies', color: 'muted', size: 'sm' }),
        post2Shares: el('post2Shares', 'Text', { content: '156 retweets', color: 'muted', size: 'sm' }),
        post3Content: el('post3Content', 'Column', { gap: 'sm' }, ['post3Header', 'post3Text', 'post3Stats']),
        post3Header: el('post3Header', 'Row', { justify: 'between', align: 'center' }, ['post3Platform', 'post3Date']),
        post3Platform: el('post3Platform', 'Badge', { text: 'LinkedIn', color: 'info' }),
        post3Date: el('post3Date', 'Text', { content: 'Yesterday', color: 'muted', size: 'sm' }),
        post3Text: el('post3Text', 'Text', { content: 'We are hiring! Looking for talented engineers to join our team. Apply now.' }),
        post3Stats: el('post3Stats', 'Row', { gap: 'md' }, ['post3Likes', 'post3Comments', 'post3Shares']),
        post3Likes: el('post3Likes', 'Text', { content: '567 reactions', color: 'muted', size: 'sm' }),
        post3Comments: el('post3Comments', 'Text', { content: '42 comments', color: 'muted', size: 'sm' }),
        post3Shares: el('post3Shares', 'Text', { content: '89 shares', color: 'muted', size: 'sm' }),
        scheduled: el('scheduled', 'Card', { title: 'Scheduled Posts' }, ['scheduledList']),
        scheduledList: el('scheduledList', 'Column', { gap: 'md' }, ['sched1', 'sched2', 'sched3']),
        sched1: el('sched1', 'Row', { justify: 'between', align: 'center' }, ['sched1Info', 'sched1Actions']),
        sched2: el('sched2', 'Row', { justify: 'between', align: 'center' }, ['sched2Info', 'sched2Actions']),
        sched3: el('sched3', 'Row', { justify: 'between', align: 'center' }, ['sched3Info', 'sched3Actions']),
        sched1Info: el('sched1Info', 'Column', { gap: 'xs' }, ['sched1Title', 'sched1Meta']),
        sched1Title: el('sched1Title', 'Text', { content: 'Product feature highlight' }),
        sched1Meta: el('sched1Meta', 'Row', { gap: 'sm' }, ['sched1Platform', 'sched1Time']),
        sched1Platform: el('sched1Platform', 'Badge', { text: 'All Platforms', variant: 'outline' }),
        sched1Time: el('sched1Time', 'Text', { content: 'Tomorrow, 10:00 AM', color: 'muted', size: 'sm' }),
        sched1Actions: el('sched1Actions', 'Row', { gap: 'xs' }, ['sched1Edit', 'sched1Delete']),
        sched1Edit: el('sched1Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        sched1Delete: el('sched1Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
        sched2Info: el('sched2Info', 'Column', { gap: 'xs' }, ['sched2Title', 'sched2Meta']),
        sched2Title: el('sched2Title', 'Text', { content: 'Customer testimonial video' }),
        sched2Meta: el('sched2Meta', 'Row', { gap: 'sm' }, ['sched2Platform', 'sched2Time']),
        sched2Platform: el('sched2Platform', 'Badge', { text: 'Instagram', color: 'error' }),
        sched2Time: el('sched2Time', 'Text', { content: 'Feb 5, 2:00 PM', color: 'muted', size: 'sm' }),
        sched2Actions: el('sched2Actions', 'Row', { gap: 'xs' }, ['sched2Edit', 'sched2Delete']),
        sched2Edit: el('sched2Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        sched2Delete: el('sched2Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
        sched3Info: el('sched3Info', 'Column', { gap: 'xs' }, ['sched3Title', 'sched3Meta']),
        sched3Title: el('sched3Title', 'Text', { content: 'Industry news roundup' }),
        sched3Meta: el('sched3Meta', 'Row', { gap: 'sm' }, ['sched3Platform', 'sched3Time']),
        sched3Platform: el('sched3Platform', 'Badge', { text: 'Twitter/X', variant: 'solid' }),
        sched3Time: el('sched3Time', 'Text', { content: 'Feb 6, 9:00 AM', color: 'muted', size: 'sm' }),
        sched3Actions: el('sched3Actions', 'Row', { gap: 'xs' }, ['sched3Edit', 'sched3Delete']),
        sched3Edit: el('sched3Edit', 'Button', { label: 'Edit', variant: 'ghost', size: 'sm' }),
        sched3Delete: el('sched3Delete', 'Button', { label: 'Delete', variant: 'ghost', size: 'sm' }),
      },
    },
  },
  {
    id: 'dashboard-ecommerce-admin',
    name: 'E-commerce Admin Dashboard',
    description: 'Store management with orders, products, and customers',
    category: 'dashboards',
    tags: ['dashboard', 'ecommerce', 'admin', 'orders', 'products'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'stats', 'content']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'actions']),
        title: el('title', 'Heading', { level: '1', text: 'Store Dashboard' }),
        actions: el('actions', 'Row', { gap: 'sm' }, ['addProductBtn', 'settingsBtn']),
        addProductBtn: el('addProductBtn', 'Button', { label: 'Add Product', variant: 'solid' }),
        settingsBtn: el('settingsBtn', 'Button', { label: 'Store Settings', variant: 'outline' }),
        stats: el('stats', 'Grid', { columns: 4, gap: 'md' }, ['statOrders', 'statRevenue', 'statProducts', 'statCustomers']),
        statOrders: el('statOrders', 'Card', { variant: 'elevated' }, ['metricOrders']),
        statRevenue: el('statRevenue', 'Card', { variant: 'elevated' }, ['metricRevenue']),
        statProducts: el('statProducts', 'Card', { variant: 'elevated' }, ['metricProducts']),
        statCustomers: el('statCustomers', 'Card', { variant: 'elevated' }, ['metricCustomers']),
        metricOrders: el('metricOrders', 'Metric', { label: 'Orders Today', value: '156', change: '+23', changeType: 'positive' }),
        metricRevenue: el('metricRevenue', 'Metric', { label: 'Revenue Today', value: '$12,450', change: '+18.5%', changeType: 'positive' }),
        metricProducts: el('metricProducts', 'Metric', { label: 'Active Products', value: '1,234' }),
        metricCustomers: el('metricCustomers', 'Metric', { label: 'New Customers', value: '45', change: '+12', changeType: 'positive' }),
        content: el('content', 'Grid', { columns: 2, gap: 'lg' }, ['recentOrders', 'lowStock']),
        recentOrders: el('recentOrders', 'Card', { title: 'Recent Orders' }, ['ordersList']),
        ordersList: el('ordersList', 'Column', { gap: 'sm' }, ['order1', 'order2', 'order3', 'order4', 'viewAllOrders']),
        order1: el('order1', 'Row', { justify: 'between', align: 'center' }, ['order1Info', 'order1Status']),
        order2: el('order2', 'Row', { justify: 'between', align: 'center' }, ['order2Info', 'order2Status']),
        order3: el('order3', 'Row', { justify: 'between', align: 'center' }, ['order3Info', 'order3Status']),
        order4: el('order4', 'Row', { justify: 'between', align: 'center' }, ['order4Info', 'order4Status']),
        order1Info: el('order1Info', 'Column', { gap: 'xs' }, ['order1Id', 'order1Customer', 'order1Total']),
        order1Id: el('order1Id', 'Text', { content: '#ORD-5678' }),
        order1Customer: el('order1Customer', 'Text', { content: 'John Smith', color: 'muted', size: 'sm' }),
        order1Total: el('order1Total', 'Text', { content: '$125.00', size: 'sm' }),
        order1Status: el('order1Status', 'Badge', { text: 'Processing', color: 'warning' }),
        order2Info: el('order2Info', 'Column', { gap: 'xs' }, ['order2Id', 'order2Customer', 'order2Total']),
        order2Id: el('order2Id', 'Text', { content: '#ORD-5677' }),
        order2Customer: el('order2Customer', 'Text', { content: 'Emily Johnson', color: 'muted', size: 'sm' }),
        order2Total: el('order2Total', 'Text', { content: '$89.99', size: 'sm' }),
        order2Status: el('order2Status', 'Badge', { text: 'Shipped', color: 'info' }),
        order3Info: el('order3Info', 'Column', { gap: 'xs' }, ['order3Id', 'order3Customer', 'order3Total']),
        order3Id: el('order3Id', 'Text', { content: '#ORD-5676' }),
        order3Customer: el('order3Customer', 'Text', { content: 'Michael Brown', color: 'muted', size: 'sm' }),
        order3Total: el('order3Total', 'Text', { content: '$245.50', size: 'sm' }),
        order3Status: el('order3Status', 'Badge', { text: 'Delivered', color: 'success' }),
        order4Info: el('order4Info', 'Column', { gap: 'xs' }, ['order4Id', 'order4Customer', 'order4Total']),
        order4Id: el('order4Id', 'Text', { content: '#ORD-5675' }),
        order4Customer: el('order4Customer', 'Text', { content: 'Sarah Davis', color: 'muted', size: 'sm' }),
        order4Total: el('order4Total', 'Text', { content: '$67.00', size: 'sm' }),
        order4Status: el('order4Status', 'Badge', { text: 'Refunded', color: 'error' }),
        viewAllOrders: el('viewAllOrders', 'Button', { label: 'View All Orders', variant: 'ghost', fullWidth: true }),
        lowStock: el('lowStock', 'Card', { title: 'Low Stock Alerts' }, ['stockList']),
        stockList: el('stockList', 'Column', { gap: 'sm' }, ['stock1', 'stock2', 'stock3', 'stock4']),
        stock1: el('stock1', 'Row', { justify: 'between', align: 'center' }, ['stock1Info', 'stock1Qty']),
        stock2: el('stock2', 'Row', { justify: 'between', align: 'center' }, ['stock2Info', 'stock2Qty']),
        stock3: el('stock3', 'Row', { justify: 'between', align: 'center' }, ['stock3Info', 'stock3Qty']),
        stock4: el('stock4', 'Row', { justify: 'between', align: 'center' }, ['stock4Info', 'stock4Qty']),
        stock1Info: el('stock1Info', 'Column', { gap: 'xs' }, ['stock1Name', 'stock1Sku']),
        stock1Name: el('stock1Name', 'Text', { content: 'Wireless Headphones' }),
        stock1Sku: el('stock1Sku', 'Text', { content: 'SKU: WH-001', color: 'muted', size: 'sm' }),
        stock1Qty: el('stock1Qty', 'Badge', { text: '3 left', color: 'error' }),
        stock2Info: el('stock2Info', 'Column', { gap: 'xs' }, ['stock2Name', 'stock2Sku']),
        stock2Name: el('stock2Name', 'Text', { content: 'USB-C Cable' }),
        stock2Sku: el('stock2Sku', 'Text', { content: 'SKU: UC-015', color: 'muted', size: 'sm' }),
        stock2Qty: el('stock2Qty', 'Badge', { text: '5 left', color: 'warning' }),
        stock3Info: el('stock3Info', 'Column', { gap: 'xs' }, ['stock3Name', 'stock3Sku']),
        stock3Name: el('stock3Name', 'Text', { content: 'Phone Case - Black' }),
        stock3Sku: el('stock3Sku', 'Text', { content: 'SKU: PC-BLK', color: 'muted', size: 'sm' }),
        stock3Qty: el('stock3Qty', 'Badge', { text: '8 left', color: 'warning' }),
        stock4Info: el('stock4Info', 'Column', { gap: 'xs' }, ['stock4Name', 'stock4Sku']),
        stock4Name: el('stock4Name', 'Text', { content: 'Laptop Stand' }),
        stock4Sku: el('stock4Sku', 'Text', { content: 'SKU: LS-PRO', color: 'muted', size: 'sm' }),
        stock4Qty: el('stock4Qty', 'Badge', { text: '2 left', color: 'error' }),
      },
    },
  },
  {
    id: 'dashboard-support',
    name: 'Support Ticket Dashboard',
    description: 'Help desk with tickets, status, and agent workload',
    category: 'dashboards',
    tags: ['dashboard', 'support', 'tickets', 'helpdesk', 'customer-service'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'stats', 'content']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'newTicketBtn']),
        title: el('title', 'Heading', { level: '1', text: 'Support Dashboard' }),
        newTicketBtn: el('newTicketBtn', 'Button', { label: 'New Ticket', variant: 'solid' }),
        stats: el('stats', 'Grid', { columns: 4, gap: 'md' }, ['statOpen', 'statPending', 'statResolved', 'statAvgTime']),
        statOpen: el('statOpen', 'Card', { variant: 'elevated' }, ['metricOpen']),
        statPending: el('statPending', 'Card', { variant: 'elevated' }, ['metricPending']),
        statResolved: el('statResolved', 'Card', { variant: 'elevated' }, ['metricResolved']),
        statAvgTime: el('statAvgTime', 'Card', { variant: 'elevated' }, ['metricAvgTime']),
        metricOpen: el('metricOpen', 'Metric', { label: 'Open Tickets', value: '24', change: '+5', changeType: 'negative' }),
        metricPending: el('metricPending', 'Metric', { label: 'Pending Response', value: '12' }),
        metricResolved: el('metricResolved', 'Metric', { label: 'Resolved Today', value: '18', change: '+3', changeType: 'positive' }),
        metricAvgTime: el('metricAvgTime', 'Metric', { label: 'Avg Response Time', value: '2.4h', change: '-15min', changeType: 'positive' }),
        content: el('content', 'Grid', { columns: 2, gap: 'lg' }, ['ticketList', 'agentLoad']),
        ticketList: el('ticketList', 'Card', { title: 'Recent Tickets' }, ['tickets']),
        tickets: el('tickets', 'Column', { gap: 'sm' }, ['ticket1', 'ticket2', 'ticket3', 'ticket4']),
        ticket1: el('ticket1', 'Card', { variant: 'outlined' }, ['ticket1Content']),
        ticket2: el('ticket2', 'Card', { variant: 'outlined' }, ['ticket2Content']),
        ticket3: el('ticket3', 'Card', { variant: 'outlined' }, ['ticket3Content']),
        ticket4: el('ticket4', 'Card', { variant: 'outlined' }, ['ticket4Content']),
        ticket1Content: el('ticket1Content', 'Column', { gap: 'sm' }, ['ticket1Header', 'ticket1Subject', 'ticket1Meta']),
        ticket1Header: el('ticket1Header', 'Row', { justify: 'between', align: 'center' }, ['ticket1Id', 'ticket1Priority']),
        ticket1Id: el('ticket1Id', 'Text', { content: '#TKT-1234', size: 'sm' }),
        ticket1Priority: el('ticket1Priority', 'Badge', { text: 'High', color: 'error' }),
        ticket1Subject: el('ticket1Subject', 'Text', { content: 'Unable to access account after password reset' }),
        ticket1Meta: el('ticket1Meta', 'Row', { justify: 'between' }, ['ticket1Customer', 'ticket1Time']),
        ticket1Customer: el('ticket1Customer', 'Text', { content: 'John Doe', color: 'muted', size: 'sm' }),
        ticket1Time: el('ticket1Time', 'Text', { content: '15 min ago', color: 'muted', size: 'sm' }),
        ticket2Content: el('ticket2Content', 'Column', { gap: 'sm' }, ['ticket2Header', 'ticket2Subject', 'ticket2Meta']),
        ticket2Header: el('ticket2Header', 'Row', { justify: 'between', align: 'center' }, ['ticket2Id', 'ticket2Priority']),
        ticket2Id: el('ticket2Id', 'Text', { content: '#TKT-1233', size: 'sm' }),
        ticket2Priority: el('ticket2Priority', 'Badge', { text: 'Medium', color: 'warning' }),
        ticket2Subject: el('ticket2Subject', 'Text', { content: 'Billing discrepancy on last invoice' }),
        ticket2Meta: el('ticket2Meta', 'Row', { justify: 'between' }, ['ticket2Customer', 'ticket2Time']),
        ticket2Customer: el('ticket2Customer', 'Text', { content: 'Jane Smith', color: 'muted', size: 'sm' }),
        ticket2Time: el('ticket2Time', 'Text', { content: '1 hour ago', color: 'muted', size: 'sm' }),
        ticket3Content: el('ticket3Content', 'Column', { gap: 'sm' }, ['ticket3Header', 'ticket3Subject', 'ticket3Meta']),
        ticket3Header: el('ticket3Header', 'Row', { justify: 'between', align: 'center' }, ['ticket3Id', 'ticket3Priority']),
        ticket3Id: el('ticket3Id', 'Text', { content: '#TKT-1232', size: 'sm' }),
        ticket3Priority: el('ticket3Priority', 'Badge', { text: 'Low', variant: 'outline' }),
        ticket3Subject: el('ticket3Subject', 'Text', { content: 'Feature request: Dark mode support' }),
        ticket3Meta: el('ticket3Meta', 'Row', { justify: 'between' }, ['ticket3Customer', 'ticket3Time']),
        ticket3Customer: el('ticket3Customer', 'Text', { content: 'Mike Johnson', color: 'muted', size: 'sm' }),
        ticket3Time: el('ticket3Time', 'Text', { content: '3 hours ago', color: 'muted', size: 'sm' }),
        ticket4Content: el('ticket4Content', 'Column', { gap: 'sm' }, ['ticket4Header', 'ticket4Subject', 'ticket4Meta']),
        ticket4Header: el('ticket4Header', 'Row', { justify: 'between', align: 'center' }, ['ticket4Id', 'ticket4Priority']),
        ticket4Id: el('ticket4Id', 'Text', { content: '#TKT-1231', size: 'sm' }),
        ticket4Priority: el('ticket4Priority', 'Badge', { text: 'High', color: 'error' }),
        ticket4Subject: el('ticket4Subject', 'Text', { content: 'Integration not syncing data properly' }),
        ticket4Meta: el('ticket4Meta', 'Row', { justify: 'between' }, ['ticket4Customer', 'ticket4Time']),
        ticket4Customer: el('ticket4Customer', 'Text', { content: 'Sarah Wilson', color: 'muted', size: 'sm' }),
        ticket4Time: el('ticket4Time', 'Text', { content: '4 hours ago', color: 'muted', size: 'sm' }),
        agentLoad: el('agentLoad', 'Card', { title: 'Agent Workload' }, ['agentList']),
        agentList: el('agentList', 'Column', { gap: 'md' }, ['agent1', 'agent2', 'agent3']),
        agent1: el('agent1', 'Column', { gap: 'sm' }, ['agent1Info', 'agent1Bar']),
        agent2: el('agent2', 'Column', { gap: 'sm' }, ['agent2Info', 'agent2Bar']),
        agent3: el('agent3', 'Column', { gap: 'sm' }, ['agent3Info', 'agent3Bar']),
        agent1Info: el('agent1Info', 'Row', { justify: 'between', align: 'center' }, ['agent1Profile', 'agent1Tickets']),
        agent1Profile: el('agent1Profile', 'Row', { gap: 'sm', align: 'center' }, ['agent1Avatar', 'agent1Name']),
        agent1Avatar: el('agent1Avatar', 'Avatar', { name: 'Alex Rivera', size: 'sm' }),
        agent1Name: el('agent1Name', 'Text', { content: 'Alex Rivera' }),
        agent1Tickets: el('agent1Tickets', 'Text', { content: '8 tickets', color: 'muted', size: 'sm' }),
        agent1Bar: el('agent1Bar', 'Progress', { value: 80, max: 100, color: 'warning' }),
        agent2Info: el('agent2Info', 'Row', { justify: 'between', align: 'center' }, ['agent2Profile', 'agent2Tickets']),
        agent2Profile: el('agent2Profile', 'Row', { gap: 'sm', align: 'center' }, ['agent2Avatar', 'agent2Name']),
        agent2Avatar: el('agent2Avatar', 'Avatar', { name: 'Kim Lee', size: 'sm' }),
        agent2Name: el('agent2Name', 'Text', { content: 'Kim Lee' }),
        agent2Tickets: el('agent2Tickets', 'Text', { content: '6 tickets', color: 'muted', size: 'sm' }),
        agent2Bar: el('agent2Bar', 'Progress', { value: 60, max: 100, color: 'info' }),
        agent3Info: el('agent3Info', 'Row', { justify: 'between', align: 'center' }, ['agent3Profile', 'agent3Tickets']),
        agent3Profile: el('agent3Profile', 'Row', { gap: 'sm', align: 'center' }, ['agent3Avatar', 'agent3Name']),
        agent3Avatar: el('agent3Avatar', 'Avatar', { name: 'Jordan Taylor', size: 'sm' }),
        agent3Name: el('agent3Name', 'Text', { content: 'Jordan Taylor' }),
        agent3Tickets: el('agent3Tickets', 'Text', { content: '10 tickets', color: 'muted', size: 'sm' }),
        agent3Bar: el('agent3Bar', 'Progress', { value: 100, max: 100, color: 'error' }),
      },
    },
  },
  {
    id: 'dashboard-hr',
    name: 'HR Dashboard',
    description: 'Human resources with employees, attendance, and departments',
    category: 'dashboards',
    tags: ['dashboard', 'hr', 'employees', 'attendance', 'human-resources'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'stats', 'content']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'actions']),
        title: el('title', 'Heading', { level: '1', text: 'HR Dashboard' }),
        actions: el('actions', 'Row', { gap: 'sm' }, ['addEmployeeBtn', 'reportsBtn']),
        addEmployeeBtn: el('addEmployeeBtn', 'Button', { label: 'Add Employee', variant: 'solid' }),
        reportsBtn: el('reportsBtn', 'Button', { label: 'Reports', variant: 'outline' }),
        stats: el('stats', 'Grid', { columns: 4, gap: 'md' }, ['statTotal', 'statPresent', 'statOnLeave', 'statOpen']),
        statTotal: el('statTotal', 'Card', { variant: 'elevated' }, ['metricTotal']),
        statPresent: el('statPresent', 'Card', { variant: 'elevated' }, ['metricPresent']),
        statOnLeave: el('statOnLeave', 'Card', { variant: 'elevated' }, ['metricOnLeave']),
        statOpen: el('statOpen', 'Card', { variant: 'elevated' }, ['metricOpenPos']),
        metricTotal: el('metricTotal', 'Metric', { label: 'Total Employees', value: '248' }),
        metricPresent: el('metricPresent', 'Metric', { label: 'Present Today', value: '231', change: '93%', changeType: 'positive' }),
        metricOnLeave: el('metricOnLeave', 'Metric', { label: 'On Leave', value: '12' }),
        metricOpenPos: el('metricOpenPos', 'Metric', { label: 'Open Positions', value: '8', change: '+3 this week', changeType: 'positive' }),
        content: el('content', 'Grid', { columns: 2, gap: 'lg' }, ['departments', 'attendance']),
        departments: el('departments', 'Card', { title: 'Department Overview' }, ['deptList']),
        deptList: el('deptList', 'Column', { gap: 'md' }, ['dept1', 'dept2', 'dept3', 'dept4']),
        dept1: el('dept1', 'Row', { justify: 'between', align: 'center' }, ['dept1Info', 'dept1Count']),
        dept2: el('dept2', 'Row', { justify: 'between', align: 'center' }, ['dept2Info', 'dept2Count']),
        dept3: el('dept3', 'Row', { justify: 'between', align: 'center' }, ['dept3Info', 'dept3Count']),
        dept4: el('dept4', 'Row', { justify: 'between', align: 'center' }, ['dept4Info', 'dept4Count']),
        dept1Info: el('dept1Info', 'Column', { gap: 'xs' }, ['dept1Name', 'dept1Head']),
        dept1Name: el('dept1Name', 'Text', { content: 'Engineering' }),
        dept1Head: el('dept1Head', 'Text', { content: 'Head: John Smith', color: 'muted', size: 'sm' }),
        dept1Count: el('dept1Count', 'Badge', { text: '85 employees', variant: 'outline' }),
        dept2Info: el('dept2Info', 'Column', { gap: 'xs' }, ['dept2Name', 'dept2Head']),
        dept2Name: el('dept2Name', 'Text', { content: 'Sales & Marketing' }),
        dept2Head: el('dept2Head', 'Text', { content: 'Head: Lisa Chen', color: 'muted', size: 'sm' }),
        dept2Count: el('dept2Count', 'Badge', { text: '62 employees', variant: 'outline' }),
        dept3Info: el('dept3Info', 'Column', { gap: 'xs' }, ['dept3Name', 'dept3Head']),
        dept3Name: el('dept3Name', 'Text', { content: 'Operations' }),
        dept3Head: el('dept3Head', 'Text', { content: 'Head: Mike Johnson', color: 'muted', size: 'sm' }),
        dept3Count: el('dept3Count', 'Badge', { text: '54 employees', variant: 'outline' }),
        dept4Info: el('dept4Info', 'Column', { gap: 'xs' }, ['dept4Name', 'dept4Head']),
        dept4Name: el('dept4Name', 'Text', { content: 'Human Resources' }),
        dept4Head: el('dept4Head', 'Text', { content: 'Head: Sarah Williams', color: 'muted', size: 'sm' }),
        dept4Count: el('dept4Count', 'Badge', { text: '12 employees', variant: 'outline' }),
        attendance: el('attendance', 'Card', { title: 'Today\'s Attendance' }, ['attendanceContent']),
        attendanceContent: el('attendanceContent', 'Column', { gap: 'md' }, ['attendanceSummary', 'attendanceList']),
        attendanceSummary: el('attendanceSummary', 'Row', { gap: 'lg', justify: 'center' }, ['presentCount', 'lateCount', 'absentCount']),
        presentCount: el('presentCount', 'Column', { align: 'center' }, ['presentNum', 'presentLabel']),
        presentNum: el('presentNum', 'Heading', { level: '2', text: '218' }),
        presentLabel: el('presentLabel', 'Text', { content: 'On Time', color: 'success' }),
        lateCount: el('lateCount', 'Column', { align: 'center' }, ['lateNum', 'lateLabel']),
        lateNum: el('lateNum', 'Heading', { level: '2', text: '13' }),
        lateLabel: el('lateLabel', 'Text', { content: 'Late', color: 'warning' }),
        absentCount: el('absentCount', 'Column', { align: 'center' }, ['absentNum', 'absentLabel']),
        absentNum: el('absentNum', 'Heading', { level: '2', text: '5' }),
        absentLabel: el('absentLabel', 'Text', { content: 'Absent', color: 'error' }),
        attendanceList: el('attendanceList', 'Column', { gap: 'sm' }, ['attTitle', 'att1', 'att2', 'att3']),
        attTitle: el('attTitle', 'Text', { content: 'Recent Check-ins', size: 'sm', color: 'muted' }),
        att1: el('att1', 'Row', { justify: 'between', align: 'center' }, ['att1Info', 'att1Time']),
        att2: el('att2', 'Row', { justify: 'between', align: 'center' }, ['att2Info', 'att2Time']),
        att3: el('att3', 'Row', { justify: 'between', align: 'center' }, ['att3Info', 'att3Time']),
        att1Info: el('att1Info', 'Row', { gap: 'sm', align: 'center' }, ['att1Avatar', 'att1Name']),
        att1Avatar: el('att1Avatar', 'Avatar', { name: 'Emma Davis', size: 'sm' }),
        att1Name: el('att1Name', 'Text', { content: 'Emma Davis' }),
        att1Time: el('att1Time', 'Badge', { text: '8:45 AM', color: 'success' }),
        att2Info: el('att2Info', 'Row', { gap: 'sm', align: 'center' }, ['att2Avatar', 'att2Name']),
        att2Avatar: el('att2Avatar', 'Avatar', { name: 'David Miller', size: 'sm' }),
        att2Name: el('att2Name', 'Text', { content: 'David Miller' }),
        att2Time: el('att2Time', 'Badge', { text: '8:52 AM', color: 'success' }),
        att3Info: el('att3Info', 'Row', { gap: 'sm', align: 'center' }, ['att3Avatar', 'att3Name']),
        att3Avatar: el('att3Avatar', 'Avatar', { name: 'Chris Brown', size: 'sm' }),
        att3Name: el('att3Name', 'Text', { content: 'Chris Brown' }),
        att3Time: el('att3Time', 'Badge', { text: '9:15 AM', color: 'warning' }),
      },
    },
  },
  {
    id: 'dashboard-iot',
    name: 'IoT Monitoring Dashboard',
    description: 'Device monitoring with sensors, alerts, and metrics',
    category: 'dashboards',
    tags: ['dashboard', 'iot', 'monitoring', 'devices', 'sensors'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'lg' }, ['header', 'stats', 'content']),
        header: el('header', 'Row', { justify: 'between', align: 'center' }, ['title', 'actions']),
        title: el('title', 'Heading', { level: '1', text: 'IoT Monitoring' }),
        actions: el('actions', 'Row', { gap: 'sm' }, ['addDeviceBtn', 'refreshBtn']),
        addDeviceBtn: el('addDeviceBtn', 'Button', { label: 'Add Device', variant: 'outline' }),
        refreshBtn: el('refreshBtn', 'Button', { label: 'Refresh', variant: 'solid' }),
        stats: el('stats', 'Grid', { columns: 4, gap: 'md' }, ['statDevices', 'statOnline', 'statAlerts', 'statData']),
        statDevices: el('statDevices', 'Card', { variant: 'elevated' }, ['metricDevices']),
        statOnline: el('statOnline', 'Card', { variant: 'elevated' }, ['metricOnline']),
        statAlerts: el('statAlerts', 'Card', { variant: 'elevated' }, ['metricAlerts']),
        statData: el('statData', 'Card', { variant: 'elevated' }, ['metricData']),
        metricDevices: el('metricDevices', 'Metric', { label: 'Total Devices', value: '156' }),
        metricOnline: el('metricOnline', 'Metric', { label: 'Online', value: '148', change: '95%', changeType: 'positive' }),
        metricAlerts: el('metricAlerts', 'Metric', { label: 'Active Alerts', value: '3', change: 'Critical', changeType: 'negative' }),
        metricData: el('metricData', 'Metric', { label: 'Data Points/min', value: '12.4K' }),
        content: el('content', 'Grid', { columns: 2, gap: 'lg' }, ['devices', 'alerts']),
        devices: el('devices', 'Card', { title: 'Device Status' }, ['deviceList']),
        deviceList: el('deviceList', 'Column', { gap: 'sm' }, ['device1', 'device2', 'device3', 'device4']),
        device1: el('device1', 'Row', { justify: 'between', align: 'center' }, ['device1Info', 'device1Status']),
        device2: el('device2', 'Row', { justify: 'between', align: 'center' }, ['device2Info', 'device2Status']),
        device3: el('device3', 'Row', { justify: 'between', align: 'center' }, ['device3Info', 'device3Status']),
        device4: el('device4', 'Row', { justify: 'between', align: 'center' }, ['device4Info', 'device4Status']),
        device1Info: el('device1Info', 'Column', { gap: 'xs' }, ['device1Name', 'device1Location', 'device1Reading']),
        device1Name: el('device1Name', 'Text', { content: 'Temperature Sensor A1' }),
        device1Location: el('device1Location', 'Text', { content: 'Building A, Floor 1', color: 'muted', size: 'sm' }),
        device1Reading: el('device1Reading', 'Text', { content: '72.5°F', size: 'lg' }),
        device1Status: el('device1Status', 'Badge', { text: 'Online', color: 'success' }),
        device2Info: el('device2Info', 'Column', { gap: 'xs' }, ['device2Name', 'device2Location', 'device2Reading']),
        device2Name: el('device2Name', 'Text', { content: 'Humidity Sensor B2' }),
        device2Location: el('device2Location', 'Text', { content: 'Building B, Floor 2', color: 'muted', size: 'sm' }),
        device2Reading: el('device2Reading', 'Text', { content: '45%', size: 'lg' }),
        device2Status: el('device2Status', 'Badge', { text: 'Online', color: 'success' }),
        device3Info: el('device3Info', 'Column', { gap: 'xs' }, ['device3Name', 'device3Location', 'device3Reading']),
        device3Name: el('device3Name', 'Text', { content: 'Motion Sensor C1' }),
        device3Location: el('device3Location', 'Text', { content: 'Building C, Entrance', color: 'muted', size: 'sm' }),
        device3Reading: el('device3Reading', 'Text', { content: 'Active', size: 'lg' }),
        device3Status: el('device3Status', 'Badge', { text: 'Warning', color: 'warning' }),
        device4Info: el('device4Info', 'Column', { gap: 'xs' }, ['device4Name', 'device4Location', 'device4Reading']),
        device4Name: el('device4Name', 'Text', { content: 'Power Meter D1' }),
        device4Location: el('device4Location', 'Text', { content: 'Building D, Server Room', color: 'muted', size: 'sm' }),
        device4Reading: el('device4Reading', 'Text', { content: '---', size: 'lg', color: 'error' }),
        device4Status: el('device4Status', 'Badge', { text: 'Offline', color: 'error' }),
        alerts: el('alerts', 'Card', { title: 'Active Alerts' }, ['alertList']),
        alertList: el('alertList', 'Column', { gap: 'sm' }, ['alert1', 'alert2', 'alert3']),
        alert1: el('alert1', 'Card', { variant: 'outlined' }, ['alert1Content']),
        alert2: el('alert2', 'Card', { variant: 'outlined' }, ['alert2Content']),
        alert3: el('alert3', 'Card', { variant: 'outlined' }, ['alert3Content']),
        alert1Content: el('alert1Content', 'Column', { gap: 'sm' }, ['alert1Header', 'alert1Desc', 'alert1Actions']),
        alert1Header: el('alert1Header', 'Row', { justify: 'between', align: 'center' }, ['alert1Title', 'alert1Severity']),
        alert1Title: el('alert1Title', 'Text', { content: 'Device Offline' }),
        alert1Severity: el('alert1Severity', 'Badge', { text: 'Critical', color: 'error' }),
        alert1Desc: el('alert1Desc', 'Text', { content: 'Power Meter D1 has been offline for 15 minutes', color: 'muted', size: 'sm' }),
        alert1Actions: el('alert1Actions', 'Row', { gap: 'sm' }, ['alert1Ack', 'alert1View']),
        alert1Ack: el('alert1Ack', 'Button', { label: 'Acknowledge', variant: 'outline', size: 'sm' }),
        alert1View: el('alert1View', 'Button', { label: 'View Details', variant: 'ghost', size: 'sm' }),
        alert2Content: el('alert2Content', 'Column', { gap: 'sm' }, ['alert2Header', 'alert2Desc', 'alert2Actions']),
        alert2Header: el('alert2Header', 'Row', { justify: 'between', align: 'center' }, ['alert2Title', 'alert2Severity']),
        alert2Title: el('alert2Title', 'Text', { content: 'High Motion Activity' }),
        alert2Severity: el('alert2Severity', 'Badge', { text: 'Warning', color: 'warning' }),
        alert2Desc: el('alert2Desc', 'Text', { content: 'Motion Sensor C1 detecting unusual activity', color: 'muted', size: 'sm' }),
        alert2Actions: el('alert2Actions', 'Row', { gap: 'sm' }, ['alert2Ack', 'alert2View']),
        alert2Ack: el('alert2Ack', 'Button', { label: 'Acknowledge', variant: 'outline', size: 'sm' }),
        alert2View: el('alert2View', 'Button', { label: 'View Details', variant: 'ghost', size: 'sm' }),
        alert3Content: el('alert3Content', 'Column', { gap: 'sm' }, ['alert3Header', 'alert3Desc', 'alert3Actions']),
        alert3Header: el('alert3Header', 'Row', { justify: 'between', align: 'center' }, ['alert3Title', 'alert3Severity']),
        alert3Title: el('alert3Title', 'Text', { content: 'Battery Low' }),
        alert3Severity: el('alert3Severity', 'Badge', { text: 'Info', color: 'info' }),
        alert3Desc: el('alert3Desc', 'Text', { content: '5 devices have battery below 20%', color: 'muted', size: 'sm' }),
        alert3Actions: el('alert3Actions', 'Row', { gap: 'sm' }, ['alert3Ack', 'alert3View']),
        alert3Ack: el('alert3Ack', 'Button', { label: 'Acknowledge', variant: 'outline', size: 'sm' }),
        alert3View: el('alert3View', 'Button', { label: 'View Details', variant: 'ghost', size: 'sm' }),
      },
    },
  },
];
