/**
 * E-commerce Test Cases
 * Real-world e-commerce UI configurations
 */

import type { UITree, UIElement } from '@json-render/core';
import type { TestCase } from './test-cases';

function el(key: string, type: string, props: Record<string, unknown>, children?: string[]): UIElement {
  return { key, type, props, children };
}

export const ecommerceTestCases: TestCase[] = [
  {
    id: 'ecommerce-product-listing',
    name: 'Product Listing Page',
    description: 'Product grid with filters and sorting',
    category: 'ecommerce',
    tags: ['ecommerce', 'products', 'listing', 'grid', 'filters'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'xl' }, ['header', 'content']),
        header: el('header', 'Column', { gap: 'md' }, ['breadcrumb', 'titleRow']),
        breadcrumb: el('breadcrumb', 'Row', { gap: 'xs' }, ['bc1', 'bcSep1', 'bc2', 'bcSep2', 'bc3']),
        bc1: el('bc1', 'Link', { text: 'Home', href: '/' }),
        bcSep1: el('bcSep1', 'Text', { content: '/' }),
        bc2: el('bc2', 'Link', { text: 'Electronics', href: '/electronics' }),
        bcSep2: el('bcSep2', 'Text', { content: '/' }),
        bc3: el('bc3', 'Text', { content: 'Headphones' }),
        titleRow: el('titleRow', 'Row', { justify: 'between', align: 'center' }, ['title', 'sortSelect']),
        title: el('title', 'Heading', { level: '1', text: 'Headphones' }),
        sortSelect: el('sortSelect', 'Select', { label: 'Sort by', options: [{ value: 'featured', label: 'Featured' }, { value: 'price-asc', label: 'Price: Low to High' }, { value: 'price-desc', label: 'Price: High to Low' }, { value: 'rating', label: 'Highest Rated' }] }),
        content: el('content', 'Row', { gap: 'lg' }, ['filters', 'products']),
        filters: el('filters', 'Card', { variant: 'outlined' }, ['filterContent']),
        filterContent: el('filterContent', 'Column', { gap: 'lg' }, ['priceFilter', 'brandFilter', 'ratingFilter', 'featuresFilter']),
        priceFilter: el('priceFilter', 'Column', { gap: 'sm' }, ['priceTitle', 'priceSlider']),
        priceTitle: el('priceTitle', 'Text', { content: 'Price Range', size: 'sm' }),
        priceSlider: el('priceSlider', 'Slider', { min: 0, max: 500 }),
        brandFilter: el('brandFilter', 'Column', { gap: 'sm' }, ['brandTitle', 'brand1', 'brand2', 'brand3', 'brand4']),
        brandTitle: el('brandTitle', 'Text', { content: 'Brand', size: 'sm' }),
        brand1: el('brand1', 'Checkbox', { label: 'Sony' }),
        brand2: el('brand2', 'Checkbox', { label: 'Bose' }),
        brand3: el('brand3', 'Checkbox', { label: 'Apple' }),
        brand4: el('brand4', 'Checkbox', { label: 'Sennheiser' }),
        ratingFilter: el('ratingFilter', 'Column', { gap: 'sm' }, ['ratingTitle', 'rating4', 'rating3', 'rating2']),
        ratingTitle: el('ratingTitle', 'Text', { content: 'Rating', size: 'sm' }),
        rating4: el('rating4', 'Checkbox', { label: '4 stars & up' }),
        rating3: el('rating3', 'Checkbox', { label: '3 stars & up' }),
        rating2: el('rating2', 'Checkbox', { label: '2 stars & up' }),
        featuresFilter: el('featuresFilter', 'Column', { gap: 'sm' }, ['featuresTitle', 'feat1', 'feat2', 'feat3']),
        featuresTitle: el('featuresTitle', 'Text', { content: 'Features', size: 'sm' }),
        feat1: el('feat1', 'Checkbox', { label: 'Wireless' }),
        feat2: el('feat2', 'Checkbox', { label: 'Noise Cancelling' }),
        feat3: el('feat3', 'Checkbox', { label: 'Built-in Mic' }),
        products: el('products', 'Column', { gap: 'md' }, ['productCount', 'productGrid', 'pagination']),
        productCount: el('productCount', 'Text', { content: 'Showing 1-12 of 48 products', color: 'muted' }),
        productGrid: el('productGrid', 'Grid', { columns: 3, gap: 'md' }, ['prod1', 'prod2', 'prod3', 'prod4', 'prod5', 'prod6']),
        prod1: el('prod1', 'Card', { variant: 'elevated', hoverable: true }, ['prod1Content']),
        prod2: el('prod2', 'Card', { variant: 'elevated', hoverable: true }, ['prod2Content']),
        prod3: el('prod3', 'Card', { variant: 'elevated', hoverable: true }, ['prod3Content']),
        prod4: el('prod4', 'Card', { variant: 'elevated', hoverable: true }, ['prod4Content']),
        prod5: el('prod5', 'Card', { variant: 'elevated', hoverable: true }, ['prod5Content']),
        prod6: el('prod6', 'Card', { variant: 'elevated', hoverable: true }, ['prod6Content']),
        prod1Content: el('prod1Content', 'Column', { gap: 'sm' }, ['prod1Img', 'prod1Name', 'prod1Rating', 'prod1Price', 'prod1Btn']),
        prod1Img: el('prod1Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Sony WH-1000XM5' }),
        prod1Name: el('prod1Name', 'Text', { content: 'Sony WH-1000XM5' }),
        prod1Rating: el('prod1Rating', 'Text', { content: '★★★★★ (2,456)', color: 'muted', size: 'sm' }),
        prod1Price: el('prod1Price', 'Text', { content: '$349.99', size: 'lg' }),
        prod1Btn: el('prod1Btn', 'Button', { label: 'Add to Cart', variant: 'solid', fullWidth: true }),
        prod2Content: el('prod2Content', 'Column', { gap: 'sm' }, ['prod2Img', 'prod2Name', 'prod2Rating', 'prod2Price', 'prod2Btn']),
        prod2Img: el('prod2Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Bose QuietComfort' }),
        prod2Name: el('prod2Name', 'Text', { content: 'Bose QuietComfort 45' }),
        prod2Rating: el('prod2Rating', 'Text', { content: '★★★★★ (1,823)', color: 'muted', size: 'sm' }),
        prod2Price: el('prod2Price', 'Text', { content: '$329.00', size: 'lg' }),
        prod2Btn: el('prod2Btn', 'Button', { label: 'Add to Cart', variant: 'solid', fullWidth: true }),
        prod3Content: el('prod3Content', 'Column', { gap: 'sm' }, ['prod3Img', 'prod3Name', 'prod3Rating', 'prod3Price', 'prod3Btn']),
        prod3Img: el('prod3Img', 'Image', { src: '/placeholder-product.jpg', alt: 'AirPods Max' }),
        prod3Name: el('prod3Name', 'Text', { content: 'Apple AirPods Max' }),
        prod3Rating: el('prod3Rating', 'Text', { content: '★★★★☆ (987)', color: 'muted', size: 'sm' }),
        prod3Price: el('prod3Price', 'Text', { content: '$549.00', size: 'lg' }),
        prod3Btn: el('prod3Btn', 'Button', { label: 'Add to Cart', variant: 'solid', fullWidth: true }),
        prod4Content: el('prod4Content', 'Column', { gap: 'sm' }, ['prod4Img', 'prod4Name', 'prod4Rating', 'prod4Price', 'prod4Btn']),
        prod4Img: el('prod4Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Sennheiser HD 560S' }),
        prod4Name: el('prod4Name', 'Text', { content: 'Sennheiser HD 560S' }),
        prod4Rating: el('prod4Rating', 'Text', { content: '★★★★★ (542)', color: 'muted', size: 'sm' }),
        prod4Price: el('prod4Price', 'Text', { content: '$199.95', size: 'lg' }),
        prod4Btn: el('prod4Btn', 'Button', { label: 'Add to Cart', variant: 'solid', fullWidth: true }),
        prod5Content: el('prod5Content', 'Column', { gap: 'sm' }, ['prod5Img', 'prod5Name', 'prod5Rating', 'prod5Price', 'prod5Btn']),
        prod5Img: el('prod5Img', 'Image', { src: '/placeholder-product.jpg', alt: 'JBL Tune 760NC' }),
        prod5Name: el('prod5Name', 'Text', { content: 'JBL Tune 760NC' }),
        prod5Rating: el('prod5Rating', 'Text', { content: '★★★★☆ (3,245)', color: 'muted', size: 'sm' }),
        prod5Price: el('prod5Price', 'Text', { content: '$129.95', size: 'lg' }),
        prod5Btn: el('prod5Btn', 'Button', { label: 'Add to Cart', variant: 'solid', fullWidth: true }),
        prod6Content: el('prod6Content', 'Column', { gap: 'sm' }, ['prod6Img', 'prod6Name', 'prod6Rating', 'prod6Price', 'prod6Btn']),
        prod6Img: el('prod6Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Beats Studio Pro' }),
        prod6Name: el('prod6Name', 'Text', { content: 'Beats Studio Pro' }),
        prod6Rating: el('prod6Rating', 'Text', { content: '★★★★☆ (1,102)', color: 'muted', size: 'sm' }),
        prod6Price: el('prod6Price', 'Text', { content: '$349.99', size: 'lg' }),
        prod6Btn: el('prod6Btn', 'Button', { label: 'Add to Cart', variant: 'solid', fullWidth: true }),
        pagination: el('pagination', 'Row', { justify: 'center', gap: 'sm' }, ['prevPage', 'page1', 'page2', 'page3', 'page4', 'nextPage']),
        prevPage: el('prevPage', 'Button', { label: 'Previous', variant: 'outline' }),
        page1: el('page1', 'Button', { label: '1', variant: 'solid' }),
        page2: el('page2', 'Button', { label: '2', variant: 'outline' }),
        page3: el('page3', 'Button', { label: '3', variant: 'outline' }),
        page4: el('page4', 'Button', { label: '4', variant: 'outline' }),
        nextPage: el('nextPage', 'Button', { label: 'Next', variant: 'outline' }),
      },
    },
  },
  {
    id: 'ecommerce-product-detail',
    name: 'Product Detail Page',
    description: 'Single product page with images, info, reviews, and related items',
    category: 'ecommerce',
    tags: ['ecommerce', 'product', 'detail', 'reviews', 'pdp'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'xl' }, ['breadcrumb', 'productSection', 'reviews', 'related']),
        breadcrumb: el('breadcrumb', 'Row', { gap: 'xs' }, ['bc1', 'bcSep1', 'bc2', 'bcSep2', 'bc3']),
        bc1: el('bc1', 'Link', { text: 'Home', href: '/' }),
        bcSep1: el('bcSep1', 'Text', { content: '/' }),
        bc2: el('bc2', 'Link', { text: 'Headphones', href: '/headphones' }),
        bcSep2: el('bcSep2', 'Text', { content: '/' }),
        bc3: el('bc3', 'Text', { content: 'Sony WH-1000XM5' }),
        productSection: el('productSection', 'Row', { gap: 'xl' }, ['gallery', 'productInfo']),
        gallery: el('gallery', 'Column', { gap: 'md' }, ['mainImage', 'thumbnails']),
        mainImage: el('mainImage', 'Card', { variant: 'outlined' }, ['mainImg']),
        mainImg: el('mainImg', 'Image', { src: '/placeholder-product-large.jpg', alt: 'Sony WH-1000XM5' }),
        thumbnails: el('thumbnails', 'Row', { gap: 'sm' }, ['thumb1', 'thumb2', 'thumb3', 'thumb4']),
        thumb1: el('thumb1', 'Card', { variant: 'outlined' }, ['thumbImg1']),
        thumb2: el('thumb2', 'Card', { variant: 'outlined' }, ['thumbImg2']),
        thumb3: el('thumb3', 'Card', { variant: 'outlined' }, ['thumbImg3']),
        thumb4: el('thumb4', 'Card', { variant: 'outlined' }, ['thumbImg4']),
        thumbImg1: el('thumbImg1', 'Image', { src: '/placeholder-thumb.jpg', alt: 'Front view' }),
        thumbImg2: el('thumbImg2', 'Image', { src: '/placeholder-thumb.jpg', alt: 'Side view' }),
        thumbImg3: el('thumbImg3', 'Image', { src: '/placeholder-thumb.jpg', alt: 'Folded' }),
        thumbImg4: el('thumbImg4', 'Image', { src: '/placeholder-thumb.jpg', alt: 'With case' }),
        productInfo: el('productInfo', 'Column', { gap: 'md' }, ['productTitle', 'rating', 'price', 'description', 'colorSelect', 'quantity', 'actions', 'features']),
        productTitle: el('productTitle', 'Heading', { level: '1', text: 'Sony WH-1000XM5 Wireless Headphones' }),
        rating: el('rating', 'Row', { gap: 'sm', align: 'center' }, ['ratingStars', 'ratingCount', 'ratingLink']),
        ratingStars: el('ratingStars', 'Text', { content: '★★★★★' }),
        ratingCount: el('ratingCount', 'Text', { content: '4.8', size: 'lg' }),
        ratingLink: el('ratingLink', 'Link', { text: '2,456 reviews', href: '#reviews' }),
        price: el('price', 'Row', { gap: 'md', align: 'center' }, ['currentPrice', 'originalPrice', 'discount']),
        currentPrice: el('currentPrice', 'Heading', { level: '2', text: '$349.99' }),
        originalPrice: el('originalPrice', 'Text', { content: '$399.99', color: 'muted' }),
        discount: el('discount', 'Badge', { text: 'Save $50', color: 'success' }),
        description: el('description', 'Text', { content: 'Industry-leading noise cancellation with Auto NC Optimizer. Exceptional sound quality customizable with EQ. Crystal clear hands-free calling with 4 beamforming microphones. Up to 30 hours of battery life.', color: 'muted' }),
        colorSelect: el('colorSelect', 'Column', { gap: 'sm' }, ['colorLabel', 'colorOptions']),
        colorLabel: el('colorLabel', 'Text', { content: 'Color: Black', size: 'sm' }),
        colorOptions: el('colorOptions', 'Row', { gap: 'sm' }, ['colorBlack', 'colorSilver', 'colorBlue']),
        colorBlack: el('colorBlack', 'Badge', { text: 'Black', variant: 'solid' }),
        colorSilver: el('colorSilver', 'Badge', { text: 'Silver', variant: 'outline' }),
        colorBlue: el('colorBlue', 'Badge', { text: 'Blue', variant: 'outline' }),
        quantity: el('quantity', 'Row', { gap: 'sm', align: 'center' }, ['qtyLabel', 'qtyMinus', 'qtyValue', 'qtyPlus']),
        qtyLabel: el('qtyLabel', 'Text', { content: 'Quantity:' }),
        qtyMinus: el('qtyMinus', 'Button', { label: '-', variant: 'outline' }),
        qtyValue: el('qtyValue', 'Text', { content: '1', size: 'lg' }),
        qtyPlus: el('qtyPlus', 'Button', { label: '+', variant: 'outline' }),
        actions: el('actions', 'Row', { gap: 'md' }, ['addToCart', 'wishlist']),
        addToCart: el('addToCart', 'Button', { label: 'Add to Cart', variant: 'solid' }),
        wishlist: el('wishlist', 'Button', { label: 'Add to Wishlist', variant: 'outline' }),
        features: el('features', 'Column', { gap: 'sm' }, ['featuresTitle', 'feat1', 'feat2', 'feat3', 'feat4']),
        featuresTitle: el('featuresTitle', 'Text', { content: 'Key Features', size: 'sm' }),
        feat1: el('feat1', 'Text', { content: '• Industry-leading noise cancellation', size: 'sm', color: 'muted' }),
        feat2: el('feat2', 'Text', { content: '• 30-hour battery life', size: 'sm', color: 'muted' }),
        feat3: el('feat3', 'Text', { content: '• Multipoint connection', size: 'sm', color: 'muted' }),
        feat4: el('feat4', 'Text', { content: '• Speak-to-chat technology', size: 'sm', color: 'muted' }),
        reviews: el('reviews', 'Card', { title: 'Customer Reviews' }, ['reviewsContent']),
        reviewsContent: el('reviewsContent', 'Column', { gap: 'lg' }, ['reviewsSummary', 'reviewsList']),
        reviewsSummary: el('reviewsSummary', 'Row', { gap: 'lg', align: 'center' }, ['reviewsAvg', 'reviewsBars']),
        reviewsAvg: el('reviewsAvg', 'Column', { gap: 'sm', align: 'center' }, ['avgScore', 'avgStars', 'avgCount']),
        avgScore: el('avgScore', 'Heading', { level: '1', text: '4.8' }),
        avgStars: el('avgStars', 'Text', { content: '★★★★★' }),
        avgCount: el('avgCount', 'Text', { content: '2,456 reviews', color: 'muted' }),
        reviewsBars: el('reviewsBars', 'Column', { gap: 'xs' }, ['bar5', 'bar4', 'bar3', 'bar2', 'bar1']),
        bar5: el('bar5', 'Row', { gap: 'sm', align: 'center' }, ['bar5Label', 'bar5Progress', 'bar5Count']),
        bar4: el('bar4', 'Row', { gap: 'sm', align: 'center' }, ['bar4Label', 'bar4Progress', 'bar4Count']),
        bar3: el('bar3', 'Row', { gap: 'sm', align: 'center' }, ['bar3Label', 'bar3Progress', 'bar3Count']),
        bar2: el('bar2', 'Row', { gap: 'sm', align: 'center' }, ['bar2Label', 'bar2Progress', 'bar2Count']),
        bar1: el('bar1', 'Row', { gap: 'sm', align: 'center' }, ['bar1Label', 'bar1Progress', 'bar1Count']),
        bar5Label: el('bar5Label', 'Text', { content: '5 star', size: 'sm' }),
        bar5Progress: el('bar5Progress', 'Progress', { value: 82, max: 100 }),
        bar5Count: el('bar5Count', 'Text', { content: '82%', size: 'sm' }),
        bar4Label: el('bar4Label', 'Text', { content: '4 star', size: 'sm' }),
        bar4Progress: el('bar4Progress', 'Progress', { value: 12, max: 100 }),
        bar4Count: el('bar4Count', 'Text', { content: '12%', size: 'sm' }),
        bar3Label: el('bar3Label', 'Text', { content: '3 star', size: 'sm' }),
        bar3Progress: el('bar3Progress', 'Progress', { value: 4, max: 100 }),
        bar3Count: el('bar3Count', 'Text', { content: '4%', size: 'sm' }),
        bar2Label: el('bar2Label', 'Text', { content: '2 star', size: 'sm' }),
        bar2Progress: el('bar2Progress', 'Progress', { value: 1, max: 100 }),
        bar2Count: el('bar2Count', 'Text', { content: '1%', size: 'sm' }),
        bar1Label: el('bar1Label', 'Text', { content: '1 star', size: 'sm' }),
        bar1Progress: el('bar1Progress', 'Progress', { value: 1, max: 100 }),
        bar1Count: el('bar1Count', 'Text', { content: '1%', size: 'sm' }),
        reviewsList: el('reviewsList', 'Column', { gap: 'md' }, ['review1', 'review2']),
        review1: el('review1', 'Card', { variant: 'outlined' }, ['review1Content']),
        review2: el('review2', 'Card', { variant: 'outlined' }, ['review2Content']),
        review1Content: el('review1Content', 'Column', { gap: 'sm' }, ['review1Header', 'review1Text', 'review1Helpful']),
        review1Header: el('review1Header', 'Row', { justify: 'between', align: 'center' }, ['review1Author', 'review1Date']),
        review1Author: el('review1Author', 'Row', { gap: 'sm', align: 'center' }, ['review1Avatar', 'review1Name', 'review1Stars']),
        review1Avatar: el('review1Avatar', 'Avatar', { name: 'John D.', size: 'sm' }),
        review1Name: el('review1Name', 'Text', { content: 'John D.' }),
        review1Stars: el('review1Stars', 'Text', { content: '★★★★★' }),
        review1Date: el('review1Date', 'Text', { content: '2 days ago', color: 'muted', size: 'sm' }),
        review1Text: el('review1Text', 'Text', { content: 'Best headphones I have ever owned. The noise cancellation is incredible and the sound quality is amazing. Battery life is exactly as advertised.' }),
        review1Helpful: el('review1Helpful', 'Row', { gap: 'sm' }, ['review1HelpfulText', 'review1HelpfulBtn']),
        review1HelpfulText: el('review1HelpfulText', 'Text', { content: '45 people found this helpful', color: 'muted', size: 'sm' }),
        review1HelpfulBtn: el('review1HelpfulBtn', 'Button', { label: 'Helpful', variant: 'ghost', size: 'sm' }),
        review2Content: el('review2Content', 'Column', { gap: 'sm' }, ['review2Header', 'review2Text', 'review2Helpful']),
        review2Header: el('review2Header', 'Row', { justify: 'between', align: 'center' }, ['review2Author', 'review2Date']),
        review2Author: el('review2Author', 'Row', { gap: 'sm', align: 'center' }, ['review2Avatar', 'review2Name', 'review2Stars']),
        review2Avatar: el('review2Avatar', 'Avatar', { name: 'Sarah M.', size: 'sm' }),
        review2Name: el('review2Name', 'Text', { content: 'Sarah M.' }),
        review2Stars: el('review2Stars', 'Text', { content: '★★★★☆' }),
        review2Date: el('review2Date', 'Text', { content: '1 week ago', color: 'muted', size: 'sm' }),
        review2Text: el('review2Text', 'Text', { content: 'Great headphones overall. The only reason I gave 4 stars is because they are a bit pricey, but the quality justifies it.' }),
        review2Helpful: el('review2Helpful', 'Row', { gap: 'sm' }, ['review2HelpfulText', 'review2HelpfulBtn']),
        review2HelpfulText: el('review2HelpfulText', 'Text', { content: '23 people found this helpful', color: 'muted', size: 'sm' }),
        review2HelpfulBtn: el('review2HelpfulBtn', 'Button', { label: 'Helpful', variant: 'ghost', size: 'sm' }),
        related: el('related', 'Column', { gap: 'md' }, ['relatedTitle', 'relatedGrid']),
        relatedTitle: el('relatedTitle', 'Heading', { level: '2', text: 'You May Also Like' }),
        relatedGrid: el('relatedGrid', 'Grid', { columns: 4, gap: 'md' }, ['rel1', 'rel2', 'rel3', 'rel4']),
        rel1: el('rel1', 'Card', { variant: 'elevated', hoverable: true }, ['rel1Img', 'rel1Name', 'rel1Price']),
        rel2: el('rel2', 'Card', { variant: 'elevated', hoverable: true }, ['rel2Img', 'rel2Name', 'rel2Price']),
        rel3: el('rel3', 'Card', { variant: 'elevated', hoverable: true }, ['rel3Img', 'rel3Name', 'rel3Price']),
        rel4: el('rel4', 'Card', { variant: 'elevated', hoverable: true }, ['rel4Img', 'rel4Name', 'rel4Price']),
        rel1Img: el('rel1Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Carrying Case' }),
        rel1Name: el('rel1Name', 'Text', { content: 'Carrying Case' }),
        rel1Price: el('rel1Price', 'Text', { content: '$29.99' }),
        rel2Img: el('rel2Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Replacement Ear Pads' }),
        rel2Name: el('rel2Name', 'Text', { content: 'Replacement Ear Pads' }),
        rel2Price: el('rel2Price', 'Text', { content: '$24.99' }),
        rel3Img: el('rel3Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Audio Cable' }),
        rel3Name: el('rel3Name', 'Text', { content: 'Audio Cable 3.5mm' }),
        rel3Price: el('rel3Price', 'Text', { content: '$14.99' }),
        rel4Img: el('rel4Img', 'Image', { src: '/placeholder-product.jpg', alt: 'USB-C Charger' }),
        rel4Name: el('rel4Name', 'Text', { content: 'USB-C Fast Charger' }),
        rel4Price: el('rel4Price', 'Text', { content: '$19.99' }),
      },
    },
  },
  {
    id: 'ecommerce-cart',
    name: 'Shopping Cart',
    description: 'Cart page with items, summary, and checkout button',
    category: 'ecommerce',
    tags: ['ecommerce', 'cart', 'shopping', 'checkout'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'xl' }, ['header', 'content']),
        header: el('header', 'Heading', { level: '1', text: 'Shopping Cart' }),
        content: el('content', 'Row', { gap: 'xl' }, ['cartItems', 'summary']),
        cartItems: el('cartItems', 'Column', { gap: 'md' }, ['item1', 'item2', 'item3']),
        item1: el('item1', 'Card', { variant: 'outlined' }, ['item1Content']),
        item2: el('item2', 'Card', { variant: 'outlined' }, ['item2Content']),
        item3: el('item3', 'Card', { variant: 'outlined' }, ['item3Content']),
        item1Content: el('item1Content', 'Row', { gap: 'lg', align: 'center' }, ['item1Img', 'item1Info', 'item1Actions']),
        item1Img: el('item1Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Sony Headphones' }),
        item1Info: el('item1Info', 'Column', { gap: 'sm' }, ['item1Name', 'item1Color', 'item1Price']),
        item1Name: el('item1Name', 'Text', { content: 'Sony WH-1000XM5' }),
        item1Color: el('item1Color', 'Text', { content: 'Color: Black', color: 'muted', size: 'sm' }),
        item1Price: el('item1Price', 'Text', { content: '$349.99', size: 'lg' }),
        item1Actions: el('item1Actions', 'Column', { gap: 'sm', align: 'end' }, ['item1Qty', 'item1Remove']),
        item1Qty: el('item1Qty', 'Row', { gap: 'sm', align: 'center' }, ['item1Minus', 'item1QtyVal', 'item1Plus']),
        item1Minus: el('item1Minus', 'Button', { label: '-', variant: 'outline', size: 'sm' }),
        item1QtyVal: el('item1QtyVal', 'Text', { content: '1' }),
        item1Plus: el('item1Plus', 'Button', { label: '+', variant: 'outline', size: 'sm' }),
        item1Remove: el('item1Remove', 'Button', { label: 'Remove', variant: 'ghost', size: 'sm' }),
        item2Content: el('item2Content', 'Row', { gap: 'lg', align: 'center' }, ['item2Img', 'item2Info', 'item2Actions']),
        item2Img: el('item2Img', 'Image', { src: '/placeholder-product.jpg', alt: 'Carrying Case' }),
        item2Info: el('item2Info', 'Column', { gap: 'sm' }, ['item2Name', 'item2Color', 'item2Price']),
        item2Name: el('item2Name', 'Text', { content: 'Premium Carrying Case' }),
        item2Color: el('item2Color', 'Text', { content: 'Color: Black', color: 'muted', size: 'sm' }),
        item2Price: el('item2Price', 'Text', { content: '$29.99', size: 'lg' }),
        item2Actions: el('item2Actions', 'Column', { gap: 'sm', align: 'end' }, ['item2Qty', 'item2Remove']),
        item2Qty: el('item2Qty', 'Row', { gap: 'sm', align: 'center' }, ['item2Minus', 'item2QtyVal', 'item2Plus']),
        item2Minus: el('item2Minus', 'Button', { label: '-', variant: 'outline', size: 'sm' }),
        item2QtyVal: el('item2QtyVal', 'Text', { content: '1' }),
        item2Plus: el('item2Plus', 'Button', { label: '+', variant: 'outline', size: 'sm' }),
        item2Remove: el('item2Remove', 'Button', { label: 'Remove', variant: 'ghost', size: 'sm' }),
        item3Content: el('item3Content', 'Row', { gap: 'lg', align: 'center' }, ['item3Img', 'item3Info', 'item3Actions']),
        item3Img: el('item3Img', 'Image', { src: '/placeholder-product.jpg', alt: 'USB-C Cable' }),
        item3Info: el('item3Info', 'Column', { gap: 'sm' }, ['item3Name', 'item3Color', 'item3Price']),
        item3Name: el('item3Name', 'Text', { content: 'USB-C Charging Cable' }),
        item3Color: el('item3Color', 'Text', { content: 'Length: 6ft', color: 'muted', size: 'sm' }),
        item3Price: el('item3Price', 'Text', { content: '$14.99', size: 'lg' }),
        item3Actions: el('item3Actions', 'Column', { gap: 'sm', align: 'end' }, ['item3Qty', 'item3Remove']),
        item3Qty: el('item3Qty', 'Row', { gap: 'sm', align: 'center' }, ['item3Minus', 'item3QtyVal', 'item3Plus']),
        item3Minus: el('item3Minus', 'Button', { label: '-', variant: 'outline', size: 'sm' }),
        item3QtyVal: el('item3QtyVal', 'Text', { content: '2' }),
        item3Plus: el('item3Plus', 'Button', { label: '+', variant: 'outline', size: 'sm' }),
        item3Remove: el('item3Remove', 'Button', { label: 'Remove', variant: 'ghost', size: 'sm' }),
        summary: el('summary', 'Card', { title: 'Order Summary' }, ['summaryContent']),
        summaryContent: el('summaryContent', 'Column', { gap: 'md' }, ['promoCode', 'subtotal', 'shipping', 'tax', 'total', 'checkoutBtn', 'continueShopping']),
        promoCode: el('promoCode', 'Row', { gap: 'sm' }, ['promoInput', 'promoBtn']),
        promoInput: el('promoInput', 'Input', { placeholder: 'Promo code' }),
        promoBtn: el('promoBtn', 'Button', { label: 'Apply', variant: 'outline' }),
        subtotal: el('subtotal', 'Row', { justify: 'between' }, ['subtotalLabel', 'subtotalValue']),
        subtotalLabel: el('subtotalLabel', 'Text', { content: 'Subtotal' }),
        subtotalValue: el('subtotalValue', 'Text', { content: '$409.96' }),
        shipping: el('shipping', 'Row', { justify: 'between' }, ['shippingLabel', 'shippingValue']),
        shippingLabel: el('shippingLabel', 'Text', { content: 'Shipping' }),
        shippingValue: el('shippingValue', 'Text', { content: 'FREE', color: 'success' }),
        tax: el('tax', 'Row', { justify: 'between' }, ['taxLabel', 'taxValue']),
        taxLabel: el('taxLabel', 'Text', { content: 'Tax' }),
        taxValue: el('taxValue', 'Text', { content: '$32.80' }),
        total: el('total', 'Row', { justify: 'between' }, ['totalLabel', 'totalValue']),
        totalLabel: el('totalLabel', 'Heading', { level: '4', text: 'Total' }),
        totalValue: el('totalValue', 'Heading', { level: '4', text: '$442.76' }),
        checkoutBtn: el('checkoutBtn', 'Button', { label: 'Proceed to Checkout', variant: 'solid', fullWidth: true }),
        continueShopping: el('continueShopping', 'Button', { label: 'Continue Shopping', variant: 'ghost', fullWidth: true }),
      },
    },
  },
  {
    id: 'ecommerce-checkout',
    name: 'Checkout Flow',
    description: 'Multi-step checkout with shipping, payment, and confirmation',
    category: 'ecommerce',
    tags: ['ecommerce', 'checkout', 'payment', 'shipping', 'form'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'lg' }, ['header', 'stepper', 'content']),
        header: el('header', 'Heading', { level: '1', text: 'Checkout', align: 'center' }),
        stepper: el('stepper', 'Row', { justify: 'center', gap: 'lg' }, ['step1', 'stepLine1', 'step2', 'stepLine2', 'step3']),
        step1: el('step1', 'Column', { align: 'center', gap: 'xs' }, ['step1Badge', 'step1Label']),
        step1Badge: el('step1Badge', 'Badge', { text: '1', variant: 'solid', color: 'success' }),
        step1Label: el('step1Label', 'Text', { content: 'Shipping', size: 'sm' }),
        stepLine1: el('stepLine1', 'Text', { content: '---' }),
        step2: el('step2', 'Column', { align: 'center', gap: 'xs' }, ['step2Badge', 'step2Label']),
        step2Badge: el('step2Badge', 'Badge', { text: '2', variant: 'solid', color: 'info' }),
        step2Label: el('step2Label', 'Text', { content: 'Payment', size: 'sm' }),
        stepLine2: el('stepLine2', 'Text', { content: '---', color: 'muted' }),
        step3: el('step3', 'Column', { align: 'center', gap: 'xs' }, ['step3Badge', 'step3Label']),
        step3Badge: el('step3Badge', 'Badge', { text: '3', variant: 'outline' }),
        step3Label: el('step3Label', 'Text', { content: 'Confirm', size: 'sm', color: 'muted' }),
        content: el('content', 'Row', { gap: 'xl' }, ['form', 'summary']),
        form: el('form', 'Card', { title: 'Payment Information' }, ['formContent']),
        formContent: el('formContent', 'Column', { gap: 'md' }, ['cardNumber', 'cardRow', 'cardName', 'billingAddr', 'sameBilling', 'actions']),
        cardNumber: el('cardNumber', 'Input', { label: 'Card Number', placeholder: '1234 5678 9012 3456' }),
        cardRow: el('cardRow', 'Row', { gap: 'md' }, ['expiry', 'cvv']),
        expiry: el('expiry', 'Input', { label: 'Expiry Date', placeholder: 'MM/YY' }),
        cvv: el('cvv', 'Input', { label: 'CVV', placeholder: '123' }),
        cardName: el('cardName', 'Input', { label: 'Name on Card', placeholder: 'John Doe' }),
        billingAddr: el('billingAddr', 'Text', { content: 'Billing Address', size: 'sm' }),
        sameBilling: el('sameBilling', 'Checkbox', { label: 'Same as shipping address' }),
        actions: el('actions', 'Row', { justify: 'between' }, ['backBtn', 'nextBtn']),
        backBtn: el('backBtn', 'Button', { label: 'Back', variant: 'outline' }),
        nextBtn: el('nextBtn', 'Button', { label: 'Review Order', variant: 'solid' }),
        summary: el('summary', 'Card', { title: 'Order Summary' }, ['summaryContent']),
        summaryContent: el('summaryContent', 'Column', { gap: 'md' }, ['summaryItems', 'summaryTotals']),
        summaryItems: el('summaryItems', 'Column', { gap: 'sm' }, ['sumItem1', 'sumItem2']),
        sumItem1: el('sumItem1', 'Row', { justify: 'between' }, ['sumItem1Name', 'sumItem1Price']),
        sumItem1Name: el('sumItem1Name', 'Text', { content: 'Sony WH-1000XM5 x1', size: 'sm' }),
        sumItem1Price: el('sumItem1Price', 'Text', { content: '$349.99', size: 'sm' }),
        sumItem2: el('sumItem2', 'Row', { justify: 'between' }, ['sumItem2Name', 'sumItem2Price']),
        sumItem2Name: el('sumItem2Name', 'Text', { content: 'Carrying Case x1', size: 'sm' }),
        sumItem2Price: el('sumItem2Price', 'Text', { content: '$29.99', size: 'sm' }),
        summaryTotals: el('summaryTotals', 'Column', { gap: 'sm' }, ['sumSubtotal', 'sumShipping', 'sumTax', 'sumTotal']),
        sumSubtotal: el('sumSubtotal', 'Row', { justify: 'between' }, ['subtotalLabel', 'subtotalVal']),
        subtotalLabel: el('subtotalLabel', 'Text', { content: 'Subtotal', color: 'muted', size: 'sm' }),
        subtotalVal: el('subtotalVal', 'Text', { content: '$379.98', size: 'sm' }),
        sumShipping: el('sumShipping', 'Row', { justify: 'between' }, ['shipLabel', 'shipVal']),
        shipLabel: el('shipLabel', 'Text', { content: 'Shipping', color: 'muted', size: 'sm' }),
        shipVal: el('shipVal', 'Text', { content: 'FREE', color: 'success', size: 'sm' }),
        sumTax: el('sumTax', 'Row', { justify: 'between' }, ['taxLabel', 'taxVal']),
        taxLabel: el('taxLabel', 'Text', { content: 'Tax', color: 'muted', size: 'sm' }),
        taxVal: el('taxVal', 'Text', { content: '$30.40', size: 'sm' }),
        sumTotal: el('sumTotal', 'Row', { justify: 'between' }, ['totalLabel', 'totalVal']),
        totalLabel: el('totalLabel', 'Text', { content: 'Total' }),
        totalVal: el('totalVal', 'Heading', { level: '4', text: '$410.38' }),
      },
    },
  },
  {
    id: 'ecommerce-order-history',
    name: 'Order History',
    description: 'Customer order history with status and tracking',
    category: 'ecommerce',
    tags: ['ecommerce', 'orders', 'history', 'tracking', 'account'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'xl' }, ['header', 'filters', 'orders']),
        header: el('header', 'Heading', { level: '1', text: 'Order History' }),
        filters: el('filters', 'Row', { gap: 'md', align: 'end' }, ['searchInput', 'statusFilter', 'dateFilter']),
        searchInput: el('searchInput', 'Input', { label: 'Search Orders', placeholder: 'Order number or item...' }),
        statusFilter: el('statusFilter', 'Select', { label: 'Status', options: [{ value: 'all', label: 'All Orders' }, { value: 'processing', label: 'Processing' }, { value: 'shipped', label: 'Shipped' }, { value: 'delivered', label: 'Delivered' }] }),
        dateFilter: el('dateFilter', 'Select', { label: 'Date', options: [{ value: '30', label: 'Last 30 days' }, { value: '90', label: 'Last 90 days' }, { value: 'year', label: 'This year' }] }),
        orders: el('orders', 'Column', { gap: 'md' }, ['order1', 'order2', 'order3']),
        order1: el('order1', 'Card', { variant: 'outlined' }, ['order1Content']),
        order2: el('order2', 'Card', { variant: 'outlined' }, ['order2Content']),
        order3: el('order3', 'Card', { variant: 'outlined' }, ['order3Content']),
        order1Content: el('order1Content', 'Column', { gap: 'md' }, ['order1Header', 'order1Items', 'order1Footer']),
        order1Header: el('order1Header', 'Row', { justify: 'between', align: 'center' }, ['order1Info', 'order1Status']),
        order1Info: el('order1Info', 'Row', { gap: 'lg' }, ['order1Number', 'order1Date', 'order1Total']),
        order1Number: el('order1Number', 'Text', { content: 'Order #ORD-12345' }),
        order1Date: el('order1Date', 'Text', { content: 'January 28, 2024', color: 'muted' }),
        order1Total: el('order1Total', 'Text', { content: '$379.98' }),
        order1Status: el('order1Status', 'Badge', { text: 'Delivered', color: 'success' }),
        order1Items: el('order1Items', 'Row', { gap: 'md' }, ['order1Item1', 'order1Item2']),
        order1Item1: el('order1Item1', 'Row', { gap: 'sm', align: 'center' }, ['order1Img1', 'order1Name1']),
        order1Img1: el('order1Img1', 'Image', { src: '/placeholder-product.jpg', alt: 'Sony Headphones' }),
        order1Name1: el('order1Name1', 'Text', { content: 'Sony WH-1000XM5', size: 'sm' }),
        order1Item2: el('order1Item2', 'Row', { gap: 'sm', align: 'center' }, ['order1Img2', 'order1Name2']),
        order1Img2: el('order1Img2', 'Image', { src: '/placeholder-product.jpg', alt: 'Carrying Case' }),
        order1Name2: el('order1Name2', 'Text', { content: 'Carrying Case', size: 'sm' }),
        order1Footer: el('order1Footer', 'Row', { gap: 'sm' }, ['order1ViewBtn', 'order1TrackBtn', 'order1ReviewBtn']),
        order1ViewBtn: el('order1ViewBtn', 'Button', { label: 'View Details', variant: 'outline', size: 'sm' }),
        order1TrackBtn: el('order1TrackBtn', 'Button', { label: 'Track Package', variant: 'ghost', size: 'sm' }),
        order1ReviewBtn: el('order1ReviewBtn', 'Button', { label: 'Write Review', variant: 'ghost', size: 'sm' }),
        order2Content: el('order2Content', 'Column', { gap: 'md' }, ['order2Header', 'order2Items', 'order2Footer']),
        order2Header: el('order2Header', 'Row', { justify: 'between', align: 'center' }, ['order2Info', 'order2Status']),
        order2Info: el('order2Info', 'Row', { gap: 'lg' }, ['order2Number', 'order2Date', 'order2Total']),
        order2Number: el('order2Number', 'Text', { content: 'Order #ORD-12344' }),
        order2Date: el('order2Date', 'Text', { content: 'January 20, 2024', color: 'muted' }),
        order2Total: el('order2Total', 'Text', { content: '$129.95' }),
        order2Status: el('order2Status', 'Badge', { text: 'Shipped', color: 'info' }),
        order2Items: el('order2Items', 'Row', { gap: 'md' }, ['order2Item1']),
        order2Item1: el('order2Item1', 'Row', { gap: 'sm', align: 'center' }, ['order2Img1', 'order2Name1']),
        order2Img1: el('order2Img1', 'Image', { src: '/placeholder-product.jpg', alt: 'JBL Headphones' }),
        order2Name1: el('order2Name1', 'Text', { content: 'JBL Tune 760NC', size: 'sm' }),
        order2Footer: el('order2Footer', 'Row', { gap: 'sm' }, ['order2ViewBtn', 'order2TrackBtn']),
        order2ViewBtn: el('order2ViewBtn', 'Button', { label: 'View Details', variant: 'outline', size: 'sm' }),
        order2TrackBtn: el('order2TrackBtn', 'Button', { label: 'Track Package', variant: 'solid', size: 'sm' }),
        order3Content: el('order3Content', 'Column', { gap: 'md' }, ['order3Header', 'order3Items', 'order3Footer']),
        order3Header: el('order3Header', 'Row', { justify: 'between', align: 'center' }, ['order3Info', 'order3Status']),
        order3Info: el('order3Info', 'Row', { gap: 'lg' }, ['order3Number', 'order3Date', 'order3Total']),
        order3Number: el('order3Number', 'Text', { content: 'Order #ORD-12343' }),
        order3Date: el('order3Date', 'Text', { content: 'January 15, 2024', color: 'muted' }),
        order3Total: el('order3Total', 'Text', { content: '$549.00' }),
        order3Status: el('order3Status', 'Badge', { text: 'Processing', color: 'warning' }),
        order3Items: el('order3Items', 'Row', { gap: 'md' }, ['order3Item1']),
        order3Item1: el('order3Item1', 'Row', { gap: 'sm', align: 'center' }, ['order3Img1', 'order3Name1']),
        order3Img1: el('order3Img1', 'Image', { src: '/placeholder-product.jpg', alt: 'AirPods Max' }),
        order3Name1: el('order3Name1', 'Text', { content: 'Apple AirPods Max', size: 'sm' }),
        order3Footer: el('order3Footer', 'Row', { gap: 'sm' }, ['order3ViewBtn', 'order3CancelBtn']),
        order3ViewBtn: el('order3ViewBtn', 'Button', { label: 'View Details', variant: 'outline', size: 'sm' }),
        order3CancelBtn: el('order3CancelBtn', 'Button', { label: 'Cancel Order', variant: 'ghost', size: 'sm' }),
      },
    },
  },
  {
    id: 'ecommerce-account-settings',
    name: 'Account Settings',
    description: 'Account profile, addresses, and payment methods',
    category: 'ecommerce',
    tags: ['ecommerce', 'account', 'settings', 'profile', 'addresses'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'lg' }, ['header', 'tabs', 'content']),
        header: el('header', 'Heading', { level: '1', text: 'Account Settings' }),
        tabs: el('tabs', 'Row', { gap: 'md' }, ['tabProfile', 'tabAddresses', 'tabPayment', 'tabNotifications']),
        tabProfile: el('tabProfile', 'Button', { label: 'Profile', variant: 'solid' }),
        tabAddresses: el('tabAddresses', 'Button', { label: 'Addresses', variant: 'ghost' }),
        tabPayment: el('tabPayment', 'Button', { label: 'Payment', variant: 'ghost' }),
        tabNotifications: el('tabNotifications', 'Button', { label: 'Notifications', variant: 'ghost' }),
        content: el('content', 'Card', { title: 'Profile Information' }, ['profileContent']),
        profileContent: el('profileContent', 'Column', { gap: 'lg' }, ['avatarSection', 'formSection', 'actionSection']),
        avatarSection: el('avatarSection', 'Row', { gap: 'md', align: 'center' }, ['avatar', 'avatarActions']),
        avatar: el('avatar', 'Avatar', { name: 'John Doe', size: 'lg' }),
        avatarActions: el('avatarActions', 'Column', { gap: 'sm' }, ['changePhotoBtn', 'removePhotoBtn']),
        changePhotoBtn: el('changePhotoBtn', 'Button', { label: 'Change Photo', variant: 'outline', size: 'sm' }),
        removePhotoBtn: el('removePhotoBtn', 'Button', { label: 'Remove', variant: 'ghost', size: 'sm' }),
        formSection: el('formSection', 'Column', { gap: 'md' }, ['nameRow', 'emailField', 'phoneField', 'passwordSection']),
        nameRow: el('nameRow', 'Row', { gap: 'md' }, ['firstNameField', 'lastNameField']),
        firstNameField: el('firstNameField', 'Input', { label: 'First Name', placeholder: 'John' }),
        lastNameField: el('lastNameField', 'Input', { label: 'Last Name', placeholder: 'Doe' }),
        emailField: el('emailField', 'Input', { label: 'Email', type: 'email', placeholder: 'john@example.com' }),
        phoneField: el('phoneField', 'Input', { label: 'Phone', placeholder: '(555) 123-4567' }),
        passwordSection: el('passwordSection', 'Column', { gap: 'sm' }, ['passwordLabel', 'passwordRow']),
        passwordLabel: el('passwordLabel', 'Text', { content: 'Password', size: 'sm' }),
        passwordRow: el('passwordRow', 'Row', { gap: 'md', align: 'center' }, ['passwordMask', 'changePasswordBtn']),
        passwordMask: el('passwordMask', 'Text', { content: '••••••••••' }),
        changePasswordBtn: el('changePasswordBtn', 'Button', { label: 'Change Password', variant: 'ghost', size: 'sm' }),
        actionSection: el('actionSection', 'Row', { justify: 'between' }, ['deleteAccountBtn', 'saveBtn']),
        deleteAccountBtn: el('deleteAccountBtn', 'Button', { label: 'Delete Account', variant: 'ghost' }),
        saveBtn: el('saveBtn', 'Button', { label: 'Save Changes', variant: 'solid' }),
      },
    },
  },
];
