/**
 * Form Test Cases
 * Real-world form UI configurations
 */

import type { UITree, UIElement } from '@json-render/core';
import type { TestCase } from './test-cases';

function el(key: string, type: string, props: Record<string, unknown>, children?: string[]): UIElement {
  return { key, type, props, children };
}

export const formTestCases: TestCase[] = [
  {
    id: 'form-multi-step-registration',
    name: 'Multi-step Registration Form',
    description: 'User registration with progress steps',
    category: 'forms',
    tags: ['form', 'registration', 'multi-step', 'wizard', 'signup'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'md' }, ['card']),
        card: el('card', 'Card', {}, ['stepper', 'form', 'actions']),
        stepper: el('stepper', 'Row', { justify: 'center', gap: 'lg' }, ['step1', 'step2', 'step3', 'step4']),
        step1: el('step1', 'Column', { align: 'center', gap: 'xs' }, ['step1Badge', 'step1Label']),
        step1Badge: el('step1Badge', 'Badge', { text: '1', variant: 'solid', color: 'success' }),
        step1Label: el('step1Label', 'Text', { content: 'Account', size: 'sm' }),
        step2: el('step2', 'Column', { align: 'center', gap: 'xs' }, ['step2Badge', 'step2Label']),
        step2Badge: el('step2Badge', 'Badge', { text: '2', variant: 'solid', color: 'info' }),
        step2Label: el('step2Label', 'Text', { content: 'Personal', size: 'sm' }),
        step3: el('step3', 'Column', { align: 'center', gap: 'xs' }, ['step3Badge', 'step3Label']),
        step3Badge: el('step3Badge', 'Badge', { text: '3', variant: 'outline' }),
        step3Label: el('step3Label', 'Text', { content: 'Preferences', size: 'sm', color: 'muted' }),
        step4: el('step4', 'Column', { align: 'center', gap: 'xs' }, ['step4Badge', 'step4Label']),
        step4Badge: el('step4Badge', 'Badge', { text: '4', variant: 'outline' }),
        step4Label: el('step4Label', 'Text', { content: 'Confirm', size: 'sm', color: 'muted' }),
        form: el('form', 'Column', { gap: 'lg' }, ['formTitle', 'formFields']),
        formTitle: el('formTitle', 'Heading', { level: '3', text: 'Personal Information', align: 'center' }),
        formFields: el('formFields', 'Column', { gap: 'md' }, ['nameRow', 'dobField', 'genderField', 'phoneField', 'addressField', 'cityRow']),
        nameRow: el('nameRow', 'Row', { gap: 'md' }, ['firstName', 'lastName']),
        firstName: el('firstName', 'Input', { label: 'First Name', placeholder: 'John', required: true }),
        lastName: el('lastName', 'Input', { label: 'Last Name', placeholder: 'Doe', required: true }),
        dobField: el('dobField', 'Input', { label: 'Date of Birth', type: 'date', required: true }),
        genderField: el('genderField', 'Select', { label: 'Gender', options: [{ value: '', label: 'Select gender' }, { value: 'male', label: 'Male' }, { value: 'female', label: 'Female' }, { value: 'other', label: 'Other' }, { value: 'prefer-not', label: 'Prefer not to say' }] }),
        phoneField: el('phoneField', 'Input', { label: 'Phone Number', type: 'tel', placeholder: '(555) 123-4567' }),
        addressField: el('addressField', 'Input', { label: 'Street Address', placeholder: '123 Main Street' }),
        cityRow: el('cityRow', 'Row', { gap: 'md' }, ['cityField', 'stateField', 'zipField']),
        cityField: el('cityField', 'Input', { label: 'City', placeholder: 'New York' }),
        stateField: el('stateField', 'Select', { label: 'State', options: [{ value: '', label: 'Select' }, { value: 'NY', label: 'New York' }, { value: 'CA', label: 'California' }, { value: 'TX', label: 'Texas' }] }),
        zipField: el('zipField', 'Input', { label: 'ZIP Code', placeholder: '10001' }),
        actions: el('actions', 'Row', { justify: 'between' }, ['backBtn', 'nextBtn']),
        backBtn: el('backBtn', 'Button', { label: 'Back', variant: 'outline' }),
        nextBtn: el('nextBtn', 'Button', { label: 'Next Step', variant: 'solid' }),
      },
    },
  },
  {
    id: 'form-contact-validation',
    name: 'Contact Form with Validation',
    description: 'Contact form with field validation indicators',
    category: 'forms',
    tags: ['form', 'contact', 'validation', 'required'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'sm' }, ['card']),
        card: el('card', 'Card', { title: 'Contact Us' }, ['form']),
        form: el('form', 'Column', { gap: 'md' }, ['intro', 'nameField', 'emailField', 'subjectField', 'messageField', 'consent', 'submitBtn']),
        intro: el('intro', 'Text', { content: 'Have a question or feedback? We would love to hear from you.', color: 'muted' }),
        nameField: el('nameField', 'Column', { gap: 'xs' }, ['nameInput', 'nameError']),
        nameInput: el('nameInput', 'Input', { label: 'Full Name', placeholder: 'Your name', required: true }),
        nameError: el('nameError', 'Text', { content: 'Please enter your name', color: 'error', size: 'sm' }),
        emailField: el('emailField', 'Column', { gap: 'xs' }, ['emailInput', 'emailHelp']),
        emailInput: el('emailInput', 'Input', { label: 'Email Address', type: 'email', placeholder: 'you@example.com', required: true }),
        emailHelp: el('emailHelp', 'Text', { content: 'We will never share your email.', color: 'muted', size: 'sm' }),
        subjectField: el('subjectField', 'Select', { label: 'Subject', required: true, options: [{ value: '', label: 'Select a topic' }, { value: 'general', label: 'General Inquiry' }, { value: 'support', label: 'Technical Support' }, { value: 'billing', label: 'Billing Question' }, { value: 'feedback', label: 'Feedback' }] }),
        messageField: el('messageField', 'TextArea', { label: 'Message', placeholder: 'How can we help you?', rows: 5, required: true }),
        consent: el('consent', 'Checkbox', { label: 'I agree to the privacy policy and terms of service' }),
        submitBtn: el('submitBtn', 'Button', { label: 'Send Message', variant: 'solid', fullWidth: true }),
      },
    },
  },
  {
    id: 'form-survey',
    name: 'Survey/Questionnaire Form',
    description: 'Multi-question survey with various input types',
    category: 'forms',
    tags: ['form', 'survey', 'questionnaire', 'feedback'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'md' }, ['card']),
        card: el('card', 'Card', {}, ['header', 'progress', 'question', 'actions']),
        header: el('header', 'Column', { gap: 'sm' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'Customer Satisfaction Survey' }),
        subtitle: el('subtitle', 'Text', { content: 'Help us improve our service by answering a few questions.', color: 'muted' }),
        progress: el('progress', 'Column', { gap: 'xs' }, ['progressLabel', 'progressBar']),
        progressLabel: el('progressLabel', 'Row', { justify: 'between' }, ['progressText', 'progressCount']),
        progressText: el('progressText', 'Text', { content: 'Progress', size: 'sm', color: 'muted' }),
        progressCount: el('progressCount', 'Text', { content: '3 of 10', size: 'sm', color: 'muted' }),
        progressBar: el('progressBar', 'Progress', { value: 30, max: 100 }),
        question: el('question', 'Column', { gap: 'lg' }, ['q3']),
        q3: el('q3', 'Column', { gap: 'md' }, ['q3Label', 'q3Options']),
        q3Label: el('q3Label', 'Text', { content: '3. How satisfied are you with our product quality?' }),
        q3Options: el('q3Options', 'Column', { gap: 'sm' }, ['q3Opt1', 'q3Opt2', 'q3Opt3', 'q3Opt4', 'q3Opt5']),
        q3Opt1: el('q3Opt1', 'Row', { gap: 'sm', align: 'center' }, ['q3Radio1', 'q3Label1']),
        q3Opt2: el('q3Opt2', 'Row', { gap: 'sm', align: 'center' }, ['q3Radio2', 'q3Label2']),
        q3Opt3: el('q3Opt3', 'Row', { gap: 'sm', align: 'center' }, ['q3Radio3', 'q3Label3']),
        q3Opt4: el('q3Opt4', 'Row', { gap: 'sm', align: 'center' }, ['q3Radio4', 'q3Label4']),
        q3Opt5: el('q3Opt5', 'Row', { gap: 'sm', align: 'center' }, ['q3Radio5', 'q3Label5']),
        q3Radio1: el('q3Radio1', 'Checkbox', {}),
        q3Label1: el('q3Label1', 'Text', { content: 'Very Satisfied' }),
        q3Radio2: el('q3Radio2', 'Checkbox', {}),
        q3Label2: el('q3Label2', 'Text', { content: 'Satisfied' }),
        q3Radio3: el('q3Radio3', 'Checkbox', {}),
        q3Label3: el('q3Label3', 'Text', { content: 'Neutral' }),
        q3Radio4: el('q3Radio4', 'Checkbox', {}),
        q3Label4: el('q3Label4', 'Text', { content: 'Dissatisfied' }),
        q3Radio5: el('q3Radio5', 'Checkbox', {}),
        q3Label5: el('q3Label5', 'Text', { content: 'Very Dissatisfied' }),
        actions: el('actions', 'Row', { justify: 'between' }, ['prevBtn', 'nextBtn']),
        prevBtn: el('prevBtn', 'Button', { label: 'Previous', variant: 'outline' }),
        nextBtn: el('nextBtn', 'Button', { label: 'Next Question', variant: 'solid' }),
      },
    },
  },
  {
    id: 'form-job-application',
    name: 'Job Application Form',
    description: 'Complete job application with resume upload',
    category: 'forms',
    tags: ['form', 'job', 'application', 'career', 'resume'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'lg' }, ['header', 'form']),
        header: el('header', 'Column', { gap: 'sm' }, ['title', 'position', 'location']),
        title: el('title', 'Heading', { level: '1', text: 'Apply for this Position' }),
        position: el('position', 'Text', { content: 'Senior Software Engineer', size: 'lg' }),
        location: el('location', 'Text', { content: 'San Francisco, CA | Remote OK', color: 'muted' }),
        form: el('form', 'Column', { gap: 'xl' }, ['personalSection', 'experienceSection', 'resumeSection', 'additionalSection', 'submitSection']),
        personalSection: el('personalSection', 'Card', { title: 'Personal Information' }, ['personalFields']),
        personalFields: el('personalFields', 'Column', { gap: 'md' }, ['nameRow', 'emailField', 'phoneField', 'linkedinField', 'portfolioField']),
        nameRow: el('nameRow', 'Row', { gap: 'md' }, ['firstNameInput', 'lastNameInput']),
        firstNameInput: el('firstNameInput', 'Input', { label: 'First Name', placeholder: 'John', required: true }),
        lastNameInput: el('lastNameInput', 'Input', { label: 'Last Name', placeholder: 'Doe', required: true }),
        emailField: el('emailField', 'Input', { label: 'Email', type: 'email', placeholder: 'john@example.com', required: true }),
        phoneField: el('phoneField', 'Input', { label: 'Phone', type: 'tel', placeholder: '(555) 123-4567', required: true }),
        linkedinField: el('linkedinField', 'Input', { label: 'LinkedIn Profile', type: 'url', placeholder: 'https://linkedin.com/in/...' }),
        portfolioField: el('portfolioField', 'Input', { label: 'Portfolio/Website', type: 'url', placeholder: 'https://...' }),
        experienceSection: el('experienceSection', 'Card', { title: 'Work Experience' }, ['experienceFields']),
        experienceFields: el('experienceFields', 'Column', { gap: 'md' }, ['yearsField', 'currentRoleField', 'currentCompanyField', 'skillsField']),
        yearsField: el('yearsField', 'Select', { label: 'Years of Experience', required: true, options: [{ value: '', label: 'Select' }, { value: '0-2', label: '0-2 years' }, { value: '3-5', label: '3-5 years' }, { value: '6-10', label: '6-10 years' }, { value: '10+', label: '10+ years' }] }),
        currentRoleField: el('currentRoleField', 'Input', { label: 'Current Job Title', placeholder: 'Software Engineer' }),
        currentCompanyField: el('currentCompanyField', 'Input', { label: 'Current Company', placeholder: 'Acme Inc.' }),
        skillsField: el('skillsField', 'TextArea', { label: 'Key Skills', placeholder: 'List your relevant skills...', rows: 3 }),
        resumeSection: el('resumeSection', 'Card', { title: 'Resume' }, ['resumeFields']),
        resumeFields: el('resumeFields', 'Column', { gap: 'md' }, ['resumeUpload', 'resumeHelp']),
        resumeUpload: el('resumeUpload', 'Card', { variant: 'outlined' }, ['uploadContent']),
        uploadContent: el('uploadContent', 'Column', { gap: 'sm', align: 'center' }, ['uploadIcon', 'uploadText', 'uploadBtn']),
        uploadIcon: el('uploadIcon', 'Text', { content: '[Upload Icon]', color: 'muted' }),
        uploadText: el('uploadText', 'Text', { content: 'Drag and drop your resume or', color: 'muted' }),
        uploadBtn: el('uploadBtn', 'Button', { label: 'Browse Files', variant: 'outline' }),
        resumeHelp: el('resumeHelp', 'Text', { content: 'Accepted formats: PDF, DOC, DOCX (Max 5MB)', color: 'muted', size: 'sm' }),
        additionalSection: el('additionalSection', 'Card', { title: 'Additional Information' }, ['additionalFields']),
        additionalFields: el('additionalFields', 'Column', { gap: 'md' }, ['salaryField', 'startField', 'sponsorField', 'coverField']),
        salaryField: el('salaryField', 'Input', { label: 'Expected Salary', placeholder: '$120,000' }),
        startField: el('startField', 'Select', { label: 'Available to Start', options: [{ value: '', label: 'Select' }, { value: 'immediately', label: 'Immediately' }, { value: '2-weeks', label: '2 weeks notice' }, { value: '1-month', label: '1 month notice' }, { value: 'other', label: 'Other' }] }),
        sponsorField: el('sponsorField', 'Column', { gap: 'sm' }, ['sponsorLabel', 'sponsorOptions']),
        sponsorLabel: el('sponsorLabel', 'Text', { content: 'Do you require visa sponsorship?', size: 'sm' }),
        sponsorOptions: el('sponsorOptions', 'Row', { gap: 'md' }, ['sponsorYes', 'sponsorNo']),
        sponsorYes: el('sponsorYes', 'Checkbox', { label: 'Yes' }),
        sponsorNo: el('sponsorNo', 'Checkbox', { label: 'No' }),
        coverField: el('coverField', 'TextArea', { label: 'Cover Letter (Optional)', placeholder: 'Tell us why you are interested in this role...', rows: 5 }),
        submitSection: el('submitSection', 'Column', { gap: 'md' }, ['consent', 'submitBtn']),
        consent: el('consent', 'Checkbox', { label: 'I certify that all information provided is accurate and complete' }),
        submitBtn: el('submitBtn', 'Button', { label: 'Submit Application', variant: 'solid', fullWidth: true }),
      },
    },
  },
  {
    id: 'form-feedback-rating',
    name: 'Feedback Form with Rating',
    description: 'Product/service feedback with star rating',
    category: 'forms',
    tags: ['form', 'feedback', 'rating', 'review', 'stars'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'sm' }, ['card']),
        card: el('card', 'Card', {}, ['header', 'form']),
        header: el('header', 'Column', { gap: 'sm', align: 'center' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'How was your experience?', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Your feedback helps us improve', align: 'center', color: 'muted' }),
        form: el('form', 'Column', { gap: 'lg' }, ['ratingSection', 'aspectsSection', 'commentSection', 'submitBtn']),
        ratingSection: el('ratingSection', 'Column', { gap: 'md', align: 'center' }, ['overallLabel', 'starRating', 'ratingText']),
        overallLabel: el('overallLabel', 'Text', { content: 'Overall Rating', size: 'sm' }),
        starRating: el('starRating', 'Row', { gap: 'sm' }, ['star1', 'star2', 'star3', 'star4', 'star5']),
        star1: el('star1', 'Button', { label: '★', variant: 'ghost' }),
        star2: el('star2', 'Button', { label: '★', variant: 'ghost' }),
        star3: el('star3', 'Button', { label: '★', variant: 'ghost' }),
        star4: el('star4', 'Button', { label: '★', variant: 'solid' }),
        star5: el('star5', 'Button', { label: '★', variant: 'solid' }),
        ratingText: el('ratingText', 'Text', { content: 'Good', color: 'muted' }),
        aspectsSection: el('aspectsSection', 'Column', { gap: 'md' }, ['aspectsLabel', 'aspect1', 'aspect2', 'aspect3']),
        aspectsLabel: el('aspectsLabel', 'Text', { content: 'Rate specific aspects', size: 'sm' }),
        aspect1: el('aspect1', 'Row', { justify: 'between', align: 'center' }, ['aspect1Label', 'aspect1Rating']),
        aspect1Label: el('aspect1Label', 'Text', { content: 'Product Quality' }),
        aspect1Rating: el('aspect1Rating', 'Row', { gap: 'xs' }, ['a1s1', 'a1s2', 'a1s3', 'a1s4', 'a1s5']),
        a1s1: el('a1s1', 'Text', { content: '★' }),
        a1s2: el('a1s2', 'Text', { content: '★' }),
        a1s3: el('a1s3', 'Text', { content: '★' }),
        a1s4: el('a1s4', 'Text', { content: '★' }),
        a1s5: el('a1s5', 'Text', { content: '☆', color: 'muted' }),
        aspect2: el('aspect2', 'Row', { justify: 'between', align: 'center' }, ['aspect2Label', 'aspect2Rating']),
        aspect2Label: el('aspect2Label', 'Text', { content: 'Shipping Speed' }),
        aspect2Rating: el('aspect2Rating', 'Row', { gap: 'xs' }, ['a2s1', 'a2s2', 'a2s3', 'a2s4', 'a2s5']),
        a2s1: el('a2s1', 'Text', { content: '★' }),
        a2s2: el('a2s2', 'Text', { content: '★' }),
        a2s3: el('a2s3', 'Text', { content: '★' }),
        a2s4: el('a2s4', 'Text', { content: '★' }),
        a2s5: el('a2s5', 'Text', { content: '★' }),
        aspect3: el('aspect3', 'Row', { justify: 'between', align: 'center' }, ['aspect3Label', 'aspect3Rating']),
        aspect3Label: el('aspect3Label', 'Text', { content: 'Customer Service' }),
        aspect3Rating: el('aspect3Rating', 'Row', { gap: 'xs' }, ['a3s1', 'a3s2', 'a3s3', 'a3s4', 'a3s5']),
        a3s1: el('a3s1', 'Text', { content: '★' }),
        a3s2: el('a3s2', 'Text', { content: '★' }),
        a3s3: el('a3s3', 'Text', { content: '★' }),
        a3s4: el('a3s4', 'Text', { content: '☆', color: 'muted' }),
        a3s5: el('a3s5', 'Text', { content: '☆', color: 'muted' }),
        commentSection: el('commentSection', 'TextArea', { label: 'Additional Comments', placeholder: 'Tell us more about your experience...', rows: 4 }),
        submitBtn: el('submitBtn', 'Button', { label: 'Submit Feedback', variant: 'solid', fullWidth: true }),
      },
    },
  },
  {
    id: 'form-settings-preferences',
    name: 'Settings Preferences Form',
    description: 'Application settings with toggles and selects',
    category: 'forms',
    tags: ['form', 'settings', 'preferences', 'toggles', 'options'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'md' }, ['header', 'sections']),
        header: el('header', 'Heading', { level: '1', text: 'Settings' }),
        sections: el('sections', 'Column', { gap: 'lg' }, ['generalSection', 'notificationSection', 'privacySection', 'actionsSection']),
        generalSection: el('generalSection', 'Card', { title: 'General' }, ['generalContent']),
        generalContent: el('generalContent', 'Column', { gap: 'md' }, ['themeSelect', 'langSelect', 'timezoneSelect']),
        themeSelect: el('themeSelect', 'Row', { justify: 'between', align: 'center' }, ['themeLabel', 'themeOptions']),
        themeLabel: el('themeLabel', 'Column', { gap: 'xs' }, ['themeName', 'themeDesc']),
        themeName: el('themeName', 'Text', { content: 'Theme' }),
        themeDesc: el('themeDesc', 'Text', { content: 'Select your preferred color theme', color: 'muted', size: 'sm' }),
        themeOptions: el('themeOptions', 'Select', { options: [{ value: 'system', label: 'System' }, { value: 'light', label: 'Light' }, { value: 'dark', label: 'Dark' }] }),
        langSelect: el('langSelect', 'Row', { justify: 'between', align: 'center' }, ['langLabel', 'langOptions']),
        langLabel: el('langLabel', 'Column', { gap: 'xs' }, ['langName', 'langDesc']),
        langName: el('langName', 'Text', { content: 'Language' }),
        langDesc: el('langDesc', 'Text', { content: 'Choose your display language', color: 'muted', size: 'sm' }),
        langOptions: el('langOptions', 'Select', { options: [{ value: 'en', label: 'English' }, { value: 'es', label: 'Spanish' }, { value: 'fr', label: 'French' }, { value: 'de', label: 'German' }] }),
        timezoneSelect: el('timezoneSelect', 'Row', { justify: 'between', align: 'center' }, ['tzLabel', 'tzOptions']),
        tzLabel: el('tzLabel', 'Column', { gap: 'xs' }, ['tzName', 'tzDesc']),
        tzName: el('tzName', 'Text', { content: 'Timezone' }),
        tzDesc: el('tzDesc', 'Text', { content: 'Set your local timezone', color: 'muted', size: 'sm' }),
        tzOptions: el('tzOptions', 'Select', { options: [{ value: 'pst', label: 'Pacific Time (PST)' }, { value: 'mst', label: 'Mountain Time (MST)' }, { value: 'cst', label: 'Central Time (CST)' }, { value: 'est', label: 'Eastern Time (EST)' }] }),
        notificationSection: el('notificationSection', 'Card', { title: 'Notifications' }, ['notificationContent']),
        notificationContent: el('notificationContent', 'Column', { gap: 'md' }, ['emailNotif', 'pushNotif', 'smsNotif', 'marketingNotif']),
        emailNotif: el('emailNotif', 'Row', { justify: 'between', align: 'center' }, ['emailLabel', 'emailToggle']),
        emailLabel: el('emailLabel', 'Column', { gap: 'xs' }, ['emailName', 'emailDesc']),
        emailName: el('emailName', 'Text', { content: 'Email Notifications' }),
        emailDesc: el('emailDesc', 'Text', { content: 'Receive updates via email', color: 'muted', size: 'sm' }),
        emailToggle: el('emailToggle', 'Switch', {}),
        pushNotif: el('pushNotif', 'Row', { justify: 'between', align: 'center' }, ['pushLabel', 'pushToggle']),
        pushLabel: el('pushLabel', 'Column', { gap: 'xs' }, ['pushName', 'pushDesc']),
        pushName: el('pushName', 'Text', { content: 'Push Notifications' }),
        pushDesc: el('pushDesc', 'Text', { content: 'Receive browser push notifications', color: 'muted', size: 'sm' }),
        pushToggle: el('pushToggle', 'Switch', {}),
        smsNotif: el('smsNotif', 'Row', { justify: 'between', align: 'center' }, ['smsLabel', 'smsToggle']),
        smsLabel: el('smsLabel', 'Column', { gap: 'xs' }, ['smsName', 'smsDesc']),
        smsName: el('smsName', 'Text', { content: 'SMS Notifications' }),
        smsDesc: el('smsDesc', 'Text', { content: 'Receive important alerts via SMS', color: 'muted', size: 'sm' }),
        smsToggle: el('smsToggle', 'Switch', {}),
        marketingNotif: el('marketingNotif', 'Row', { justify: 'between', align: 'center' }, ['marketingLabel', 'marketingToggle']),
        marketingLabel: el('marketingLabel', 'Column', { gap: 'xs' }, ['marketingName', 'marketingDesc']),
        marketingName: el('marketingName', 'Text', { content: 'Marketing Communications' }),
        marketingDesc: el('marketingDesc', 'Text', { content: 'Receive product updates and offers', color: 'muted', size: 'sm' }),
        marketingToggle: el('marketingToggle', 'Switch', {}),
        privacySection: el('privacySection', 'Card', { title: 'Privacy' }, ['privacyContent']),
        privacyContent: el('privacyContent', 'Column', { gap: 'md' }, ['profileVisibility', 'activityStatus', 'dataSharing']),
        profileVisibility: el('profileVisibility', 'Row', { justify: 'between', align: 'center' }, ['visLabel', 'visToggle']),
        visLabel: el('visLabel', 'Column', { gap: 'xs' }, ['visName', 'visDesc']),
        visName: el('visName', 'Text', { content: 'Profile Visibility' }),
        visDesc: el('visDesc', 'Text', { content: 'Make your profile visible to others', color: 'muted', size: 'sm' }),
        visToggle: el('visToggle', 'Switch', {}),
        activityStatus: el('activityStatus', 'Row', { justify: 'between', align: 'center' }, ['actLabel', 'actToggle']),
        actLabel: el('actLabel', 'Column', { gap: 'xs' }, ['actName', 'actDesc']),
        actName: el('actName', 'Text', { content: 'Activity Status' }),
        actDesc: el('actDesc', 'Text', { content: 'Show when you are active', color: 'muted', size: 'sm' }),
        actToggle: el('actToggle', 'Switch', {}),
        dataSharing: el('dataSharing', 'Row', { justify: 'between', align: 'center' }, ['dataLabel', 'dataToggle']),
        dataLabel: el('dataLabel', 'Column', { gap: 'xs' }, ['dataName', 'dataDesc']),
        dataName: el('dataName', 'Text', { content: 'Data Sharing' }),
        dataDesc: el('dataDesc', 'Text', { content: 'Help improve the app by sharing usage data', color: 'muted', size: 'sm' }),
        dataToggle: el('dataToggle', 'Switch', {}),
        actionsSection: el('actionsSection', 'Row', { justify: 'end', gap: 'md' }, ['cancelBtn', 'saveBtn']),
        cancelBtn: el('cancelBtn', 'Button', { label: 'Cancel', variant: 'outline' }),
        saveBtn: el('saveBtn', 'Button', { label: 'Save Changes', variant: 'solid' }),
      },
    },
  },
  {
    id: 'form-profile-edit',
    name: 'Profile Edit Form',
    description: 'User profile editing with avatar upload',
    category: 'forms',
    tags: ['form', 'profile', 'edit', 'avatar', 'account'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'md' }, ['card']),
        card: el('card', 'Card', { title: 'Edit Profile' }, ['form']),
        form: el('form', 'Column', { gap: 'lg' }, ['avatarSection', 'basicSection', 'bioSection', 'socialSection', 'actionsSection']),
        avatarSection: el('avatarSection', 'Row', { gap: 'lg', align: 'center' }, ['avatar', 'avatarActions']),
        avatar: el('avatar', 'Avatar', { name: 'John Doe', size: 'lg' }),
        avatarActions: el('avatarActions', 'Column', { gap: 'sm' }, ['uploadBtn', 'removeBtn', 'avatarHelp']),
        uploadBtn: el('uploadBtn', 'Button', { label: 'Upload New Photo', variant: 'outline' }),
        removeBtn: el('removeBtn', 'Button', { label: 'Remove Photo', variant: 'ghost' }),
        avatarHelp: el('avatarHelp', 'Text', { content: 'JPG, PNG or GIF. Max size 2MB.', color: 'muted', size: 'sm' }),
        basicSection: el('basicSection', 'Column', { gap: 'md' }, ['nameRow', 'usernameField', 'emailField']),
        nameRow: el('nameRow', 'Row', { gap: 'md' }, ['firstNameField', 'lastNameField']),
        firstNameField: el('firstNameField', 'Input', { label: 'First Name', placeholder: 'John' }),
        lastNameField: el('lastNameField', 'Input', { label: 'Last Name', placeholder: 'Doe' }),
        usernameField: el('usernameField', 'Input', { label: 'Username', placeholder: '@johndoe' }),
        emailField: el('emailField', 'Input', { label: 'Email', type: 'email', placeholder: 'john@example.com' }),
        bioSection: el('bioSection', 'Column', { gap: 'md' }, ['bioField', 'locationField', 'websiteField']),
        bioField: el('bioField', 'TextArea', { label: 'Bio', placeholder: 'Tell us about yourself...', rows: 3 }),
        locationField: el('locationField', 'Input', { label: 'Location', placeholder: 'San Francisco, CA' }),
        websiteField: el('websiteField', 'Input', { label: 'Website', type: 'url', placeholder: 'https://...' }),
        socialSection: el('socialSection', 'Column', { gap: 'md' }, ['socialTitle', 'twitterField', 'linkedinField', 'githubField']),
        socialTitle: el('socialTitle', 'Text', { content: 'Social Links', size: 'sm' }),
        twitterField: el('twitterField', 'Input', { label: 'Twitter', placeholder: '@username' }),
        linkedinField: el('linkedinField', 'Input', { label: 'LinkedIn', placeholder: 'linkedin.com/in/...' }),
        githubField: el('githubField', 'Input', { label: 'GitHub', placeholder: 'github.com/...' }),
        actionsSection: el('actionsSection', 'Row', { justify: 'end', gap: 'md' }, ['cancelBtn', 'saveBtn']),
        cancelBtn: el('cancelBtn', 'Button', { label: 'Cancel', variant: 'outline' }),
        saveBtn: el('saveBtn', 'Button', { label: 'Save Profile', variant: 'solid' }),
      },
    },
  },
  {
    id: 'form-password-change',
    name: 'Password Change Form',
    description: 'Secure password change with requirements',
    category: 'forms',
    tags: ['form', 'password', 'security', 'account', 'change'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'sm' }, ['card']),
        card: el('card', 'Card', { title: 'Change Password' }, ['form']),
        form: el('form', 'Column', { gap: 'md' }, ['currentPassword', 'newPassword', 'confirmPassword', 'requirements', 'submitBtn']),
        currentPassword: el('currentPassword', 'Input', { label: 'Current Password', type: 'password', placeholder: 'Enter current password', required: true }),
        newPassword: el('newPassword', 'Input', { label: 'New Password', type: 'password', placeholder: 'Enter new password', required: true }),
        confirmPassword: el('confirmPassword', 'Input', { label: 'Confirm New Password', type: 'password', placeholder: 'Confirm new password', required: true }),
        requirements: el('requirements', 'Card', { variant: 'outlined' }, ['reqContent']),
        reqContent: el('reqContent', 'Column', { gap: 'sm' }, ['reqTitle', 'req1', 'req2', 'req3', 'req4']),
        reqTitle: el('reqTitle', 'Text', { content: 'Password Requirements:', size: 'sm' }),
        req1: el('req1', 'Row', { gap: 'sm', align: 'center' }, ['req1Icon', 'req1Text']),
        req1Icon: el('req1Icon', 'Badge', { text: '✓', color: 'success' }),
        req1Text: el('req1Text', 'Text', { content: 'At least 8 characters', size: 'sm', color: 'success' }),
        req2: el('req2', 'Row', { gap: 'sm', align: 'center' }, ['req2Icon', 'req2Text']),
        req2Icon: el('req2Icon', 'Badge', { text: '✓', color: 'success' }),
        req2Text: el('req2Text', 'Text', { content: 'Contains uppercase letter', size: 'sm', color: 'success' }),
        req3: el('req3', 'Row', { gap: 'sm', align: 'center' }, ['req3Icon', 'req3Text']),
        req3Icon: el('req3Icon', 'Badge', { text: '○', variant: 'outline' }),
        req3Text: el('req3Text', 'Text', { content: 'Contains a number', size: 'sm', color: 'muted' }),
        req4: el('req4', 'Row', { gap: 'sm', align: 'center' }, ['req4Icon', 'req4Text']),
        req4Icon: el('req4Icon', 'Badge', { text: '○', variant: 'outline' }),
        req4Text: el('req4Text', 'Text', { content: 'Contains special character', size: 'sm', color: 'muted' }),
        submitBtn: el('submitBtn', 'Button', { label: 'Update Password', variant: 'solid', fullWidth: true }),
      },
    },
  },
  {
    id: 'form-newsletter',
    name: 'Newsletter Subscription',
    description: 'Email subscription with preferences',
    category: 'forms',
    tags: ['form', 'newsletter', 'subscription', 'email', 'marketing'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'sm' }, ['card']),
        card: el('card', 'Card', { variant: 'elevated' }, ['content']),
        content: el('content', 'Column', { gap: 'md', align: 'center' }, ['icon', 'title', 'subtitle', 'form']),
        icon: el('icon', 'Text', { content: '[Email Icon]', size: 'lg' }),
        title: el('title', 'Heading', { level: '2', text: 'Stay in the loop', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Get the latest news, updates and tips delivered directly to your inbox.', align: 'center', color: 'muted' }),
        form: el('form', 'Column', { gap: 'md' }, ['emailField', 'preferences', 'frequency', 'subscribeBtn', 'privacyNote']),
        emailField: el('emailField', 'Input', { label: 'Email Address', type: 'email', placeholder: 'you@example.com', required: true }),
        preferences: el('preferences', 'Column', { gap: 'sm' }, ['prefLabel', 'pref1', 'pref2', 'pref3']),
        prefLabel: el('prefLabel', 'Text', { content: 'I am interested in:', size: 'sm' }),
        pref1: el('pref1', 'Checkbox', { label: 'Product updates & new features' }),
        pref2: el('pref2', 'Checkbox', { label: 'Tips, tutorials & best practices' }),
        pref3: el('pref3', 'Checkbox', { label: 'Industry news & trends' }),
        frequency: el('frequency', 'Select', { label: 'Email Frequency', options: [{ value: 'weekly', label: 'Weekly digest' }, { value: 'biweekly', label: 'Bi-weekly' }, { value: 'monthly', label: 'Monthly' }] }),
        subscribeBtn: el('subscribeBtn', 'Button', { label: 'Subscribe', variant: 'solid', fullWidth: true }),
        privacyNote: el('privacyNote', 'Text', { content: 'By subscribing, you agree to our Privacy Policy. Unsubscribe anytime.', align: 'center', color: 'muted', size: 'sm' }),
      },
    },
  },
  {
    id: 'form-event-registration',
    name: 'Event Registration Form',
    description: 'Event signup with ticket selection',
    category: 'forms',
    tags: ['form', 'event', 'registration', 'tickets', 'conference'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Container', { maxWidth: 'lg' }, ['header', 'content']),
        header: el('header', 'Column', { gap: 'sm' }, ['eventTitle', 'eventMeta']),
        eventTitle: el('eventTitle', 'Heading', { level: '1', text: 'Tech Conference 2024' }),
        eventMeta: el('eventMeta', 'Row', { gap: 'md' }, ['eventDate', 'eventLocation']),
        eventDate: el('eventDate', 'Badge', { text: 'March 15-17, 2024', variant: 'outline' }),
        eventLocation: el('eventLocation', 'Badge', { text: 'San Francisco, CA', variant: 'outline' }),
        content: el('content', 'Row', { gap: 'xl' }, ['form', 'summary']),
        form: el('form', 'Column', { gap: 'lg' }, ['attendeeSection', 'ticketSection', 'dietarySection']),
        attendeeSection: el('attendeeSection', 'Card', { title: 'Attendee Information' }, ['attendeeFields']),
        attendeeFields: el('attendeeFields', 'Column', { gap: 'md' }, ['nameRow', 'emailField', 'companyField', 'titleField']),
        nameRow: el('nameRow', 'Row', { gap: 'md' }, ['firstNameInput', 'lastNameInput']),
        firstNameInput: el('firstNameInput', 'Input', { label: 'First Name', placeholder: 'John', required: true }),
        lastNameInput: el('lastNameInput', 'Input', { label: 'Last Name', placeholder: 'Doe', required: true }),
        emailField: el('emailField', 'Input', { label: 'Email', type: 'email', placeholder: 'john@company.com', required: true }),
        companyField: el('companyField', 'Input', { label: 'Company', placeholder: 'Acme Inc.' }),
        titleField: el('titleField', 'Input', { label: 'Job Title', placeholder: 'Software Engineer' }),
        ticketSection: el('ticketSection', 'Card', { title: 'Select Ticket Type' }, ['ticketOptions']),
        ticketOptions: el('ticketOptions', 'Column', { gap: 'sm' }, ['ticket1', 'ticket2', 'ticket3']),
        ticket1: el('ticket1', 'Card', { variant: 'outlined' }, ['ticket1Content']),
        ticket2: el('ticket2', 'Card', { variant: 'elevated' }, ['ticket2Content']),
        ticket3: el('ticket3', 'Card', { variant: 'outlined' }, ['ticket3Content']),
        ticket1Content: el('ticket1Content', 'Row', { justify: 'between', align: 'center' }, ['ticket1Info', 'ticket1Price']),
        ticket1Info: el('ticket1Info', 'Column', { gap: 'xs' }, ['ticket1Name', 'ticket1Desc']),
        ticket1Name: el('ticket1Name', 'Text', { content: 'General Admission' }),
        ticket1Desc: el('ticket1Desc', 'Text', { content: 'Access to all sessions', color: 'muted', size: 'sm' }),
        ticket1Price: el('ticket1Price', 'Text', { content: '$299', size: 'lg' }),
        ticket2Content: el('ticket2Content', 'Row', { justify: 'between', align: 'center' }, ['ticket2Info', 'ticket2Price', 'ticket2Badge']),
        ticket2Info: el('ticket2Info', 'Column', { gap: 'xs' }, ['ticket2Name', 'ticket2Desc']),
        ticket2Name: el('ticket2Name', 'Text', { content: 'VIP Pass' }),
        ticket2Desc: el('ticket2Desc', 'Text', { content: 'Priority seating + networking dinner', color: 'muted', size: 'sm' }),
        ticket2Price: el('ticket2Price', 'Text', { content: '$599', size: 'lg' }),
        ticket2Badge: el('ticket2Badge', 'Badge', { text: 'Selected', color: 'success' }),
        ticket3Content: el('ticket3Content', 'Row', { justify: 'between', align: 'center' }, ['ticket3Info', 'ticket3Price']),
        ticket3Info: el('ticket3Info', 'Column', { gap: 'xs' }, ['ticket3Name', 'ticket3Desc']),
        ticket3Name: el('ticket3Name', 'Text', { content: 'Workshop Bundle' }),
        ticket3Desc: el('ticket3Desc', 'Text', { content: 'VIP + hands-on workshops', color: 'muted', size: 'sm' }),
        ticket3Price: el('ticket3Price', 'Text', { content: '$899', size: 'lg' }),
        dietarySection: el('dietarySection', 'Card', { title: 'Additional Options' }, ['dietaryFields']),
        dietaryFields: el('dietaryFields', 'Column', { gap: 'md' }, ['dietarySelect', 'accessibilityCheck', 'specialRequests']),
        dietarySelect: el('dietarySelect', 'Select', { label: 'Dietary Requirements', options: [{ value: 'none', label: 'None' }, { value: 'vegetarian', label: 'Vegetarian' }, { value: 'vegan', label: 'Vegan' }, { value: 'gluten-free', label: 'Gluten Free' }, { value: 'halal', label: 'Halal' }, { value: 'kosher', label: 'Kosher' }] }),
        accessibilityCheck: el('accessibilityCheck', 'Checkbox', { label: 'I require accessibility accommodations' }),
        specialRequests: el('specialRequests', 'TextArea', { label: 'Special Requests', placeholder: 'Any additional requirements...', rows: 2 }),
        summary: el('summary', 'Card', { title: 'Order Summary' }, ['summaryContent']),
        summaryContent: el('summaryContent', 'Column', { gap: 'md' }, ['summaryItem', 'summaryTotal', 'registerBtn', 'termsNote']),
        summaryItem: el('summaryItem', 'Row', { justify: 'between' }, ['itemName', 'itemPrice']),
        itemName: el('itemName', 'Text', { content: 'VIP Pass x 1' }),
        itemPrice: el('itemPrice', 'Text', { content: '$599.00' }),
        summaryTotal: el('summaryTotal', 'Row', { justify: 'between' }, ['totalLabel', 'totalPrice']),
        totalLabel: el('totalLabel', 'Heading', { level: '4', text: 'Total' }),
        totalPrice: el('totalPrice', 'Heading', { level: '4', text: '$599.00' }),
        registerBtn: el('registerBtn', 'Button', { label: 'Complete Registration', variant: 'solid', fullWidth: true }),
        termsNote: el('termsNote', 'Text', { content: 'By registering, you agree to our Terms of Service and Privacy Policy.', color: 'muted', size: 'sm', align: 'center' }),
      },
    },
  },
];
