/**
 * Landing Page Test Cases
 * Real-world landing page UI configurations
 */

import type { UITree, UIElement } from '@json-render/core';
import type { TestCase } from './test-cases';

function el(key: string, type: string, props: Record<string, unknown>, children?: string[]): UIElement {
  return { key, type, props, children };
}

export const landingPageTestCases: TestCase[] = [
  {
    id: 'landing-restaurant',
    name: 'Restaurant Landing Page',
    description: 'Full restaurant website with hero, menu, gallery, reviews, and contact',
    category: 'landing-pages',
    tags: ['landing', 'restaurant', 'food', 'hero', 'menu', 'reviews'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'none' }, ['nav', 'hero', 'menuSection', 'gallery', 'reviews', 'contact', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center', gap: 'md' }, ['logo', 'navLinks', 'reserveBtn']),
        logo: el('logo', 'Heading', { level: '4', text: 'La Bella Italia' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navMenu', 'navAbout', 'navReservations', 'navContact']),
        navMenu: el('navMenu', 'Link', { text: 'Menu', href: '#menu' }),
        navAbout: el('navAbout', 'Link', { text: 'About', href: '#about' }),
        navReservations: el('navReservations', 'Link', { text: 'Reservations', href: '#reserve' }),
        navContact: el('navContact', 'Link', { text: 'Contact', href: '#contact' }),
        reserveBtn: el('reserveBtn', 'Button', { label: 'Book a Table', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'xl' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroSubtitle', 'heroCta']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Authentic Italian Cuisine', align: 'center' }),
        heroSubtitle: el('heroSubtitle', 'Text', { content: 'Experience the taste of Italy in every bite. Fresh ingredients, family recipes, unforgettable moments.', align: 'center', color: 'muted' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['viewMenuBtn', 'reserveHeroBtn']),
        viewMenuBtn: el('viewMenuBtn', 'Button', { label: 'View Menu', variant: 'solid' }),
        reserveHeroBtn: el('reserveHeroBtn', 'Button', { label: 'Make Reservation', variant: 'outline' }),
        menuSection: el('menuSection', 'Container', { maxWidth: 'xl' }, ['menuHeader', 'menuGrid']),
        menuHeader: el('menuHeader', 'Column', { gap: 'sm', align: 'center' }, ['menuTitle', 'menuDesc']),
        menuTitle: el('menuTitle', 'Heading', { level: '2', text: 'Our Menu', align: 'center' }),
        menuDesc: el('menuDesc', 'Text', { content: 'Handcrafted dishes made with love', align: 'center', color: 'muted' }),
        menuGrid: el('menuGrid', 'Grid', { columns: 3, gap: 'lg' }, ['menuItem1', 'menuItem2', 'menuItem3', 'menuItem4', 'menuItem5', 'menuItem6']),
        menuItem1: el('menuItem1', 'Card', { variant: 'elevated' }, ['mi1Content']),
        menuItem2: el('menuItem2', 'Card', { variant: 'elevated' }, ['mi2Content']),
        menuItem3: el('menuItem3', 'Card', { variant: 'elevated' }, ['mi3Content']),
        menuItem4: el('menuItem4', 'Card', { variant: 'elevated' }, ['mi4Content']),
        menuItem5: el('menuItem5', 'Card', { variant: 'elevated' }, ['mi5Content']),
        menuItem6: el('menuItem6', 'Card', { variant: 'elevated' }, ['mi6Content']),
        mi1Content: el('mi1Content', 'Column', { gap: 'sm' }, ['mi1Name', 'mi1Desc', 'mi1Price']),
        mi1Name: el('mi1Name', 'Heading', { level: '4', text: 'Margherita Pizza' }),
        mi1Desc: el('mi1Desc', 'Text', { content: 'Fresh mozzarella, tomatoes, basil', color: 'muted', size: 'sm' }),
        mi1Price: el('mi1Price', 'Text', { content: '$18', size: 'lg' }),
        mi2Content: el('mi2Content', 'Column', { gap: 'sm' }, ['mi2Name', 'mi2Desc', 'mi2Price']),
        mi2Name: el('mi2Name', 'Heading', { level: '4', text: 'Spaghetti Carbonara' }),
        mi2Desc: el('mi2Desc', 'Text', { content: 'Pancetta, egg, pecorino, black pepper', color: 'muted', size: 'sm' }),
        mi2Price: el('mi2Price', 'Text', { content: '$22', size: 'lg' }),
        mi3Content: el('mi3Content', 'Column', { gap: 'sm' }, ['mi3Name', 'mi3Desc', 'mi3Price']),
        mi3Name: el('mi3Name', 'Heading', { level: '4', text: 'Osso Buco' }),
        mi3Desc: el('mi3Desc', 'Text', { content: 'Braised veal shanks, gremolata', color: 'muted', size: 'sm' }),
        mi3Price: el('mi3Price', 'Text', { content: '$34', size: 'lg' }),
        mi4Content: el('mi4Content', 'Column', { gap: 'sm' }, ['mi4Name', 'mi4Desc', 'mi4Price']),
        mi4Name: el('mi4Name', 'Heading', { level: '4', text: 'Tiramisu' }),
        mi4Desc: el('mi4Desc', 'Text', { content: 'Espresso-soaked ladyfingers, mascarpone', color: 'muted', size: 'sm' }),
        mi4Price: el('mi4Price', 'Text', { content: '$12', size: 'lg' }),
        mi5Content: el('mi5Content', 'Column', { gap: 'sm' }, ['mi5Name', 'mi5Desc', 'mi5Price']),
        mi5Name: el('mi5Name', 'Heading', { level: '4', text: 'Bruschetta' }),
        mi5Desc: el('mi5Desc', 'Text', { content: 'Grilled bread, tomatoes, garlic, olive oil', color: 'muted', size: 'sm' }),
        mi5Price: el('mi5Price', 'Text', { content: '$10', size: 'lg' }),
        mi6Content: el('mi6Content', 'Column', { gap: 'sm' }, ['mi6Name', 'mi6Desc', 'mi6Price']),
        mi6Name: el('mi6Name', 'Heading', { level: '4', text: 'Risotto ai Funghi' }),
        mi6Desc: el('mi6Desc', 'Text', { content: 'Arborio rice, wild mushrooms, parmesan', color: 'muted', size: 'sm' }),
        mi6Price: el('mi6Price', 'Text', { content: '$26', size: 'lg' }),
        gallery: el('gallery', 'Container', { maxWidth: 'xl' }, ['galleryTitle', 'galleryGrid']),
        galleryTitle: el('galleryTitle', 'Heading', { level: '2', text: 'Our Restaurant', align: 'center' }),
        galleryGrid: el('galleryGrid', 'Grid', { columns: 4, gap: 'md' }, ['gal1', 'gal2', 'gal3', 'gal4']),
        gal1: el('gal1', 'Card', { variant: 'elevated' }, ['galImg1']),
        gal2: el('gal2', 'Card', { variant: 'elevated' }, ['galImg2']),
        gal3: el('gal3', 'Card', { variant: 'elevated' }, ['galImg3']),
        gal4: el('gal4', 'Card', { variant: 'elevated' }, ['galImg4']),
        galImg1: el('galImg1', 'Image', { src: '/placeholder.jpg', alt: 'Restaurant interior' }),
        galImg2: el('galImg2', 'Image', { src: '/placeholder.jpg', alt: 'Chef at work' }),
        galImg3: el('galImg3', 'Image', { src: '/placeholder.jpg', alt: 'Signature dish' }),
        galImg4: el('galImg4', 'Image', { src: '/placeholder.jpg', alt: 'Wine cellar' }),
        reviews: el('reviews', 'Container', { maxWidth: 'lg' }, ['reviewsTitle', 'reviewsGrid']),
        reviewsTitle: el('reviewsTitle', 'Heading', { level: '2', text: 'What Our Guests Say', align: 'center' }),
        reviewsGrid: el('reviewsGrid', 'Grid', { columns: 2, gap: 'lg' }, ['review1', 'review2']),
        review1: el('review1', 'Card', { variant: 'outlined' }, ['rev1Content']),
        review2: el('review2', 'Card', { variant: 'outlined' }, ['rev2Content']),
        rev1Content: el('rev1Content', 'Column', { gap: 'sm' }, ['rev1Stars', 'rev1Text', 'rev1Author']),
        rev1Stars: el('rev1Stars', 'Text', { content: '★★★★★' }),
        rev1Text: el('rev1Text', 'Text', { content: 'The best Italian food outside of Italy. The pasta is made fresh daily and you can taste the difference.' }),
        rev1Author: el('rev1Author', 'Text', { content: '— Maria S.', color: 'muted', size: 'sm' }),
        rev2Content: el('rev2Content', 'Column', { gap: 'sm' }, ['rev2Stars', 'rev2Text', 'rev2Author']),
        rev2Stars: el('rev2Stars', 'Text', { content: '★★★★★' }),
        rev2Text: el('rev2Text', 'Text', { content: 'Amazing atmosphere and even better food. We celebrated our anniversary here and it was perfect.' }),
        rev2Author: el('rev2Author', 'Text', { content: '— John & Lisa R.', color: 'muted', size: 'sm' }),
        contact: el('contact', 'Container', { maxWidth: 'md' }, ['contactTitle', 'contactInfo']),
        contactTitle: el('contactTitle', 'Heading', { level: '2', text: 'Visit Us', align: 'center' }),
        contactInfo: el('contactInfo', 'Column', { gap: 'md', align: 'center' }, ['address', 'phone', 'hours']),
        address: el('address', 'Text', { content: '123 Main Street, New York, NY 10001', align: 'center' }),
        phone: el('phone', 'Text', { content: '(212) 555-0123', align: 'center' }),
        hours: el('hours', 'Text', { content: 'Open Daily: 11am - 11pm', align: 'center', color: 'muted' }),
        footer: el('footer', 'Text', { content: '© 2024 La Bella Italia. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-car-dealership',
    name: 'Car Dealership Landing',
    description: 'Auto dealership with hero, featured vehicles, financing, and locations',
    category: 'landing-pages',
    tags: ['landing', 'automotive', 'cars', 'dealership', 'vehicles'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'featured', 'financing', 'locations', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'navActions']),
        logo: el('logo', 'Heading', { level: '4', text: 'Premier Auto' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navNew', 'navUsed', 'navService', 'navFinancing']),
        navNew: el('navNew', 'Link', { text: 'New Vehicles', href: '#' }),
        navUsed: el('navUsed', 'Link', { text: 'Pre-Owned', href: '#' }),
        navService: el('navService', 'Link', { text: 'Service', href: '#' }),
        navFinancing: el('navFinancing', 'Link', { text: 'Financing', href: '#' }),
        navActions: el('navActions', 'Row', { gap: 'sm' }, ['searchBtn', 'contactBtn']),
        searchBtn: el('searchBtn', 'Button', { label: 'Search Inventory', variant: 'outline' }),
        contactBtn: el('contactBtn', 'Button', { label: 'Contact Us', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'xl' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroSubtitle', 'heroStats', 'heroCta']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Find Your Perfect Drive', align: 'center' }),
        heroSubtitle: el('heroSubtitle', 'Text', { content: 'Over 500 vehicles in stock. Competitive financing. Exceptional service.', align: 'center', color: 'muted' }),
        heroStats: el('heroStats', 'Row', { gap: 'xl', justify: 'center' }, ['stat1', 'stat2', 'stat3']),
        stat1: el('stat1', 'Column', { align: 'center' }, ['stat1Val', 'stat1Label']),
        stat2: el('stat2', 'Column', { align: 'center' }, ['stat2Val', 'stat2Label']),
        stat3: el('stat3', 'Column', { align: 'center' }, ['stat3Val', 'stat3Label']),
        stat1Val: el('stat1Val', 'Heading', { level: '2', text: '500+' }),
        stat1Label: el('stat1Label', 'Text', { content: 'Vehicles', color: 'muted' }),
        stat2Val: el('stat2Val', 'Heading', { level: '2', text: '25+' }),
        stat2Label: el('stat2Label', 'Text', { content: 'Years Experience', color: 'muted' }),
        stat3Val: el('stat3Val', 'Heading', { level: '2', text: '10K+' }),
        stat3Label: el('stat3Label', 'Text', { content: 'Happy Customers', color: 'muted' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['browseBtn', 'tradeBtn']),
        browseBtn: el('browseBtn', 'Button', { label: 'Browse Inventory', variant: 'solid' }),
        tradeBtn: el('tradeBtn', 'Button', { label: 'Value Your Trade', variant: 'outline' }),
        featured: el('featured', 'Container', { maxWidth: 'xl' }, ['featuredHeader', 'featuredGrid']),
        featuredHeader: el('featuredHeader', 'Column', { gap: 'sm', align: 'center' }, ['featuredTitle', 'featuredDesc']),
        featuredTitle: el('featuredTitle', 'Heading', { level: '2', text: 'Featured Vehicles', align: 'center' }),
        featuredDesc: el('featuredDesc', 'Text', { content: 'Hand-picked selections from our inventory', align: 'center', color: 'muted' }),
        featuredGrid: el('featuredGrid', 'Grid', { columns: 3, gap: 'lg' }, ['car1', 'car2', 'car3']),
        car1: el('car1', 'Card', { variant: 'elevated' }, ['car1Img', 'car1Body']),
        car2: el('car2', 'Card', { variant: 'elevated' }, ['car2Img', 'car2Body']),
        car3: el('car3', 'Card', { variant: 'elevated' }, ['car3Img', 'car3Body']),
        car1Img: el('car1Img', 'Image', { src: '/placeholder-car.jpg', alt: '2024 BMW X5' }),
        car2Img: el('car2Img', 'Image', { src: '/placeholder-car.jpg', alt: '2024 Mercedes GLE' }),
        car3Img: el('car3Img', 'Image', { src: '/placeholder-car.jpg', alt: '2024 Audi Q7' }),
        car1Body: el('car1Body', 'Column', { gap: 'sm' }, ['car1Name', 'car1Details', 'car1Price', 'car1Btn']),
        car2Body: el('car2Body', 'Column', { gap: 'sm' }, ['car2Name', 'car2Details', 'car2Price', 'car2Btn']),
        car3Body: el('car3Body', 'Column', { gap: 'sm' }, ['car3Name', 'car3Details', 'car3Price', 'car3Btn']),
        car1Name: el('car1Name', 'Heading', { level: '4', text: '2024 BMW X5 xDrive40i' }),
        car2Name: el('car2Name', 'Heading', { level: '4', text: '2024 Mercedes-Benz GLE 350' }),
        car3Name: el('car3Name', 'Heading', { level: '4', text: '2024 Audi Q7 Premium' }),
        car1Details: el('car1Details', 'Text', { content: '12,450 miles | AWD | Alpine White', color: 'muted', size: 'sm' }),
        car2Details: el('car2Details', 'Text', { content: '8,200 miles | AWD | Obsidian Black', color: 'muted', size: 'sm' }),
        car3Details: el('car3Details', 'Text', { content: '15,800 miles | AWD | Glacier White', color: 'muted', size: 'sm' }),
        car1Price: el('car1Price', 'Text', { content: '$62,995', size: 'lg' }),
        car2Price: el('car2Price', 'Text', { content: '$58,750', size: 'lg' }),
        car3Price: el('car3Price', 'Text', { content: '$54,900', size: 'lg' }),
        car1Btn: el('car1Btn', 'Button', { label: 'View Details', variant: 'outline', fullWidth: true }),
        car2Btn: el('car2Btn', 'Button', { label: 'View Details', variant: 'outline', fullWidth: true }),
        car3Btn: el('car3Btn', 'Button', { label: 'View Details', variant: 'outline', fullWidth: true }),
        financing: el('financing', 'Container', { maxWidth: 'lg' }, ['financeCard']),
        financeCard: el('financeCard', 'Card', { variant: 'elevated' }, ['financeContent']),
        financeContent: el('financeContent', 'Column', { gap: 'lg', align: 'center' }, ['financeTitle', 'financeDesc', 'financeFeatures', 'financeBtn']),
        financeTitle: el('financeTitle', 'Heading', { level: '2', text: 'Flexible Financing Options', align: 'center' }),
        financeDesc: el('financeDesc', 'Text', { content: 'Get pre-approved in minutes with rates as low as 2.9% APR', align: 'center', color: 'muted' }),
        financeFeatures: el('financeFeatures', 'Row', { gap: 'lg', justify: 'center' }, ['ff1', 'ff2', 'ff3']),
        ff1: el('ff1', 'Badge', { text: 'No Hidden Fees', variant: 'outline' }),
        ff2: el('ff2', 'Badge', { text: 'Quick Approval', variant: 'outline' }),
        ff3: el('ff3', 'Badge', { text: 'All Credit Welcome', variant: 'outline' }),
        financeBtn: el('financeBtn', 'Button', { label: 'Apply Now', variant: 'solid' }),
        locations: el('locations', 'Container', { maxWidth: 'xl' }, ['locHeader', 'locGrid']),
        locHeader: el('locHeader', 'Heading', { level: '2', text: 'Our Locations', align: 'center' }),
        locGrid: el('locGrid', 'Grid', { columns: 2, gap: 'lg' }, ['loc1', 'loc2']),
        loc1: el('loc1', 'Card', { variant: 'outlined' }, ['loc1Content']),
        loc2: el('loc2', 'Card', { variant: 'outlined' }, ['loc2Content']),
        loc1Content: el('loc1Content', 'Column', { gap: 'sm' }, ['loc1Name', 'loc1Addr', 'loc1Phone', 'loc1Hours']),
        loc2Content: el('loc2Content', 'Column', { gap: 'sm' }, ['loc2Name', 'loc2Addr', 'loc2Phone', 'loc2Hours']),
        loc1Name: el('loc1Name', 'Heading', { level: '4', text: 'Downtown Showroom' }),
        loc1Addr: el('loc1Addr', 'Text', { content: '100 Auto Drive, Downtown, NY 10001' }),
        loc1Phone: el('loc1Phone', 'Text', { content: '(212) 555-0100', color: 'muted' }),
        loc1Hours: el('loc1Hours', 'Text', { content: 'Mon-Sat: 9am-8pm | Sun: 11am-5pm', color: 'muted', size: 'sm' }),
        loc2Name: el('loc2Name', 'Heading', { level: '4', text: 'Westside Location' }),
        loc2Addr: el('loc2Addr', 'Text', { content: '500 Highway Blvd, Westside, NY 10025' }),
        loc2Phone: el('loc2Phone', 'Text', { content: '(212) 555-0500', color: 'muted' }),
        loc2Hours: el('loc2Hours', 'Text', { content: 'Mon-Sat: 9am-8pm | Sun: 11am-5pm', color: 'muted', size: 'sm' }),
        footer: el('footer', 'Text', { content: '© 2024 Premier Auto. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-coffee-shop',
    name: 'Coffee Shop Landing',
    description: 'Cozy coffee shop with menu, locations, and about section',
    category: 'landing-pages',
    tags: ['landing', 'coffee', 'cafe', 'food', 'beverage'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'menu', 'locations', 'about', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'orderBtn']),
        logo: el('logo', 'Heading', { level: '4', text: 'Brew & Bean' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navMenu', 'navLocations', 'navAbout']),
        navMenu: el('navMenu', 'Link', { text: 'Menu', href: '#' }),
        navLocations: el('navLocations', 'Link', { text: 'Locations', href: '#' }),
        navAbout: el('navAbout', 'Link', { text: 'About', href: '#' }),
        orderBtn: el('orderBtn', 'Button', { label: 'Order Online', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'lg' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroDesc', 'heroCta']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Crafted with Care', align: 'center' }),
        heroDesc: el('heroDesc', 'Text', { content: 'Specialty coffee roasted in-house. Artisan pastries baked fresh daily.', align: 'center', color: 'muted' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['menuBtn', 'findBtn']),
        menuBtn: el('menuBtn', 'Button', { label: 'View Menu', variant: 'solid' }),
        findBtn: el('findBtn', 'Button', { label: 'Find a Location', variant: 'outline' }),
        menu: el('menu', 'Container', { maxWidth: 'xl' }, ['menuHeader', 'menuCategories']),
        menuHeader: el('menuHeader', 'Heading', { level: '2', text: 'Our Menu', align: 'center' }),
        menuCategories: el('menuCategories', 'Grid', { columns: 3, gap: 'lg' }, ['drinks', 'pastries', 'food']),
        drinks: el('drinks', 'Card', { title: 'Coffee & Drinks' }, ['drinksList']),
        pastries: el('pastries', 'Card', { title: 'Fresh Pastries' }, ['pastriesList']),
        food: el('food', 'Card', { title: 'Light Bites' }, ['foodList']),
        drinksList: el('drinksList', 'Column', { gap: 'sm' }, ['drink1', 'drink2', 'drink3', 'drink4']),
        drink1: el('drink1', 'Row', { justify: 'between' }, ['drink1Name', 'drink1Price']),
        drink2: el('drink2', 'Row', { justify: 'between' }, ['drink2Name', 'drink2Price']),
        drink3: el('drink3', 'Row', { justify: 'between' }, ['drink3Name', 'drink3Price']),
        drink4: el('drink4', 'Row', { justify: 'between' }, ['drink4Name', 'drink4Price']),
        drink1Name: el('drink1Name', 'Text', { content: 'Espresso' }),
        drink1Price: el('drink1Price', 'Text', { content: '$3.50' }),
        drink2Name: el('drink2Name', 'Text', { content: 'Cappuccino' }),
        drink2Price: el('drink2Price', 'Text', { content: '$4.75' }),
        drink3Name: el('drink3Name', 'Text', { content: 'Pour Over' }),
        drink3Price: el('drink3Price', 'Text', { content: '$5.00' }),
        drink4Name: el('drink4Name', 'Text', { content: 'Cold Brew' }),
        drink4Price: el('drink4Price', 'Text', { content: '$4.50' }),
        pastriesList: el('pastriesList', 'Column', { gap: 'sm' }, ['pastry1', 'pastry2', 'pastry3', 'pastry4']),
        pastry1: el('pastry1', 'Row', { justify: 'between' }, ['pastry1Name', 'pastry1Price']),
        pastry2: el('pastry2', 'Row', { justify: 'between' }, ['pastry2Name', 'pastry2Price']),
        pastry3: el('pastry3', 'Row', { justify: 'between' }, ['pastry3Name', 'pastry3Price']),
        pastry4: el('pastry4', 'Row', { justify: 'between' }, ['pastry4Name', 'pastry4Price']),
        pastry1Name: el('pastry1Name', 'Text', { content: 'Croissant' }),
        pastry1Price: el('pastry1Price', 'Text', { content: '$4.00' }),
        pastry2Name: el('pastry2Name', 'Text', { content: 'Blueberry Muffin' }),
        pastry2Price: el('pastry2Price', 'Text', { content: '$3.75' }),
        pastry3Name: el('pastry3Name', 'Text', { content: 'Cinnamon Roll' }),
        pastry3Price: el('pastry3Price', 'Text', { content: '$4.50' }),
        pastry4Name: el('pastry4Name', 'Text', { content: 'Banana Bread' }),
        pastry4Price: el('pastry4Price', 'Text', { content: '$3.50' }),
        foodList: el('foodList', 'Column', { gap: 'sm' }, ['food1', 'food2', 'food3', 'food4']),
        food1: el('food1', 'Row', { justify: 'between' }, ['food1Name', 'food1Price']),
        food2: el('food2', 'Row', { justify: 'between' }, ['food2Name', 'food2Price']),
        food3: el('food3', 'Row', { justify: 'between' }, ['food3Name', 'food3Price']),
        food4: el('food4', 'Row', { justify: 'between' }, ['food4Name', 'food4Price']),
        food1Name: el('food1Name', 'Text', { content: 'Avocado Toast' }),
        food1Price: el('food1Price', 'Text', { content: '$9.00' }),
        food2Name: el('food2Name', 'Text', { content: 'Breakfast Sandwich' }),
        food2Price: el('food2Price', 'Text', { content: '$8.50' }),
        food3Name: el('food3Name', 'Text', { content: 'Grain Bowl' }),
        food3Price: el('food3Price', 'Text', { content: '$12.00' }),
        food4Name: el('food4Name', 'Text', { content: 'Yogurt Parfait' }),
        food4Price: el('food4Price', 'Text', { content: '$7.00' }),
        locations: el('locations', 'Container', { maxWidth: 'lg' }, ['locHeader', 'locList']),
        locHeader: el('locHeader', 'Heading', { level: '2', text: 'Find Us', align: 'center' }),
        locList: el('locList', 'Grid', { columns: 2, gap: 'md' }, ['loc1', 'loc2']),
        loc1: el('loc1', 'Card', { variant: 'outlined' }, ['loc1Info']),
        loc2: el('loc2', 'Card', { variant: 'outlined' }, ['loc2Info']),
        loc1Info: el('loc1Info', 'Column', { gap: 'xs' }, ['loc1Name', 'loc1Addr', 'loc1Hours']),
        loc2Info: el('loc2Info', 'Column', { gap: 'xs' }, ['loc2Name', 'loc2Addr', 'loc2Hours']),
        loc1Name: el('loc1Name', 'Heading', { level: '5', text: 'Midtown' }),
        loc1Addr: el('loc1Addr', 'Text', { content: '456 Coffee Lane', color: 'muted' }),
        loc1Hours: el('loc1Hours', 'Text', { content: '6am - 8pm Daily', color: 'muted', size: 'sm' }),
        loc2Name: el('loc2Name', 'Heading', { level: '5', text: 'Brooklyn Heights' }),
        loc2Addr: el('loc2Addr', 'Text', { content: '789 Bean Street', color: 'muted' }),
        loc2Hours: el('loc2Hours', 'Text', { content: '7am - 7pm Daily', color: 'muted', size: 'sm' }),
        about: el('about', 'Container', { maxWidth: 'md' }, ['aboutContent']),
        aboutContent: el('aboutContent', 'Column', { gap: 'md', align: 'center' }, ['aboutTitle', 'aboutText']),
        aboutTitle: el('aboutTitle', 'Heading', { level: '2', text: 'Our Story', align: 'center' }),
        aboutText: el('aboutText', 'Text', { content: 'Founded in 2015, Brew & Bean started as a small roastery with a big dream: to bring exceptional coffee to our community. Today, we source beans from sustainable farms around the world and roast them right here in Brooklyn.', align: 'center', color: 'muted' }),
        footer: el('footer', 'Text', { content: '© 2024 Brew & Bean Coffee Co.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-fitness-gym',
    name: 'Fitness Gym Landing',
    description: 'Gym website with classes, trainers, pricing, and testimonials',
    category: 'landing-pages',
    tags: ['landing', 'fitness', 'gym', 'health', 'workout'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'classes', 'trainers', 'pricing', 'testimonials', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'joinBtn']),
        logo: el('logo', 'Heading', { level: '4', text: 'FitPro Gym' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navClasses', 'navTrainers', 'navPricing', 'navContact']),
        navClasses: el('navClasses', 'Link', { text: 'Classes', href: '#' }),
        navTrainers: el('navTrainers', 'Link', { text: 'Trainers', href: '#' }),
        navPricing: el('navPricing', 'Link', { text: 'Pricing', href: '#' }),
        navContact: el('navContact', 'Link', { text: 'Contact', href: '#' }),
        joinBtn: el('joinBtn', 'Button', { label: 'Join Now', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'xl' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroDesc', 'heroStats', 'heroCta']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Transform Your Body', align: 'center' }),
        heroDesc: el('heroDesc', 'Text', { content: 'State-of-the-art equipment. Expert trainers. Results guaranteed.', align: 'center', color: 'muted' }),
        heroStats: el('heroStats', 'Row', { gap: 'xl', justify: 'center' }, ['hStat1', 'hStat2', 'hStat3']),
        hStat1: el('hStat1', 'Metric', { label: 'Members', value: '5,000+' }),
        hStat2: el('hStat2', 'Metric', { label: 'Classes/Week', value: '100+' }),
        hStat3: el('hStat3', 'Metric', { label: 'Trainers', value: '25' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['trialBtn', 'tourBtn']),
        trialBtn: el('trialBtn', 'Button', { label: 'Start Free Trial', variant: 'solid' }),
        tourBtn: el('tourBtn', 'Button', { label: 'Book a Tour', variant: 'outline' }),
        classes: el('classes', 'Container', { maxWidth: 'xl' }, ['classesHeader', 'classesGrid']),
        classesHeader: el('classesHeader', 'Column', { gap: 'sm', align: 'center' }, ['classesTitle', 'classesDesc']),
        classesTitle: el('classesTitle', 'Heading', { level: '2', text: 'Our Classes', align: 'center' }),
        classesDesc: el('classesDesc', 'Text', { content: 'Something for every fitness level', align: 'center', color: 'muted' }),
        classesGrid: el('classesGrid', 'Grid', { columns: 4, gap: 'md' }, ['class1', 'class2', 'class3', 'class4']),
        class1: el('class1', 'Card', { variant: 'elevated' }, ['class1Content']),
        class2: el('class2', 'Card', { variant: 'elevated' }, ['class2Content']),
        class3: el('class3', 'Card', { variant: 'elevated' }, ['class3Content']),
        class4: el('class4', 'Card', { variant: 'elevated' }, ['class4Content']),
        class1Content: el('class1Content', 'Column', { gap: 'sm', align: 'center' }, ['class1Name', 'class1Desc', 'class1Duration']),
        class2Content: el('class2Content', 'Column', { gap: 'sm', align: 'center' }, ['class2Name', 'class2Desc', 'class2Duration']),
        class3Content: el('class3Content', 'Column', { gap: 'sm', align: 'center' }, ['class3Name', 'class3Desc', 'class3Duration']),
        class4Content: el('class4Content', 'Column', { gap: 'sm', align: 'center' }, ['class4Name', 'class4Desc', 'class4Duration']),
        class1Name: el('class1Name', 'Heading', { level: '4', text: 'HIIT' }),
        class1Desc: el('class1Desc', 'Text', { content: 'High-intensity interval training', color: 'muted', size: 'sm', align: 'center' }),
        class1Duration: el('class1Duration', 'Badge', { text: '45 min', variant: 'outline' }),
        class2Name: el('class2Name', 'Heading', { level: '4', text: 'Yoga' }),
        class2Desc: el('class2Desc', 'Text', { content: 'Mind-body connection', color: 'muted', size: 'sm', align: 'center' }),
        class2Duration: el('class2Duration', 'Badge', { text: '60 min', variant: 'outline' }),
        class3Name: el('class3Name', 'Heading', { level: '4', text: 'Spin' }),
        class3Desc: el('class3Desc', 'Text', { content: 'Indoor cycling cardio', color: 'muted', size: 'sm', align: 'center' }),
        class3Duration: el('class3Duration', 'Badge', { text: '45 min', variant: 'outline' }),
        class4Name: el('class4Name', 'Heading', { level: '4', text: 'Strength' }),
        class4Desc: el('class4Desc', 'Text', { content: 'Build muscle & power', color: 'muted', size: 'sm', align: 'center' }),
        class4Duration: el('class4Duration', 'Badge', { text: '50 min', variant: 'outline' }),
        trainers: el('trainers', 'Container', { maxWidth: 'xl' }, ['trainersHeader', 'trainersGrid']),
        trainersHeader: el('trainersHeader', 'Heading', { level: '2', text: 'Meet Our Trainers', align: 'center' }),
        trainersGrid: el('trainersGrid', 'Grid', { columns: 3, gap: 'lg' }, ['trainer1', 'trainer2', 'trainer3']),
        trainer1: el('trainer1', 'Card', { variant: 'outlined' }, ['trainer1Content']),
        trainer2: el('trainer2', 'Card', { variant: 'outlined' }, ['trainer2Content']),
        trainer3: el('trainer3', 'Card', { variant: 'outlined' }, ['trainer3Content']),
        trainer1Content: el('trainer1Content', 'Column', { gap: 'sm', align: 'center' }, ['trainer1Avatar', 'trainer1Name', 'trainer1Spec']),
        trainer2Content: el('trainer2Content', 'Column', { gap: 'sm', align: 'center' }, ['trainer2Avatar', 'trainer2Name', 'trainer2Spec']),
        trainer3Content: el('trainer3Content', 'Column', { gap: 'sm', align: 'center' }, ['trainer3Avatar', 'trainer3Name', 'trainer3Spec']),
        trainer1Avatar: el('trainer1Avatar', 'Avatar', { name: 'Mike Johnson', size: 'lg' }),
        trainer1Name: el('trainer1Name', 'Heading', { level: '4', text: 'Mike Johnson' }),
        trainer1Spec: el('trainer1Spec', 'Text', { content: 'Strength & Conditioning', color: 'muted' }),
        trainer2Avatar: el('trainer2Avatar', 'Avatar', { name: 'Sarah Chen', size: 'lg' }),
        trainer2Name: el('trainer2Name', 'Heading', { level: '4', text: 'Sarah Chen' }),
        trainer2Spec: el('trainer2Spec', 'Text', { content: 'Yoga & Pilates', color: 'muted' }),
        trainer3Avatar: el('trainer3Avatar', 'Avatar', { name: 'David Martinez', size: 'lg' }),
        trainer3Name: el('trainer3Name', 'Heading', { level: '4', text: 'David Martinez' }),
        trainer3Spec: el('trainer3Spec', 'Text', { content: 'HIIT & Cardio', color: 'muted' }),
        pricing: el('pricing', 'Container', { maxWidth: 'xl' }, ['pricingHeader', 'pricingGrid']),
        pricingHeader: el('pricingHeader', 'Heading', { level: '2', text: 'Membership Plans', align: 'center' }),
        pricingGrid: el('pricingGrid', 'Grid', { columns: 3, gap: 'lg' }, ['plan1', 'plan2', 'plan3']),
        plan1: el('plan1', 'Card', { variant: 'outlined' }, ['plan1Content']),
        plan2: el('plan2', 'Card', { variant: 'elevated' }, ['plan2Content']),
        plan3: el('plan3', 'Card', { variant: 'outlined' }, ['plan3Content']),
        plan1Content: el('plan1Content', 'Column', { gap: 'md', align: 'center' }, ['plan1Name', 'plan1Price', 'plan1Features', 'plan1Btn']),
        plan2Content: el('plan2Content', 'Column', { gap: 'md', align: 'center' }, ['plan2Badge', 'plan2Name', 'plan2Price', 'plan2Features', 'plan2Btn']),
        plan3Content: el('plan3Content', 'Column', { gap: 'md', align: 'center' }, ['plan3Name', 'plan3Price', 'plan3Features', 'plan3Btn']),
        plan1Name: el('plan1Name', 'Heading', { level: '4', text: 'Basic' }),
        plan1Price: el('plan1Price', 'Heading', { level: '2', text: '$29/mo' }),
        plan1Features: el('plan1Features', 'Column', { gap: 'xs' }, ['p1f1', 'p1f2', 'p1f3']),
        p1f1: el('p1f1', 'Text', { content: 'Gym access', color: 'muted' }),
        p1f2: el('p1f2', 'Text', { content: 'Locker room', color: 'muted' }),
        p1f3: el('p1f3', 'Text', { content: 'Free parking', color: 'muted' }),
        plan1Btn: el('plan1Btn', 'Button', { label: 'Choose Basic', variant: 'outline', fullWidth: true }),
        plan2Badge: el('plan2Badge', 'Badge', { text: 'Most Popular', variant: 'solid', color: 'success' }),
        plan2Name: el('plan2Name', 'Heading', { level: '4', text: 'Pro' }),
        plan2Price: el('plan2Price', 'Heading', { level: '2', text: '$59/mo' }),
        plan2Features: el('plan2Features', 'Column', { gap: 'xs' }, ['p2f1', 'p2f2', 'p2f3', 'p2f4']),
        p2f1: el('p2f1', 'Text', { content: 'All Basic features', color: 'muted' }),
        p2f2: el('p2f2', 'Text', { content: 'Unlimited classes', color: 'muted' }),
        p2f3: el('p2f3', 'Text', { content: 'Sauna access', color: 'muted' }),
        p2f4: el('p2f4', 'Text', { content: 'Guest passes (2/mo)', color: 'muted' }),
        plan2Btn: el('plan2Btn', 'Button', { label: 'Choose Pro', variant: 'solid', fullWidth: true }),
        plan3Name: el('plan3Name', 'Heading', { level: '4', text: 'Elite' }),
        plan3Price: el('plan3Price', 'Heading', { level: '2', text: '$99/mo' }),
        plan3Features: el('plan3Features', 'Column', { gap: 'xs' }, ['p3f1', 'p3f2', 'p3f3', 'p3f4']),
        p3f1: el('p3f1', 'Text', { content: 'All Pro features', color: 'muted' }),
        p3f2: el('p3f2', 'Text', { content: 'Personal training (4/mo)', color: 'muted' }),
        p3f3: el('p3f3', 'Text', { content: 'Nutrition coaching', color: 'muted' }),
        p3f4: el('p3f4', 'Text', { content: 'Priority booking', color: 'muted' }),
        plan3Btn: el('plan3Btn', 'Button', { label: 'Choose Elite', variant: 'outline', fullWidth: true }),
        testimonials: el('testimonials', 'Container', { maxWidth: 'lg' }, ['testHeader', 'testGrid']),
        testHeader: el('testHeader', 'Heading', { level: '2', text: 'Success Stories', align: 'center' }),
        testGrid: el('testGrid', 'Grid', { columns: 2, gap: 'lg' }, ['test1', 'test2']),
        test1: el('test1', 'Card', { variant: 'outlined' }, ['test1Content']),
        test2: el('test2', 'Card', { variant: 'outlined' }, ['test2Content']),
        test1Content: el('test1Content', 'Column', { gap: 'sm' }, ['test1Text', 'test1Author']),
        test2Content: el('test2Content', 'Column', { gap: 'sm' }, ['test2Text', 'test2Author']),
        test1Text: el('test1Text', 'Text', { content: 'Lost 30 pounds in 6 months! The trainers here are amazing and the community keeps me motivated.' }),
        test1Author: el('test1Author', 'Text', { content: '— Jennifer K.', color: 'muted' }),
        test2Text: el('test2Text', 'Text', { content: 'Best gym I have ever been to. Clean facilities, great equipment, and the classes are top-notch.' }),
        test2Author: el('test2Author', 'Text', { content: '— Mark T.', color: 'muted' }),
        footer: el('footer', 'Text', { content: '© 2024 FitPro Gym. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-saas',
    name: 'SaaS Product Landing',
    description: 'Software product page with features, pricing, testimonials, FAQ, and CTA',
    category: 'landing-pages',
    tags: ['landing', 'saas', 'software', 'product', 'tech'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'features', 'pricing', 'testimonials', 'faq', 'cta', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'navActions']),
        logo: el('logo', 'Heading', { level: '4', text: 'CloudSync' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navFeatures', 'navPricing', 'navDocs', 'navBlog']),
        navFeatures: el('navFeatures', 'Link', { text: 'Features', href: '#' }),
        navPricing: el('navPricing', 'Link', { text: 'Pricing', href: '#' }),
        navDocs: el('navDocs', 'Link', { text: 'Docs', href: '#' }),
        navBlog: el('navBlog', 'Link', { text: 'Blog', href: '#' }),
        navActions: el('navActions', 'Row', { gap: 'sm' }, ['loginBtn', 'signupBtn']),
        loginBtn: el('loginBtn', 'Button', { label: 'Log In', variant: 'ghost' }),
        signupBtn: el('signupBtn', 'Button', { label: 'Start Free', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'lg' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroBadge', 'heroTitle', 'heroDesc', 'heroCta', 'heroTrust']),
        heroBadge: el('heroBadge', 'Badge', { text: 'New: AI-Powered Analytics', variant: 'outline' }),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Sync Your Data Everywhere', align: 'center' }),
        heroDesc: el('heroDesc', 'Text', { content: 'Real-time data synchronization across all your devices and teams. Secure, fast, and reliable.', align: 'center', color: 'muted' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['startBtn', 'demoBtn']),
        startBtn: el('startBtn', 'Button', { label: 'Start Free Trial', variant: 'solid' }),
        demoBtn: el('demoBtn', 'Button', { label: 'Watch Demo', variant: 'outline' }),
        heroTrust: el('heroTrust', 'Text', { content: 'Trusted by 10,000+ companies worldwide', color: 'muted', size: 'sm', align: 'center' }),
        features: el('features', 'Container', { maxWidth: 'xl' }, ['featuresHeader', 'featuresGrid']),
        featuresHeader: el('featuresHeader', 'Column', { gap: 'sm', align: 'center' }, ['featuresTitle', 'featuresDesc']),
        featuresTitle: el('featuresTitle', 'Heading', { level: '2', text: 'Everything You Need', align: 'center' }),
        featuresDesc: el('featuresDesc', 'Text', { content: 'Powerful features to help your team work smarter', align: 'center', color: 'muted' }),
        featuresGrid: el('featuresGrid', 'Grid', { columns: 3, gap: 'lg' }, ['feat1', 'feat2', 'feat3', 'feat4', 'feat5', 'feat6']),
        feat1: el('feat1', 'Card', { variant: 'outlined' }, ['feat1Content']),
        feat2: el('feat2', 'Card', { variant: 'outlined' }, ['feat2Content']),
        feat3: el('feat3', 'Card', { variant: 'outlined' }, ['feat3Content']),
        feat4: el('feat4', 'Card', { variant: 'outlined' }, ['feat4Content']),
        feat5: el('feat5', 'Card', { variant: 'outlined' }, ['feat5Content']),
        feat6: el('feat6', 'Card', { variant: 'outlined' }, ['feat6Content']),
        feat1Content: el('feat1Content', 'Column', { gap: 'sm' }, ['feat1Title', 'feat1Desc']),
        feat2Content: el('feat2Content', 'Column', { gap: 'sm' }, ['feat2Title', 'feat2Desc']),
        feat3Content: el('feat3Content', 'Column', { gap: 'sm' }, ['feat3Title', 'feat3Desc']),
        feat4Content: el('feat4Content', 'Column', { gap: 'sm' }, ['feat4Title', 'feat4Desc']),
        feat5Content: el('feat5Content', 'Column', { gap: 'sm' }, ['feat5Title', 'feat5Desc']),
        feat6Content: el('feat6Content', 'Column', { gap: 'sm' }, ['feat6Title', 'feat6Desc']),
        feat1Title: el('feat1Title', 'Heading', { level: '4', text: 'Real-time Sync' }),
        feat1Desc: el('feat1Desc', 'Text', { content: 'Changes sync instantly across all devices', color: 'muted' }),
        feat2Title: el('feat2Title', 'Heading', { level: '4', text: 'Team Collaboration' }),
        feat2Desc: el('feat2Desc', 'Text', { content: 'Work together with unlimited team members', color: 'muted' }),
        feat3Title: el('feat3Title', 'Heading', { level: '4', text: 'Advanced Security' }),
        feat3Desc: el('feat3Desc', 'Text', { content: 'Enterprise-grade encryption and compliance', color: 'muted' }),
        feat4Title: el('feat4Title', 'Heading', { level: '4', text: 'API Access' }),
        feat4Desc: el('feat4Desc', 'Text', { content: 'RESTful API for custom integrations', color: 'muted' }),
        feat5Title: el('feat5Title', 'Heading', { level: '4', text: 'Analytics Dashboard' }),
        feat5Desc: el('feat5Desc', 'Text', { content: 'Deep insights into your data usage', color: 'muted' }),
        feat6Title: el('feat6Title', 'Heading', { level: '4', text: '24/7 Support' }),
        feat6Desc: el('feat6Desc', 'Text', { content: 'Expert support whenever you need it', color: 'muted' }),
        pricing: el('pricing', 'Container', { maxWidth: 'xl' }, ['pricingHeader', 'pricingGrid']),
        pricingHeader: el('pricingHeader', 'Heading', { level: '2', text: 'Simple Pricing', align: 'center' }),
        pricingGrid: el('pricingGrid', 'Grid', { columns: 3, gap: 'lg' }, ['price1', 'price2', 'price3']),
        price1: el('price1', 'Card', { variant: 'outlined' }, ['price1Content']),
        price2: el('price2', 'Card', { variant: 'elevated' }, ['price2Content']),
        price3: el('price3', 'Card', { variant: 'outlined' }, ['price3Content']),
        price1Content: el('price1Content', 'Column', { gap: 'md', align: 'center' }, ['price1Name', 'price1Amount', 'price1Feats', 'price1Btn']),
        price2Content: el('price2Content', 'Column', { gap: 'md', align: 'center' }, ['price2Badge', 'price2Name', 'price2Amount', 'price2Feats', 'price2Btn']),
        price3Content: el('price3Content', 'Column', { gap: 'md', align: 'center' }, ['price3Name', 'price3Amount', 'price3Feats', 'price3Btn']),
        price1Name: el('price1Name', 'Heading', { level: '4', text: 'Starter' }),
        price1Amount: el('price1Amount', 'Heading', { level: '2', text: '$19/mo' }),
        price1Feats: el('price1Feats', 'Column', { gap: 'xs' }, ['pr1f1', 'pr1f2', 'pr1f3']),
        pr1f1: el('pr1f1', 'Text', { content: '5 GB storage', color: 'muted' }),
        pr1f2: el('pr1f2', 'Text', { content: '3 team members', color: 'muted' }),
        pr1f3: el('pr1f3', 'Text', { content: 'Email support', color: 'muted' }),
        price1Btn: el('price1Btn', 'Button', { label: 'Get Started', variant: 'outline', fullWidth: true }),
        price2Badge: el('price2Badge', 'Badge', { text: 'Best Value', variant: 'solid', color: 'info' }),
        price2Name: el('price2Name', 'Heading', { level: '4', text: 'Team' }),
        price2Amount: el('price2Amount', 'Heading', { level: '2', text: '$49/mo' }),
        price2Feats: el('price2Feats', 'Column', { gap: 'xs' }, ['pr2f1', 'pr2f2', 'pr2f3', 'pr2f4']),
        pr2f1: el('pr2f1', 'Text', { content: '100 GB storage', color: 'muted' }),
        pr2f2: el('pr2f2', 'Text', { content: 'Unlimited members', color: 'muted' }),
        pr2f3: el('pr2f3', 'Text', { content: 'Priority support', color: 'muted' }),
        pr2f4: el('pr2f4', 'Text', { content: 'API access', color: 'muted' }),
        price2Btn: el('price2Btn', 'Button', { label: 'Get Started', variant: 'solid', fullWidth: true }),
        price3Name: el('price3Name', 'Heading', { level: '4', text: 'Enterprise' }),
        price3Amount: el('price3Amount', 'Heading', { level: '2', text: 'Custom' }),
        price3Feats: el('price3Feats', 'Column', { gap: 'xs' }, ['pr3f1', 'pr3f2', 'pr3f3', 'pr3f4']),
        pr3f1: el('pr3f1', 'Text', { content: 'Unlimited storage', color: 'muted' }),
        pr3f2: el('pr3f2', 'Text', { content: 'SSO & SAML', color: 'muted' }),
        pr3f3: el('pr3f3', 'Text', { content: 'Dedicated support', color: 'muted' }),
        pr3f4: el('pr3f4', 'Text', { content: 'Custom integrations', color: 'muted' }),
        price3Btn: el('price3Btn', 'Button', { label: 'Contact Sales', variant: 'outline', fullWidth: true }),
        testimonials: el('testimonials', 'Container', { maxWidth: 'lg' }, ['testHeader', 'testGrid']),
        testHeader: el('testHeader', 'Heading', { level: '2', text: 'Loved by Teams', align: 'center' }),
        testGrid: el('testGrid', 'Grid', { columns: 2, gap: 'lg' }, ['test1', 'test2']),
        test1: el('test1', 'Card', { variant: 'outlined' }, ['test1Content']),
        test2: el('test2', 'Card', { variant: 'outlined' }, ['test2Content']),
        test1Content: el('test1Content', 'Column', { gap: 'sm' }, ['test1Quote', 'test1Author']),
        test2Content: el('test2Content', 'Column', { gap: 'sm' }, ['test2Quote', 'test2Author']),
        test1Quote: el('test1Quote', 'Text', { content: 'CloudSync has transformed how our team collaborates. We can not imagine working without it.' }),
        test1Author: el('test1Author', 'Text', { content: '— Sarah J., CTO at TechCorp', color: 'muted' }),
        test2Quote: el('test2Quote', 'Text', { content: 'The best investment we have made. Setup took minutes and the ROI was immediate.' }),
        test2Author: el('test2Author', 'Text', { content: '— Mike R., Founder at StartupX', color: 'muted' }),
        faq: el('faq', 'Container', { maxWidth: 'md' }, ['faqHeader', 'faqList']),
        faqHeader: el('faqHeader', 'Heading', { level: '2', text: 'Frequently Asked Questions', align: 'center' }),
        faqList: el('faqList', 'Accordion', {}, ['faq1', 'faq2', 'faq3']),
        faq1: el('faq1', 'AccordionItem', { title: 'How does the free trial work?' }, ['faq1Answer']),
        faq1Answer: el('faq1Answer', 'Text', { content: 'Start with 14 days free, no credit card required. Access all features during your trial.' }),
        faq2: el('faq2', 'AccordionItem', { title: 'Can I change plans later?' }, ['faq2Answer']),
        faq2Answer: el('faq2Answer', 'Text', { content: 'Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately.' }),
        faq3: el('faq3', 'AccordionItem', { title: 'Is my data secure?' }, ['faq3Answer']),
        faq3Answer: el('faq3Answer', 'Text', { content: 'We use AES-256 encryption, SOC 2 compliance, and regular security audits to protect your data.' }),
        cta: el('cta', 'Container', { maxWidth: 'md' }, ['ctaCard']),
        ctaCard: el('ctaCard', 'Card', { variant: 'elevated' }, ['ctaContent']),
        ctaContent: el('ctaContent', 'Column', { gap: 'md', align: 'center' }, ['ctaTitle', 'ctaDesc', 'ctaBtn']),
        ctaTitle: el('ctaTitle', 'Heading', { level: '2', text: 'Ready to Get Started?', align: 'center' }),
        ctaDesc: el('ctaDesc', 'Text', { content: 'Join thousands of teams already using CloudSync', align: 'center', color: 'muted' }),
        ctaBtn: el('ctaBtn', 'Button', { label: 'Start Your Free Trial', variant: 'solid' }),
        footer: el('footer', 'Text', { content: '© 2024 CloudSync Inc. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-portfolio',
    name: 'Portfolio Website',
    description: 'Personal portfolio with hero, projects, about, and contact',
    category: 'landing-pages',
    tags: ['landing', 'portfolio', 'personal', 'creative', 'designer'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'projects', 'about', 'contact', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks']),
        logo: el('logo', 'Heading', { level: '4', text: 'Alex Chen' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navWork', 'navAbout', 'navContact']),
        navWork: el('navWork', 'Link', { text: 'Work', href: '#' }),
        navAbout: el('navAbout', 'Link', { text: 'About', href: '#' }),
        navContact: el('navContact', 'Link', { text: 'Contact', href: '#' }),
        hero: el('hero', 'Container', { maxWidth: 'lg' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'md' }, ['heroTitle', 'heroDesc', 'heroLinks']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Product Designer & Developer' }),
        heroDesc: el('heroDesc', 'Text', { content: 'I craft digital experiences that are beautiful, functional, and user-centered. Based in San Francisco, working globally.', color: 'muted' }),
        heroLinks: el('heroLinks', 'Row', { gap: 'md' }, ['resumeBtn', 'linkedinLink', 'githubLink']),
        resumeBtn: el('resumeBtn', 'Button', { label: 'Download Resume', variant: 'solid' }),
        linkedinLink: el('linkedinLink', 'Button', { label: 'LinkedIn', variant: 'ghost' }),
        githubLink: el('githubLink', 'Button', { label: 'GitHub', variant: 'ghost' }),
        projects: el('projects', 'Container', { maxWidth: 'xl' }, ['projectsHeader', 'projectsGrid']),
        projectsHeader: el('projectsHeader', 'Heading', { level: '2', text: 'Selected Work' }),
        projectsGrid: el('projectsGrid', 'Grid', { columns: 2, gap: 'lg' }, ['proj1', 'proj2', 'proj3', 'proj4']),
        proj1: el('proj1', 'Card', { variant: 'elevated', hoverable: true }, ['proj1Img', 'proj1Body']),
        proj2: el('proj2', 'Card', { variant: 'elevated', hoverable: true }, ['proj2Img', 'proj2Body']),
        proj3: el('proj3', 'Card', { variant: 'elevated', hoverable: true }, ['proj3Img', 'proj3Body']),
        proj4: el('proj4', 'Card', { variant: 'elevated', hoverable: true }, ['proj4Img', 'proj4Body']),
        proj1Img: el('proj1Img', 'Image', { src: '/placeholder-project.jpg', alt: 'FinTech Dashboard' }),
        proj2Img: el('proj2Img', 'Image', { src: '/placeholder-project.jpg', alt: 'E-commerce Redesign' }),
        proj3Img: el('proj3Img', 'Image', { src: '/placeholder-project.jpg', alt: 'Mobile Banking App' }),
        proj4Img: el('proj4Img', 'Image', { src: '/placeholder-project.jpg', alt: 'Healthcare Platform' }),
        proj1Body: el('proj1Body', 'Column', { gap: 'sm' }, ['proj1Title', 'proj1Desc', 'proj1Tags']),
        proj2Body: el('proj2Body', 'Column', { gap: 'sm' }, ['proj2Title', 'proj2Desc', 'proj2Tags']),
        proj3Body: el('proj3Body', 'Column', { gap: 'sm' }, ['proj3Title', 'proj3Desc', 'proj3Tags']),
        proj4Body: el('proj4Body', 'Column', { gap: 'sm' }, ['proj4Title', 'proj4Desc', 'proj4Tags']),
        proj1Title: el('proj1Title', 'Heading', { level: '4', text: 'FinTech Dashboard' }),
        proj1Desc: el('proj1Desc', 'Text', { content: 'Analytics platform for financial services', color: 'muted' }),
        proj1Tags: el('proj1Tags', 'Row', { gap: 'xs' }, ['proj1Tag1', 'proj1Tag2']),
        proj1Tag1: el('proj1Tag1', 'Badge', { text: 'UX Design', variant: 'outline' }),
        proj1Tag2: el('proj1Tag2', 'Badge', { text: 'React', variant: 'outline' }),
        proj2Title: el('proj2Title', 'Heading', { level: '4', text: 'E-commerce Redesign' }),
        proj2Desc: el('proj2Desc', 'Text', { content: 'Complete overhaul of shopping experience', color: 'muted' }),
        proj2Tags: el('proj2Tags', 'Row', { gap: 'xs' }, ['proj2Tag1', 'proj2Tag2']),
        proj2Tag1: el('proj2Tag1', 'Badge', { text: 'UI Design', variant: 'outline' }),
        proj2Tag2: el('proj2Tag2', 'Badge', { text: 'Figma', variant: 'outline' }),
        proj3Title: el('proj3Title', 'Heading', { level: '4', text: 'Mobile Banking App' }),
        proj3Desc: el('proj3Desc', 'Text', { content: 'iOS and Android banking application', color: 'muted' }),
        proj3Tags: el('proj3Tags', 'Row', { gap: 'xs' }, ['proj3Tag1', 'proj3Tag2']),
        proj3Tag1: el('proj3Tag1', 'Badge', { text: 'Mobile', variant: 'outline' }),
        proj3Tag2: el('proj3Tag2', 'Badge', { text: 'Flutter', variant: 'outline' }),
        proj4Title: el('proj4Title', 'Heading', { level: '4', text: 'Healthcare Platform' }),
        proj4Desc: el('proj4Desc', 'Text', { content: 'Patient management system design', color: 'muted' }),
        proj4Tags: el('proj4Tags', 'Row', { gap: 'xs' }, ['proj4Tag1', 'proj4Tag2']),
        proj4Tag1: el('proj4Tag1', 'Badge', { text: 'Research', variant: 'outline' }),
        proj4Tag2: el('proj4Tag2', 'Badge', { text: 'Design System', variant: 'outline' }),
        about: el('about', 'Container', { maxWidth: 'md' }, ['aboutContent']),
        aboutContent: el('aboutContent', 'Row', { gap: 'xl', align: 'start' }, ['aboutAvatar', 'aboutText']),
        aboutAvatar: el('aboutAvatar', 'Avatar', { name: 'Alex Chen', size: 'lg' }),
        aboutText: el('aboutText', 'Column', { gap: 'md' }, ['aboutTitle', 'aboutBio', 'aboutSkills']),
        aboutTitle: el('aboutTitle', 'Heading', { level: '2', text: 'About Me' }),
        aboutBio: el('aboutBio', 'Text', { content: 'With 8 years of experience in product design and development, I bridge the gap between beautiful design and technical implementation. I have worked with startups and Fortune 500 companies to create impactful digital products.', color: 'muted' }),
        aboutSkills: el('aboutSkills', 'Row', { gap: 'sm' }, ['skill1', 'skill2', 'skill3', 'skill4']),
        skill1: el('skill1', 'Badge', { text: 'Figma', variant: 'solid' }),
        skill2: el('skill2', 'Badge', { text: 'React', variant: 'solid' }),
        skill3: el('skill3', 'Badge', { text: 'TypeScript', variant: 'solid' }),
        skill4: el('skill4', 'Badge', { text: 'Node.js', variant: 'solid' }),
        contact: el('contact', 'Container', { maxWidth: 'sm' }, ['contactContent']),
        contactContent: el('contactContent', 'Column', { gap: 'md', align: 'center' }, ['contactTitle', 'contactDesc', 'contactEmail', 'contactBtn']),
        contactTitle: el('contactTitle', 'Heading', { level: '2', text: 'Let\'s Work Together', align: 'center' }),
        contactDesc: el('contactDesc', 'Text', { content: 'Have a project in mind? I would love to hear about it.', align: 'center', color: 'muted' }),
        contactEmail: el('contactEmail', 'Text', { content: 'alex@designstudio.com', align: 'center' }),
        contactBtn: el('contactBtn', 'Button', { label: 'Send Message', variant: 'solid' }),
        footer: el('footer', 'Text', { content: '© 2024 Alex Chen. Built with love.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-real-estate',
    name: 'Real Estate Agency',
    description: 'Real estate website with listings, agents, and contact form',
    category: 'landing-pages',
    tags: ['landing', 'real-estate', 'property', 'listings', 'agents'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'search', 'listings', 'agents', 'contact', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'navActions']),
        logo: el('logo', 'Heading', { level: '4', text: 'HomeFind Realty' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navBuy', 'navSell', 'navRent', 'navAgents']),
        navBuy: el('navBuy', 'Link', { text: 'Buy', href: '#' }),
        navSell: el('navSell', 'Link', { text: 'Sell', href: '#' }),
        navRent: el('navRent', 'Link', { text: 'Rent', href: '#' }),
        navAgents: el('navAgents', 'Link', { text: 'Agents', href: '#' }),
        navActions: el('navActions', 'Button', { label: 'List Your Property', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'lg' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroDesc']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Find Your Dream Home', align: 'center' }),
        heroDesc: el('heroDesc', 'Text', { content: 'Discover the perfect property from our extensive listings', align: 'center', color: 'muted' }),
        search: el('search', 'Container', { maxWidth: 'xl' }, ['searchCard']),
        searchCard: el('searchCard', 'Card', { variant: 'elevated' }, ['searchForm']),
        searchForm: el('searchForm', 'Row', { gap: 'md', align: 'end' }, ['searchLocation', 'searchType', 'searchPrice', 'searchBtn']),
        searchLocation: el('searchLocation', 'Input', { label: 'Location', placeholder: 'City, ZIP, or neighborhood' }),
        searchType: el('searchType', 'Select', { label: 'Property Type', options: [{ value: 'all', label: 'All Types' }, { value: 'house', label: 'House' }, { value: 'condo', label: 'Condo' }, { value: 'townhouse', label: 'Townhouse' }] }),
        searchPrice: el('searchPrice', 'Select', { label: 'Price Range', options: [{ value: 'any', label: 'Any Price' }, { value: '500k', label: 'Up to $500K' }, { value: '1m', label: '$500K - $1M' }, { value: '2m', label: '$1M - $2M' }] }),
        searchBtn: el('searchBtn', 'Button', { label: 'Search', variant: 'solid' }),
        listings: el('listings', 'Container', { maxWidth: 'xl' }, ['listingsHeader', 'listingsGrid']),
        listingsHeader: el('listingsHeader', 'Row', { justify: 'between', align: 'center' }, ['listingsTitle', 'viewAllBtn']),
        listingsTitle: el('listingsTitle', 'Heading', { level: '2', text: 'Featured Properties' }),
        viewAllBtn: el('viewAllBtn', 'Button', { label: 'View All', variant: 'ghost' }),
        listingsGrid: el('listingsGrid', 'Grid', { columns: 3, gap: 'lg' }, ['listing1', 'listing2', 'listing3']),
        listing1: el('listing1', 'Card', { variant: 'elevated' }, ['list1Img', 'list1Body']),
        listing2: el('listing2', 'Card', { variant: 'elevated' }, ['list2Img', 'list2Body']),
        listing3: el('listing3', 'Card', { variant: 'elevated' }, ['list3Img', 'list3Body']),
        list1Img: el('list1Img', 'Image', { src: '/placeholder-house.jpg', alt: 'Modern Family Home' }),
        list2Img: el('list2Img', 'Image', { src: '/placeholder-house.jpg', alt: 'Downtown Condo' }),
        list3Img: el('list3Img', 'Image', { src: '/placeholder-house.jpg', alt: 'Suburban Estate' }),
        list1Body: el('list1Body', 'Column', { gap: 'sm' }, ['list1Price', 'list1Title', 'list1Details', 'list1Features']),
        list2Body: el('list2Body', 'Column', { gap: 'sm' }, ['list2Price', 'list2Title', 'list2Details', 'list2Features']),
        list3Body: el('list3Body', 'Column', { gap: 'sm' }, ['list3Price', 'list3Title', 'list3Details', 'list3Features']),
        list1Price: el('list1Price', 'Heading', { level: '3', text: '$750,000' }),
        list1Title: el('list1Title', 'Text', { content: '123 Oak Street, Palo Alto' }),
        list1Details: el('list1Details', 'Text', { content: '4 bed | 3 bath | 2,450 sqft', color: 'muted', size: 'sm' }),
        list1Features: el('list1Features', 'Row', { gap: 'xs' }, ['list1Tag1', 'list1Tag2']),
        list1Tag1: el('list1Tag1', 'Badge', { text: 'New Listing', color: 'success' }),
        list1Tag2: el('list1Tag2', 'Badge', { text: 'Open House', variant: 'outline' }),
        list2Price: el('list2Price', 'Heading', { level: '3', text: '$525,000' }),
        list2Title: el('list2Title', 'Text', { content: '456 Market St #12, San Francisco' }),
        list2Details: el('list2Details', 'Text', { content: '2 bed | 2 bath | 1,200 sqft', color: 'muted', size: 'sm' }),
        list2Features: el('list2Features', 'Row', { gap: 'xs' }, ['list2Tag1']),
        list2Tag1: el('list2Tag1', 'Badge', { text: 'Price Reduced', color: 'warning' }),
        list3Price: el('list3Price', 'Heading', { level: '3', text: '$1,250,000' }),
        list3Title: el('list3Title', 'Text', { content: '789 Hillside Dr, Los Altos' }),
        list3Details: el('list3Details', 'Text', { content: '5 bed | 4 bath | 3,800 sqft', color: 'muted', size: 'sm' }),
        list3Features: el('list3Features', 'Row', { gap: 'xs' }, ['list3Tag1', 'list3Tag2']),
        list3Tag1: el('list3Tag1', 'Badge', { text: 'Pool', variant: 'outline' }),
        list3Tag2: el('list3Tag2', 'Badge', { text: 'View', variant: 'outline' }),
        agents: el('agents', 'Container', { maxWidth: 'xl' }, ['agentsHeader', 'agentsGrid']),
        agentsHeader: el('agentsHeader', 'Heading', { level: '2', text: 'Our Top Agents', align: 'center' }),
        agentsGrid: el('agentsGrid', 'Grid', { columns: 4, gap: 'md' }, ['agent1', 'agent2', 'agent3', 'agent4']),
        agent1: el('agent1', 'Card', { variant: 'outlined' }, ['agent1Content']),
        agent2: el('agent2', 'Card', { variant: 'outlined' }, ['agent2Content']),
        agent3: el('agent3', 'Card', { variant: 'outlined' }, ['agent3Content']),
        agent4: el('agent4', 'Card', { variant: 'outlined' }, ['agent4Content']),
        agent1Content: el('agent1Content', 'Column', { gap: 'sm', align: 'center' }, ['agent1Avatar', 'agent1Name', 'agent1Sales', 'agent1Btn']),
        agent2Content: el('agent2Content', 'Column', { gap: 'sm', align: 'center' }, ['agent2Avatar', 'agent2Name', 'agent2Sales', 'agent2Btn']),
        agent3Content: el('agent3Content', 'Column', { gap: 'sm', align: 'center' }, ['agent3Avatar', 'agent3Name', 'agent3Sales', 'agent3Btn']),
        agent4Content: el('agent4Content', 'Column', { gap: 'sm', align: 'center' }, ['agent4Avatar', 'agent4Name', 'agent4Sales', 'agent4Btn']),
        agent1Avatar: el('agent1Avatar', 'Avatar', { name: 'Jennifer Lopez', size: 'lg' }),
        agent1Name: el('agent1Name', 'Heading', { level: '5', text: 'Jennifer Lopez' }),
        agent1Sales: el('agent1Sales', 'Text', { content: '142 homes sold', color: 'muted', size: 'sm' }),
        agent1Btn: el('agent1Btn', 'Button', { label: 'Contact', variant: 'outline', size: 'sm' }),
        agent2Avatar: el('agent2Avatar', 'Avatar', { name: 'Michael Park', size: 'lg' }),
        agent2Name: el('agent2Name', 'Heading', { level: '5', text: 'Michael Park' }),
        agent2Sales: el('agent2Sales', 'Text', { content: '98 homes sold', color: 'muted', size: 'sm' }),
        agent2Btn: el('agent2Btn', 'Button', { label: 'Contact', variant: 'outline', size: 'sm' }),
        agent3Avatar: el('agent3Avatar', 'Avatar', { name: 'Sarah Kim', size: 'lg' }),
        agent3Name: el('agent3Name', 'Heading', { level: '5', text: 'Sarah Kim' }),
        agent3Sales: el('agent3Sales', 'Text', { content: '87 homes sold', color: 'muted', size: 'sm' }),
        agent3Btn: el('agent3Btn', 'Button', { label: 'Contact', variant: 'outline', size: 'sm' }),
        agent4Avatar: el('agent4Avatar', 'Avatar', { name: 'David Chen', size: 'lg' }),
        agent4Name: el('agent4Name', 'Heading', { level: '5', text: 'David Chen' }),
        agent4Sales: el('agent4Sales', 'Text', { content: '76 homes sold', color: 'muted', size: 'sm' }),
        agent4Btn: el('agent4Btn', 'Button', { label: 'Contact', variant: 'outline', size: 'sm' }),
        contact: el('contact', 'Container', { maxWidth: 'md' }, ['contactCard']),
        contactCard: el('contactCard', 'Card', { variant: 'elevated' }, ['contactContent']),
        contactContent: el('contactContent', 'Column', { gap: 'md' }, ['contactTitle', 'contactForm']),
        contactTitle: el('contactTitle', 'Heading', { level: '2', text: 'Get in Touch', align: 'center' }),
        contactForm: el('contactForm', 'Column', { gap: 'md' }, ['contactRow', 'contactEmail', 'contactMessage', 'contactSubmit']),
        contactRow: el('contactRow', 'Row', { gap: 'md' }, ['contactFirstName', 'contactLastName']),
        contactFirstName: el('contactFirstName', 'Input', { label: 'First Name', placeholder: 'John' }),
        contactLastName: el('contactLastName', 'Input', { label: 'Last Name', placeholder: 'Doe' }),
        contactEmail: el('contactEmail', 'Input', { label: 'Email', type: 'email', placeholder: 'john@example.com' }),
        contactMessage: el('contactMessage', 'TextArea', { label: 'Message', placeholder: 'How can we help you?', rows: 4 }),
        contactSubmit: el('contactSubmit', 'Button', { label: 'Send Message', variant: 'solid', fullWidth: true }),
        footer: el('footer', 'Text', { content: '© 2024 HomeFind Realty. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-law-firm',
    name: 'Law Firm Landing',
    description: 'Professional law firm with practice areas, attorneys, and testimonials',
    category: 'landing-pages',
    tags: ['landing', 'law', 'legal', 'professional', 'attorneys'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'practiceAreas', 'attorneys', 'testimonials', 'contact', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'consultBtn']),
        logo: el('logo', 'Heading', { level: '4', text: 'Morrison & Associates' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navPractice', 'navTeam', 'navAbout', 'navContact']),
        navPractice: el('navPractice', 'Link', { text: 'Practice Areas', href: '#' }),
        navTeam: el('navTeam', 'Link', { text: 'Our Team', href: '#' }),
        navAbout: el('navAbout', 'Link', { text: 'About', href: '#' }),
        navContact: el('navContact', 'Link', { text: 'Contact', href: '#' }),
        consultBtn: el('consultBtn', 'Button', { label: 'Free Consultation', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'lg' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroDesc', 'heroStats', 'heroCta']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Justice. Integrity. Results.', align: 'center' }),
        heroDesc: el('heroDesc', 'Text', { content: 'Dedicated legal representation for individuals and businesses. Over 30 years of experience fighting for our clients.', align: 'center', color: 'muted' }),
        heroStats: el('heroStats', 'Row', { gap: 'xl', justify: 'center' }, ['heroStat1', 'heroStat2', 'heroStat3']),
        heroStat1: el('heroStat1', 'Column', { align: 'center' }, ['hs1Val', 'hs1Label']),
        heroStat2: el('heroStat2', 'Column', { align: 'center' }, ['hs2Val', 'hs2Label']),
        heroStat3: el('heroStat3', 'Column', { align: 'center' }, ['hs3Val', 'hs3Label']),
        hs1Val: el('hs1Val', 'Heading', { level: '2', text: '5,000+' }),
        hs1Label: el('hs1Label', 'Text', { content: 'Cases Won', color: 'muted' }),
        hs2Val: el('hs2Val', 'Heading', { level: '2', text: '98%' }),
        hs2Label: el('hs2Label', 'Text', { content: 'Success Rate', color: 'muted' }),
        hs3Val: el('hs3Val', 'Heading', { level: '2', text: '$500M+' }),
        hs3Label: el('hs3Label', 'Text', { content: 'Recovered', color: 'muted' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['heroConsult', 'heroCall']),
        heroConsult: el('heroConsult', 'Button', { label: 'Schedule Consultation', variant: 'solid' }),
        heroCall: el('heroCall', 'Button', { label: 'Call (555) 123-4567', variant: 'outline' }),
        practiceAreas: el('practiceAreas', 'Container', { maxWidth: 'xl' }, ['practiceHeader', 'practiceGrid']),
        practiceHeader: el('practiceHeader', 'Heading', { level: '2', text: 'Practice Areas', align: 'center' }),
        practiceGrid: el('practiceGrid', 'Grid', { columns: 3, gap: 'lg' }, ['area1', 'area2', 'area3', 'area4', 'area5', 'area6']),
        area1: el('area1', 'Card', { variant: 'outlined', hoverable: true }, ['area1Content']),
        area2: el('area2', 'Card', { variant: 'outlined', hoverable: true }, ['area2Content']),
        area3: el('area3', 'Card', { variant: 'outlined', hoverable: true }, ['area3Content']),
        area4: el('area4', 'Card', { variant: 'outlined', hoverable: true }, ['area4Content']),
        area5: el('area5', 'Card', { variant: 'outlined', hoverable: true }, ['area5Content']),
        area6: el('area6', 'Card', { variant: 'outlined', hoverable: true }, ['area6Content']),
        area1Content: el('area1Content', 'Column', { gap: 'sm' }, ['area1Title', 'area1Desc']),
        area2Content: el('area2Content', 'Column', { gap: 'sm' }, ['area2Title', 'area2Desc']),
        area3Content: el('area3Content', 'Column', { gap: 'sm' }, ['area3Title', 'area3Desc']),
        area4Content: el('area4Content', 'Column', { gap: 'sm' }, ['area4Title', 'area4Desc']),
        area5Content: el('area5Content', 'Column', { gap: 'sm' }, ['area5Title', 'area5Desc']),
        area6Content: el('area6Content', 'Column', { gap: 'sm' }, ['area6Title', 'area6Desc']),
        area1Title: el('area1Title', 'Heading', { level: '4', text: 'Personal Injury' }),
        area1Desc: el('area1Desc', 'Text', { content: 'Car accidents, slip and fall, medical malpractice', color: 'muted' }),
        area2Title: el('area2Title', 'Heading', { level: '4', text: 'Business Law' }),
        area2Desc: el('area2Desc', 'Text', { content: 'Contracts, disputes, corporate formation', color: 'muted' }),
        area3Title: el('area3Title', 'Heading', { level: '4', text: 'Family Law' }),
        area3Desc: el('area3Desc', 'Text', { content: 'Divorce, custody, adoption, prenuptial agreements', color: 'muted' }),
        area4Title: el('area4Title', 'Heading', { level: '4', text: 'Criminal Defense' }),
        area4Desc: el('area4Desc', 'Text', { content: 'DUI, drug offenses, white collar crimes', color: 'muted' }),
        area5Title: el('area5Title', 'Heading', { level: '4', text: 'Estate Planning' }),
        area5Desc: el('area5Desc', 'Text', { content: 'Wills, trusts, probate, asset protection', color: 'muted' }),
        area6Title: el('area6Title', 'Heading', { level: '4', text: 'Real Estate' }),
        area6Desc: el('area6Desc', 'Text', { content: 'Transactions, disputes, landlord-tenant', color: 'muted' }),
        attorneys: el('attorneys', 'Container', { maxWidth: 'xl' }, ['attorneysHeader', 'attorneysGrid']),
        attorneysHeader: el('attorneysHeader', 'Heading', { level: '2', text: 'Our Attorneys', align: 'center' }),
        attorneysGrid: el('attorneysGrid', 'Grid', { columns: 3, gap: 'lg' }, ['atty1', 'atty2', 'atty3']),
        atty1: el('atty1', 'Card', { variant: 'elevated' }, ['atty1Content']),
        atty2: el('atty2', 'Card', { variant: 'elevated' }, ['atty2Content']),
        atty3: el('atty3', 'Card', { variant: 'elevated' }, ['atty3Content']),
        atty1Content: el('atty1Content', 'Column', { gap: 'sm', align: 'center' }, ['atty1Avatar', 'atty1Name', 'atty1Title', 'atty1Spec']),
        atty2Content: el('atty2Content', 'Column', { gap: 'sm', align: 'center' }, ['atty2Avatar', 'atty2Name', 'atty2Title', 'atty2Spec']),
        atty3Content: el('atty3Content', 'Column', { gap: 'sm', align: 'center' }, ['atty3Avatar', 'atty3Name', 'atty3Title', 'atty3Spec']),
        atty1Avatar: el('atty1Avatar', 'Avatar', { name: 'Robert Morrison', size: 'lg' }),
        atty1Name: el('atty1Name', 'Heading', { level: '4', text: 'Robert Morrison' }),
        atty1Title: el('atty1Title', 'Text', { content: 'Founding Partner', color: 'muted' }),
        atty1Spec: el('atty1Spec', 'Badge', { text: 'Personal Injury', variant: 'outline' }),
        atty2Avatar: el('atty2Avatar', 'Avatar', { name: 'Elizabeth Chen', size: 'lg' }),
        atty2Name: el('atty2Name', 'Heading', { level: '4', text: 'Elizabeth Chen' }),
        atty2Title: el('atty2Title', 'Text', { content: 'Senior Partner', color: 'muted' }),
        atty2Spec: el('atty2Spec', 'Badge', { text: 'Business Law', variant: 'outline' }),
        atty3Avatar: el('atty3Avatar', 'Avatar', { name: 'Marcus Johnson', size: 'lg' }),
        atty3Name: el('atty3Name', 'Heading', { level: '4', text: 'Marcus Johnson' }),
        atty3Title: el('atty3Title', 'Text', { content: 'Partner', color: 'muted' }),
        atty3Spec: el('atty3Spec', 'Badge', { text: 'Criminal Defense', variant: 'outline' }),
        testimonials: el('testimonials', 'Container', { maxWidth: 'lg' }, ['testHeader', 'testGrid']),
        testHeader: el('testHeader', 'Heading', { level: '2', text: 'Client Testimonials', align: 'center' }),
        testGrid: el('testGrid', 'Grid', { columns: 2, gap: 'lg' }, ['test1', 'test2']),
        test1: el('test1', 'Card', { variant: 'outlined' }, ['test1Content']),
        test2: el('test2', 'Card', { variant: 'outlined' }, ['test2Content']),
        test1Content: el('test1Content', 'Column', { gap: 'sm' }, ['test1Quote', 'test1Author']),
        test2Content: el('test2Content', 'Column', { gap: 'sm' }, ['test2Quote', 'test2Author']),
        test1Quote: el('test1Quote', 'Text', { content: 'Morrison & Associates fought tirelessly for my case. They secured a settlement that exceeded my expectations.' }),
        test1Author: el('test1Author', 'Text', { content: '— James R., Personal Injury Client', color: 'muted' }),
        test2Quote: el('test2Quote', 'Text', { content: 'Professional, responsive, and genuinely cared about my situation. I highly recommend them to anyone needing legal help.' }),
        test2Author: el('test2Author', 'Text', { content: '— Maria S., Family Law Client', color: 'muted' }),
        contact: el('contact', 'Container', { maxWidth: 'md' }, ['contactCard']),
        contactCard: el('contactCard', 'Card', { variant: 'elevated' }, ['contactContent']),
        contactContent: el('contactContent', 'Column', { gap: 'md', align: 'center' }, ['contactTitle', 'contactDesc', 'contactPhone', 'contactBtn']),
        contactTitle: el('contactTitle', 'Heading', { level: '2', text: 'Free Case Evaluation', align: 'center' }),
        contactDesc: el('contactDesc', 'Text', { content: 'Call us today for a confidential consultation', align: 'center', color: 'muted' }),
        contactPhone: el('contactPhone', 'Heading', { level: '3', text: '(555) 123-4567', align: 'center' }),
        contactBtn: el('contactBtn', 'Button', { label: 'Request Consultation', variant: 'solid' }),
        footer: el('footer', 'Text', { content: '© 2024 Morrison & Associates. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-dental',
    name: 'Dental Clinic Landing',
    description: 'Dental practice with services, doctors, and online booking',
    category: 'landing-pages',
    tags: ['landing', 'dental', 'healthcare', 'medical', 'clinic'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'services', 'doctors', 'booking', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'bookBtn']),
        logo: el('logo', 'Heading', { level: '4', text: 'Bright Smile Dental' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navServices', 'navTeam', 'navPatients', 'navContact']),
        navServices: el('navServices', 'Link', { text: 'Services', href: '#' }),
        navTeam: el('navTeam', 'Link', { text: 'Our Team', href: '#' }),
        navPatients: el('navPatients', 'Link', { text: 'Patient Info', href: '#' }),
        navContact: el('navContact', 'Link', { text: 'Contact', href: '#' }),
        bookBtn: el('bookBtn', 'Button', { label: 'Book Appointment', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'lg' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroDesc', 'heroFeatures', 'heroCta']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Your Smile, Our Priority', align: 'center' }),
        heroDesc: el('heroDesc', 'Text', { content: 'Comprehensive dental care for the whole family in a comfortable, modern environment.', align: 'center', color: 'muted' }),
        heroFeatures: el('heroFeatures', 'Row', { gap: 'lg', justify: 'center' }, ['hf1', 'hf2', 'hf3']),
        hf1: el('hf1', 'Badge', { text: 'Same-Day Appointments', variant: 'outline' }),
        hf2: el('hf2', 'Badge', { text: 'Insurance Accepted', variant: 'outline' }),
        hf3: el('hf3', 'Badge', { text: 'Evening Hours', variant: 'outline' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['heroBook', 'heroCall']),
        heroBook: el('heroBook', 'Button', { label: 'Book Online', variant: 'solid' }),
        heroCall: el('heroCall', 'Button', { label: 'Call (555) 234-5678', variant: 'outline' }),
        services: el('services', 'Container', { maxWidth: 'xl' }, ['servicesHeader', 'servicesGrid']),
        servicesHeader: el('servicesHeader', 'Heading', { level: '2', text: 'Our Services', align: 'center' }),
        servicesGrid: el('servicesGrid', 'Grid', { columns: 4, gap: 'md' }, ['svc1', 'svc2', 'svc3', 'svc4', 'svc5', 'svc6', 'svc7', 'svc8']),
        svc1: el('svc1', 'Card', { variant: 'outlined' }, ['svc1Content']),
        svc2: el('svc2', 'Card', { variant: 'outlined' }, ['svc2Content']),
        svc3: el('svc3', 'Card', { variant: 'outlined' }, ['svc3Content']),
        svc4: el('svc4', 'Card', { variant: 'outlined' }, ['svc4Content']),
        svc5: el('svc5', 'Card', { variant: 'outlined' }, ['svc5Content']),
        svc6: el('svc6', 'Card', { variant: 'outlined' }, ['svc6Content']),
        svc7: el('svc7', 'Card', { variant: 'outlined' }, ['svc7Content']),
        svc8: el('svc8', 'Card', { variant: 'outlined' }, ['svc8Content']),
        svc1Content: el('svc1Content', 'Column', { gap: 'xs', align: 'center' }, ['svc1Title']),
        svc2Content: el('svc2Content', 'Column', { gap: 'xs', align: 'center' }, ['svc2Title']),
        svc3Content: el('svc3Content', 'Column', { gap: 'xs', align: 'center' }, ['svc3Title']),
        svc4Content: el('svc4Content', 'Column', { gap: 'xs', align: 'center' }, ['svc4Title']),
        svc5Content: el('svc5Content', 'Column', { gap: 'xs', align: 'center' }, ['svc5Title']),
        svc6Content: el('svc6Content', 'Column', { gap: 'xs', align: 'center' }, ['svc6Title']),
        svc7Content: el('svc7Content', 'Column', { gap: 'xs', align: 'center' }, ['svc7Title']),
        svc8Content: el('svc8Content', 'Column', { gap: 'xs', align: 'center' }, ['svc8Title']),
        svc1Title: el('svc1Title', 'Text', { content: 'Cleanings & Exams', align: 'center' }),
        svc2Title: el('svc2Title', 'Text', { content: 'Teeth Whitening', align: 'center' }),
        svc3Title: el('svc3Title', 'Text', { content: 'Invisalign', align: 'center' }),
        svc4Title: el('svc4Title', 'Text', { content: 'Dental Implants', align: 'center' }),
        svc5Title: el('svc5Title', 'Text', { content: 'Root Canals', align: 'center' }),
        svc6Title: el('svc6Title', 'Text', { content: 'Crowns & Bridges', align: 'center' }),
        svc7Title: el('svc7Title', 'Text', { content: 'Pediatric Dentistry', align: 'center' }),
        svc8Title: el('svc8Title', 'Text', { content: 'Emergency Care', align: 'center' }),
        doctors: el('doctors', 'Container', { maxWidth: 'xl' }, ['doctorsHeader', 'doctorsGrid']),
        doctorsHeader: el('doctorsHeader', 'Heading', { level: '2', text: 'Meet Our Dentists', align: 'center' }),
        doctorsGrid: el('doctorsGrid', 'Grid', { columns: 3, gap: 'lg' }, ['doc1', 'doc2', 'doc3']),
        doc1: el('doc1', 'Card', { variant: 'elevated' }, ['doc1Content']),
        doc2: el('doc2', 'Card', { variant: 'elevated' }, ['doc2Content']),
        doc3: el('doc3', 'Card', { variant: 'elevated' }, ['doc3Content']),
        doc1Content: el('doc1Content', 'Column', { gap: 'sm', align: 'center' }, ['doc1Avatar', 'doc1Name', 'doc1Title', 'doc1Spec']),
        doc2Content: el('doc2Content', 'Column', { gap: 'sm', align: 'center' }, ['doc2Avatar', 'doc2Name', 'doc2Title', 'doc2Spec']),
        doc3Content: el('doc3Content', 'Column', { gap: 'sm', align: 'center' }, ['doc3Avatar', 'doc3Name', 'doc3Title', 'doc3Spec']),
        doc1Avatar: el('doc1Avatar', 'Avatar', { name: 'Dr. Emily Park', size: 'lg' }),
        doc1Name: el('doc1Name', 'Heading', { level: '4', text: 'Dr. Emily Park, DDS' }),
        doc1Title: el('doc1Title', 'Text', { content: 'General Dentistry', color: 'muted' }),
        doc1Spec: el('doc1Spec', 'Text', { content: '15+ years experience', color: 'muted', size: 'sm' }),
        doc2Avatar: el('doc2Avatar', 'Avatar', { name: 'Dr. James Lee', size: 'lg' }),
        doc2Name: el('doc2Name', 'Heading', { level: '4', text: 'Dr. James Lee, DMD' }),
        doc2Title: el('doc2Title', 'Text', { content: 'Cosmetic Dentistry', color: 'muted' }),
        doc2Spec: el('doc2Spec', 'Text', { content: '12+ years experience', color: 'muted', size: 'sm' }),
        doc3Avatar: el('doc3Avatar', 'Avatar', { name: 'Dr. Sarah Johnson', size: 'lg' }),
        doc3Name: el('doc3Name', 'Heading', { level: '4', text: 'Dr. Sarah Johnson, DDS' }),
        doc3Title: el('doc3Title', 'Text', { content: 'Pediatric Dentistry', color: 'muted' }),
        doc3Spec: el('doc3Spec', 'Text', { content: '10+ years experience', color: 'muted', size: 'sm' }),
        booking: el('booking', 'Container', { maxWidth: 'md' }, ['bookingCard']),
        bookingCard: el('bookingCard', 'Card', { variant: 'elevated' }, ['bookingContent']),
        bookingContent: el('bookingContent', 'Column', { gap: 'md' }, ['bookingTitle', 'bookingForm']),
        bookingTitle: el('bookingTitle', 'Heading', { level: '2', text: 'Book Your Appointment', align: 'center' }),
        bookingForm: el('bookingForm', 'Column', { gap: 'md' }, ['bookingRow1', 'bookingRow2', 'bookingService', 'bookingNotes', 'bookingSubmit']),
        bookingRow1: el('bookingRow1', 'Row', { gap: 'md' }, ['bookingName', 'bookingPhone']),
        bookingName: el('bookingName', 'Input', { label: 'Full Name', placeholder: 'Your name' }),
        bookingPhone: el('bookingPhone', 'Input', { label: 'Phone', placeholder: '(555) 000-0000' }),
        bookingRow2: el('bookingRow2', 'Row', { gap: 'md' }, ['bookingDate', 'bookingTime']),
        bookingDate: el('bookingDate', 'Input', { label: 'Preferred Date', type: 'date' }),
        bookingTime: el('bookingTime', 'Select', { label: 'Preferred Time', options: [{ value: 'morning', label: 'Morning (9am-12pm)' }, { value: 'afternoon', label: 'Afternoon (12pm-5pm)' }, { value: 'evening', label: 'Evening (5pm-7pm)' }] }),
        bookingService: el('bookingService', 'Select', { label: 'Service Needed', options: [{ value: 'cleaning', label: 'Cleaning & Exam' }, { value: 'whitening', label: 'Teeth Whitening' }, { value: 'emergency', label: 'Emergency Care' }, { value: 'other', label: 'Other' }] }),
        bookingNotes: el('bookingNotes', 'TextArea', { label: 'Additional Notes', placeholder: 'Any concerns or special requests?', rows: 3 }),
        bookingSubmit: el('bookingSubmit', 'Button', { label: 'Request Appointment', variant: 'solid', fullWidth: true }),
        footer: el('footer', 'Text', { content: '© 2024 Bright Smile Dental. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'landing-hotel',
    name: 'Hotel Website Landing',
    description: 'Luxury hotel with rooms, amenities, booking, and reviews',
    category: 'landing-pages',
    tags: ['landing', 'hotel', 'hospitality', 'travel', 'booking'],
    tree: {
      root: 'page',
      elements: {
        page: el('page', 'Column', { gap: 'xl' }, ['nav', 'hero', 'rooms', 'amenities', 'booking', 'reviews', 'footer']),
        nav: el('nav', 'Row', { justify: 'between', align: 'center' }, ['logo', 'navLinks', 'bookBtn']),
        logo: el('logo', 'Heading', { level: '4', text: 'The Grand Plaza' }),
        navLinks: el('navLinks', 'Row', { gap: 'md' }, ['navRooms', 'navDining', 'navSpa', 'navEvents']),
        navRooms: el('navRooms', 'Link', { text: 'Rooms', href: '#' }),
        navDining: el('navDining', 'Link', { text: 'Dining', href: '#' }),
        navSpa: el('navSpa', 'Link', { text: 'Spa', href: '#' }),
        navEvents: el('navEvents', 'Link', { text: 'Events', href: '#' }),
        bookBtn: el('bookBtn', 'Button', { label: 'Book Now', variant: 'solid' }),
        hero: el('hero', 'Container', { maxWidth: 'lg' }, ['heroContent']),
        heroContent: el('heroContent', 'Column', { gap: 'lg', align: 'center' }, ['heroTitle', 'heroDesc', 'heroRating', 'heroCta']),
        heroTitle: el('heroTitle', 'Heading', { level: '1', text: 'Luxury Awaits You', align: 'center' }),
        heroDesc: el('heroDesc', 'Text', { content: 'Experience unparalleled elegance in the heart of the city. Where every stay becomes an unforgettable memory.', align: 'center', color: 'muted' }),
        heroRating: el('heroRating', 'Row', { gap: 'sm', justify: 'center' }, ['heroStars', 'heroReviews']),
        heroStars: el('heroStars', 'Text', { content: '★★★★★' }),
        heroReviews: el('heroReviews', 'Text', { content: '4.9/5 from 2,500+ reviews', color: 'muted' }),
        heroCta: el('heroCta', 'Row', { gap: 'md' }, ['heroCheck', 'heroTour']),
        heroCheck: el('heroCheck', 'Button', { label: 'Check Availability', variant: 'solid' }),
        heroTour: el('heroTour', 'Button', { label: 'Virtual Tour', variant: 'outline' }),
        rooms: el('rooms', 'Container', { maxWidth: 'xl' }, ['roomsHeader', 'roomsGrid']),
        roomsHeader: el('roomsHeader', 'Column', { gap: 'sm', align: 'center' }, ['roomsTitle', 'roomsDesc']),
        roomsTitle: el('roomsTitle', 'Heading', { level: '2', text: 'Our Rooms & Suites', align: 'center' }),
        roomsDesc: el('roomsDesc', 'Text', { content: 'Choose from our selection of elegantly appointed accommodations', align: 'center', color: 'muted' }),
        roomsGrid: el('roomsGrid', 'Grid', { columns: 3, gap: 'lg' }, ['room1', 'room2', 'room3']),
        room1: el('room1', 'Card', { variant: 'elevated' }, ['room1Img', 'room1Body']),
        room2: el('room2', 'Card', { variant: 'elevated' }, ['room2Img', 'room2Body']),
        room3: el('room3', 'Card', { variant: 'elevated' }, ['room3Img', 'room3Body']),
        room1Img: el('room1Img', 'Image', { src: '/placeholder-room.jpg', alt: 'Deluxe Room' }),
        room2Img: el('room2Img', 'Image', { src: '/placeholder-room.jpg', alt: 'Executive Suite' }),
        room3Img: el('room3Img', 'Image', { src: '/placeholder-room.jpg', alt: 'Presidential Suite' }),
        room1Body: el('room1Body', 'Column', { gap: 'sm' }, ['room1Name', 'room1Size', 'room1Price', 'room1Btn']),
        room2Body: el('room2Body', 'Column', { gap: 'sm' }, ['room2Name', 'room2Size', 'room2Price', 'room2Btn']),
        room3Body: el('room3Body', 'Column', { gap: 'sm' }, ['room3Name', 'room3Size', 'room3Price', 'room3Btn']),
        room1Name: el('room1Name', 'Heading', { level: '4', text: 'Deluxe Room' }),
        room1Size: el('room1Size', 'Text', { content: '400 sq ft | King Bed | City View', color: 'muted', size: 'sm' }),
        room1Price: el('room1Price', 'Text', { content: 'From $299/night' }),
        room1Btn: el('room1Btn', 'Button', { label: 'View Details', variant: 'outline', fullWidth: true }),
        room2Name: el('room2Name', 'Heading', { level: '4', text: 'Executive Suite' }),
        room2Size: el('room2Size', 'Text', { content: '650 sq ft | King Bed | Lounge Area', color: 'muted', size: 'sm' }),
        room2Price: el('room2Price', 'Text', { content: 'From $499/night' }),
        room2Btn: el('room2Btn', 'Button', { label: 'View Details', variant: 'outline', fullWidth: true }),
        room3Name: el('room3Name', 'Heading', { level: '4', text: 'Presidential Suite' }),
        room3Size: el('room3Size', 'Text', { content: '1,200 sq ft | 2 Bedrooms | Panoramic View', color: 'muted', size: 'sm' }),
        room3Price: el('room3Price', 'Text', { content: 'From $999/night' }),
        room3Btn: el('room3Btn', 'Button', { label: 'View Details', variant: 'outline', fullWidth: true }),
        amenities: el('amenities', 'Container', { maxWidth: 'xl' }, ['amenitiesHeader', 'amenitiesGrid']),
        amenitiesHeader: el('amenitiesHeader', 'Heading', { level: '2', text: 'Hotel Amenities', align: 'center' }),
        amenitiesGrid: el('amenitiesGrid', 'Grid', { columns: 4, gap: 'md' }, ['amen1', 'amen2', 'amen3', 'amen4', 'amen5', 'amen6', 'amen7', 'amen8']),
        amen1: el('amen1', 'Card', { variant: 'outlined' }, ['amen1Text']),
        amen2: el('amen2', 'Card', { variant: 'outlined' }, ['amen2Text']),
        amen3: el('amen3', 'Card', { variant: 'outlined' }, ['amen3Text']),
        amen4: el('amen4', 'Card', { variant: 'outlined' }, ['amen4Text']),
        amen5: el('amen5', 'Card', { variant: 'outlined' }, ['amen5Text']),
        amen6: el('amen6', 'Card', { variant: 'outlined' }, ['amen6Text']),
        amen7: el('amen7', 'Card', { variant: 'outlined' }, ['amen7Text']),
        amen8: el('amen8', 'Card', { variant: 'outlined' }, ['amen8Text']),
        amen1Text: el('amen1Text', 'Text', { content: 'Rooftop Pool', align: 'center' }),
        amen2Text: el('amen2Text', 'Text', { content: 'Full-Service Spa', align: 'center' }),
        amen3Text: el('amen3Text', 'Text', { content: 'Fitness Center', align: 'center' }),
        amen4Text: el('amen4Text', 'Text', { content: 'Fine Dining', align: 'center' }),
        amen5Text: el('amen5Text', 'Text', { content: 'Concierge', align: 'center' }),
        amen6Text: el('amen6Text', 'Text', { content: 'Valet Parking', align: 'center' }),
        amen7Text: el('amen7Text', 'Text', { content: 'Business Center', align: 'center' }),
        amen8Text: el('amen8Text', 'Text', { content: 'Free Wi-Fi', align: 'center' }),
        booking: el('booking', 'Container', { maxWidth: 'lg' }, ['bookingCard']),
        bookingCard: el('bookingCard', 'Card', { variant: 'elevated' }, ['bookingContent']),
        bookingContent: el('bookingContent', 'Column', { gap: 'md' }, ['bookingTitle', 'bookingForm']),
        bookingTitle: el('bookingTitle', 'Heading', { level: '2', text: 'Check Availability', align: 'center' }),
        bookingForm: el('bookingForm', 'Row', { gap: 'md', align: 'end' }, ['bookingCheckIn', 'bookingCheckOut', 'bookingGuests', 'bookingRooms', 'bookingSubmit']),
        bookingCheckIn: el('bookingCheckIn', 'Input', { label: 'Check In', type: 'date' }),
        bookingCheckOut: el('bookingCheckOut', 'Input', { label: 'Check Out', type: 'date' }),
        bookingGuests: el('bookingGuests', 'Select', { label: 'Guests', options: [{ value: '1', label: '1 Guest' }, { value: '2', label: '2 Guests' }, { value: '3', label: '3 Guests' }, { value: '4', label: '4 Guests' }] }),
        bookingRooms: el('bookingRooms', 'Select', { label: 'Rooms', options: [{ value: '1', label: '1 Room' }, { value: '2', label: '2 Rooms' }, { value: '3', label: '3 Rooms' }] }),
        bookingSubmit: el('bookingSubmit', 'Button', { label: 'Search', variant: 'solid' }),
        reviews: el('reviews', 'Container', { maxWidth: 'lg' }, ['reviewsHeader', 'reviewsGrid']),
        reviewsHeader: el('reviewsHeader', 'Heading', { level: '2', text: 'Guest Reviews', align: 'center' }),
        reviewsGrid: el('reviewsGrid', 'Grid', { columns: 2, gap: 'lg' }, ['review1', 'review2']),
        review1: el('review1', 'Card', { variant: 'outlined' }, ['review1Content']),
        review2: el('review2', 'Card', { variant: 'outlined' }, ['review2Content']),
        review1Content: el('review1Content', 'Column', { gap: 'sm' }, ['review1Stars', 'review1Text', 'review1Author']),
        review2Content: el('review2Content', 'Column', { gap: 'sm' }, ['review2Stars', 'review2Text', 'review2Author']),
        review1Stars: el('review1Stars', 'Text', { content: '★★★★★' }),
        review1Text: el('review1Text', 'Text', { content: 'Absolutely stunning hotel. The service was impeccable and the room exceeded all expectations. Will definitely return.' }),
        review1Author: el('review1Author', 'Text', { content: '— Michael T., Business Traveler', color: 'muted' }),
        review2Stars: el('review2Stars', 'Text', { content: '★★★★★' }),
        review2Text: el('review2Text', 'Text', { content: 'Perfect for our anniversary celebration. The spa was divine and the rooftop restaurant had breathtaking views.' }),
        review2Author: el('review2Author', 'Text', { content: '— Amanda & John K., Anniversary Trip', color: 'muted' }),
        footer: el('footer', 'Text', { content: '© 2024 The Grand Plaza Hotel. All rights reserved.', align: 'center', color: 'muted' }),
      },
    },
  },
];
