/**
 * Marketing Section Test Cases
 * Real-world marketing UI components
 */

import type { UITree, UIElement } from '@json-render/core';
import type { TestCase } from './test-cases';

function el(key: string, type: string, props: Record<string, unknown>, children?: string[]): UIElement {
  return { key, type, props, children };
}

export const marketingTestCases: TestCase[] = [
  {
    id: 'marketing-hero-centered',
    name: 'Hero Section - Centered',
    description: 'Centered hero with headline, subtext, and CTAs',
    category: 'marketing',
    tags: ['marketing', 'hero', 'centered', 'cta', 'headline'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'lg' }, ['content']),
        content: el('content', 'Column', { gap: 'lg', align: 'center' }, ['badge', 'title', 'subtitle', 'ctas', 'trust']),
        badge: el('badge', 'Badge', { text: 'New Release', variant: 'outline' }),
        title: el('title', 'Heading', { level: '1', text: 'Build Beautiful Products Faster', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'The all-in-one platform for modern teams. Ship products 10x faster with our powerful toolkit.', align: 'center', color: 'muted', size: 'lg' }),
        ctas: el('ctas', 'Row', { gap: 'md', justify: 'center' }, ['primaryCta', 'secondaryCta']),
        primaryCta: el('primaryCta', 'Button', { label: 'Get Started Free', variant: 'solid' }),
        secondaryCta: el('secondaryCta', 'Button', { label: 'Watch Demo', variant: 'outline' }),
        trust: el('trust', 'Column', { gap: 'sm', align: 'center' }, ['trustText', 'trustLogos']),
        trustText: el('trustText', 'Text', { content: 'Trusted by leading companies', color: 'muted', size: 'sm' }),
        trustLogos: el('trustLogos', 'Row', { gap: 'lg', justify: 'center' }, ['logo1', 'logo2', 'logo3', 'logo4']),
        logo1: el('logo1', 'Text', { content: '[Logo 1]', color: 'muted' }),
        logo2: el('logo2', 'Text', { content: '[Logo 2]', color: 'muted' }),
        logo3: el('logo3', 'Text', { content: '[Logo 3]', color: 'muted' }),
        logo4: el('logo4', 'Text', { content: '[Logo 4]', color: 'muted' }),
      },
    },
  },
  {
    id: 'marketing-hero-left',
    name: 'Hero Section - Left Aligned',
    description: 'Left-aligned hero with image on right',
    category: 'marketing',
    tags: ['marketing', 'hero', 'left-aligned', 'image', 'split'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['content']),
        content: el('content', 'Row', { gap: 'xl', align: 'center' }, ['textContent', 'imageContent']),
        textContent: el('textContent', 'Column', { gap: 'lg' }, ['title', 'subtitle', 'features', 'ctas']),
        title: el('title', 'Heading', { level: '1', text: 'Transform Your Workflow Today' }),
        subtitle: el('subtitle', 'Text', { content: 'Streamline your processes, boost productivity, and achieve more with less effort. Join thousands of teams already saving hours every week.', color: 'muted' }),
        features: el('features', 'Column', { gap: 'sm' }, ['feat1', 'feat2', 'feat3']),
        feat1: el('feat1', 'Row', { gap: 'sm', align: 'center' }, ['feat1Icon', 'feat1Text']),
        feat2: el('feat2', 'Row', { gap: 'sm', align: 'center' }, ['feat2Icon', 'feat2Text']),
        feat3: el('feat3', 'Row', { gap: 'sm', align: 'center' }, ['feat3Icon', 'feat3Text']),
        feat1Icon: el('feat1Icon', 'Badge', { text: '✓', color: 'success' }),
        feat1Text: el('feat1Text', 'Text', { content: 'No credit card required' }),
        feat2Icon: el('feat2Icon', 'Badge', { text: '✓', color: 'success' }),
        feat2Text: el('feat2Text', 'Text', { content: 'Free 14-day trial' }),
        feat3Icon: el('feat3Icon', 'Badge', { text: '✓', color: 'success' }),
        feat3Text: el('feat3Text', 'Text', { content: 'Cancel anytime' }),
        ctas: el('ctas', 'Row', { gap: 'md' }, ['primaryCta', 'secondaryCta']),
        primaryCta: el('primaryCta', 'Button', { label: 'Start Free Trial', variant: 'solid' }),
        secondaryCta: el('secondaryCta', 'Button', { label: 'Learn More', variant: 'ghost' }),
        imageContent: el('imageContent', 'Card', { variant: 'elevated' }, ['heroImage']),
        heroImage: el('heroImage', 'Image', { src: '/placeholder-dashboard.jpg', alt: 'Product dashboard preview' }),
      },
    },
  },
  {
    id: 'marketing-hero-with-image',
    name: 'Hero Section - With Background Image',
    description: 'Hero with background image overlay',
    category: 'marketing',
    tags: ['marketing', 'hero', 'image', 'background', 'overlay'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['content']),
        content: el('content', 'Column', { gap: 'lg', align: 'center' }, ['title', 'subtitle', 'cta', 'stats']),
        title: el('title', 'Heading', { level: '1', text: 'Your Success Starts Here', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Join over 50,000 professionals who trust us with their growth', align: 'center' }),
        cta: el('cta', 'Button', { label: 'Get Started Now', variant: 'solid' }),
        stats: el('stats', 'Row', { gap: 'xl', justify: 'center' }, ['stat1', 'stat2', 'stat3']),
        stat1: el('stat1', 'Column', { align: 'center' }, ['stat1Value', 'stat1Label']),
        stat2: el('stat2', 'Column', { align: 'center' }, ['stat2Value', 'stat2Label']),
        stat3: el('stat3', 'Column', { align: 'center' }, ['stat3Value', 'stat3Label']),
        stat1Value: el('stat1Value', 'Heading', { level: '2', text: '50K+' }),
        stat1Label: el('stat1Label', 'Text', { content: 'Active Users' }),
        stat2Value: el('stat2Value', 'Heading', { level: '2', text: '99.9%' }),
        stat2Label: el('stat2Label', 'Text', { content: 'Uptime' }),
        stat3Value: el('stat3Value', 'Heading', { level: '2', text: '4.9/5' }),
        stat3Label: el('stat3Label', 'Text', { content: 'User Rating' }),
      },
    },
  },
  {
    id: 'marketing-features-3col',
    name: 'Features Grid - 3 Column',
    description: 'Three-column feature grid with icons',
    category: 'marketing',
    tags: ['marketing', 'features', 'grid', 'icons', '3-column'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['header', 'grid']),
        header: el('header', 'Column', { gap: 'sm', align: 'center' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'Everything You Need', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Powerful features to help you build better products faster', align: 'center', color: 'muted' }),
        grid: el('grid', 'Grid', { columns: 3, gap: 'lg' }, ['feat1', 'feat2', 'feat3', 'feat4', 'feat5', 'feat6']),
        feat1: el('feat1', 'Card', { variant: 'outlined' }, ['feat1Content']),
        feat2: el('feat2', 'Card', { variant: 'outlined' }, ['feat2Content']),
        feat3: el('feat3', 'Card', { variant: 'outlined' }, ['feat3Content']),
        feat4: el('feat4', 'Card', { variant: 'outlined' }, ['feat4Content']),
        feat5: el('feat5', 'Card', { variant: 'outlined' }, ['feat5Content']),
        feat6: el('feat6', 'Card', { variant: 'outlined' }, ['feat6Content']),
        feat1Content: el('feat1Content', 'Column', { gap: 'md' }, ['feat1Icon', 'feat1Title', 'feat1Desc']),
        feat1Icon: el('feat1Icon', 'Badge', { text: '⚡', variant: 'solid', color: 'info' }),
        feat1Title: el('feat1Title', 'Heading', { level: '4', text: 'Lightning Fast' }),
        feat1Desc: el('feat1Desc', 'Text', { content: 'Optimized for speed with global CDN distribution and smart caching.', color: 'muted' }),
        feat2Content: el('feat2Content', 'Column', { gap: 'md' }, ['feat2Icon', 'feat2Title', 'feat2Desc']),
        feat2Icon: el('feat2Icon', 'Badge', { text: '🔒', variant: 'solid', color: 'success' }),
        feat2Title: el('feat2Title', 'Heading', { level: '4', text: 'Secure by Default' }),
        feat2Desc: el('feat2Desc', 'Text', { content: 'Enterprise-grade security with encryption at rest and in transit.', color: 'muted' }),
        feat3Content: el('feat3Content', 'Column', { gap: 'md' }, ['feat3Icon', 'feat3Title', 'feat3Desc']),
        feat3Icon: el('feat3Icon', 'Badge', { text: '📊', variant: 'solid', color: 'warning' }),
        feat3Title: el('feat3Title', 'Heading', { level: '4', text: 'Deep Analytics' }),
        feat3Desc: el('feat3Desc', 'Text', { content: 'Comprehensive insights with real-time dashboards and reports.', color: 'muted' }),
        feat4Content: el('feat4Content', 'Column', { gap: 'md' }, ['feat4Icon', 'feat4Title', 'feat4Desc']),
        feat4Icon: el('feat4Icon', 'Badge', { text: '🔄', variant: 'solid', color: 'info' }),
        feat4Title: el('feat4Title', 'Heading', { level: '4', text: 'Auto Sync' }),
        feat4Desc: el('feat4Desc', 'Text', { content: 'Automatic synchronization across all your devices and team members.', color: 'muted' }),
        feat5Content: el('feat5Content', 'Column', { gap: 'md' }, ['feat5Icon', 'feat5Title', 'feat5Desc']),
        feat5Icon: el('feat5Icon', 'Badge', { text: '🎯', variant: 'solid', color: 'error' }),
        feat5Title: el('feat5Title', 'Heading', { level: '4', text: 'Smart Targeting' }),
        feat5Desc: el('feat5Desc', 'Text', { content: 'AI-powered targeting to reach the right audience at the right time.', color: 'muted' }),
        feat6Content: el('feat6Content', 'Column', { gap: 'md' }, ['feat6Icon', 'feat6Title', 'feat6Desc']),
        feat6Icon: el('feat6Icon', 'Badge', { text: '🤝', variant: 'solid', color: 'success' }),
        feat6Title: el('feat6Title', 'Heading', { level: '4', text: 'Team Collaboration' }),
        feat6Desc: el('feat6Desc', 'Text', { content: 'Work together seamlessly with real-time collaboration features.', color: 'muted' }),
      },
    },
  },
  {
    id: 'marketing-features-4col',
    name: 'Features Grid - 4 Column',
    description: 'Four-column compact feature grid',
    category: 'marketing',
    tags: ['marketing', 'features', 'grid', '4-column', 'compact'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['header', 'grid']),
        header: el('header', 'Heading', { level: '2', text: 'Why Choose Us', align: 'center' }),
        grid: el('grid', 'Grid', { columns: 4, gap: 'md' }, ['feat1', 'feat2', 'feat3', 'feat4', 'feat5', 'feat6', 'feat7', 'feat8']),
        feat1: el('feat1', 'Column', { gap: 'sm', align: 'center' }, ['feat1Title', 'feat1Desc']),
        feat2: el('feat2', 'Column', { gap: 'sm', align: 'center' }, ['feat2Title', 'feat2Desc']),
        feat3: el('feat3', 'Column', { gap: 'sm', align: 'center' }, ['feat3Title', 'feat3Desc']),
        feat4: el('feat4', 'Column', { gap: 'sm', align: 'center' }, ['feat4Title', 'feat4Desc']),
        feat5: el('feat5', 'Column', { gap: 'sm', align: 'center' }, ['feat5Title', 'feat5Desc']),
        feat6: el('feat6', 'Column', { gap: 'sm', align: 'center' }, ['feat6Title', 'feat6Desc']),
        feat7: el('feat7', 'Column', { gap: 'sm', align: 'center' }, ['feat7Title', 'feat7Desc']),
        feat8: el('feat8', 'Column', { gap: 'sm', align: 'center' }, ['feat8Title', 'feat8Desc']),
        feat1Title: el('feat1Title', 'Heading', { level: '4', text: 'Easy Setup', align: 'center' }),
        feat1Desc: el('feat1Desc', 'Text', { content: 'Get started in minutes', align: 'center', color: 'muted', size: 'sm' }),
        feat2Title: el('feat2Title', 'Heading', { level: '4', text: '24/7 Support', align: 'center' }),
        feat2Desc: el('feat2Desc', 'Text', { content: 'Always here to help', align: 'center', color: 'muted', size: 'sm' }),
        feat3Title: el('feat3Title', 'Heading', { level: '4', text: 'No Lock-in', align: 'center' }),
        feat3Desc: el('feat3Desc', 'Text', { content: 'Export anytime', align: 'center', color: 'muted', size: 'sm' }),
        feat4Title: el('feat4Title', 'Heading', { level: '4', text: 'Free Updates', align: 'center' }),
        feat4Desc: el('feat4Desc', 'Text', { content: 'Always improving', align: 'center', color: 'muted', size: 'sm' }),
        feat5Title: el('feat5Title', 'Heading', { level: '4', text: 'API Access', align: 'center' }),
        feat5Desc: el('feat5Desc', 'Text', { content: 'Full integration', align: 'center', color: 'muted', size: 'sm' }),
        feat6Title: el('feat6Title', 'Heading', { level: '4', text: 'GDPR Ready', align: 'center' }),
        feat6Desc: el('feat6Desc', 'Text', { content: 'Fully compliant', align: 'center', color: 'muted', size: 'sm' }),
        feat7Title: el('feat7Title', 'Heading', { level: '4', text: 'Custom Branding', align: 'center' }),
        feat7Desc: el('feat7Desc', 'Text', { content: 'Your brand, your way', align: 'center', color: 'muted', size: 'sm' }),
        feat8Title: el('feat8Title', 'Heading', { level: '4', text: 'Mobile Ready', align: 'center' }),
        feat8Desc: el('feat8Desc', 'Text', { content: 'Works everywhere', align: 'center', color: 'muted', size: 'sm' }),
      },
    },
  },
  {
    id: 'marketing-pricing-table',
    name: 'Pricing Table',
    description: 'Three-tier pricing with recommended plan',
    category: 'marketing',
    tags: ['marketing', 'pricing', 'plans', 'tiers', 'subscription'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['header', 'toggle', 'grid']),
        header: el('header', 'Column', { gap: 'sm', align: 'center' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'Simple, Transparent Pricing', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Choose the plan that fits your needs. All plans include a 14-day free trial.', align: 'center', color: 'muted' }),
        toggle: el('toggle', 'Row', { justify: 'center', gap: 'sm', align: 'center' }, ['monthlyLabel', 'billingToggle', 'yearlyLabel', 'saveBadge']),
        monthlyLabel: el('monthlyLabel', 'Text', { content: 'Monthly' }),
        billingToggle: el('billingToggle', 'Switch', {}),
        yearlyLabel: el('yearlyLabel', 'Text', { content: 'Yearly' }),
        saveBadge: el('saveBadge', 'Badge', { text: 'Save 20%', color: 'success' }),
        grid: el('grid', 'Grid', { columns: 3, gap: 'lg' }, ['basic', 'pro', 'enterprise']),
        basic: el('basic', 'Card', { variant: 'outlined' }, ['basicContent']),
        pro: el('pro', 'Card', { variant: 'elevated' }, ['proContent']),
        enterprise: el('enterprise', 'Card', { variant: 'outlined' }, ['enterpriseContent']),
        basicContent: el('basicContent', 'Column', { gap: 'lg', align: 'center' }, ['basicName', 'basicPrice', 'basicFeatures', 'basicCta']),
        basicName: el('basicName', 'Heading', { level: '4', text: 'Basic', align: 'center' }),
        basicPrice: el('basicPrice', 'Column', { align: 'center' }, ['basicAmount', 'basicPeriod']),
        basicAmount: el('basicAmount', 'Heading', { level: '1', text: '$9', align: 'center' }),
        basicPeriod: el('basicPeriod', 'Text', { content: 'per month', color: 'muted', align: 'center' }),
        basicFeatures: el('basicFeatures', 'Column', { gap: 'sm' }, ['bf1', 'bf2', 'bf3', 'bf4']),
        bf1: el('bf1', 'Row', { gap: 'sm' }, ['bf1Check', 'bf1Text']),
        bf1Check: el('bf1Check', 'Text', { content: '✓', color: 'success' }),
        bf1Text: el('bf1Text', 'Text', { content: '5 projects' }),
        bf2: el('bf2', 'Row', { gap: 'sm' }, ['bf2Check', 'bf2Text']),
        bf2Check: el('bf2Check', 'Text', { content: '✓', color: 'success' }),
        bf2Text: el('bf2Text', 'Text', { content: '10GB storage' }),
        bf3: el('bf3', 'Row', { gap: 'sm' }, ['bf3Check', 'bf3Text']),
        bf3Check: el('bf3Check', 'Text', { content: '✓', color: 'success' }),
        bf3Text: el('bf3Text', 'Text', { content: 'Email support' }),
        bf4: el('bf4', 'Row', { gap: 'sm' }, ['bf4Check', 'bf4Text']),
        bf4Check: el('bf4Check', 'Text', { content: '✗', color: 'muted' }),
        bf4Text: el('bf4Text', 'Text', { content: 'API access', color: 'muted' }),
        basicCta: el('basicCta', 'Button', { label: 'Get Started', variant: 'outline', fullWidth: true }),
        proContent: el('proContent', 'Column', { gap: 'lg', align: 'center' }, ['proBadge', 'proName', 'proPrice', 'proFeatures', 'proCta']),
        proBadge: el('proBadge', 'Badge', { text: 'Most Popular', variant: 'solid', color: 'info' }),
        proName: el('proName', 'Heading', { level: '4', text: 'Pro', align: 'center' }),
        proPrice: el('proPrice', 'Column', { align: 'center' }, ['proAmount', 'proPeriod']),
        proAmount: el('proAmount', 'Heading', { level: '1', text: '$29', align: 'center' }),
        proPeriod: el('proPeriod', 'Text', { content: 'per month', color: 'muted', align: 'center' }),
        proFeatures: el('proFeatures', 'Column', { gap: 'sm' }, ['pf1', 'pf2', 'pf3', 'pf4', 'pf5']),
        pf1: el('pf1', 'Row', { gap: 'sm' }, ['pf1Check', 'pf1Text']),
        pf1Check: el('pf1Check', 'Text', { content: '✓', color: 'success' }),
        pf1Text: el('pf1Text', 'Text', { content: 'Unlimited projects' }),
        pf2: el('pf2', 'Row', { gap: 'sm' }, ['pf2Check', 'pf2Text']),
        pf2Check: el('pf2Check', 'Text', { content: '✓', color: 'success' }),
        pf2Text: el('pf2Text', 'Text', { content: '100GB storage' }),
        pf3: el('pf3', 'Row', { gap: 'sm' }, ['pf3Check', 'pf3Text']),
        pf3Check: el('pf3Check', 'Text', { content: '✓', color: 'success' }),
        pf3Text: el('pf3Text', 'Text', { content: 'Priority support' }),
        pf4: el('pf4', 'Row', { gap: 'sm' }, ['pf4Check', 'pf4Text']),
        pf4Check: el('pf4Check', 'Text', { content: '✓', color: 'success' }),
        pf4Text: el('pf4Text', 'Text', { content: 'API access' }),
        pf5: el('pf5', 'Row', { gap: 'sm' }, ['pf5Check', 'pf5Text']),
        pf5Check: el('pf5Check', 'Text', { content: '✓', color: 'success' }),
        pf5Text: el('pf5Text', 'Text', { content: 'Team collaboration' }),
        proCta: el('proCta', 'Button', { label: 'Start Free Trial', variant: 'solid', fullWidth: true }),
        enterpriseContent: el('enterpriseContent', 'Column', { gap: 'lg', align: 'center' }, ['entName', 'entPrice', 'entFeatures', 'entCta']),
        entName: el('entName', 'Heading', { level: '4', text: 'Enterprise', align: 'center' }),
        entPrice: el('entPrice', 'Column', { align: 'center' }, ['entAmount', 'entPeriod']),
        entAmount: el('entAmount', 'Heading', { level: '1', text: 'Custom', align: 'center' }),
        entPeriod: el('entPeriod', 'Text', { content: 'contact sales', color: 'muted', align: 'center' }),
        entFeatures: el('entFeatures', 'Column', { gap: 'sm' }, ['ef1', 'ef2', 'ef3', 'ef4', 'ef5']),
        ef1: el('ef1', 'Row', { gap: 'sm' }, ['ef1Check', 'ef1Text']),
        ef1Check: el('ef1Check', 'Text', { content: '✓', color: 'success' }),
        ef1Text: el('ef1Text', 'Text', { content: 'Everything in Pro' }),
        ef2: el('ef2', 'Row', { gap: 'sm' }, ['ef2Check', 'ef2Text']),
        ef2Check: el('ef2Check', 'Text', { content: '✓', color: 'success' }),
        ef2Text: el('ef2Text', 'Text', { content: 'Unlimited storage' }),
        ef3: el('ef3', 'Row', { gap: 'sm' }, ['ef3Check', 'ef3Text']),
        ef3Check: el('ef3Check', 'Text', { content: '✓', color: 'success' }),
        ef3Text: el('ef3Text', 'Text', { content: 'Dedicated support' }),
        ef4: el('ef4', 'Row', { gap: 'sm' }, ['ef4Check', 'ef4Text']),
        ef4Check: el('ef4Check', 'Text', { content: '✓', color: 'success' }),
        ef4Text: el('ef4Text', 'Text', { content: 'SSO & SAML' }),
        ef5: el('ef5', 'Row', { gap: 'sm' }, ['ef5Check', 'ef5Text']),
        ef5Check: el('ef5Check', 'Text', { content: '✓', color: 'success' }),
        ef5Text: el('ef5Text', 'Text', { content: 'Custom integrations' }),
        entCta: el('entCta', 'Button', { label: 'Contact Sales', variant: 'outline', fullWidth: true }),
      },
    },
  },
  {
    id: 'marketing-testimonials-grid',
    name: 'Testimonials Grid',
    description: 'Customer testimonials in grid layout',
    category: 'marketing',
    tags: ['marketing', 'testimonials', 'reviews', 'social-proof', 'grid'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['header', 'grid']),
        header: el('header', 'Column', { gap: 'sm', align: 'center' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'Loved by Thousands', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'See what our customers have to say about us', align: 'center', color: 'muted' }),
        grid: el('grid', 'Grid', { columns: 3, gap: 'lg' }, ['test1', 'test2', 'test3', 'test4', 'test5', 'test6']),
        test1: el('test1', 'Card', { variant: 'outlined' }, ['test1Content']),
        test2: el('test2', 'Card', { variant: 'outlined' }, ['test2Content']),
        test3: el('test3', 'Card', { variant: 'outlined' }, ['test3Content']),
        test4: el('test4', 'Card', { variant: 'outlined' }, ['test4Content']),
        test5: el('test5', 'Card', { variant: 'outlined' }, ['test5Content']),
        test6: el('test6', 'Card', { variant: 'outlined' }, ['test6Content']),
        test1Content: el('test1Content', 'Column', { gap: 'md' }, ['test1Stars', 'test1Quote', 'test1Author']),
        test1Stars: el('test1Stars', 'Text', { content: '★★★★★' }),
        test1Quote: el('test1Quote', 'Text', { content: 'This product has completely transformed how we work. Cannot imagine going back to our old workflow.' }),
        test1Author: el('test1Author', 'Row', { gap: 'sm', align: 'center' }, ['test1Avatar', 'test1Info']),
        test1Avatar: el('test1Avatar', 'Avatar', { name: 'Sarah Chen', size: 'sm' }),
        test1Info: el('test1Info', 'Column', { gap: 'none' }, ['test1Name', 'test1Role']),
        test1Name: el('test1Name', 'Text', { content: 'Sarah Chen', size: 'sm' }),
        test1Role: el('test1Role', 'Text', { content: 'CTO, TechStart', color: 'muted', size: 'sm' }),
        test2Content: el('test2Content', 'Column', { gap: 'md' }, ['test2Stars', 'test2Quote', 'test2Author']),
        test2Stars: el('test2Stars', 'Text', { content: '★★★★★' }),
        test2Quote: el('test2Quote', 'Text', { content: 'The best investment we have made this year. Our team productivity increased by 40% in the first month.' }),
        test2Author: el('test2Author', 'Row', { gap: 'sm', align: 'center' }, ['test2Avatar', 'test2Info']),
        test2Avatar: el('test2Avatar', 'Avatar', { name: 'Mike Johnson', size: 'sm' }),
        test2Info: el('test2Info', 'Column', { gap: 'none' }, ['test2Name', 'test2Role']),
        test2Name: el('test2Name', 'Text', { content: 'Mike Johnson', size: 'sm' }),
        test2Role: el('test2Role', 'Text', { content: 'VP Engineering, Acme', color: 'muted', size: 'sm' }),
        test3Content: el('test3Content', 'Column', { gap: 'md' }, ['test3Stars', 'test3Quote', 'test3Author']),
        test3Stars: el('test3Stars', 'Text', { content: '★★★★★' }),
        test3Quote: el('test3Quote', 'Text', { content: 'Outstanding customer support. They really care about their users and it shows in every interaction.' }),
        test3Author: el('test3Author', 'Row', { gap: 'sm', align: 'center' }, ['test3Avatar', 'test3Info']),
        test3Avatar: el('test3Avatar', 'Avatar', { name: 'Emily Rodriguez', size: 'sm' }),
        test3Info: el('test3Info', 'Column', { gap: 'none' }, ['test3Name', 'test3Role']),
        test3Name: el('test3Name', 'Text', { content: 'Emily Rodriguez', size: 'sm' }),
        test3Role: el('test3Role', 'Text', { content: 'Product Manager, Globex', color: 'muted', size: 'sm' }),
        test4Content: el('test4Content', 'Column', { gap: 'md' }, ['test4Stars', 'test4Quote', 'test4Author']),
        test4Stars: el('test4Stars', 'Text', { content: '★★★★☆' }),
        test4Quote: el('test4Quote', 'Text', { content: 'Intuitive interface that my entire team picked up immediately. Great for both technical and non-technical users.' }),
        test4Author: el('test4Author', 'Row', { gap: 'sm', align: 'center' }, ['test4Avatar', 'test4Info']),
        test4Avatar: el('test4Avatar', 'Avatar', { name: 'David Kim', size: 'sm' }),
        test4Info: el('test4Info', 'Column', { gap: 'none' }, ['test4Name', 'test4Role']),
        test4Name: el('test4Name', 'Text', { content: 'David Kim', size: 'sm' }),
        test4Role: el('test4Role', 'Text', { content: 'Founder, StartupXYZ', color: 'muted', size: 'sm' }),
        test5Content: el('test5Content', 'Column', { gap: 'md' }, ['test5Stars', 'test5Quote', 'test5Author']),
        test5Stars: el('test5Stars', 'Text', { content: '★★★★★' }),
        test5Quote: el('test5Quote', 'Text', { content: 'We switched from three different tools to just this one. Saved us money and made everything simpler.' }),
        test5Author: el('test5Author', 'Row', { gap: 'sm', align: 'center' }, ['test5Avatar', 'test5Info']),
        test5Avatar: el('test5Avatar', 'Avatar', { name: 'Lisa Wang', size: 'sm' }),
        test5Info: el('test5Info', 'Column', { gap: 'none' }, ['test5Name', 'test5Role']),
        test5Name: el('test5Name', 'Text', { content: 'Lisa Wang', size: 'sm' }),
        test5Role: el('test5Role', 'Text', { content: 'Operations Lead, BigCorp', color: 'muted', size: 'sm' }),
        test6Content: el('test6Content', 'Column', { gap: 'md' }, ['test6Stars', 'test6Quote', 'test6Author']),
        test6Stars: el('test6Stars', 'Text', { content: '★★★★★' }),
        test6Quote: el('test6Quote', 'Text', { content: 'The API is incredibly well-documented. Integration took us just a few hours instead of days.' }),
        test6Author: el('test6Author', 'Row', { gap: 'sm', align: 'center' }, ['test6Avatar', 'test6Info']),
        test6Avatar: el('test6Avatar', 'Avatar', { name: 'Alex Thompson', size: 'sm' }),
        test6Info: el('test6Info', 'Column', { gap: 'none' }, ['test6Name', 'test6Role']),
        test6Name: el('test6Name', 'Text', { content: 'Alex Thompson', size: 'sm' }),
        test6Role: el('test6Role', 'Text', { content: 'Dev Lead, TechnoSoft', color: 'muted', size: 'sm' }),
      },
    },
  },
  {
    id: 'marketing-team-section',
    name: 'Team Section',
    description: 'Meet the team grid with photos and roles',
    category: 'marketing',
    tags: ['marketing', 'team', 'about', 'people', 'grid'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['header', 'grid']),
        header: el('header', 'Column', { gap: 'sm', align: 'center' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'Meet Our Team', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'The talented people behind our success', align: 'center', color: 'muted' }),
        grid: el('grid', 'Grid', { columns: 4, gap: 'lg' }, ['member1', 'member2', 'member3', 'member4']),
        member1: el('member1', 'Card', { variant: 'outlined' }, ['member1Content']),
        member2: el('member2', 'Card', { variant: 'outlined' }, ['member2Content']),
        member3: el('member3', 'Card', { variant: 'outlined' }, ['member3Content']),
        member4: el('member4', 'Card', { variant: 'outlined' }, ['member4Content']),
        member1Content: el('member1Content', 'Column', { gap: 'sm', align: 'center' }, ['member1Avatar', 'member1Name', 'member1Role', 'member1Social']),
        member1Avatar: el('member1Avatar', 'Avatar', { name: 'John Smith', size: 'lg' }),
        member1Name: el('member1Name', 'Heading', { level: '4', text: 'John Smith', align: 'center' }),
        member1Role: el('member1Role', 'Text', { content: 'CEO & Founder', align: 'center', color: 'muted' }),
        member1Social: el('member1Social', 'Row', { gap: 'sm', justify: 'center' }, ['m1Twitter', 'm1LinkedIn']),
        m1Twitter: el('m1Twitter', 'Button', { label: 'X', variant: 'ghost', size: 'sm' }),
        m1LinkedIn: el('m1LinkedIn', 'Button', { label: 'in', variant: 'ghost', size: 'sm' }),
        member2Content: el('member2Content', 'Column', { gap: 'sm', align: 'center' }, ['member2Avatar', 'member2Name', 'member2Role', 'member2Social']),
        member2Avatar: el('member2Avatar', 'Avatar', { name: 'Sarah Chen', size: 'lg' }),
        member2Name: el('member2Name', 'Heading', { level: '4', text: 'Sarah Chen', align: 'center' }),
        member2Role: el('member2Role', 'Text', { content: 'CTO', align: 'center', color: 'muted' }),
        member2Social: el('member2Social', 'Row', { gap: 'sm', justify: 'center' }, ['m2Twitter', 'm2LinkedIn']),
        m2Twitter: el('m2Twitter', 'Button', { label: 'X', variant: 'ghost', size: 'sm' }),
        m2LinkedIn: el('m2LinkedIn', 'Button', { label: 'in', variant: 'ghost', size: 'sm' }),
        member3Content: el('member3Content', 'Column', { gap: 'sm', align: 'center' }, ['member3Avatar', 'member3Name', 'member3Role', 'member3Social']),
        member3Avatar: el('member3Avatar', 'Avatar', { name: 'Mike Johnson', size: 'lg' }),
        member3Name: el('member3Name', 'Heading', { level: '4', text: 'Mike Johnson', align: 'center' }),
        member3Role: el('member3Role', 'Text', { content: 'Head of Design', align: 'center', color: 'muted' }),
        member3Social: el('member3Social', 'Row', { gap: 'sm', justify: 'center' }, ['m3Twitter', 'm3LinkedIn']),
        m3Twitter: el('m3Twitter', 'Button', { label: 'X', variant: 'ghost', size: 'sm' }),
        m3LinkedIn: el('m3LinkedIn', 'Button', { label: 'in', variant: 'ghost', size: 'sm' }),
        member4Content: el('member4Content', 'Column', { gap: 'sm', align: 'center' }, ['member4Avatar', 'member4Name', 'member4Role', 'member4Social']),
        member4Avatar: el('member4Avatar', 'Avatar', { name: 'Emily Davis', size: 'lg' }),
        member4Name: el('member4Name', 'Heading', { level: '4', text: 'Emily Davis', align: 'center' }),
        member4Role: el('member4Role', 'Text', { content: 'Head of Marketing', align: 'center', color: 'muted' }),
        member4Social: el('member4Social', 'Row', { gap: 'sm', justify: 'center' }, ['m4Twitter', 'm4LinkedIn']),
        m4Twitter: el('m4Twitter', 'Button', { label: 'X', variant: 'ghost', size: 'sm' }),
        m4LinkedIn: el('m4LinkedIn', 'Button', { label: 'in', variant: 'ghost', size: 'sm' }),
      },
    },
  },
  {
    id: 'marketing-faq',
    name: 'FAQ Accordion',
    description: 'Frequently asked questions with expandable answers',
    category: 'marketing',
    tags: ['marketing', 'faq', 'accordion', 'questions', 'support'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'md' }, ['header', 'accordion']),
        header: el('header', 'Column', { gap: 'sm', align: 'center' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'Frequently Asked Questions', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Find answers to common questions about our product', align: 'center', color: 'muted' }),
        accordion: el('accordion', 'Accordion', {}, ['faq1', 'faq2', 'faq3', 'faq4', 'faq5']),
        faq1: el('faq1', 'AccordionItem', { title: 'How do I get started?' }, ['faq1Answer']),
        faq1Answer: el('faq1Answer', 'Text', { content: 'Getting started is easy! Simply sign up for a free account, and you will be guided through the setup process. Our onboarding wizard will help you configure your workspace in just a few minutes.' }),
        faq2: el('faq2', 'AccordionItem', { title: 'Is there a free trial?' }, ['faq2Answer']),
        faq2Answer: el('faq2Answer', 'Text', { content: 'Yes! We offer a 14-day free trial with full access to all features. No credit card required to start. You can upgrade or cancel at any time during the trial.' }),
        faq3: el('faq3', 'AccordionItem', { title: 'Can I cancel my subscription anytime?' }, ['faq3Answer']),
        faq3Answer: el('faq3Answer', 'Text', { content: 'Absolutely. There are no long-term contracts. You can cancel your subscription at any time from your account settings, and you will retain access until the end of your billing period.' }),
        faq4: el('faq4', 'AccordionItem', { title: 'Do you offer refunds?' }, ['faq4Answer']),
        faq4Answer: el('faq4Answer', 'Text', { content: 'We offer a 30-day money-back guarantee for all new subscriptions. If you are not satisfied, contact our support team within 30 days of your purchase for a full refund.' }),
        faq5: el('faq5', 'AccordionItem', { title: 'How secure is my data?' }, ['faq5Answer']),
        faq5Answer: el('faq5Answer', 'Text', { content: 'Security is our top priority. We use AES-256 encryption, SOC 2 Type II compliance, and regular security audits. Your data is backed up daily and stored in multiple secure locations.' }),
      },
    },
  },
  {
    id: 'marketing-cta-newsletter',
    name: 'CTA - Newsletter',
    description: 'Newsletter signup call to action',
    category: 'marketing',
    tags: ['marketing', 'cta', 'newsletter', 'email', 'signup'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'md' }, ['card']),
        card: el('card', 'Card', { variant: 'elevated' }, ['content']),
        content: el('content', 'Column', { gap: 'md', align: 'center' }, ['title', 'subtitle', 'form', 'privacy']),
        title: el('title', 'Heading', { level: '2', text: 'Stay in the Loop', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Get the latest updates, tips, and exclusive offers delivered to your inbox.', align: 'center', color: 'muted' }),
        form: el('form', 'Row', { gap: 'sm' }, ['emailInput', 'submitBtn']),
        emailInput: el('emailInput', 'Input', { placeholder: 'Enter your email', type: 'email' }),
        submitBtn: el('submitBtn', 'Button', { label: 'Subscribe', variant: 'solid' }),
        privacy: el('privacy', 'Text', { content: 'We respect your privacy. Unsubscribe anytime.', align: 'center', color: 'muted', size: 'sm' }),
      },
    },
  },
  {
    id: 'marketing-cta-demo',
    name: 'CTA - Demo Request',
    description: 'Request a demo call to action',
    category: 'marketing',
    tags: ['marketing', 'cta', 'demo', 'sales', 'contact'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'lg' }, ['content']),
        content: el('content', 'Row', { gap: 'xl', align: 'center' }, ['textContent', 'formContent']),
        textContent: el('textContent', 'Column', { gap: 'md' }, ['title', 'subtitle', 'benefits']),
        title: el('title', 'Heading', { level: '2', text: 'See It in Action' }),
        subtitle: el('subtitle', 'Text', { content: 'Schedule a personalized demo with our team and discover how we can help your business grow.', color: 'muted' }),
        benefits: el('benefits', 'Column', { gap: 'sm' }, ['ben1', 'ben2', 'ben3']),
        ben1: el('ben1', 'Row', { gap: 'sm' }, ['ben1Icon', 'ben1Text']),
        ben1Icon: el('ben1Icon', 'Badge', { text: '✓', color: 'success' }),
        ben1Text: el('ben1Text', 'Text', { content: 'Personalized walkthrough of features' }),
        ben2: el('ben2', 'Row', { gap: 'sm' }, ['ben2Icon', 'ben2Text']),
        ben2Icon: el('ben2Icon', 'Badge', { text: '✓', color: 'success' }),
        ben2Text: el('ben2Text', 'Text', { content: 'Q&A with product experts' }),
        ben3: el('ben3', 'Row', { gap: 'sm' }, ['ben3Icon', 'ben3Text']),
        ben3Icon: el('ben3Icon', 'Badge', { text: '✓', color: 'success' }),
        ben3Text: el('ben3Text', 'Text', { content: 'Custom solutions for your needs' }),
        formContent: el('formContent', 'Card', { variant: 'elevated' }, ['form']),
        form: el('form', 'Column', { gap: 'md' }, ['nameField', 'emailField', 'companyField', 'messageField', 'submitBtn']),
        nameField: el('nameField', 'Input', { label: 'Full Name', placeholder: 'John Doe' }),
        emailField: el('emailField', 'Input', { label: 'Work Email', type: 'email', placeholder: 'john@company.com' }),
        companyField: el('companyField', 'Input', { label: 'Company', placeholder: 'Acme Inc.' }),
        messageField: el('messageField', 'TextArea', { label: 'What are you looking to achieve?', placeholder: 'Tell us about your goals...', rows: 3 }),
        submitBtn: el('submitBtn', 'Button', { label: 'Request Demo', variant: 'solid', fullWidth: true }),
      },
    },
  },
  {
    id: 'marketing-stats-section',
    name: 'Stats/Numbers Section',
    description: 'Key statistics with large numbers',
    category: 'marketing',
    tags: ['marketing', 'stats', 'numbers', 'metrics', 'social-proof'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'xl' }, ['grid']),
        grid: el('grid', 'Grid', { columns: 4, gap: 'lg' }, ['stat1', 'stat2', 'stat3', 'stat4']),
        stat1: el('stat1', 'Column', { gap: 'sm', align: 'center' }, ['stat1Value', 'stat1Label']),
        stat2: el('stat2', 'Column', { gap: 'sm', align: 'center' }, ['stat2Value', 'stat2Label']),
        stat3: el('stat3', 'Column', { gap: 'sm', align: 'center' }, ['stat3Value', 'stat3Label']),
        stat4: el('stat4', 'Column', { gap: 'sm', align: 'center' }, ['stat4Value', 'stat4Label']),
        stat1Value: el('stat1Value', 'Heading', { level: '1', text: '10M+', align: 'center' }),
        stat1Label: el('stat1Label', 'Text', { content: 'Active Users', align: 'center', color: 'muted' }),
        stat2Value: el('stat2Value', 'Heading', { level: '1', text: '99.99%', align: 'center' }),
        stat2Label: el('stat2Label', 'Text', { content: 'Uptime SLA', align: 'center', color: 'muted' }),
        stat3Value: el('stat3Value', 'Heading', { level: '1', text: '150+', align: 'center' }),
        stat3Label: el('stat3Label', 'Text', { content: 'Countries Served', align: 'center', color: 'muted' }),
        stat4Value: el('stat4Value', 'Heading', { level: '1', text: '$2B+', align: 'center' }),
        stat4Label: el('stat4Label', 'Text', { content: 'Processed Annually', align: 'center', color: 'muted' }),
      },
    },
  },
  {
    id: 'marketing-timeline',
    name: 'Timeline/History Section',
    description: 'Company history or milestone timeline',
    category: 'marketing',
    tags: ['marketing', 'timeline', 'history', 'milestones', 'about'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'md' }, ['header', 'timeline']),
        header: el('header', 'Column', { gap: 'sm', align: 'center' }, ['title', 'subtitle']),
        title: el('title', 'Heading', { level: '2', text: 'Our Journey', align: 'center' }),
        subtitle: el('subtitle', 'Text', { content: 'Key milestones that shaped who we are today', align: 'center', color: 'muted' }),
        timeline: el('timeline', 'Column', { gap: 'lg' }, ['item1', 'item2', 'item3', 'item4']),
        item1: el('item1', 'Row', { gap: 'lg' }, ['item1Year', 'item1Content']),
        item2: el('item2', 'Row', { gap: 'lg' }, ['item2Year', 'item2Content']),
        item3: el('item3', 'Row', { gap: 'lg' }, ['item3Year', 'item3Content']),
        item4: el('item4', 'Row', { gap: 'lg' }, ['item4Year', 'item4Content']),
        item1Year: el('item1Year', 'Badge', { text: '2019', variant: 'solid', color: 'info' }),
        item1Content: el('item1Content', 'Column', { gap: 'xs' }, ['item1Title', 'item1Desc']),
        item1Title: el('item1Title', 'Heading', { level: '4', text: 'Founded' }),
        item1Desc: el('item1Desc', 'Text', { content: 'Started in a small garage with a big dream to revolutionize how teams work together.', color: 'muted' }),
        item2Year: el('item2Year', 'Badge', { text: '2020', variant: 'solid', color: 'info' }),
        item2Content: el('item2Content', 'Column', { gap: 'xs' }, ['item2Title', 'item2Desc']),
        item2Title: el('item2Title', 'Heading', { level: '4', text: 'First 1,000 Users' }),
        item2Desc: el('item2Desc', 'Text', { content: 'Reached our first major milestone and secured seed funding to accelerate growth.', color: 'muted' }),
        item3Year: el('item3Year', 'Badge', { text: '2022', variant: 'solid', color: 'info' }),
        item3Content: el('item3Content', 'Column', { gap: 'xs' }, ['item3Title', 'item3Desc']),
        item3Title: el('item3Title', 'Heading', { level: '4', text: 'Series A' }),
        item3Desc: el('item3Desc', 'Text', { content: 'Raised $15M to expand our team and accelerate product development.', color: 'muted' }),
        item4Year: el('item4Year', 'Badge', { text: '2024', variant: 'solid', color: 'success' }),
        item4Content: el('item4Content', 'Column', { gap: 'xs' }, ['item4Title', 'item4Desc']),
        item4Title: el('item4Title', 'Heading', { level: '4', text: '1 Million Users' }),
        item4Desc: el('item4Desc', 'Text', { content: 'Celebrated our biggest milestone yet with customers in over 100 countries.', color: 'muted' }),
      },
    },
  },
  {
    id: 'marketing-comparison',
    name: 'Comparison Table',
    description: 'Feature comparison between plans or products',
    category: 'marketing',
    tags: ['marketing', 'comparison', 'table', 'features', 'plans'],
    tree: {
      root: 'section',
      elements: {
        section: el('section', 'Container', { maxWidth: 'lg' }, ['header', 'table']),
        header: el('header', 'Heading', { level: '2', text: 'Compare Plans', align: 'center' }),
        table: el('table', 'Card', { variant: 'outlined' }, ['tableContent']),
        tableContent: el('tableContent', 'Column', { gap: 'none' }, ['headerRow', 'row1', 'row2', 'row3', 'row4', 'row5', 'row6']),
        headerRow: el('headerRow', 'Row', { gap: 'md' }, ['featureHeader', 'basicHeader', 'proHeader', 'entHeader']),
        featureHeader: el('featureHeader', 'Text', { content: 'Feature', size: 'sm' }),
        basicHeader: el('basicHeader', 'Text', { content: 'Basic', size: 'sm', align: 'center' }),
        proHeader: el('proHeader', 'Text', { content: 'Pro', size: 'sm', align: 'center' }),
        entHeader: el('entHeader', 'Text', { content: 'Enterprise', size: 'sm', align: 'center' }),
        row1: el('row1', 'Row', { gap: 'md' }, ['row1Feature', 'row1Basic', 'row1Pro', 'row1Ent']),
        row1Feature: el('row1Feature', 'Text', { content: 'Users' }),
        row1Basic: el('row1Basic', 'Text', { content: '3', align: 'center' }),
        row1Pro: el('row1Pro', 'Text', { content: '25', align: 'center' }),
        row1Ent: el('row1Ent', 'Text', { content: 'Unlimited', align: 'center' }),
        row2: el('row2', 'Row', { gap: 'md' }, ['row2Feature', 'row2Basic', 'row2Pro', 'row2Ent']),
        row2Feature: el('row2Feature', 'Text', { content: 'Storage' }),
        row2Basic: el('row2Basic', 'Text', { content: '10 GB', align: 'center' }),
        row2Pro: el('row2Pro', 'Text', { content: '100 GB', align: 'center' }),
        row2Ent: el('row2Ent', 'Text', { content: 'Unlimited', align: 'center' }),
        row3: el('row3', 'Row', { gap: 'md' }, ['row3Feature', 'row3Basic', 'row3Pro', 'row3Ent']),
        row3Feature: el('row3Feature', 'Text', { content: 'API Access' }),
        row3Basic: el('row3Basic', 'Text', { content: '—', align: 'center', color: 'muted' }),
        row3Pro: el('row3Pro', 'Text', { content: '✓', align: 'center', color: 'success' }),
        row3Ent: el('row3Ent', 'Text', { content: '✓', align: 'center', color: 'success' }),
        row4: el('row4', 'Row', { gap: 'md' }, ['row4Feature', 'row4Basic', 'row4Pro', 'row4Ent']),
        row4Feature: el('row4Feature', 'Text', { content: 'Priority Support' }),
        row4Basic: el('row4Basic', 'Text', { content: '—', align: 'center', color: 'muted' }),
        row4Pro: el('row4Pro', 'Text', { content: '✓', align: 'center', color: 'success' }),
        row4Ent: el('row4Ent', 'Text', { content: '✓', align: 'center', color: 'success' }),
        row5: el('row5', 'Row', { gap: 'md' }, ['row5Feature', 'row5Basic', 'row5Pro', 'row5Ent']),
        row5Feature: el('row5Feature', 'Text', { content: 'SSO/SAML' }),
        row5Basic: el('row5Basic', 'Text', { content: '—', align: 'center', color: 'muted' }),
        row5Pro: el('row5Pro', 'Text', { content: '—', align: 'center', color: 'muted' }),
        row5Ent: el('row5Ent', 'Text', { content: '✓', align: 'center', color: 'success' }),
        row6: el('row6', 'Row', { gap: 'md' }, ['row6Feature', 'row6Basic', 'row6Pro', 'row6Ent']),
        row6Feature: el('row6Feature', 'Text', { content: 'Custom Integrations' }),
        row6Basic: el('row6Basic', 'Text', { content: '—', align: 'center', color: 'muted' }),
        row6Pro: el('row6Pro', 'Text', { content: '—', align: 'center', color: 'muted' }),
        row6Ent: el('row6Ent', 'Text', { content: '✓', align: 'center', color: 'success' }),
      },
    },
  },
];
