/**
 * Bundle Generator for Generative UI Builder
 *
 * This module generates multi-file export structures for generated components,
 * including component code, hooks, API clients, and documentation.
 *
 * Output Structure:
 * {
 *   'components/GeneratedComponent.tsx': string,
 *   'hooks/useQuery.ts': string (optional),
 *   'lib/api-client.ts': string (optional),
 *   '.env.example': string,
 *   'README.md': string
 * }
 */

import type { UIFramework } from '@/types';
import { generateApiClientTemplate, generateUseQueryTemplate } from './templates/api-templates';
import { generateReadme } from './readme-generator';

/**
 * Options for generating an export bundle
 */
export interface BundleOptions {
  /** The generated component code */
  componentCode: string;
  /** Name of the component (PascalCase) */
  componentName: string;
  /** UI framework used */
  framework: UIFramework;
  /** Whether to include the API client utility */
  includeApiClient?: boolean;
  /** Whether to include the useQuery hook */
  includeQueryHook?: boolean;
  /** Whether to include the README file */
  includeReadme?: boolean;
  /** Whether to include TypeScript types */
  includeTypes?: boolean;
  /** Base URL for API calls */
  apiBaseUrl?: string;
  /** Additional custom files to include */
  customFiles?: Record<string, string>;
}

/**
 * File metadata for generated files
 */
export interface BundleFile {
  path: string;
  content: string;
  description?: string;
}

/**
 * Bundle generation result with metadata
 */
export interface BundleResult {
  files: Record<string, string>;
  fileList: BundleFile[];
  totalSize: number;
  fileCount: number;
}

/**
 * Convert PascalCase to kebab-case
 */
function toKebabCase(str: string): string {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

/**
 * Calculate approximate size of a string in bytes
 */
function getByteSize(str: string): number {
  return new Blob([str]).size;
}

/**
 * Generate the .env.example file content
 */
function generateEnvExample(options: BundleOptions): string {
  const lines: string[] = [
    '# Environment Variables',
    '# Copy this file to .env.local and fill in your values',
    '',
    '# API Configuration',
    `NEXT_PUBLIC_API_URL=${options.apiBaseUrl || 'https://api.example.com'}`,
    '',
    '# Optional: Authentication',
    '# NEXT_PUBLIC_AUTH_PROVIDER=',
    '# NEXTAUTH_SECRET=',
    '# NEXTAUTH_URL=http://localhost:3000',
    '',
    '# Optional: Analytics',
    '# NEXT_PUBLIC_ANALYTICS_ID=',
    '',
    '# Optional: Feature Flags',
    '# NEXT_PUBLIC_FEATURE_FLAG_NEW_UI=false',
    '',
  ];

  return lines.join('\n');
}

/**
 * Generate a basic types file for the component
 */
function generateTypesFile(componentName: string): string {
  return `/**
 * Type definitions for ${componentName}
 *
 * Add your custom types here for better type safety.
 */

/**
 * Props for the ${componentName} component
 */
export interface ${componentName}Props {
  className?: string;
  // TODO: Add your custom props here
}

/**
 * Data type returned from the API
 */
export interface ${componentName}Data {
  id: string;
  // TODO: Add your data fields here
  createdAt: string;
  updatedAt: string;
}

/**
 * API response wrapper
 */
export interface ApiResponse<T> {
  data: T;
  success: boolean;
  message?: string;
}

/**
 * Pagination parameters
 */
export interface PaginationParams {
  page: number;
  limit: number;
  total: number;
}

/**
 * List response with pagination
 */
export interface PaginatedResponse<T> {
  items: T[];
  pagination: PaginationParams;
}
`;
}

/**
 * Generate an index file for better imports
 */
function generateIndexFile(
  componentName: string,
  options: BundleOptions
): string {
  const kebabName = toKebabCase(componentName);
  const lines: string[] = [
    '/**',
    ` * ${componentName} - Generated by Generative UI Builder`,
    ' *',
    ' * This index file provides clean exports for all module files.',
    ' */',
    '',
    '// Main component',
    `export { default as ${componentName}, ${componentName} } from './components/${kebabName}';`,
    '',
  ];

  if (options.includeTypes !== false) {
    lines.push('// Types');
    lines.push(`export type { ${componentName}Props, ${componentName}Data } from './types';`);
    lines.push('');
  }

  if (options.includeQueryHook) {
    lines.push('// Hooks');
    lines.push(`export { use${componentName}, use${componentName}List } from './hooks/use-query';`);
    lines.push('');
  }

  if (options.includeApiClient) {
    lines.push('// API Client');
    lines.push("export { apiClient, ApiClientError } from './lib/api-client';");
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate a multi-file export bundle
 *
 * @param options - Bundle generation options
 * @returns Object mapping file paths to their contents
 *
 * @example
 * const bundle = generateBundle({
 *   componentCode: generatedCode,
 *   componentName: 'UserDashboard',
 *   framework: 'shadcn',
 *   includeApiClient: true,
 *   includeQueryHook: true,
 *   includeReadme: true,
 * });
 *
 * // Result:
 * // {
 * //   'components/user-dashboard.tsx': '...',
 * //   'hooks/use-query.ts': '...',
 * //   'lib/api-client.ts': '...',
 * //   'types/index.ts': '...',
 * //   '.env.example': '...',
 * //   'README.md': '...',
 * //   'index.ts': '...',
 * // }
 */
export function generateBundle(options: BundleOptions): Record<string, string> {
  const {
    componentCode,
    componentName,
    framework,
    includeApiClient = false,
    includeQueryHook = false,
    includeReadme = true,
    includeTypes = true,
    customFiles = {},
  } = options;

  const files: Record<string, string> = {};
  const kebabName = toKebabCase(componentName);

  // 1. Main component file
  const extension = includeTypes ? '.tsx' : '.jsx';
  files[`components/${kebabName}${extension}`] = componentCode;

  // 2. Types file (if TypeScript)
  if (includeTypes) {
    files['types/index.ts'] = generateTypesFile(componentName);
  }

  // 3. useQuery hook (optional)
  if (includeQueryHook) {
    const hookExtension = includeTypes ? '.ts' : '.js';
    files[`hooks/use-query${hookExtension}`] = generateUseQueryTemplate({
      name: componentName,
      includeTypes,
      framework,
    });
  }

  // 4. API client (optional)
  if (includeApiClient) {
    const clientExtension = includeTypes ? '.ts' : '.js';
    files[`lib/api-client${clientExtension}`] = generateApiClientTemplate({
      name: 'api',
      baseUrl: options.apiBaseUrl || '/api',
      includeTypes,
    });
  }

  // 5. Environment variables example
  files['.env.example'] = generateEnvExample(options);

  // 6. README (optional but recommended)
  if (includeReadme) {
    // Collect the files we've generated for the readme
    const generatedFiles = Object.keys(files);
    if (includeQueryHook) generatedFiles.push(`hooks/use-query${includeTypes ? '.ts' : '.js'}`);
    if (includeApiClient) generatedFiles.push(`lib/api-client${includeTypes ? '.ts' : '.js'}`);

    files['README.md'] = generateReadme({
      componentName,
      framework,
      files: generatedFiles,
      includeApiClient,
      includeQueryHook,
      includeTypes,
    });
  }

  // 7. Index file for clean exports
  const indexExtension = includeTypes ? '.ts' : '.js';
  files[`index${indexExtension}`] = generateIndexFile(componentName, options);

  // 8. Add any custom files
  for (const [path, content] of Object.entries(customFiles)) {
    files[path] = content;
  }

  return files;
}

/**
 * Generate a bundle with detailed metadata
 *
 * @param options - Bundle generation options
 * @returns Bundle result with files and metadata
 */
export function generateBundleWithMetadata(options: BundleOptions): BundleResult {
  const files = generateBundle(options);

  const fileList: BundleFile[] = Object.entries(files).map(([path, content]) => ({
    path,
    content,
    description: getFileDescription(path),
  }));

  const totalSize = Object.values(files).reduce(
    (sum, content) => sum + getByteSize(content),
    0
  );

  return {
    files,
    fileList,
    totalSize,
    fileCount: Object.keys(files).length,
  };
}

/**
 * Get a human-readable description for a file path
 */
function getFileDescription(path: string): string {
  const descriptions: Record<string, string> = {
    '.env.example': 'Environment variables template',
    'README.md': 'Setup and usage documentation',
    'types/index.ts': 'TypeScript type definitions',
  };

  if (descriptions[path]) {
    return descriptions[path];
  }

  if (path.startsWith('components/')) {
    return 'Main UI component';
  }

  if (path.startsWith('hooks/')) {
    return 'Data fetching hook';
  }

  if (path.startsWith('lib/')) {
    return 'Utility library';
  }

  if (path.startsWith('index.')) {
    return 'Module exports';
  }

  return 'Generated file';
}

/**
 * Generate a minimal bundle with just the component
 */
export function generateMinimalBundle(
  componentCode: string,
  componentName: string,
  framework: UIFramework
): Record<string, string> {
  return generateBundle({
    componentCode,
    componentName,
    framework,
    includeApiClient: false,
    includeQueryHook: false,
    includeReadme: false,
    includeTypes: true,
  });
}

/**
 * Generate a complete bundle with all features
 */
export function generateCompleteBundle(
  componentCode: string,
  componentName: string,
  framework: UIFramework,
  apiBaseUrl?: string
): Record<string, string> {
  return generateBundle({
    componentCode,
    componentName,
    framework,
    includeApiClient: true,
    includeQueryHook: true,
    includeReadme: true,
    includeTypes: true,
    apiBaseUrl,
  });
}

/**
 * Merge multiple bundles together
 *
 * Useful when generating multiple components that should be exported together.
 */
export function mergeBundles(
  ...bundles: Record<string, string>[]
): Record<string, string> {
  const merged: Record<string, string> = {};

  for (const bundle of bundles) {
    for (const [path, content] of Object.entries(bundle)) {
      // If file already exists, append a number suffix
      if (merged[path]) {
        const ext = path.includes('.') ? path.substring(path.lastIndexOf('.')) : '';
        const base = path.includes('.') ? path.substring(0, path.lastIndexOf('.')) : path;
        let counter = 1;
        let newPath = `${base}-${counter}${ext}`;
        while (merged[newPath]) {
          counter++;
          newPath = `${base}-${counter}${ext}`;
        }
        merged[newPath] = content;
      } else {
        merged[path] = content;
      }
    }
  }

  return merged;
}

/**
 * Create a downloadable zip file structure representation
 *
 * Note: Actual zip creation requires additional libraries like JSZip.
 * This function prepares the data structure for zip creation.
 */
export function prepareForZip(bundle: Record<string, string>): Array<{
  name: string;
  content: string;
  type: 'file';
}> {
  return Object.entries(bundle).map(([name, content]) => ({
    name,
    content,
    type: 'file' as const,
  }));
}

export default generateBundle;
