/**
 * Next.js Page Template
 *
 * Provides template structures for generating Next.js App Router
 * page components with metadata and proper conventions.
 */

import type { UIFramework } from '@/types';

/**
 * Next.js template configuration options
 */
export interface NextJSTemplateOptions {
  pageName: string;
  pageTitle: string;
  pageDescription: string;
  framework: UIFramework;
  includeTypes: boolean;
  includeMetadata: boolean;
  isServerComponent: boolean;
}

/**
 * Generate metadata export for Next.js pages
 */
export function generateMetadataExport(title: string, description: string): string {
  return `import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${title}',
  description: '${description}',
};
`;
}

/**
 * Generate dynamic metadata function
 */
export function generateDynamicMetadata(
  title: string = 'Page Title',
  includeTypes: boolean = true
): string {
  const paramsType = includeTypes ? '{ params }: { params: { id: string } }' : '{ params }';

  return `import type { Metadata } from 'next';

export async function generateMetadata(${paramsType}): Promise<Metadata> {
  // Fetch data for dynamic metadata
  // const data = await fetchData(params.id);

  return {
    title: '${title}',
    description: 'Dynamic description based on content',
    // openGraph: {
    //   title: data.title,
    //   description: data.description,
    //   images: [data.image],
    // },
  };
}
`;
}

/**
 * Get the page component template for Next.js App Router
 */
export function getNextJSPageTemplate(options: NextJSTemplateOptions): string {
  const {
    pageName = 'Page',
    pageTitle = 'Page Title',
    pageDescription = 'Page description',
    framework,
    includeTypes = true,
    includeMetadata = true,
    isServerComponent = false,
  } = options;

  const lines: string[] = [];

  // Client directive (only for client components)
  if (!isServerComponent) {
    lines.push("'use client';");
    lines.push('');
  }

  // Metadata (for server components)
  if (includeMetadata && isServerComponent) {
    lines.push(`import type { Metadata } from 'next';`);
    lines.push('');
    lines.push(`export const metadata: Metadata = {`);
    lines.push(`  title: '${pageTitle}',`);
    lines.push(`  description: '${pageDescription}',`);
    lines.push(`};`);
    lines.push('');
  }

  // Import placeholder (will be replaced with actual imports)
  lines.push(`// Import your UI components from ${framework}`);
  lines.push(`// import { Container, Stack, Card } from '${getImportPath(framework)}';`);
  lines.push('');

  // Types
  if (includeTypes) {
    lines.push('interface PageProps {');
    lines.push('  params: Promise<Record<string, string>>;');
    lines.push('  searchParams: Promise<Record<string, string | string[] | undefined>>;');
    lines.push('}');
    lines.push('');
  }

  // Component
  lines.push('/**');
  lines.push(` * ${pageName}`);
  lines.push(' * Generated by Generative UI Builder');
  lines.push(' *');
  lines.push(` * Next.js App Router ${isServerComponent ? 'Server' : 'Client'} Component`);
  lines.push(' */');

  const asyncPrefix = isServerComponent ? 'async ' : '';
  const propsType = includeTypes ? '{ params, searchParams }: PageProps' : '{ params, searchParams }';

  lines.push(`export default ${asyncPrefix}function ${pageName}(${propsType}) {`);

  // Data fetching comment
  if (isServerComponent) {
    lines.push('  // Server Component - fetch data directly');
    lines.push('  // const data = await fetchData((await params).id);');
  } else {
    lines.push('  // Client Component - use hooks for data fetching');
    lines.push('  // const { data, isLoading } = useQuery(...);');
  }
  lines.push('');

  // Return placeholder
  lines.push('  return (');
  lines.push('    <main className="container mx-auto py-8">');
  lines.push('      {/* Your generated UI goes here */}');
  lines.push('    </main>');
  lines.push('  );');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Get import path for a framework
 */
function getImportPath(framework: UIFramework): string {
  const paths: Record<UIFramework, string> = {
    shadcn: '@/components/ui',
    mui: '@mui/material',
    chakra: '@chakra-ui/react',
    tailwind: '',
    flowbite: 'flowbite-react',
    antd: 'antd',
    'magic-ui': '@/components/magicui',
    aceternity: '@/components/ui/aceternity',
  };
  return paths[framework];
}

/**
 * Get a complete Next.js page example
 */
export function getCompleteNextJSPageTemplate(
  pageName: string = 'Page',
  framework: UIFramework = 'shadcn'
): string {
  const importPath = getImportPath(framework);
  const importStatement =
    framework === 'tailwind'
      ? "import * as React from 'react';"
      : `import { Container, Stack, Card, Button, Heading, Text } from '${importPath}';`;

  return `'use client';

${importStatement}

interface PageProps {
  params: Promise<Record<string, string>>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

/**
 * ${pageName}
 * Generated by Generative UI Builder
 *
 * Next.js App Router Page Component
 */
export default function ${pageName}({ params, searchParams }: PageProps) {
  // TODO: Add your data fetching logic
  // You can use Server Actions or Client-side fetching
  // const data = await fetchData((await params).id);

  return (
    <main className="container mx-auto py-8">
      <Container maxWidth="lg">
        <Stack direction="vertical" gap="6">
          <Card>
            <Heading level="1">Welcome</Heading>
            <Text>This is your generated ${framework} page</Text>
            <Button label="Get Started" variant="primary" />
          </Card>
        </Stack>
      </Container>
    </main>
  );
}
`;
}

/**
 * Generate a layout.tsx template
 */
export function getLayoutTemplate(
  appName: string = 'My App',
  framework: UIFramework = 'shadcn'
): string {
  const wrapperImports: Record<UIFramework, string> = {
    shadcn: '',
    tailwind: '',
    mui: `import { ThemeProvider, createTheme } from '@mui/material';
import CssBaseline from '@mui/material/CssBaseline';

const theme = createTheme();`,
    chakra: `import { ChakraProvider } from '@chakra-ui/react';`,
    flowbite: `import { Flowbite } from 'flowbite-react';`,
    antd: `import { ConfigProvider } from 'antd';`,
    'magic-ui': '',
    aceternity: '',
  };

  const wrapperStart: Record<UIFramework, string> = {
    shadcn: '',
    tailwind: '',
    mui: '        <ThemeProvider theme={theme}>\n          <CssBaseline />',
    chakra: '        <ChakraProvider>',
    flowbite: '        <Flowbite>',
    antd: '        <ConfigProvider>',
    'magic-ui': '',
    aceternity: '',
  };

  const wrapperEnd: Record<UIFramework, string> = {
    shadcn: '',
    tailwind: '',
    mui: '        </ThemeProvider>',
    chakra: '        </ChakraProvider>',
    flowbite: '        </Flowbite>',
    antd: '        </ConfigProvider>',
    'magic-ui': '',
    aceternity: '',
  };

  const extraImport = wrapperImports[framework];
  const startWrapper = wrapperStart[framework];
  const endWrapper = wrapperEnd[framework];
  const hasWrapper = startWrapper !== '';

  return `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
${extraImport ? '\n' + extraImport : ''}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '${appName}',
  description: 'Generated by Generative UI Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
${hasWrapper ? startWrapper + '\n          {children}\n' + endWrapper : '        {children}'}
      </body>
    </html>
  );
}
`;
}

/**
 * Generate loading.tsx template
 */
export function getLoadingTemplate(): string {
  return `export default function Loading() {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary" />
    </div>
  );
}
`;
}

/**
 * Generate error.tsx template
 */
export function getErrorTemplate(): string {
  return `'use client';

interface ErrorProps {
  error: Error & { digest?: string };
  reset: () => void;
}

export default function Error({ error, reset }: ErrorProps) {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen gap-4">
      <h2 className="text-2xl font-bold">Something went wrong!</h2>
      <p className="text-muted-foreground">{error.message}</p>
      <button
        onClick={reset}
        className="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90"
      >
        Try again
      </button>
    </div>
  );
}
`;
}

/**
 * Generate not-found.tsx template
 */
export function getNotFoundTemplate(): string {
  return `import Link from 'next/link';

export default function NotFound() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen gap-4">
      <h2 className="text-4xl font-bold">404</h2>
      <p className="text-xl text-muted-foreground">Page not found</p>
      <Link
        href="/"
        className="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90"
      >
        Go home
      </Link>
    </div>
  );
}
`;
}
