/**
 * React Component Template
 *
 * Provides template structures for generating React components
 * with different configurations and frameworks.
 */

import type { UIFramework } from '@/types';

/**
 * Template configuration options
 */
export interface ReactTemplateOptions {
  componentName: string;
  framework: UIFramework;
  includeTypes: boolean;
  includeApiComments: boolean;
  useClientDirective: boolean;
}

/**
 * Get the import statement template for a framework
 */
export function getImportTemplate(framework: UIFramework, components: string[]): string {
  const importPaths: Record<UIFramework, string> = {
    shadcn: '@/components/ui',
    mui: '@mui/material',
    chakra: '@chakra-ui/react',
    tailwind: '',
    flowbite: 'flowbite-react',
    antd: 'antd',
    'magic-ui': '@/components/magicui',
    aceternity: '@/components/ui/aceternity',
  };

  if (framework === 'tailwind' || components.length === 0) {
    return "import * as React from 'react';";
  }

  const path = importPaths[framework];
  const sortedComponents = [...components].sort();

  return `import { ${sortedComponents.join(', ')} } from '${path}';`;
}

/**
 * Get the component wrapper template
 */
export function getComponentTemplate(options: ReactTemplateOptions): {
  header: string;
  propsInterface: string;
  functionStart: string;
  functionEnd: string;
  defaultExport: string;
} {
  const { componentName, includeTypes, includeApiComments, useClientDirective } = options;

  // Header with optional 'use client' directive
  let header = '';
  if (useClientDirective) {
    header = "'use client';\n\n";
  }

  // Props interface
  let propsInterface = '';
  if (includeTypes) {
    propsInterface = `interface ${componentName}Props {
  className?: string;
}

`;
  }

  // Function start
  let functionStart = '';
  if (includeApiComments) {
    functionStart += `/**
 * ${componentName}
 * Generated by Generative UI Builder
 */
`;
  }

  const propsType = includeTypes ? `{ className }: ${componentName}Props` : '{ className }';
  functionStart += `export function ${componentName}(${propsType}) {`;

  if (includeApiComments) {
    functionStart += `
  // TODO: Add your data fetching logic here
  // const { data, isLoading, error } = useQuery(...);
`;
  }

  functionStart += '\n  return (';

  // Function end
  const functionEnd = '  );\n}';

  // Default export
  const defaultExport = `\nexport default ${componentName};`;

  return {
    header,
    propsInterface,
    functionStart,
    functionEnd,
    defaultExport,
  };
}

/**
 * Get a complete standalone React component template
 */
export function getStandaloneReactTemplate(
  componentName: string = 'GeneratedComponent',
  framework: UIFramework = 'shadcn'
): string {
  const template = `'use client';

import { Container, Stack, Card, Button, Heading, Text } from '@/components/ui';

interface ${componentName}Props {
  className?: string;
}

/**
 * ${componentName}
 * Generated by Generative UI Builder
 */
export function ${componentName}({ className }: ${componentName}Props) {
  // TODO: Add your data fetching logic here
  // const { data, isLoading, error } = useQuery(...);

  return (
    <Container maxWidth="lg" className={className}>
      <Stack direction="vertical" gap="6">
        <Card>
          <Heading level="1">Hello World</Heading>
          <Text>This is generated content from ${framework}</Text>
          <Button label="Get Started" variant="primary" />
        </Card>
      </Stack>
    </Container>
  );
}

export default ${componentName};
`;

  return template;
}

/**
 * Framework-specific wrapper components
 */
export const FRAMEWORK_WRAPPERS: Record<UIFramework, { import: string; wrapper: string } | null> = {
  shadcn: null, // No wrapper needed
  tailwind: null, // No wrapper needed
  mui: {
    import: "import { ThemeProvider, createTheme } from '@mui/material';",
    wrapper: `const theme = createTheme();

// Wrap with ThemeProvider in your app:
// <ThemeProvider theme={theme}>{children}</ThemeProvider>`,
  },
  chakra: {
    import: "import { ChakraProvider } from '@chakra-ui/react';",
    wrapper: `// Wrap with ChakraProvider in your app:
// <ChakraProvider>{children}</ChakraProvider>`,
  },
  flowbite: {
    import: "import { Flowbite } from 'flowbite-react';",
    wrapper: `// Wrap with Flowbite in your app:
// <Flowbite>{children}</Flowbite>`,
  },
  antd: {
    import: "import { ConfigProvider } from 'antd';",
    wrapper: `// Wrap with ConfigProvider in your app:
// <ConfigProvider>{children}</ConfigProvider>`,
  },
  'magic-ui': null, // No wrapper needed, uses Tailwind + Framer Motion
  aceternity: null, // No wrapper needed, uses Tailwind + Framer Motion
};

/**
 * Get any additional setup instructions for a framework
 */
export function getFrameworkSetupNotes(framework: UIFramework): string | null {
  const wrapper = FRAMEWORK_WRAPPERS[framework];
  if (!wrapper) return null;

  return `// Additional setup required:
${wrapper.import}

${wrapper.wrapper}`;
}

/**
 * Generate example usage code
 */
export function getUsageExample(componentName: string): string {
  return `// Usage example:
import ${componentName} from './path/to/${componentName.toLowerCase()}';

function App() {
  return (
    <main>
      <${componentName} className="my-component" />
    </main>
  );
}`;
}
