export interface ComponentSchema {
  category: string;
  keywords: string[];
  description: string;
  props: Record<string, string>;
}

export const crmSchemas: Record<string, ComponentSchema> = {
  Contact: {
    category: "crm",
    keywords: ["contact", "person", "individual", "customer"],
    description: "Contact entity representing an individual in the CRM",
    props: {
      id: "string - Unique contact identifier",
      firstName: "string - First name",
      lastName: "string - Last name",
      email: "string - Primary email address",
      phone: "string - Primary phone number",
      company: "Company - Associated company",
      title: "string - Job title",
      department: "string - Department",
      avatar: "string - Profile picture URL",
      tags: "string[] - Contact tags",
      customFields: "Record<string, any> - Custom field values",
      createdAt: "Date - Creation timestamp",
      updatedAt: "Date - Last update timestamp",
      owner: "User - Contact owner",
    },
  },

  ContactCard: {
    category: "crm",
    keywords: ["contact", "card", "preview", "summary"],
    description: "Card component displaying contact summary information",
    props: {
      contact: "Contact - Contact data",
      onClick: "() => void - Click handler",
      onEdit: "() => void - Edit callback",
      onDelete: "() => void - Delete callback",
      showActions: "boolean - Whether to show action buttons",
      variant: "'compact' | 'detailed' - Card variant",
      selected: "boolean - Whether card is selected",
      showCompany: "boolean - Whether to show company info",
    },
  },

  ContactList: {
    category: "crm",
    keywords: ["contacts", "list", "directory", "people"],
    description: "List view of contacts with filtering and sorting",
    props: {
      contacts: "Contact[] - Array of contacts",
      onSelect: "(contact: Contact) => void - Selection callback",
      onBulkSelect: "(contacts: Contact[]) => void - Bulk selection callback",
      selectedIds: "string[] - Selected contact IDs",
      sortBy: "string - Sort field",
      sortOrder: "'asc' | 'desc' - Sort order",
      filters: "ContactFilters - Active filters",
      loading: "boolean - Whether list is loading",
      pagination: "PaginationProps - Pagination settings",
      columns: "ColumnDef[] - Column definitions",
      view: "'list' | 'grid' | 'table' - View mode",
    },
  },

  ContactDetail: {
    category: "crm",
    keywords: ["contact", "detail", "profile", "view"],
    description: "Detailed view of a single contact with all information",
    props: {
      contact: "Contact - Contact data",
      onEdit: "() => void - Edit callback",
      onDelete: "() => void - Delete callback",
      activities: "Activity[] - Recent activities",
      deals: "Deal[] - Associated deals",
      notes: "Note[] - Contact notes",
      emails: "Email[] - Email history",
      tasks: "Task[] - Related tasks",
      showTimeline: "boolean - Whether to show activity timeline",
      editMode: "boolean - Whether in edit mode",
    },
  },

  ContactAvatar: {
    category: "crm",
    keywords: ["avatar", "profile", "picture", "image"],
    description: "Avatar component for contact profile pictures",
    props: {
      src: "string - Image source URL",
      firstName: "string - First name for fallback initials",
      lastName: "string - Last name for fallback initials",
      size: "'xs' | 'sm' | 'md' | 'lg' | 'xl' - Avatar size",
      shape: "'circle' | 'square' | 'rounded' - Avatar shape",
      status: "'active' | 'inactive' | 'pending' - Contact status indicator",
      showBadge: "boolean - Whether to show status badge",
    },
  },

  Company: {
    category: "crm",
    keywords: ["company", "organization", "business", "account"],
    description: "Company entity representing an organization in the CRM",
    props: {
      id: "string - Unique company identifier",
      name: "string - Company name",
      domain: "string - Company website domain",
      industry: "string - Industry sector",
      size: "string - Company size range",
      revenue: "number - Annual revenue",
      employees: "number - Employee count",
      logo: "string - Company logo URL",
      address: "Address - Company address",
      phone: "string - Main phone number",
      contacts: "Contact[] - Associated contacts",
      deals: "Deal[] - Associated deals",
      owner: "User - Account owner",
      tags: "string[] - Company tags",
    },
  },

  CompanyCard: {
    category: "crm",
    keywords: ["company", "card", "preview", "account"],
    description: "Card component displaying company summary",
    props: {
      company: "Company - Company data",
      onClick: "() => void - Click handler",
      onEdit: "() => void - Edit callback",
      showLogo: "boolean - Whether to show company logo",
      showContacts: "boolean - Whether to show contact count",
      showDeals: "boolean - Whether to show deal info",
      variant: "'compact' | 'detailed' - Card variant",
      selected: "boolean - Whether card is selected",
    },
  },

  CompanyList: {
    category: "crm",
    keywords: ["companies", "list", "accounts", "organizations"],
    description: "List view of companies with search and filtering",
    props: {
      companies: "Company[] - Array of companies",
      onSelect: "(company: Company) => void - Selection callback",
      selectedIds: "string[] - Selected company IDs",
      sortBy: "string - Sort field",
      sortOrder: "'asc' | 'desc' - Sort order",
      filters: "CompanyFilters - Active filters",
      loading: "boolean - Whether list is loading",
      pagination: "PaginationProps - Pagination settings",
      view: "'list' | 'grid' | 'table' - View mode",
      groupBy: "string - Field to group by",
    },
  },

  CompanyDetail: {
    category: "crm",
    keywords: ["company", "detail", "profile", "account"],
    description: "Detailed view of a company with all information",
    props: {
      company: "Company - Company data",
      onEdit: "() => void - Edit callback",
      contacts: "Contact[] - Company contacts",
      deals: "Deal[] - Company deals",
      activities: "Activity[] - Recent activities",
      notes: "Note[] - Company notes",
      documents: "Document[] - Related documents",
      showHierarchy: "boolean - Whether to show parent/child companies",
      showMap: "boolean - Whether to show location map",
    },
  },

  Deal: {
    category: "crm",
    keywords: ["deal", "opportunity", "sale", "revenue"],
    description: "Deal entity representing a sales opportunity",
    props: {
      id: "string - Unique deal identifier",
      name: "string - Deal name",
      value: "number - Deal value",
      currency: "string - Currency code",
      stage: "DealStage - Current stage",
      probability: "number - Win probability percentage",
      expectedCloseDate: "Date - Expected close date",
      actualCloseDate: "Date - Actual close date",
      company: "Company - Associated company",
      contacts: "Contact[] - Deal contacts",
      owner: "User - Deal owner",
      status: "'open' | 'won' | 'lost' - Deal status",
      lostReason: "string - Reason for lost deal",
      products: "Product[] - Associated products",
      notes: "string - Deal notes",
    },
  },

  DealCard: {
    category: "crm",
    keywords: ["deal", "card", "opportunity", "preview"],
    description: "Card component displaying deal summary",
    props: {
      deal: "Deal - Deal data",
      onClick: "() => void - Click handler",
      onEdit: "() => void - Edit callback",
      onStageChange: "(stage: DealStage) => void - Stage change callback",
      showValue: "boolean - Whether to show deal value",
      showProgress: "boolean - Whether to show stage progress",
      showOwner: "boolean - Whether to show deal owner",
      variant: "'compact' | 'detailed' - Card variant",
      draggable: "boolean - Whether card is draggable",
    },
  },

  DealPipeline: {
    category: "crm",
    keywords: ["pipeline", "kanban", "stages", "board"],
    description: "Kanban-style pipeline view of deals across stages",
    props: {
      deals: "Deal[] - Array of deals",
      stages: "DealStage[] - Pipeline stages",
      onDealMove: "(dealId: string, stageId: string) => void - Move deal callback",
      onDealClick: "(deal: Deal) => void - Deal click callback",
      onStageAdd: "() => void - Add stage callback",
      showTotals: "boolean - Whether to show stage totals",
      showProbability: "boolean - Whether to show weighted values",
      collapsible: "boolean - Whether stages are collapsible",
      filters: "DealFilters - Active filters",
    },
  },

  DealStage: {
    category: "crm",
    keywords: ["stage", "phase", "status", "pipeline"],
    description: "Single stage in the deal pipeline",
    props: {
      id: "string - Stage identifier",
      name: "string - Stage name",
      order: "number - Stage order",
      deals: "Deal[] - Deals in this stage",
      totalValue: "number - Total value of deals",
      dealCount: "number - Number of deals",
      color: "string - Stage color",
      probability: "number - Default probability for stage",
      collapsed: "boolean - Whether stage is collapsed",
      onToggleCollapse: "() => void - Toggle collapse callback",
    },
  },

  DealValue: {
    category: "crm",
    keywords: ["value", "amount", "money", "currency"],
    description: "Formatted deal value display with currency",
    props: {
      value: "number - Monetary value",
      currency: "string - Currency code",
      locale: "string - Locale for formatting",
      showSign: "boolean - Whether to show positive/negative sign",
      size: "'sm' | 'md' | 'lg' - Text size",
      weight: "'normal' | 'medium' | 'bold' - Font weight",
      color: "string - Text color",
      abbreviated: "boolean - Whether to abbreviate large numbers",
    },
  },

  Lead: {
    category: "crm",
    keywords: ["lead", "prospect", "potential", "inquiry"],
    description: "Lead entity representing a potential customer",
    props: {
      id: "string - Unique lead identifier",
      firstName: "string - First name",
      lastName: "string - Last name",
      email: "string - Email address",
      phone: "string - Phone number",
      company: "string - Company name",
      title: "string - Job title",
      source: "string - Lead source",
      status: "LeadStatus - Current status",
      score: "number - Lead score",
      owner: "User - Lead owner",
      convertedAt: "Date - Conversion timestamp",
      convertedTo: "{ contact: Contact, company: Company, deal: Deal } - Converted entities",
      customFields: "Record<string, any> - Custom field values",
    },
  },

  LeadCard: {
    category: "crm",
    keywords: ["lead", "card", "prospect", "preview"],
    description: "Card component displaying lead summary",
    props: {
      lead: "Lead - Lead data",
      onClick: "() => void - Click handler",
      onConvert: "() => void - Convert to contact callback",
      onDisqualify: "() => void - Disqualify callback",
      showScore: "boolean - Whether to show lead score",
      showSource: "boolean - Whether to show lead source",
      showStatus: "boolean - Whether to show status badge",
      variant: "'compact' | 'detailed' - Card variant",
    },
  },

  LeadScore: {
    category: "crm",
    keywords: ["score", "rating", "quality", "rank"],
    description: "Lead scoring display component",
    props: {
      score: "number - Lead score value",
      maxScore: "number - Maximum possible score",
      variant: "'number' | 'bar' | 'stars' | 'grade' - Display variant",
      showLabel: "boolean - Whether to show score label",
      colorScale: "string[] - Colors for score ranges",
      breakdown: "ScoreBreakdown[] - Score factor breakdown",
      showBreakdown: "boolean - Whether to show breakdown",
    },
  },

  LeadStatus: {
    category: "crm",
    keywords: ["status", "state", "stage", "progress"],
    description: "Lead status badge component",
    props: {
      status: "'new' | 'contacted' | 'qualified' | 'unqualified' | 'converted' - Lead status",
      variant: "'badge' | 'dot' | 'text' - Display variant",
      size: "'sm' | 'md' | 'lg' - Badge size",
      showIcon: "boolean - Whether to show status icon",
      customColors: "Record<string, string> - Custom status colors",
    },
  },

  Opportunity: {
    category: "crm",
    keywords: ["opportunity", "deal", "sales", "prospect"],
    description: "Sales opportunity entity similar to deal",
    props: {
      id: "string - Unique opportunity identifier",
      name: "string - Opportunity name",
      amount: "number - Opportunity amount",
      stage: "string - Current stage",
      probability: "number - Win probability",
      closeDate: "Date - Expected close date",
      account: "Company - Associated account",
      contact: "Contact - Primary contact",
      type: "string - Opportunity type",
      leadSource: "string - Lead source",
      nextStep: "string - Next action step",
      description: "string - Opportunity description",
      competitors: "string[] - Competitor names",
    },
  },

  OpportunityCard: {
    category: "crm",
    keywords: ["opportunity", "card", "deal", "preview"],
    description: "Card component displaying opportunity summary",
    props: {
      opportunity: "Opportunity - Opportunity data",
      onClick: "() => void - Click handler",
      onEdit: "() => void - Edit callback",
      showAmount: "boolean - Whether to show amount",
      showProbability: "boolean - Whether to show probability",
      showCloseDate: "boolean - Whether to show close date",
      showAccount: "boolean - Whether to show account info",
      variant: "'compact' | 'detailed' - Card variant",
    },
  },

  Activity: {
    category: "crm",
    keywords: ["activity", "event", "action", "interaction"],
    description: "Activity entity representing a CRM action or event",
    props: {
      id: "string - Unique activity identifier",
      type: "'call' | 'email' | 'meeting' | 'task' | 'note' | 'deal_update' - Activity type",
      subject: "string - Activity subject",
      description: "string - Activity description",
      date: "Date - Activity date",
      duration: "number - Duration in minutes",
      outcome: "string - Activity outcome",
      user: "User - User who performed activity",
      relatedTo: "{ type: string, id: string, name: string } - Related entity",
      attachments: "Attachment[] - Activity attachments",
    },
  },

  ActivityLog: {
    category: "crm",
    keywords: ["activity", "log", "history", "timeline"],
    description: "Chronological log of activities",
    props: {
      activities: "Activity[] - Array of activities",
      loading: "boolean - Whether loading",
      hasMore: "boolean - Whether more activities exist",
      onLoadMore: "() => void - Load more callback",
      filters: "ActivityFilters - Active filters",
      groupByDate: "boolean - Whether to group by date",
      showUser: "boolean - Whether to show user info",
      onActivityClick: "(activity: Activity) => void - Activity click callback",
    },
  },

  ActivityItem: {
    category: "crm",
    keywords: ["activity", "item", "event", "entry"],
    description: "Single activity item in the activity log",
    props: {
      activity: "Activity - Activity data",
      onClick: "() => void - Click handler",
      showIcon: "boolean - Whether to show type icon",
      showTimestamp: "boolean - Whether to show timestamp",
      showUser: "boolean - Whether to show user",
      showRelated: "boolean - Whether to show related entity",
      variant: "'compact' | 'detailed' - Display variant",
    },
  },

  Task: {
    category: "crm",
    keywords: ["task", "todo", "action", "item"],
    description: "Task entity for tracking action items",
    props: {
      id: "string - Unique task identifier",
      title: "string - Task title",
      description: "string - Task description",
      dueDate: "Date - Due date",
      priority: "'low' | 'medium' | 'high' | 'urgent' - Priority level",
      status: "'pending' | 'in_progress' | 'completed' | 'cancelled' - Task status",
      assignee: "User - Assigned user",
      createdBy: "User - Task creator",
      relatedTo: "{ type: string, id: string, name: string } - Related entity",
      reminder: "Date - Reminder date/time",
      completedAt: "Date - Completion timestamp",
      tags: "string[] - Task tags",
    },
  },

  TaskCard: {
    category: "crm",
    keywords: ["task", "card", "todo", "preview"],
    description: "Card component displaying task summary",
    props: {
      task: "Task - Task data",
      onClick: "() => void - Click handler",
      onComplete: "() => void - Complete task callback",
      onEdit: "() => void - Edit callback",
      onDelete: "() => void - Delete callback",
      showAssignee: "boolean - Whether to show assignee",
      showDueDate: "boolean - Whether to show due date",
      showPriority: "boolean - Whether to show priority",
      draggable: "boolean - Whether card is draggable",
      selected: "boolean - Whether card is selected",
    },
  },

  Meeting: {
    category: "crm",
    keywords: ["meeting", "appointment", "calendar", "schedule"],
    description: "Meeting entity for scheduled meetings",
    props: {
      id: "string - Unique meeting identifier",
      title: "string - Meeting title",
      description: "string - Meeting description",
      startTime: "Date - Start date/time",
      endTime: "Date - End date/time",
      location: "string - Meeting location",
      meetingUrl: "string - Video call URL",
      organizer: "User - Meeting organizer",
      attendees: "{ user: User, status: 'pending' | 'accepted' | 'declined' }[] - Attendees",
      relatedTo: "{ type: string, id: string, name: string } - Related entity",
      outcome: "string - Meeting outcome",
      notes: "string - Meeting notes",
      recurring: "RecurrenceRule - Recurrence settings",
    },
  },

  MeetingCard: {
    category: "crm",
    keywords: ["meeting", "card", "appointment", "preview"],
    description: "Card component displaying meeting summary",
    props: {
      meeting: "Meeting - Meeting data",
      onClick: "() => void - Click handler",
      onJoin: "() => void - Join meeting callback",
      onEdit: "() => void - Edit callback",
      onCancel: "() => void - Cancel callback",
      showAttendees: "boolean - Whether to show attendees",
      showLocation: "boolean - Whether to show location",
      variant: "'compact' | 'detailed' - Card variant",
      timeFormat: "'12h' | '24h' - Time format",
    },
  },

  Call: {
    category: "crm",
    keywords: ["call", "phone", "conversation", "contact"],
    description: "Call entity for phone call records",
    props: {
      id: "string - Unique call identifier",
      direction: "'inbound' | 'outbound' - Call direction",
      status: "'completed' | 'missed' | 'voicemail' | 'no_answer' - Call status",
      startTime: "Date - Call start time",
      duration: "number - Duration in seconds",
      phoneNumber: "string - Phone number",
      contact: "Contact - Associated contact",
      user: "User - User who made/received call",
      recording: "string - Recording URL",
      notes: "string - Call notes",
      outcome: "string - Call outcome",
      followUp: "Task - Follow-up task",
    },
  },

  CallLog: {
    category: "crm",
    keywords: ["calls", "log", "history", "phone"],
    description: "Log of call records",
    props: {
      calls: "Call[] - Array of calls",
      loading: "boolean - Whether loading",
      hasMore: "boolean - Whether more calls exist",
      onLoadMore: "() => void - Load more callback",
      filters: "CallFilters - Active filters",
      groupByDate: "boolean - Whether to group by date",
      onCallClick: "(call: Call) => void - Call click callback",
      onPlayRecording: "(call: Call) => void - Play recording callback",
    },
  },

  Email: {
    category: "crm",
    keywords: ["email", "message", "mail", "correspondence"],
    description: "Email entity for email records",
    props: {
      id: "string - Unique email identifier",
      subject: "string - Email subject",
      body: "string - Email body (HTML or text)",
      from: "{ name: string, email: string } - Sender",
      to: "{ name: string, email: string }[] - Recipients",
      cc: "{ name: string, email: string }[] - CC recipients",
      bcc: "{ name: string, email: string }[] - BCC recipients",
      sentAt: "Date - Sent timestamp",
      receivedAt: "Date - Received timestamp",
      status: "'draft' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' - Email status",
      attachments: "Attachment[] - Email attachments",
      relatedTo: "{ type: string, id: string, name: string } - Related entity",
      threadId: "string - Email thread ID",
    },
  },

  EmailThread: {
    category: "crm",
    keywords: ["email", "thread", "conversation", "chain"],
    description: "Email thread showing conversation history",
    props: {
      threadId: "string - Thread identifier",
      emails: "Email[] - Emails in thread",
      subject: "string - Thread subject",
      participants: "{ name: string, email: string }[] - Thread participants",
      onReply: "() => void - Reply callback",
      onReplyAll: "() => void - Reply all callback",
      onForward: "() => void - Forward callback",
      collapsed: "boolean - Whether older emails are collapsed",
      onToggleCollapse: "() => void - Toggle collapse callback",
    },
  },

  Note: {
    category: "crm",
    keywords: ["note", "comment", "annotation", "memo"],
    description: "Note entity for text notes",
    props: {
      id: "string - Unique note identifier",
      content: "string - Note content",
      createdAt: "Date - Creation timestamp",
      updatedAt: "Date - Last update timestamp",
      author: "User - Note author",
      relatedTo: "{ type: string, id: string, name: string } - Related entity",
      isPinned: "boolean - Whether note is pinned",
      mentions: "User[] - Mentioned users",
      attachments: "Attachment[] - Note attachments",
      visibility: "'public' | 'private' | 'team' - Note visibility",
    },
  },

  NoteCard: {
    category: "crm",
    keywords: ["note", "card", "comment", "preview"],
    description: "Card component displaying note content",
    props: {
      note: "Note - Note data",
      onClick: "() => void - Click handler",
      onEdit: "() => void - Edit callback",
      onDelete: "() => void - Delete callback",
      onPin: "() => void - Pin/unpin callback",
      showAuthor: "boolean - Whether to show author",
      showTimestamp: "boolean - Whether to show timestamp",
      truncate: "boolean - Whether to truncate long content",
      maxLines: "number - Maximum lines before truncation",
    },
  },

  Document: {
    category: "crm",
    keywords: ["document", "file", "attachment", "resource"],
    description: "Document entity for file attachments",
    props: {
      id: "string - Unique document identifier",
      name: "string - Document name",
      type: "string - Document type/extension",
      size: "number - File size in bytes",
      url: "string - Download URL",
      thumbnail: "string - Thumbnail URL",
      mimeType: "string - MIME type",
      uploadedBy: "User - User who uploaded",
      uploadedAt: "Date - Upload timestamp",
      relatedTo: "{ type: string, id: string, name: string } - Related entity",
      folder: "string - Folder path",
      tags: "string[] - Document tags",
      version: "number - Document version",
    },
  },

  DocumentList: {
    category: "crm",
    keywords: ["documents", "files", "list", "attachments"],
    description: "List view of documents with actions",
    props: {
      documents: "Document[] - Array of documents",
      onSelect: "(document: Document) => void - Selection callback",
      onDownload: "(document: Document) => void - Download callback",
      onDelete: "(document: Document) => void - Delete callback",
      onPreview: "(document: Document) => void - Preview callback",
      selectedIds: "string[] - Selected document IDs",
      sortBy: "string - Sort field",
      sortOrder: "'asc' | 'desc' - Sort order",
      view: "'list' | 'grid' - View mode",
      groupByType: "boolean - Whether to group by file type",
      loading: "boolean - Whether list is loading",
    },
  },
};
