export interface ComponentSchema {
  category: string;
  keywords: string[];
  description: string;
  props: Record<string, string>;
}

export const dataDisplaySchemas: Record<string, ComponentSchema> = {
  // ============================================================================
  // TABLES & GRIDS
  // ============================================================================

  Table: {
    category: "data-display",
    keywords: ["data", "grid", "rows", "columns", "tabular"],
    description: "Basic data table with sorting and filtering",
    props: {
      columns: "Array<{header: string, accessorKey: string, sortable?: boolean, width?: string | number}>",
      data: "Array<Record<string, any>>",
      caption: "string",
      striped: "boolean",
      hoverable: "boolean",
      selectable: "boolean",
      bordered: "boolean",
      size: "'sm' | 'md' | 'lg'",
      stickyHeader: "boolean",
      emptyMessage: "string",
    },
  },

  DataTable: {
    category: "data-display",
    keywords: ["data", "grid", "rows", "columns", "sortable", "filterable", "pagination"],
    description: "Advanced data table with built-in sorting, filtering, and pagination",
    props: {
      columns: "Array<{header: string, accessorKey: string, sortable?: boolean, filterable?: boolean, cell?: (value: any) => ReactNode}>",
      data: "Array<Record<string, any>>",
      sortable: "boolean",
      filterable: "boolean",
      searchable: "boolean",
      pagination: "boolean",
      pageSize: "number",
      pageSizeOptions: "number[]",
      selectable: "boolean",
      onRowSelect: "(selectedRows: any[]) => void",
      onSort: "(column: string, direction: 'asc' | 'desc') => void",
      onFilter: "(filters: Record<string, any>) => void",
      loading: "boolean",
      emptyState: "ReactNode",
      rowActions: "Array<{label: string, onClick: (row: any) => void, icon?: ReactNode}>",
    },
  },

  DataGrid: {
    category: "data-display",
    keywords: ["data", "grid", "editable", "cells", "spreadsheet"],
    description: "Spreadsheet-like data grid with inline editing and cell selection",
    props: {
      columns: "Array<{field: string, headerName: string, width?: number, editable?: boolean, type?: 'string' | 'number' | 'date' | 'boolean', renderCell?: (params: any) => ReactNode}>",
      rows: "Array<Record<string, any>>",
      rowHeight: "number",
      headerHeight: "number",
      editable: "boolean",
      onCellEdit: "(rowId: string, field: string, value: any) => void",
      selectionMode: "'single' | 'multiple' | 'none'",
      onSelectionChange: "(selection: string[]) => void",
      pinnedColumns: "{left?: string[], right?: string[]}",
      groupBy: "string[]",
      aggregation: "Record<string, 'sum' | 'avg' | 'count' | 'min' | 'max'>",
      columnResize: "boolean",
      columnReorder: "boolean",
      clipboard: "boolean",
    },
  },

  VirtualTable: {
    category: "data-display",
    keywords: ["virtual", "scroll", "performance", "large", "dataset"],
    description: "Virtualized table for rendering large datasets efficiently",
    props: {
      columns: "Array<{header: string, accessorKey: string, width: number}>",
      data: "Array<Record<string, any>>",
      rowHeight: "number",
      overscan: "number",
      estimatedRowHeight: "number",
      onEndReached: "() => void",
      endReachedThreshold: "number",
      loading: "boolean",
      loadingMore: "boolean",
      stickyHeader: "boolean",
      height: "number | string",
    },
  },

  TreeTable: {
    category: "data-display",
    keywords: ["tree", "hierarchical", "nested", "expandable", "parent", "child"],
    description: "Hierarchical table with expandable rows for nested data",
    props: {
      columns: "Array<{header: string, accessorKey: string, width?: number}>",
      data: "Array<{id: string, parentId?: string, [key: string]: any}>",
      childrenKey: "string",
      defaultExpanded: "string[]",
      onExpand: "(expandedIds: string[]) => void",
      indentSize: "number",
      expandIcon: "ReactNode",
      collapseIcon: "ReactNode",
      selectable: "boolean",
      onSelect: "(selectedIds: string[]) => void",
      loadChildren: "(parentId: string) => Promise<any[]>",
    },
  },

  PivotTable: {
    category: "data-display",
    keywords: ["pivot", "aggregate", "analysis", "dimensions", "measures", "crosstab"],
    description: "Pivot table for multi-dimensional data analysis",
    props: {
      data: "Array<Record<string, any>>",
      rows: "string[]",
      columns: "string[]",
      values: "Array<{field: string, aggregation: 'sum' | 'count' | 'avg' | 'min' | 'max'}>",
      filters: "Record<string, any[]>",
      sortBy: "{field: string, direction: 'asc' | 'desc'}",
      showTotals: "boolean",
      showSubtotals: "boolean",
      grandTotalLabel: "string",
      onDrillDown: "(dimensions: Record<string, any>) => void",
      formatValue: "(value: number) => string",
    },
  },

  // ============================================================================
  // LISTS
  // ============================================================================

  List: {
    category: "data-display",
    keywords: ["list", "items", "collection", "vertical"],
    description: "Ordered or unordered list of items",
    props: {
      items: "Array<{id: string, content: ReactNode, icon?: ReactNode, disabled?: boolean}>",
      ordered: "boolean",
      spacing: "'none' | 'sm' | 'md' | 'lg'",
      dividers: "boolean",
      selectable: "boolean",
      selectedId: "string",
      onSelect: "(id: string) => void",
      emptyMessage: "string",
      dense: "boolean",
    },
  },

  ListItem: {
    category: "data-display",
    keywords: ["list", "item", "row", "entry"],
    description: "Individual item within a list",
    props: {
      id: "string",
      primary: "ReactNode",
      secondary: "ReactNode",
      leading: "ReactNode",
      trailing: "ReactNode",
      href: "string",
      onClick: "() => void",
      selected: "boolean",
      disabled: "boolean",
      interactive: "boolean",
      divider: "boolean",
    },
  },

  ListGroup: {
    category: "data-display",
    keywords: ["list", "group", "section", "category"],
    description: "Grouped list with section headers",
    props: {
      groups: "Array<{id: string, label: string, items: Array<{id: string, content: ReactNode}>}>",
      collapsible: "boolean",
      defaultExpanded: "string[]",
      onToggle: "(groupId: string, expanded: boolean) => void",
      dividers: "boolean",
      stickyHeaders: "boolean",
    },
  },

  VirtualList: {
    category: "data-display",
    keywords: ["virtual", "scroll", "performance", "large", "list"],
    description: "Virtualized list for rendering large collections efficiently",
    props: {
      items: "Array<any>",
      itemHeight: "number | ((index: number) => number)",
      renderItem: "(item: any, index: number) => ReactNode",
      overscan: "number",
      height: "number | string",
      width: "number | string",
      onEndReached: "() => void",
      endReachedThreshold: "number",
      loading: "boolean",
      loadingComponent: "ReactNode",
      emptyComponent: "ReactNode",
    },
  },

  // ============================================================================
  // CARDS
  // ============================================================================

  Card: {
    category: "data-display",
    keywords: ["card", "container", "box", "panel"],
    description: "Container card for grouping related content",
    props: {
      variant: "'elevated' | 'outlined' | 'filled'",
      padding: "'none' | 'sm' | 'md' | 'lg'",
      radius: "'none' | 'sm' | 'md' | 'lg' | 'full'",
      shadow: "'none' | 'sm' | 'md' | 'lg'",
      interactive: "boolean",
      href: "string",
      onClick: "() => void",
      selected: "boolean",
      disabled: "boolean",
      children: "ReactNode",
    },
  },

  CardHeader: {
    category: "data-display",
    keywords: ["card", "header", "title", "top"],
    description: "Header section of a card with title and actions",
    props: {
      title: "ReactNode",
      subtitle: "ReactNode",
      avatar: "ReactNode",
      action: "ReactNode",
      divider: "boolean",
    },
  },

  CardBody: {
    category: "data-display",
    keywords: ["card", "body", "content", "main"],
    description: "Main content area of a card",
    props: {
      children: "ReactNode",
      padding: "'none' | 'sm' | 'md' | 'lg'",
      scrollable: "boolean",
      maxHeight: "number | string",
    },
  },

  CardFooter: {
    category: "data-display",
    keywords: ["card", "footer", "actions", "bottom"],
    description: "Footer section of a card with actions",
    props: {
      children: "ReactNode",
      divider: "boolean",
      justify: "'start' | 'center' | 'end' | 'between'",
    },
  },

  CardGrid: {
    category: "data-display",
    keywords: ["card", "grid", "layout", "masonry"],
    description: "Responsive grid layout for displaying cards",
    props: {
      items: "Array<{id: string, content: ReactNode}>",
      columns: "number | {xs?: number, sm?: number, md?: number, lg?: number, xl?: number}",
      gap: "'none' | 'sm' | 'md' | 'lg'",
      masonry: "boolean",
      renderItem: "(item: any) => ReactNode",
    },
  },

  // ============================================================================
  // CHARTS - BASIC
  // ============================================================================

  Chart: {
    category: "data-display",
    keywords: ["chart", "visualization", "graph", "data"],
    description: "Generic chart container supporting multiple chart types",
    props: {
      type: "'bar' | 'line' | 'area' | 'pie' | 'donut' | 'radar' | 'scatter'",
      data: "Array<Record<string, any>>",
      xKey: "string",
      yKey: "string | string[]",
      width: "number | string",
      height: "number | string",
      colors: "string[]",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (value: any) => string}",
      grid: "boolean | {horizontal?: boolean, vertical?: boolean}",
      animation: "boolean | {duration: number}",
      responsive: "boolean",
    },
  },

  BarChart: {
    category: "data-display",
    keywords: ["bar", "chart", "histogram", "column"],
    description: "Vertical or horizontal bar chart for comparing values",
    props: {
      data: "Array<{name: string, value: number, [key: string]: any}>",
      xKey: "string",
      yKey: "string | string[]",
      orientation: "'vertical' | 'horizontal'",
      stacked: "boolean",
      grouped: "boolean",
      barWidth: "number | 'auto'",
      barGap: "number",
      colors: "string[]",
      xAxis: "{label?: string, tickFormat?: (value: any) => string}",
      yAxis: "{label?: string, tickFormat?: (value: any) => string, domain?: [number, number]}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      onBarClick: "(data: any, index: number) => void",
      referenceLines: "Array<{y: number, label?: string, color?: string}>",
    },
  },

  LineChart: {
    category: "data-display",
    keywords: ["line", "chart", "trend", "time", "series"],
    description: "Line chart for showing trends over time",
    props: {
      data: "Array<{x: string | number, y: number, [key: string]: any}>",
      xKey: "string",
      yKey: "string | string[]",
      curve: "'linear' | 'monotone' | 'step' | 'natural'",
      strokeWidth: "number",
      colors: "string[]",
      dots: "boolean | {radius: number, fill?: string}",
      xAxis: "{label?: string, tickFormat?: (value: any) => string, type?: 'category' | 'time' | 'number'}",
      yAxis: "{label?: string, tickFormat?: (value: any) => string, domain?: [number, number]}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      brush: "boolean",
      zoom: "boolean",
      referenceLines: "Array<{y: number, label?: string, color?: string, dashed?: boolean}>",
      annotations: "Array<{x: string | number, label: string}>",
    },
  },

  AreaChart: {
    category: "data-display",
    keywords: ["area", "chart", "filled", "stacked"],
    description: "Area chart for showing volume and trends",
    props: {
      data: "Array<{x: string | number, y: number, [key: string]: any}>",
      xKey: "string",
      yKey: "string | string[]",
      stacked: "boolean",
      curve: "'linear' | 'monotone' | 'step' | 'natural'",
      fillOpacity: "number",
      gradient: "boolean | {from: string, to: string}",
      colors: "string[]",
      xAxis: "{label?: string, tickFormat?: (value: any) => string}",
      yAxis: "{label?: string, tickFormat?: (value: any) => string, domain?: [number, number]}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
    },
  },

  PieChart: {
    category: "data-display",
    keywords: ["pie", "chart", "circular", "proportion", "percentage"],
    description: "Pie chart for showing proportions of a whole",
    props: {
      data: "Array<{name: string, value: number, color?: string}>",
      nameKey: "string",
      valueKey: "string",
      colors: "string[]",
      innerRadius: "number",
      outerRadius: "number",
      startAngle: "number",
      endAngle: "number",
      padAngle: "number",
      labels: "boolean | {type: 'inside' | 'outside', formatter: (data: any) => string}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      onSliceClick: "(data: any, index: number) => void",
      activeIndex: "number",
    },
  },

  DonutChart: {
    category: "data-display",
    keywords: ["donut", "chart", "ring", "circular", "percentage"],
    description: "Donut chart with center content area",
    props: {
      data: "Array<{name: string, value: number, color?: string}>",
      nameKey: "string",
      valueKey: "string",
      colors: "string[]",
      innerRadius: "number",
      outerRadius: "number",
      cornerRadius: "number",
      centerContent: "ReactNode",
      labels: "boolean | {formatter: (data: any) => string}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      onSliceClick: "(data: any, index: number) => void",
    },
  },

  // ============================================================================
  // CHARTS - ADVANCED
  // ============================================================================

  RadarChart: {
    category: "data-display",
    keywords: ["radar", "chart", "spider", "web", "multivariate"],
    description: "Radar/spider chart for comparing multiple variables",
    props: {
      data: "Array<Record<string, number>>",
      categories: "string[]",
      series: "Array<{name: string, dataKey: string, color?: string}>",
      maxValue: "number",
      gridType: "'polygon' | 'circle'",
      gridLevels: "number",
      fillOpacity: "number",
      strokeWidth: "number",
      dots: "boolean",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean",
    },
  },

  ScatterChart: {
    category: "data-display",
    keywords: ["scatter", "chart", "plot", "correlation", "points"],
    description: "Scatter plot for showing correlations between variables",
    props: {
      data: "Array<{x: number, y: number, z?: number, category?: string}>",
      xKey: "string",
      yKey: "string",
      zKey: "string",
      categoryKey: "string",
      colors: "string[]",
      pointSize: "number | ((data: any) => number)",
      pointShape: "'circle' | 'square' | 'triangle' | 'diamond'",
      xAxis: "{label?: string, domain?: [number, number], tickFormat?: (value: any) => string}",
      yAxis: "{label?: string, domain?: [number, number], tickFormat?: (value: any) => string}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      trendLine: "boolean | {type: 'linear' | 'polynomial', color?: string}",
      quadrants: "boolean | {xThreshold: number, yThreshold: number, labels?: string[]}",
    },
  },

  BubbleChart: {
    category: "data-display",
    keywords: ["bubble", "chart", "scatter", "size", "three", "dimensional"],
    description: "Bubble chart for visualizing three dimensions of data",
    props: {
      data: "Array<{x: number, y: number, z: number, name?: string, category?: string}>",
      xKey: "string",
      yKey: "string",
      zKey: "string",
      nameKey: "string",
      categoryKey: "string",
      colors: "string[]",
      minBubbleSize: "number",
      maxBubbleSize: "number",
      xAxis: "{label?: string, domain?: [number, number]}",
      yAxis: "{label?: string, domain?: [number, number]}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      opacity: "number",
    },
  },

  Heatmap: {
    category: "data-display",
    keywords: ["heatmap", "matrix", "grid", "intensity", "color"],
    description: "Heatmap for visualizing data intensity in a matrix",
    props: {
      data: "Array<{x: string, y: string, value: number}>",
      xCategories: "string[]",
      yCategories: "string[]",
      colorScale: "string[] | {min: string, max: string}",
      minValue: "number",
      maxValue: "number",
      cellSize: "{width: number, height: number}",
      cellGap: "number",
      cellRadius: "number",
      showValues: "boolean | {formatter: (value: number) => string}",
      xAxis: "{label?: string, rotate?: number}",
      yAxis: "{label?: string}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      onClick: "(data: {x: string, y: string, value: number}) => void",
    },
  },

  Treemap: {
    category: "data-display",
    keywords: ["treemap", "hierarchy", "nested", "proportion", "area"],
    description: "Treemap for visualizing hierarchical data as nested rectangles",
    props: {
      data: "Array<{name: string, value: number, children?: Array<any>, color?: string}>",
      nameKey: "string",
      valueKey: "string",
      childrenKey: "string",
      colors: "string[]",
      colorByDepth: "boolean",
      padding: "number",
      labels: "boolean | {minSize: number, formatter: (data: any) => string}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      onClick: "(data: any) => void",
      breadcrumbs: "boolean",
      aspectRatio: "number",
    },
  },

  Funnel: {
    category: "data-display",
    keywords: ["funnel", "chart", "conversion", "stages", "pipeline"],
    description: "Funnel chart for visualizing conversion stages",
    props: {
      data: "Array<{name: string, value: number, color?: string}>",
      nameKey: "string",
      valueKey: "string",
      colors: "string[]",
      orientation: "'vertical' | 'horizontal'",
      shape: "'funnel' | 'pyramid'",
      showConversionRate: "boolean",
      labels: "boolean | {position: 'inside' | 'outside', formatter: (data: any) => string}",
      legend: "boolean | {position: 'top' | 'bottom' | 'left' | 'right'}",
      tooltip: "boolean | {formatter: (data: any) => ReactNode}",
      onClick: "(data: any, index: number) => void",
      gap: "number",
    },
  },

  Gauge: {
    category: "data-display",
    keywords: ["gauge", "meter", "dial", "speedometer", "progress"],
    description: "Gauge chart for displaying a single value within a range",
    props: {
      value: "number",
      min: "number",
      max: "number",
      startAngle: "number",
      endAngle: "number",
      colors: "Array<{value: number, color: string}> | string[]",
      thickness: "number",
      showValue: "boolean",
      valueFormatter: "(value: number) => string",
      label: "string",
      sublabel: "string",
      ticks: "boolean | {count: number, labels?: boolean}",
      pointer: "boolean | {type: 'needle' | 'arrow', color?: string}",
      animation: "boolean | {duration: number}",
    },
  },

  Sparkline: {
    category: "data-display",
    keywords: ["sparkline", "mini", "chart", "inline", "trend"],
    description: "Compact inline chart for showing trends",
    props: {
      data: "number[]",
      type: "'line' | 'bar' | 'area'",
      width: "number",
      height: "number",
      color: "string",
      fillColor: "string",
      strokeWidth: "number",
      showMin: "boolean",
      showMax: "boolean",
      showLast: "boolean",
      referenceValue: "number",
      positiveColor: "string",
      negativeColor: "string",
    },
  },

  MiniChart: {
    category: "data-display",
    keywords: ["mini", "chart", "small", "compact", "thumbnail"],
    description: "Compact chart for dashboards and cards",
    props: {
      type: "'line' | 'bar' | 'area' | 'pie'",
      data: "Array<{x: string | number, y: number}>",
      width: "number",
      height: "number",
      color: "string",
      colors: "string[]",
      showAxis: "boolean",
      showGrid: "boolean",
      showTooltip: "boolean",
      animation: "boolean",
    },
  },

  // ============================================================================
  // METRICS & STATS
  // ============================================================================

  Metric: {
    category: "data-display",
    keywords: ["metric", "number", "value", "statistic"],
    description: "Single metric display with label and optional trend",
    props: {
      value: "string | number",
      label: "string",
      prefix: "string",
      suffix: "string",
      formatter: "(value: number) => string",
      trend: "{value: number, direction: 'up' | 'down' | 'neutral'}",
      trendLabel: "string",
      size: "'sm' | 'md' | 'lg' | 'xl'",
      color: "string",
      loading: "boolean",
    },
  },

  MetricCard: {
    category: "data-display",
    keywords: ["metric", "card", "kpi", "dashboard"],
    description: "Card displaying a key metric with context",
    props: {
      title: "string",
      value: "string | number",
      prefix: "string",
      suffix: "string",
      formatter: "(value: number) => string",
      change: "{value: number, period: string}",
      changeType: "'positive' | 'negative' | 'neutral'",
      icon: "ReactNode",
      chart: "ReactNode",
      footer: "ReactNode",
      loading: "boolean",
      onClick: "() => void",
    },
  },

  KPI: {
    category: "data-display",
    keywords: ["kpi", "indicator", "performance", "target"],
    description: "Key Performance Indicator with target tracking",
    props: {
      value: "number",
      target: "number",
      label: "string",
      formatter: "(value: number) => string",
      status: "'on-track' | 'at-risk' | 'behind' | 'exceeded'",
      showProgress: "boolean",
      progressType: "'bar' | 'circle'",
      period: "string",
      trend: "number[]",
      thresholds: "{warning: number, danger: number}",
    },
  },

  KPICard: {
    category: "data-display",
    keywords: ["kpi", "card", "performance", "dashboard"],
    description: "Card displaying KPI with progress and context",
    props: {
      title: "string",
      value: "number",
      target: "number",
      formatter: "(value: number) => string",
      status: "'on-track' | 'at-risk' | 'behind' | 'exceeded'",
      statusLabel: "string",
      progress: "number",
      progressColor: "string",
      icon: "ReactNode",
      sparkline: "number[]",
      footer: "ReactNode",
      actions: "ReactNode",
    },
  },

  Stats: {
    category: "data-display",
    keywords: ["stats", "statistics", "numbers", "overview"],
    description: "Collection of statistics displayed together",
    props: {
      items: "Array<{label: string, value: string | number, change?: number, icon?: ReactNode}>",
      columns: "number | {xs?: number, sm?: number, md?: number, lg?: number}",
      variant: "'default' | 'cards' | 'minimal'",
      size: "'sm' | 'md' | 'lg'",
      dividers: "boolean",
    },
  },

  StatCard: {
    category: "data-display",
    keywords: ["stat", "card", "number", "dashboard"],
    description: "Individual statistic card with details",
    props: {
      label: "string",
      value: "string | number",
      helpText: "string",
      icon: "ReactNode",
      iconBackground: "string",
      change: "{value: number, label: string}",
      changeType: "'increase' | 'decrease' | 'neutral'",
      footer: "ReactNode",
      loading: "boolean",
    },
  },

  StatGroup: {
    category: "data-display",
    keywords: ["stat", "group", "collection", "summary"],
    description: "Group of related statistics",
    props: {
      stats: "Array<{label: string, value: string | number, helpText?: string, change?: number}>",
      orientation: "'horizontal' | 'vertical'",
      dividers: "boolean",
      size: "'sm' | 'md' | 'lg'",
      align: "'start' | 'center' | 'end'",
    },
  },

  // ============================================================================
  // PROGRESS
  // ============================================================================

  Progress: {
    category: "data-display",
    keywords: ["progress", "loading", "percentage", "completion"],
    description: "Progress indicator showing completion status",
    props: {
      value: "number",
      max: "number",
      label: "string",
      showValue: "boolean",
      valueFormatter: "(value: number, max: number) => string",
      size: "'sm' | 'md' | 'lg'",
      color: "string",
      trackColor: "string",
      animated: "boolean",
      striped: "boolean",
      indeterminate: "boolean",
    },
  },

  ProgressBar: {
    category: "data-display",
    keywords: ["progress", "bar", "linear", "horizontal"],
    description: "Linear progress bar with optional segments",
    props: {
      value: "number",
      max: "number",
      segments: "Array<{value: number, color: string, label?: string}>",
      showLabel: "boolean",
      labelPosition: "'inside' | 'outside' | 'top'",
      size: "'xs' | 'sm' | 'md' | 'lg'",
      color: "string",
      trackColor: "string",
      radius: "'none' | 'sm' | 'md' | 'full'",
      animated: "boolean",
      striped: "boolean",
    },
  },

  ProgressCircle: {
    category: "data-display",
    keywords: ["progress", "circle", "radial", "donut"],
    description: "Circular progress indicator",
    props: {
      value: "number",
      max: "number",
      size: "number | 'sm' | 'md' | 'lg' | 'xl'",
      strokeWidth: "number",
      color: "string",
      trackColor: "string",
      showValue: "boolean",
      valueFormatter: "(value: number) => string",
      label: "string",
      children: "ReactNode",
      animated: "boolean",
      rotation: "number",
    },
  },

  ProgressSteps: {
    category: "data-display",
    keywords: ["progress", "steps", "wizard", "stepper", "stages"],
    description: "Step-by-step progress indicator",
    props: {
      steps: "Array<{id: string, label: string, description?: string, icon?: ReactNode}>",
      currentStep: "number",
      orientation: "'horizontal' | 'vertical'",
      variant: "'circles' | 'dots' | 'arrows'",
      size: "'sm' | 'md' | 'lg'",
      completedColor: "string",
      activeColor: "string",
      onStepClick: "(stepIndex: number) => void",
      clickable: "boolean",
      showConnector: "boolean",
    },
  },

  // ============================================================================
  // TIMELINE
  // ============================================================================

  Timeline: {
    category: "data-display",
    keywords: ["timeline", "history", "events", "chronological"],
    description: "Chronological timeline of events",
    props: {
      items: "Array<{id: string, date: string | Date, title: string, description?: string, icon?: ReactNode, color?: string}>",
      orientation: "'vertical' | 'horizontal'",
      align: "'left' | 'right' | 'alternate'",
      lineColor: "string",
      lineWidth: "number",
      showConnector: "boolean",
      reverse: "boolean",
      animate: "boolean",
      pending: "ReactNode",
    },
  },

  TimelineItem: {
    category: "data-display",
    keywords: ["timeline", "item", "event", "entry"],
    description: "Individual item in a timeline",
    props: {
      date: "string | Date",
      dateFormat: "string",
      title: "string",
      description: "ReactNode",
      icon: "ReactNode",
      iconColor: "string",
      iconBackground: "string",
      dot: "ReactNode",
      position: "'left' | 'right'",
      children: "ReactNode",
    },
  },

  // ============================================================================
  // CALENDAR & SCHEDULING
  // ============================================================================

  Calendar: {
    category: "data-display",
    keywords: ["calendar", "date", "month", "schedule"],
    description: "Calendar view for date selection and event display",
    props: {
      value: "Date | Date[]",
      defaultValue: "Date",
      mode: "'single' | 'multiple' | 'range'",
      events: "Array<{id: string, date: Date, title: string, color?: string}>",
      minDate: "Date",
      maxDate: "Date",
      disabledDates: "Date[] | ((date: Date) => boolean)",
      firstDayOfWeek: "0 | 1 | 2 | 3 | 4 | 5 | 6",
      showWeekNumbers: "boolean",
      showOutsideDays: "boolean",
      onChange: "(date: Date | Date[]) => void",
      onMonthChange: "(month: Date) => void",
      onEventClick: "(event: any) => void",
      locale: "string",
    },
  },

  CalendarDay: {
    category: "data-display",
    keywords: ["calendar", "day", "date", "cell"],
    description: "Individual day cell in a calendar",
    props: {
      date: "Date",
      selected: "boolean",
      disabled: "boolean",
      today: "boolean",
      outsideMonth: "boolean",
      events: "Array<{id: string, title: string, color?: string}>",
      maxEvents: "number",
      onClick: "(date: Date) => void",
      onEventClick: "(event: any) => void",
    },
  },

  CalendarEvent: {
    category: "data-display",
    keywords: ["calendar", "event", "appointment", "meeting"],
    description: "Event displayed within a calendar",
    props: {
      id: "string",
      title: "string",
      start: "Date",
      end: "Date",
      allDay: "boolean",
      color: "string",
      description: "string",
      location: "string",
      attendees: "Array<{name: string, email: string, avatar?: string}>",
      onClick: "(event: any) => void",
      onEdit: "(event: any) => void",
      onDelete: "(event: any) => void",
    },
  },

  Agenda: {
    category: "data-display",
    keywords: ["agenda", "schedule", "list", "events", "appointments"],
    description: "List view of upcoming events and appointments",
    props: {
      events: "Array<{id: string, title: string, start: Date, end: Date, description?: string, location?: string}>",
      startDate: "Date",
      endDate: "Date",
      groupBy: "'day' | 'week' | 'month'",
      showTime: "boolean",
      showLocation: "boolean",
      emptyMessage: "string",
      onEventClick: "(event: any) => void",
      renderEvent: "(event: any) => ReactNode",
    },
  },

  Scheduler: {
    category: "data-display",
    keywords: ["scheduler", "calendar", "booking", "appointments", "resources"],
    description: "Resource scheduling calendar with time slots",
    props: {
      events: "Array<{id: string, resourceId: string, start: Date, end: Date, title: string}>",
      resources: "Array<{id: string, name: string, avatar?: string}>",
      view: "'day' | 'week' | 'month' | 'timeline'",
      date: "Date",
      startHour: "number",
      endHour: "number",
      slotDuration: "number",
      showCurrentTime: "boolean",
      editable: "boolean",
      onEventClick: "(event: any) => void",
      onEventDrop: "(event: any, newStart: Date, newEnd: Date) => void",
      onSlotClick: "(resourceId: string, start: Date, end: Date) => void",
      onViewChange: "(view: string) => void",
      onDateChange: "(date: Date) => void",
    },
  },

  Gantt: {
    category: "data-display",
    keywords: ["gantt", "chart", "project", "timeline", "tasks"],
    description: "Gantt chart for project planning and tracking",
    props: {
      tasks: "Array<{id: string, name: string, start: Date, end: Date, progress?: number, dependencies?: string[], assignee?: string}>",
      viewMode: "'day' | 'week' | 'month' | 'quarter' | 'year'",
      startDate: "Date",
      endDate: "Date",
      todayMarker: "boolean",
      showProgress: "boolean",
      showDependencies: "boolean",
      editable: "boolean",
      onTaskClick: "(task: any) => void",
      onTaskUpdate: "(task: any) => void",
      onDependencyClick: "(from: string, to: string) => void",
      milestones: "Array<{id: string, date: Date, label: string}>",
      columnWidth: "number",
      rowHeight: "number",
    },
  },

  // ============================================================================
  // TREE & HIERARCHY
  // ============================================================================

  Tree: {
    category: "data-display",
    keywords: ["tree", "hierarchy", "nested", "folder", "structure"],
    description: "Tree view for hierarchical data",
    props: {
      data: "Array<{id: string, label: string, children?: Array<any>, icon?: ReactNode, disabled?: boolean}>",
      defaultExpandedIds: "string[]",
      expandedIds: "string[]",
      selectedIds: "string[]",
      selectionMode: "'single' | 'multiple' | 'none'",
      checkable: "boolean",
      checkedIds: "string[]",
      draggable: "boolean",
      showLines: "boolean",
      showIcon: "boolean",
      onExpand: "(expandedIds: string[]) => void",
      onSelect: "(selectedIds: string[]) => void",
      onCheck: "(checkedIds: string[]) => void",
      onDrop: "(dragId: string, dropId: string, position: 'before' | 'after' | 'inside') => void",
      loadData: "(node: any) => Promise<any[]>",
    },
  },

  TreeNode: {
    category: "data-display",
    keywords: ["tree", "node", "item", "branch", "leaf"],
    description: "Individual node in a tree structure",
    props: {
      id: "string",
      label: "ReactNode",
      icon: "ReactNode",
      expandIcon: "ReactNode",
      collapseIcon: "ReactNode",
      expanded: "boolean",
      selected: "boolean",
      checked: "boolean",
      indeterminate: "boolean",
      disabled: "boolean",
      leaf: "boolean",
      loading: "boolean",
      children: "ReactNode",
      onToggle: "() => void",
      onSelect: "() => void",
      onCheck: "(checked: boolean) => void",
    },
  },

  OrgChart: {
    category: "data-display",
    keywords: ["org", "chart", "organization", "hierarchy", "reporting"],
    description: "Organization chart showing reporting structure",
    props: {
      data: "Array<{id: string, name: string, title: string, parentId?: string, avatar?: string, department?: string}>",
      rootId: "string",
      orientation: "'vertical' | 'horizontal'",
      nodeWidth: "number",
      nodeHeight: "number",
      levelGap: "number",
      siblingGap: "number",
      renderNode: "(node: any) => ReactNode",
      onNodeClick: "(node: any) => void",
      expandable: "boolean",
      defaultExpandedIds: "string[]",
      zoomable: "boolean",
      pannable: "boolean",
      fitView: "boolean",
    },
  },

  // ============================================================================
  // KANBAN
  // ============================================================================

  Kanban: {
    category: "data-display",
    keywords: ["kanban", "board", "tasks", "workflow", "drag", "drop"],
    description: "Kanban board for workflow management",
    props: {
      columns: "Array<{id: string, title: string, color?: string, limit?: number}>",
      cards: "Array<{id: string, columnId: string, title: string, description?: string, tags?: string[], assignee?: any}>",
      onCardMove: "(cardId: string, fromColumnId: string, toColumnId: string, position: number) => void",
      onCardClick: "(card: any) => void",
      onAddCard: "(columnId: string) => void",
      onColumnAdd: "() => void",
      onColumnEdit: "(column: any) => void",
      renderCard: "(card: any) => ReactNode",
      renderColumnHeader: "(column: any) => ReactNode",
      draggable: "boolean",
      collapsible: "boolean",
      showCardCount: "boolean",
    },
  },

  KanbanColumn: {
    category: "data-display",
    keywords: ["kanban", "column", "lane", "status"],
    description: "Column/lane in a Kanban board",
    props: {
      id: "string",
      title: "string",
      color: "string",
      limit: "number",
      cardCount: "number",
      collapsed: "boolean",
      onCollapse: "() => void",
      onAddCard: "() => void",
      onEdit: "() => void",
      onDelete: "() => void",
      children: "ReactNode",
      droppable: "boolean",
    },
  },

  KanbanCard: {
    category: "data-display",
    keywords: ["kanban", "card", "task", "item"],
    description: "Card/task in a Kanban board",
    props: {
      id: "string",
      title: "string",
      description: "string",
      tags: "Array<{label: string, color: string}>",
      assignee: "{name: string, avatar?: string}",
      dueDate: "Date",
      priority: "'low' | 'medium' | 'high' | 'urgent'",
      attachments: "number",
      comments: "number",
      checklist: "{completed: number, total: number}",
      onClick: "() => void",
      onEdit: "() => void",
      onDelete: "() => void",
      draggable: "boolean",
      selected: "boolean",
    },
  },

  // ============================================================================
  // GALLERY & MEDIA
  // ============================================================================

  Gallery: {
    category: "data-display",
    keywords: ["gallery", "images", "photos", "grid", "collection"],
    description: "Image gallery with grid and lightbox",
    props: {
      images: "Array<{id: string, src: string, alt: string, thumbnail?: string, caption?: string}>",
      columns: "number | {xs?: number, sm?: number, md?: number, lg?: number}",
      gap: "number",
      aspectRatio: "number | 'auto'",
      objectFit: "'cover' | 'contain' | 'fill'",
      lightbox: "boolean",
      onImageClick: "(image: any, index: number) => void",
      loading: "'lazy' | 'eager'",
      selectable: "boolean",
      selectedIds: "string[]",
      onSelectionChange: "(selectedIds: string[]) => void",
    },
  },

  ImageGrid: {
    category: "data-display",
    keywords: ["image", "grid", "photos", "masonry"],
    description: "Responsive grid layout for images",
    props: {
      images: "Array<{id: string, src: string, alt: string, width?: number, height?: number}>",
      columns: "number | {xs?: number, sm?: number, md?: number, lg?: number}",
      gap: "number",
      layout: "'grid' | 'masonry'",
      aspectRatio: "number",
      objectFit: "'cover' | 'contain'",
      borderRadius: "number",
      onClick: "(image: any, index: number) => void",
      renderOverlay: "(image: any) => ReactNode",
      loading: "'lazy' | 'eager'",
    },
  },

  Carousel: {
    category: "data-display",
    keywords: ["carousel", "slider", "slideshow", "images"],
    description: "Carousel/slider for cycling through content",
    props: {
      items: "Array<{id: string, content: ReactNode}>",
      autoPlay: "boolean",
      autoPlayInterval: "number",
      loop: "boolean",
      showArrows: "boolean",
      showDots: "boolean",
      showThumbnails: "boolean",
      slidesToShow: "number",
      slidesToScroll: "number",
      gap: "number",
      animation: "'slide' | 'fade'",
      onSlideChange: "(index: number) => void",
      initialSlide: "number",
      pauseOnHover: "boolean",
      draggable: "boolean",
    },
  },

  Lightbox: {
    category: "data-display",
    keywords: ["lightbox", "modal", "image", "viewer", "fullscreen"],
    description: "Fullscreen image viewer with navigation",
    props: {
      images: "Array<{src: string, alt: string, caption?: string, description?: string}>",
      open: "boolean",
      initialIndex: "number",
      onClose: "() => void",
      onIndexChange: "(index: number) => void",
      showThumbnails: "boolean",
      showCaption: "boolean",
      showNavigation: "boolean",
      showCounter: "boolean",
      zoom: "boolean",
      download: "boolean",
      share: "boolean",
      slideshow: "boolean",
      slideshowInterval: "number",
    },
  },

  Video: {
    category: "data-display",
    keywords: ["video", "media", "player", "embed"],
    description: "Video embed component",
    props: {
      src: "string",
      poster: "string",
      width: "number | string",
      height: "number | string",
      aspectRatio: "string",
      autoPlay: "boolean",
      muted: "boolean",
      loop: "boolean",
      controls: "boolean",
      playsInline: "boolean",
      preload: "'none' | 'metadata' | 'auto'",
      onPlay: "() => void",
      onPause: "() => void",
      onEnded: "() => void",
      onTimeUpdate: "(currentTime: number) => void",
    },
  },

  VideoPlayer: {
    category: "data-display",
    keywords: ["video", "player", "controls", "streaming"],
    description: "Full-featured video player with custom controls",
    props: {
      src: "string | Array<{src: string, type: string}>",
      poster: "string",
      title: "string",
      autoPlay: "boolean",
      muted: "boolean",
      loop: "boolean",
      playbackRates: "number[]",
      quality: "Array<{label: string, src: string}>",
      subtitles: "Array<{label: string, src: string, lang: string}>",
      chapters: "Array<{time: number, title: string}>",
      hotkeys: "boolean",
      pip: "boolean",
      fullscreen: "boolean",
      theater: "boolean",
      onPlay: "() => void",
      onPause: "() => void",
      onEnded: "() => void",
      onError: "(error: any) => void",
    },
  },

  Audio: {
    category: "data-display",
    keywords: ["audio", "sound", "media", "music"],
    description: "Audio embed component",
    props: {
      src: "string",
      autoPlay: "boolean",
      muted: "boolean",
      loop: "boolean",
      controls: "boolean",
      preload: "'none' | 'metadata' | 'auto'",
      onPlay: "() => void",
      onPause: "() => void",
      onEnded: "() => void",
      onTimeUpdate: "(currentTime: number) => void",
      onVolumeChange: "(volume: number) => void",
    },
  },

  AudioPlayer: {
    category: "data-display",
    keywords: ["audio", "player", "music", "podcast", "controls"],
    description: "Full-featured audio player with custom controls",
    props: {
      src: "string",
      title: "string",
      artist: "string",
      album: "string",
      artwork: "string",
      autoPlay: "boolean",
      muted: "boolean",
      loop: "boolean",
      playbackRates: "number[]",
      showWaveform: "boolean",
      showSpectrum: "boolean",
      downloadable: "boolean",
      onPlay: "() => void",
      onPause: "() => void",
      onEnded: "() => void",
      onTimeUpdate: "(currentTime: number, duration: number) => void",
    },
  },

  PDF: {
    category: "data-display",
    keywords: ["pdf", "document", "embed", "file"],
    description: "PDF document embed",
    props: {
      src: "string | File",
      page: "number",
      scale: "number",
      width: "number | string",
      height: "number | string",
      onLoadSuccess: "(numPages: number) => void",
      onLoadError: "(error: any) => void",
      onPageChange: "(page: number) => void",
      loading: "ReactNode",
      error: "ReactNode",
    },
  },

  PDFViewer: {
    category: "data-display",
    keywords: ["pdf", "viewer", "document", "reader"],
    description: "Full-featured PDF viewer with navigation",
    props: {
      src: "string | File",
      initialPage: "number",
      initialScale: "number | 'auto' | 'page-fit' | 'page-width'",
      showToolbar: "boolean",
      showThumbnails: "boolean",
      showOutline: "boolean",
      searchable: "boolean",
      downloadable: "boolean",
      printable: "boolean",
      rotatable: "boolean",
      onPageChange: "(page: number) => void",
      onScaleChange: "(scale: number) => void",
      onTextSelect: "(text: string) => void",
    },
  },

  // ============================================================================
  // MAP
  // ============================================================================

  Map: {
    category: "data-display",
    keywords: ["map", "location", "geographic", "coordinates"],
    description: "Interactive map component",
    props: {
      center: "{lat: number, lng: number}",
      zoom: "number",
      minZoom: "number",
      maxZoom: "number",
      markers: "Array<{id: string, position: {lat: number, lng: number}, title?: string, icon?: string}>",
      polygons: "Array<{id: string, paths: Array<{lat: number, lng: number}>, fillColor?: string, strokeColor?: string}>",
      polylines: "Array<{id: string, path: Array<{lat: number, lng: number}>, strokeColor?: string}>",
      style: "'roadmap' | 'satellite' | 'terrain' | 'hybrid'",
      onMapClick: "(position: {lat: number, lng: number}) => void",
      onMarkerClick: "(markerId: string) => void",
      onZoomChange: "(zoom: number) => void",
      onCenterChange: "(center: {lat: number, lng: number}) => void",
      draggable: "boolean",
      zoomControl: "boolean",
      fullscreenControl: "boolean",
    },
  },

  MapMarker: {
    category: "data-display",
    keywords: ["map", "marker", "pin", "location", "point"],
    description: "Marker/pin on a map",
    props: {
      position: "{lat: number, lng: number}",
      title: "string",
      label: "string | {text: string, color?: string}",
      icon: "string | {url: string, size?: {width: number, height: number}}",
      draggable: "boolean",
      onClick: "() => void",
      onDragEnd: "(position: {lat: number, lng: number}) => void",
      popup: "ReactNode",
      popupOpen: "boolean",
      zIndex: "number",
    },
  },

  // ============================================================================
  // CODE & TEXT
  // ============================================================================

  CodeBlock: {
    category: "data-display",
    keywords: ["code", "syntax", "highlight", "programming"],
    description: "Syntax-highlighted code block",
    props: {
      code: "string",
      language: "string",
      theme: "'light' | 'dark' | string",
      showLineNumbers: "boolean",
      startingLineNumber: "number",
      highlightLines: "number[]",
      wrapLines: "boolean",
      copyButton: "boolean",
      onCopy: "(code: string) => void",
      maxHeight: "number | string",
      fileName: "string",
      showLanguage: "boolean",
    },
  },

  Diff: {
    category: "data-display",
    keywords: ["diff", "compare", "changes", "version", "code"],
    description: "Code diff viewer showing changes between versions",
    props: {
      oldValue: "string",
      newValue: "string",
      language: "string",
      viewType: "'split' | 'unified'",
      showLineNumbers: "boolean",
      highlightLines: "boolean",
      renderContent: "(content: string) => ReactNode",
      oldTitle: "string",
      newTitle: "string",
      theme: "'light' | 'dark'",
      hideUnchanged: "boolean",
      contextLines: "number",
    },
  },

  JSON: {
    category: "data-display",
    keywords: ["json", "data", "object", "viewer", "tree"],
    description: "Interactive JSON viewer with collapsible nodes",
    props: {
      data: "any",
      collapsed: "boolean | number",
      enableClipboard: "boolean",
      displayDataTypes: "boolean",
      displayObjectSize: "boolean",
      indentWidth: "number",
      quotesOnKeys: "boolean",
      sortKeys: "boolean",
      theme: "'light' | 'dark' | Record<string, string>",
      onEdit: "(edit: {updated_src: any, name: string, namespace: string[]}) => void",
      onAdd: "(add: {updated_src: any, name: string, namespace: string[]}) => void",
      onDelete: "(del: {updated_src: any, name: string, namespace: string[]}) => void",
      editable: "boolean",
    },
  },

  Markdown: {
    category: "data-display",
    keywords: ["markdown", "text", "content", "formatted", "rich"],
    description: "Markdown content renderer",
    props: {
      content: "string",
      allowHtml: "boolean",
      linkTarget: "'_blank' | '_self'",
      components: "Record<string, React.ComponentType<any>>",
      remarkPlugins: "any[]",
      rehypePlugins: "any[]",
      className: "string",
      skipHtml: "boolean",
      unwrapDisallowed: "boolean",
      transformLinkUri: "(uri: string) => string",
      transformImageUri: "(uri: string) => string",
    },
  },
};

export default dataDisplaySchemas;
