export interface ComponentSchema {
  category: string;
  keywords: string[];
  description: string;
  props: Record<string, string>;
}

export const formsSchemas: Record<string, ComponentSchema> = {
  Input: {
    category: "forms",
    keywords: ["text", "field", "form", "input", "textbox"],
    description: "Basic text input field for single-line text entry",
    props: {
      label: "string",
      placeholder: "string",
      type: "'text' | 'email' | 'password' | 'number' | 'tel' | 'url'",
      value: "string",
      defaultValue: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      maxLength: "number",
      minLength: "number",
      autoFocus: "boolean",
      autoComplete: "string",
      name: "string",
      id: "string",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      leftIcon: "ReactNode",
      rightIcon: "ReactNode",
      onChange: "(value: string) => void",
      onBlur: "() => void",
      onFocus: "() => void"
    }
  },

  TextInput: {
    category: "forms",
    keywords: ["text", "input", "field", "string", "textbox"],
    description: "Text input specifically for plain text entry",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      maxLength: "number",
      minLength: "number",
      pattern: "string",
      spellCheck: "boolean",
      autoCapitalize: "'none' | 'sentences' | 'words' | 'characters'",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      clearable: "boolean",
      showCharacterCount: "boolean",
      onChange: "(value: string) => void"
    }
  },

  EmailInput: {
    category: "forms",
    keywords: ["email", "input", "mail", "address", "contact"],
    description: "Input field optimized for email address entry with validation",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      multiple: "boolean",
      validateOnBlur: "boolean",
      allowedDomains: "string[]",
      blockedDomains: "string[]",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      showValidIcon: "boolean",
      onChange: "(value: string) => void",
      onValidate: "(isValid: boolean) => void"
    }
  },

  PasswordInput: {
    category: "forms",
    keywords: ["password", "secret", "secure", "login", "credential"],
    description: "Secure password input with visibility toggle and strength indicator",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      minLength: "number",
      maxLength: "number",
      showToggle: "boolean",
      showStrengthMeter: "boolean",
      strengthLevels: "{ weak: string; medium: string; strong: string }",
      requireUppercase: "boolean",
      requireLowercase: "boolean",
      requireNumbers: "boolean",
      requireSpecialChars: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      autoComplete: "'current-password' | 'new-password'",
      onChange: "(value: string) => void",
      onStrengthChange: "(strength: 'weak' | 'medium' | 'strong') => void"
    }
  },

  NumberInput: {
    category: "forms",
    keywords: ["number", "numeric", "integer", "decimal", "quantity", "amount"],
    description: "Numeric input with increment/decrement controls and formatting",
    props: {
      label: "string",
      placeholder: "string",
      value: "number",
      defaultValue: "number",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      min: "number",
      max: "number",
      step: "number",
      precision: "number",
      showStepper: "boolean",
      allowNegative: "boolean",
      allowDecimal: "boolean",
      thousandSeparator: "string",
      decimalSeparator: "string",
      prefix: "string",
      suffix: "string",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      clampValueOnBlur: "boolean",
      onChange: "(value: number) => void"
    }
  },

  PhoneInput: {
    category: "forms",
    keywords: ["phone", "telephone", "mobile", "number", "contact", "cell"],
    description: "Phone number input with country code selector and formatting",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      defaultCountry: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      preferredCountries: "string[]",
      excludeCountries: "string[]",
      onlyCountries: "string[]",
      showCountryFlag: "boolean",
      showCountryCode: "boolean",
      autoFormat: "boolean",
      enableSearch: "boolean",
      searchPlaceholder: "string",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: string, country: object) => void",
      onValidate: "(isValid: boolean) => void"
    }
  },

  SearchInput: {
    category: "forms",
    keywords: ["search", "find", "query", "filter", "lookup"],
    description: "Search input with icon, clear button, and optional suggestions",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      disabled: "boolean",
      loading: "boolean",
      showIcon: "boolean",
      iconPosition: "'left' | 'right'",
      clearable: "boolean",
      suggestions: "string[]",
      showSuggestions: "boolean",
      maxSuggestions: "number",
      highlightMatch: "boolean",
      debounceMs: "number",
      minSearchLength: "number",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: string) => void",
      onSearch: "(value: string) => void",
      onSuggestionSelect: "(suggestion: string) => void",
      onClear: "() => void"
    }
  },

  UrlInput: {
    category: "forms",
    keywords: ["url", "link", "website", "address", "href", "web"],
    description: "URL input with validation and optional preview",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      protocols: "string[]",
      requireProtocol: "boolean",
      validateOnBlur: "boolean",
      showPreview: "boolean",
      showFavicon: "boolean",
      allowedDomains: "string[]",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: string) => void",
      onValidate: "(isValid: boolean) => void"
    }
  },

  Textarea: {
    category: "forms",
    keywords: ["textarea", "multiline", "text", "paragraph", "description", "comment"],
    description: "Multi-line text input for longer content",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      rows: "number",
      minRows: "number",
      maxRows: "number",
      maxLength: "number",
      minLength: "number",
      resize: "'none' | 'vertical' | 'horizontal' | 'both'",
      autoResize: "boolean",
      showCharacterCount: "boolean",
      spellCheck: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: string) => void"
    }
  },

  RichTextEditor: {
    category: "forms",
    keywords: ["rich", "text", "editor", "wysiwyg", "html", "formatting"],
    description: "Rich text editor with formatting toolbar and HTML output",
    props: {
      label: "string",
      value: "string",
      defaultValue: "string",
      placeholder: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      minHeight: "number | string",
      maxHeight: "number | string",
      toolbar: "string[]",
      toolbarPosition: "'top' | 'bottom'",
      modules: "object",
      formats: "string[]",
      allowImages: "boolean",
      allowLinks: "boolean",
      allowTables: "boolean",
      allowCodeBlocks: "boolean",
      imageUploadHandler: "(file: File) => Promise<string>",
      mentionSuggestions: "object[]",
      outputFormat: "'html' | 'markdown' | 'delta'",
      onChange: "(value: string) => void",
      onImageUpload: "(file: File) => void"
    }
  },

  MarkdownEditor: {
    category: "forms",
    keywords: ["markdown", "md", "editor", "text", "formatting", "preview"],
    description: "Markdown editor with live preview and syntax highlighting",
    props: {
      label: "string",
      value: "string",
      defaultValue: "string",
      placeholder: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      minHeight: "number | string",
      maxHeight: "number | string",
      showToolbar: "boolean",
      showPreview: "boolean",
      previewPosition: "'right' | 'bottom' | 'tab'",
      splitRatio: "number",
      allowImages: "boolean",
      imageUploadHandler: "(file: File) => Promise<string>",
      syntaxHighlighting: "boolean",
      highlightTheme: "string",
      tabSize: "number",
      lineNumbers: "boolean",
      onChange: "(value: string) => void"
    }
  },

  CodeEditor: {
    category: "forms",
    keywords: ["code", "editor", "syntax", "programming", "ide", "snippet"],
    description: "Code editor with syntax highlighting and language support",
    props: {
      label: "string",
      value: "string",
      defaultValue: "string",
      placeholder: "string",
      language: "string",
      theme: "'light' | 'dark' | 'vs-dark' | 'github' | string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      minHeight: "number | string",
      maxHeight: "number | string",
      lineNumbers: "boolean",
      lineWrapping: "boolean",
      highlightActiveLine: "boolean",
      showMinimap: "boolean",
      tabSize: "number",
      insertSpaces: "boolean",
      autoCloseBrackets: "boolean",
      autoCloseQuotes: "boolean",
      matchBrackets: "boolean",
      foldGutter: "boolean",
      lintOnChange: "boolean",
      formatOnSave: "boolean",
      onChange: "(value: string) => void",
      onValidate: "(errors: object[]) => void"
    }
  },

  Select: {
    category: "forms",
    keywords: ["select", "dropdown", "option", "choice", "picker"],
    description: "Single-select dropdown for choosing from a list of options",
    props: {
      label: "string",
      placeholder: "string",
      value: "string | number",
      defaultValue: "string | number",
      options: "{ value: string | number; label: string; disabled?: boolean }[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      searchable: "boolean",
      clearable: "boolean",
      loading: "boolean",
      loadingText: "string",
      noOptionsText: "string",
      groupBy: "(option: object) => string",
      renderOption: "(option: object) => ReactNode",
      renderValue: "(option: object) => ReactNode",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      placement: "'bottom' | 'top' | 'auto'",
      maxMenuHeight: "number",
      menuPortalTarget: "HTMLElement",
      onChange: "(value: string | number) => void",
      onSearch: "(query: string) => void"
    }
  },

  MultiSelect: {
    category: "forms",
    keywords: ["multiselect", "multiple", "select", "tags", "chips", "dropdown"],
    description: "Multi-select dropdown for choosing multiple options",
    props: {
      label: "string",
      placeholder: "string",
      value: "(string | number)[]",
      defaultValue: "(string | number)[]",
      options: "{ value: string | number; label: string; disabled?: boolean }[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      searchable: "boolean",
      clearable: "boolean",
      loading: "boolean",
      maxItems: "number",
      minItems: "number",
      showSelectAll: "boolean",
      selectAllText: "string",
      chipVariant: "'filled' | 'outlined'",
      chipSize: "'sm' | 'md'",
      hideSelectedOptions: "boolean",
      closeOnSelect: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      maxMenuHeight: "number",
      onChange: "(values: (string | number)[]) => void",
      onSearch: "(query: string) => void"
    }
  },

  Combobox: {
    category: "forms",
    keywords: ["combobox", "autocomplete", "select", "input", "search", "dropdown"],
    description: "Combination of text input and dropdown with type-ahead filtering",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      options: "{ value: string; label: string; disabled?: boolean }[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      allowCustomValue: "boolean",
      openOnFocus: "boolean",
      clearable: "boolean",
      loading: "boolean",
      filterFunction: "(option: object, inputValue: string) => boolean",
      noOptionsText: "string",
      createText: "string",
      highlightMatch: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      maxMenuHeight: "number",
      onChange: "(value: string) => void",
      onInputChange: "(inputValue: string) => void",
      onCreate: "(value: string) => void"
    }
  },

  Autocomplete: {
    category: "forms",
    keywords: ["autocomplete", "typeahead", "suggest", "search", "complete"],
    description: "Text input with dynamic suggestions based on user input",
    props: {
      label: "string",
      placeholder: "string",
      value: "string | object",
      defaultValue: "string | object",
      options: "object[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      loading: "boolean",
      async: "boolean",
      debounceMs: "number",
      minInputLength: "number",
      maxSuggestions: "number",
      filterOptions: "(options: object[], inputValue: string) => object[]",
      getOptionLabel: "(option: object) => string",
      getOptionValue: "(option: object) => string",
      isOptionEqualToValue: "(option: object, value: object) => boolean",
      renderOption: "(option: object) => ReactNode",
      noOptionsText: "string",
      loadingText: "string",
      freeSolo: "boolean",
      multiple: "boolean",
      highlightMatch: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: string | object) => void",
      onInputChange: "(value: string) => void"
    }
  },

  Checkbox: {
    category: "forms",
    keywords: ["checkbox", "check", "tick", "boolean", "toggle", "select"],
    description: "Single checkbox for boolean input",
    props: {
      label: "string",
      checked: "boolean",
      defaultChecked: "boolean",
      indeterminate: "boolean",
      value: "string",
      name: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      size: "'sm' | 'md' | 'lg'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      labelPlacement: "'start' | 'end' | 'top' | 'bottom'",
      icon: "ReactNode",
      checkedIcon: "ReactNode",
      indeterminateIcon: "ReactNode",
      onChange: "(checked: boolean, event: ChangeEvent) => void"
    }
  },

  CheckboxGroup: {
    category: "forms",
    keywords: ["checkbox", "group", "multiple", "selection", "options"],
    description: "Group of checkboxes for multiple selections",
    props: {
      label: "string",
      value: "string[]",
      defaultValue: "string[]",
      options: "{ value: string; label: string; disabled?: boolean }[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      orientation: "'horizontal' | 'vertical'",
      spacing: "number | string",
      size: "'sm' | 'md' | 'lg'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      minSelections: "number",
      maxSelections: "number",
      showSelectAll: "boolean",
      selectAllLabel: "string",
      onChange: "(values: string[]) => void"
    }
  },

  Radio: {
    category: "forms",
    keywords: ["radio", "option", "single", "choice", "select"],
    description: "Single radio button for mutually exclusive choices",
    props: {
      label: "string",
      checked: "boolean",
      value: "string",
      name: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      size: "'sm' | 'md' | 'lg'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      labelPlacement: "'start' | 'end' | 'top' | 'bottom'",
      icon: "ReactNode",
      checkedIcon: "ReactNode",
      onChange: "(event: ChangeEvent) => void"
    }
  },

  RadioGroup: {
    category: "forms",
    keywords: ["radio", "group", "options", "single", "selection", "choice"],
    description: "Group of radio buttons for single selection from multiple options",
    props: {
      label: "string",
      value: "string",
      defaultValue: "string",
      name: "string",
      options: "{ value: string; label: string; description?: string; disabled?: boolean }[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      orientation: "'horizontal' | 'vertical'",
      spacing: "number | string",
      size: "'sm' | 'md' | 'lg'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      variant: "'default' | 'card' | 'button'",
      onChange: "(value: string) => void"
    }
  },

  Switch: {
    category: "forms",
    keywords: ["switch", "toggle", "boolean", "on", "off", "flip"],
    description: "Toggle switch for binary on/off states",
    props: {
      label: "string",
      checked: "boolean",
      defaultChecked: "boolean",
      value: "string",
      name: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      size: "'sm' | 'md' | 'lg'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      labelPlacement: "'start' | 'end' | 'top' | 'bottom'",
      thumbIcon: "ReactNode",
      onIcon: "ReactNode",
      offIcon: "ReactNode",
      onChange: "(checked: boolean) => void"
    }
  },

  Toggle: {
    category: "forms",
    keywords: ["toggle", "button", "switch", "active", "press"],
    description: "Toggle button that can be pressed to toggle state",
    props: {
      label: "string",
      pressed: "boolean",
      defaultPressed: "boolean",
      value: "string",
      disabled: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'default' | 'outline' | 'ghost'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      icon: "ReactNode",
      pressedIcon: "ReactNode",
      showLabel: "boolean",
      onChange: "(pressed: boolean) => void"
    }
  },

  ToggleGroup: {
    category: "forms",
    keywords: ["toggle", "group", "buttons", "segment", "options"],
    description: "Group of toggle buttons for single or multiple selection",
    props: {
      value: "string | string[]",
      defaultValue: "string | string[]",
      type: "'single' | 'multiple'",
      options: "{ value: string; label: string; icon?: ReactNode; disabled?: boolean }[]",
      disabled: "boolean",
      orientation: "'horizontal' | 'vertical'",
      size: "'sm' | 'md' | 'lg'",
      variant: "'default' | 'outline' | 'ghost'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      spacing: "number | string",
      fullWidth: "boolean",
      onChange: "(value: string | string[]) => void"
    }
  },

  Slider: {
    category: "forms",
    keywords: ["slider", "range", "value", "track", "thumb", "drag"],
    description: "Slider for selecting a single value from a range",
    props: {
      label: "string",
      value: "number",
      defaultValue: "number",
      min: "number",
      max: "number",
      step: "number",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      orientation: "'horizontal' | 'vertical'",
      size: "'sm' | 'md' | 'lg'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      showValue: "boolean",
      showTooltip: "boolean | 'always' | 'hover'",
      tooltipFormat: "(value: number) => string",
      marks: "boolean | { value: number; label?: string }[]",
      showMinMax: "boolean",
      track: "'normal' | 'inverted' | false",
      thumbLabel: "string",
      onChange: "(value: number) => void",
      onChangeCommitted: "(value: number) => void"
    }
  },

  RangeSlider: {
    category: "forms",
    keywords: ["range", "slider", "dual", "between", "min", "max"],
    description: "Dual-thumb slider for selecting a value range",
    props: {
      label: "string",
      value: "[number, number]",
      defaultValue: "[number, number]",
      min: "number",
      max: "number",
      step: "number",
      minDistance: "number",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      orientation: "'horizontal' | 'vertical'",
      size: "'sm' | 'md' | 'lg'",
      color: "'primary' | 'secondary' | 'success' | 'warning' | 'error'",
      showValues: "boolean",
      showTooltip: "boolean | 'always' | 'hover'",
      tooltipFormat: "(value: number) => string",
      marks: "boolean | { value: number; label?: string }[]",
      showMinMax: "boolean",
      disableSwap: "boolean",
      onChange: "(value: [number, number]) => void",
      onChangeCommitted: "(value: [number, number]) => void"
    }
  },

  DatePicker: {
    category: "forms",
    keywords: ["date", "picker", "calendar", "day", "month", "year"],
    description: "Date picker for selecting a single date",
    props: {
      label: "string",
      placeholder: "string",
      value: "Date | string",
      defaultValue: "Date | string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      format: "string",
      minDate: "Date | string",
      maxDate: "Date | string",
      disabledDates: "Date[] | ((date: Date) => boolean)",
      firstDayOfWeek: "0 | 1 | 2 | 3 | 4 | 5 | 6",
      showWeekNumbers: "boolean",
      showTodayButton: "boolean",
      showClearButton: "boolean",
      closeOnSelect: "boolean",
      openTo: "'day' | 'month' | 'year'",
      views: "('day' | 'month' | 'year')[]",
      locale: "string | object",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      placement: "'bottom' | 'top' | 'auto'",
      onChange: "(date: Date | null) => void",
      onMonthChange: "(date: Date) => void"
    }
  },

  DateRangePicker: {
    category: "forms",
    keywords: ["date", "range", "picker", "start", "end", "period"],
    description: "Date picker for selecting a date range",
    props: {
      label: "string",
      startPlaceholder: "string",
      endPlaceholder: "string",
      value: "[Date | null, Date | null]",
      defaultValue: "[Date | null, Date | null]",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      format: "string",
      minDate: "Date | string",
      maxDate: "Date | string",
      minRange: "number",
      maxRange: "number",
      disabledDates: "Date[] | ((date: Date) => boolean)",
      firstDayOfWeek: "0 | 1 | 2 | 3 | 4 | 5 | 6",
      showWeekNumbers: "boolean",
      showPresets: "boolean",
      presets: "{ label: string; value: [Date, Date] }[]",
      numberOfMonths: "number",
      locale: "string | object",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(range: [Date | null, Date | null]) => void"
    }
  },

  TimePicker: {
    category: "forms",
    keywords: ["time", "picker", "hour", "minute", "clock"],
    description: "Time picker for selecting time values",
    props: {
      label: "string",
      placeholder: "string",
      value: "Date | string",
      defaultValue: "Date | string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      format: "'12h' | '24h'",
      minuteStep: "number",
      secondStep: "number",
      showSeconds: "boolean",
      minTime: "Date | string",
      maxTime: "Date | string",
      disabledHours: "number[]",
      disabledMinutes: "(hour: number) => number[]",
      showNowButton: "boolean",
      showClearButton: "boolean",
      closeOnSelect: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      clockType: "'analog' | 'digital'",
      onChange: "(time: Date | null) => void"
    }
  },

  DateTimePicker: {
    category: "forms",
    keywords: ["datetime", "date", "time", "picker", "calendar", "clock"],
    description: "Combined date and time picker",
    props: {
      label: "string",
      placeholder: "string",
      value: "Date | string",
      defaultValue: "Date | string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      dateFormat: "string",
      timeFormat: "'12h' | '24h'",
      minDateTime: "Date | string",
      maxDateTime: "Date | string",
      minuteStep: "number",
      showSeconds: "boolean",
      disabledDates: "Date[] | ((date: Date) => boolean)",
      firstDayOfWeek: "0 | 1 | 2 | 3 | 4 | 5 | 6",
      showTodayButton: "boolean",
      showNowButton: "boolean",
      showClearButton: "boolean",
      locale: "string | object",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(dateTime: Date | null) => void"
    }
  },

  ColorPicker: {
    category: "forms",
    keywords: ["color", "picker", "palette", "hue", "saturation", "hex", "rgb"],
    description: "Color picker for selecting colors in various formats",
    props: {
      label: "string",
      value: "string",
      defaultValue: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      format: "'hex' | 'rgb' | 'rgba' | 'hsl' | 'hsla'",
      showAlpha: "boolean",
      showInput: "boolean",
      showPreview: "boolean",
      showSwatches: "boolean",
      swatches: "string[]",
      presetColors: "string[]",
      showEyeDropper: "boolean",
      showRecentColors: "boolean",
      maxRecentColors: "number",
      size: "'sm' | 'md' | 'lg'",
      variant: "'default' | 'inline' | 'popover'",
      placement: "'bottom' | 'top' | 'left' | 'right'",
      onChange: "(color: string) => void",
      onChangeComplete: "(color: string) => void"
    }
  },

  FilePicker: {
    category: "forms",
    keywords: ["file", "picker", "select", "browse", "choose"],
    description: "File picker button for selecting files from the file system",
    props: {
      label: "string",
      value: "File | File[]",
      placeholder: "string",
      buttonText: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      accept: "string",
      multiple: "boolean",
      maxFiles: "number",
      maxSize: "number",
      minSize: "number",
      showFileList: "boolean",
      showFileSize: "boolean",
      showFilePreview: "boolean",
      allowRemove: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'default' | 'outline' | 'ghost'",
      onChange: "(files: File | File[]) => void",
      onRemove: "(file: File) => void",
      onError: "(error: { type: string; file: File }) => void"
    }
  },

  FileUpload: {
    category: "forms",
    keywords: ["file", "upload", "upload", "send", "submit"],
    description: "File upload component with progress tracking",
    props: {
      label: "string",
      value: "File[]",
      endpoint: "string",
      method: "'POST' | 'PUT'",
      headers: "Record<string, string>",
      fieldName: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      accept: "string",
      multiple: "boolean",
      maxFiles: "number",
      maxSize: "number",
      minSize: "number",
      autoUpload: "boolean",
      withCredentials: "boolean",
      showProgress: "boolean",
      showFileList: "boolean",
      showRetry: "boolean",
      showCancel: "boolean",
      chunkSize: "number",
      concurrent: "number",
      onChange: "(files: File[]) => void",
      onUploadStart: "(file: File) => void",
      onUploadProgress: "(file: File, progress: number) => void",
      onUploadComplete: "(file: File, response: any) => void",
      onUploadError: "(file: File, error: Error) => void",
      beforeUpload: "(file: File) => boolean | Promise<boolean>"
    }
  },

  FileDropzone: {
    category: "forms",
    keywords: ["file", "dropzone", "drag", "drop", "upload", "zone"],
    description: "Drag and drop zone for file uploads",
    props: {
      label: "string",
      value: "File[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      accept: "string",
      multiple: "boolean",
      maxFiles: "number",
      maxSize: "number",
      minSize: "number",
      noClick: "boolean",
      noKeyboard: "boolean",
      noDrag: "boolean",
      preventDropOnDocument: "boolean",
      showFileList: "boolean",
      showPreview: "boolean",
      dropzoneText: "string",
      activeDropzoneText: "string",
      rejectDropzoneText: "string",
      icon: "ReactNode",
      height: "number | string",
      variant: "'default' | 'bordered' | 'dashed'",
      onChange: "(files: File[]) => void",
      onDrop: "(acceptedFiles: File[], rejectedFiles: File[]) => void",
      onDropAccepted: "(files: File[]) => void",
      onDropRejected: "(files: File[]) => void",
      validator: "(file: File) => { code: string; message: string } | null"
    }
  },

  ImageUpload: {
    category: "forms",
    keywords: ["image", "upload", "photo", "picture", "gallery"],
    description: "Image-specific upload with preview and cropping",
    props: {
      label: "string",
      value: "string | File | (string | File)[]",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      accept: "string",
      multiple: "boolean",
      maxFiles: "number",
      maxSize: "number",
      minWidth: "number",
      minHeight: "number",
      maxWidth: "number",
      maxHeight: "number",
      aspectRatio: "number",
      allowCrop: "boolean",
      cropShape: "'rect' | 'round'",
      showPreview: "boolean",
      previewSize: "number | { width: number; height: number }",
      compressImages: "boolean",
      compressionQuality: "number",
      outputFormat: "'jpeg' | 'png' | 'webp'",
      layout: "'grid' | 'list' | 'single'",
      columns: "number",
      onChange: "(images: (string | File)[]) => void",
      onCrop: "(file: File, croppedFile: File) => void"
    }
  },

  AvatarUpload: {
    category: "forms",
    keywords: ["avatar", "upload", "profile", "picture", "photo", "user"],
    description: "Avatar-specific upload with circular cropping",
    props: {
      label: "string",
      value: "string | File",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      accept: "string",
      maxSize: "number",
      size: "number | 'sm' | 'md' | 'lg' | 'xl'",
      shape: "'circle' | 'square' | 'rounded'",
      allowCrop: "boolean",
      showEditButton: "boolean",
      showRemoveButton: "boolean",
      editButtonIcon: "ReactNode",
      removeButtonIcon: "ReactNode",
      placeholder: "ReactNode",
      fallback: "string",
      compressImage: "boolean",
      compressionQuality: "number",
      outputSize: "number",
      outputFormat: "'jpeg' | 'png' | 'webp'",
      onChange: "(avatar: string | File | null) => void",
      onRemove: "() => void"
    }
  },

  Signature: {
    category: "forms",
    keywords: ["signature", "draw", "sign", "handwriting", "canvas"],
    description: "Digital signature pad for capturing signatures",
    props: {
      label: "string",
      value: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      width: "number | string",
      height: "number | string",
      penColor: "string",
      penWidth: "number",
      backgroundColor: "string",
      showClearButton: "boolean",
      showUndoButton: "boolean",
      clearButtonText: "string",
      undoButtonText: "string",
      outputFormat: "'base64' | 'blob' | 'svg'",
      outputType: "'image/png' | 'image/jpeg' | 'image/svg+xml'",
      trimWhitespace: "boolean",
      velocityFilterWeight: "number",
      minDistance: "number",
      throttle: "number",
      onChange: "(signature: string) => void",
      onBegin: "() => void",
      onEnd: "() => void"
    }
  },

  Rating: {
    category: "forms",
    keywords: ["rating", "rate", "stars", "score", "feedback"],
    description: "Rating input using icons for scoring",
    props: {
      label: "string",
      value: "number",
      defaultValue: "number",
      max: "number",
      precision: "0.5 | 1",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      size: "'sm' | 'md' | 'lg'",
      color: "string",
      emptyColor: "string",
      icon: "ReactNode",
      emptyIcon: "ReactNode",
      highlightSelectedOnly: "boolean",
      showValue: "boolean",
      valueFormat: "(value: number) => string",
      labels: "string[]",
      showLabels: "boolean",
      direction: "'ltr' | 'rtl'",
      onChange: "(value: number) => void",
      onHover: "(value: number) => void"
    }
  },

  StarRating: {
    category: "forms",
    keywords: ["star", "rating", "review", "score", "five"],
    description: "Star-based rating input for reviews and feedback",
    props: {
      label: "string",
      value: "number",
      defaultValue: "number",
      count: "number",
      allowHalf: "boolean",
      allowClear: "boolean",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      size: "'sm' | 'md' | 'lg'",
      color: "string",
      emptyColor: "string",
      hoverColor: "string",
      character: "ReactNode | ((index: number) => ReactNode)",
      showValue: "boolean",
      tooltips: "string[]",
      onChange: "(value: number) => void",
      onHoverChange: "(value: number) => void"
    }
  },

  OTPInput: {
    category: "forms",
    keywords: ["otp", "code", "verification", "pin", "two-factor", "2fa"],
    description: "One-time password input with individual digit fields",
    props: {
      label: "string",
      value: "string",
      defaultValue: "string",
      length: "number",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      type: "'text' | 'number' | 'password'",
      mask: "boolean",
      maskChar: "string",
      autoFocus: "boolean",
      autoSubmit: "boolean",
      allowPaste: "boolean",
      inputMode: "'numeric' | 'text'",
      pattern: "string",
      separator: "ReactNode",
      separatorAfter: "number[]",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      gap: "number | string",
      onChange: "(value: string) => void",
      onComplete: "(value: string) => void"
    }
  },

  PinInput: {
    category: "forms",
    keywords: ["pin", "code", "password", "numeric", "secure"],
    description: "PIN code input for numeric security codes",
    props: {
      label: "string",
      value: "string",
      defaultValue: "string",
      length: "number",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      mask: "boolean",
      maskChar: "string",
      autoFocus: "boolean",
      autoSubmit: "boolean",
      allowLetters: "boolean",
      manageFocus: "boolean",
      placeholder: "string",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      gap: "number | string",
      shape: "'square' | 'circle'",
      onChange: "(value: string) => void",
      onComplete: "(value: string) => void"
    }
  },

  CreditCardInput: {
    category: "forms",
    keywords: ["credit", "card", "payment", "visa", "mastercard", "stripe"],
    description: "Credit card input with number formatting and validation",
    props: {
      label: "string",
      value: "{ number: string; expiry: string; cvc: string; name?: string }",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      showCardIcon: "boolean",
      showCardType: "boolean",
      acceptedCards: "string[]",
      includeNameField: "boolean",
      namePlaceholder: "string",
      numberPlaceholder: "string",
      expiryPlaceholder: "string",
      cvcPlaceholder: "string",
      layout: "'single' | 'multi'",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: object) => void",
      onCardTypeChange: "(cardType: string) => void",
      onValidate: "(isValid: boolean, errors: object) => void"
    }
  },

  Form: {
    category: "forms",
    keywords: ["form", "submit", "validation", "fields", "input"],
    description: "Form wrapper component with validation and submission handling",
    props: {
      id: "string",
      name: "string",
      initialValues: "object",
      validationSchema: "object",
      validateOnBlur: "boolean",
      validateOnChange: "boolean",
      validateOnMount: "boolean",
      enableReinitialize: "boolean",
      disabled: "boolean",
      autoComplete: "'on' | 'off'",
      noValidate: "boolean",
      layout: "'vertical' | 'horizontal' | 'inline'",
      labelWidth: "number | string",
      labelAlign: "'left' | 'right'",
      requiredMark: "boolean | 'optional'",
      colon: "boolean",
      scrollToError: "boolean",
      scrollToErrorOptions: "object",
      onSubmit: "(values: object) => void | Promise<void>",
      onReset: "() => void",
      onValuesChange: "(changedValues: object, allValues: object) => void",
      onFieldsChange: "(changedFields: object[], allFields: object[]) => void",
      onFinishFailed: "(errorInfo: object) => void"
    }
  },

  FormField: {
    category: "forms",
    keywords: ["field", "form", "input", "control", "wrapper"],
    description: "Form field wrapper that connects inputs to form state",
    props: {
      name: "string",
      label: "string",
      required: "boolean",
      disabled: "boolean",
      hidden: "boolean",
      rules: "object[]",
      validateTrigger: "string | string[]",
      validateFirst: "boolean",
      valuePropName: "string",
      getValueFromEvent: "(event: any) => any",
      normalize: "(value: any, prevValue: any, allValues: object) => any",
      preserve: "boolean",
      dependencies: "string[]",
      shouldUpdate: "boolean | ((prevValues: object, curValues: object) => boolean)",
      tooltip: "string | ReactNode",
      extra: "string | ReactNode",
      help: "string | ReactNode",
      hasFeedback: "boolean",
      validateStatus: "'success' | 'warning' | 'error' | 'validating'",
      labelCol: "object",
      wrapperCol: "object",
      children: "ReactNode | ((control: object, meta: object, form: object) => ReactNode)"
    }
  },

  FormGroup: {
    category: "forms",
    keywords: ["group", "form", "section", "fieldset", "cluster"],
    description: "Groups related form fields together visually",
    props: {
      label: "string",
      description: "string",
      required: "boolean",
      disabled: "boolean",
      error: "string",
      helperText: "string",
      orientation: "'vertical' | 'horizontal'",
      spacing: "number | string",
      columns: "number",
      labelWidth: "number | string",
      labelAlign: "'left' | 'right' | 'top'",
      collapsible: "boolean",
      defaultCollapsed: "boolean",
      showBorder: "boolean",
      variant: "'default' | 'card' | 'outlined'",
      children: "ReactNode"
    }
  },

  FormSection: {
    category: "forms",
    keywords: ["section", "form", "divider", "group", "area"],
    description: "Divides form into logical sections with optional titles",
    props: {
      title: "string",
      subtitle: "string",
      description: "string",
      icon: "ReactNode",
      collapsible: "boolean",
      defaultCollapsed: "boolean",
      disabled: "boolean",
      showDivider: "boolean",
      dividerPosition: "'top' | 'bottom' | 'both'",
      spacing: "number | string",
      variant: "'default' | 'card' | 'outlined' | 'filled'",
      headerAction: "ReactNode",
      footer: "ReactNode",
      children: "ReactNode"
    }
  },

  FormError: {
    category: "forms",
    keywords: ["error", "form", "message", "validation", "alert"],
    description: "Displays form-level error messages",
    props: {
      error: "string | string[]",
      show: "boolean",
      variant: "'text' | 'filled' | 'outlined'",
      severity: "'error' | 'warning'",
      icon: "ReactNode",
      showIcon: "boolean",
      closable: "boolean",
      onClose: "() => void",
      className: "string",
      style: "CSSProperties"
    }
  },

  FormHelperText: {
    category: "forms",
    keywords: ["helper", "text", "hint", "description", "info"],
    description: "Helper text displayed below form fields",
    props: {
      children: "ReactNode",
      error: "boolean",
      disabled: "boolean",
      id: "string",
      variant: "'default' | 'error' | 'success' | 'warning'",
      icon: "ReactNode",
      showIcon: "boolean",
      className: "string",
      style: "CSSProperties"
    }
  },

  FormLabel: {
    category: "forms",
    keywords: ["label", "form", "title", "field", "name"],
    description: "Label component for form fields",
    props: {
      children: "ReactNode",
      htmlFor: "string",
      required: "boolean",
      disabled: "boolean",
      error: "boolean",
      tooltip: "string | ReactNode",
      tooltipPlacement: "'top' | 'right' | 'bottom' | 'left'",
      optionalText: "string",
      showOptional: "boolean",
      colon: "boolean",
      align: "'left' | 'right'",
      width: "number | string",
      className: "string",
      style: "CSSProperties"
    }
  },

  RequiredIndicator: {
    category: "forms",
    keywords: ["required", "asterisk", "indicator", "mandatory", "star"],
    description: "Visual indicator for required form fields",
    props: {
      show: "boolean",
      character: "string",
      color: "string",
      position: "'before' | 'after'",
      tooltip: "string",
      className: "string",
      style: "CSSProperties"
    }
  },

  FieldArray: {
    category: "forms",
    keywords: ["array", "field", "dynamic", "list", "repeatable"],
    description: "Manages dynamic arrays of form fields",
    props: {
      name: "string",
      initialValue: "any[]",
      minItems: "number",
      maxItems: "number",
      sortable: "boolean",
      removable: "boolean",
      addable: "boolean",
      addButtonText: "string",
      removeButtonText: "string",
      addButtonPosition: "'top' | 'bottom'",
      emptyMessage: "string",
      itemLabel: "string | ((index: number) => string)",
      showIndex: "boolean",
      confirmRemove: "boolean",
      confirmRemoveMessage: "string",
      layout: "'vertical' | 'horizontal'",
      spacing: "number | string",
      children: "(fields: object[], operations: object) => ReactNode",
      onAdd: "(index: number) => void",
      onRemove: "(index: number) => void",
      onMove: "(fromIndex: number, toIndex: number) => void"
    }
  },

  Fieldset: {
    category: "forms",
    keywords: ["fieldset", "group", "border", "legend", "section"],
    description: "HTML fieldset element for grouping form controls",
    props: {
      legend: "string | ReactNode",
      disabled: "boolean",
      form: "string",
      name: "string",
      variant: "'default' | 'bordered' | 'filled'",
      borderStyle: "'solid' | 'dashed' | 'dotted'",
      borderColor: "string",
      borderRadius: "number | string",
      padding: "number | string",
      spacing: "number | string",
      children: "ReactNode",
      className: "string",
      style: "CSSProperties"
    }
  },

  Legend: {
    category: "forms",
    keywords: ["legend", "fieldset", "title", "caption", "header"],
    description: "Legend element for fieldset captions",
    props: {
      children: "ReactNode",
      required: "boolean",
      disabled: "boolean",
      align: "'left' | 'center' | 'right'",
      size: "'sm' | 'md' | 'lg'",
      weight: "'normal' | 'medium' | 'bold'",
      color: "string",
      icon: "ReactNode",
      iconPosition: "'left' | 'right'",
      className: "string",
      style: "CSSProperties"
    }
  },

  InputGroup: {
    category: "forms",
    keywords: ["input", "group", "addon", "prefix", "suffix"],
    description: "Groups inputs with addons, buttons, or icons",
    props: {
      children: "ReactNode",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      disabled: "boolean",
      error: "boolean",
      compact: "boolean",
      orientation: "'horizontal' | 'vertical'",
      className: "string",
      style: "CSSProperties"
    }
  },

  InputAddon: {
    category: "forms",
    keywords: ["addon", "input", "prefix", "suffix", "attachment"],
    description: "Addon element for input groups",
    props: {
      children: "ReactNode",
      position: "'left' | 'right'",
      type: "'text' | 'icon' | 'button' | 'select'",
      disabled: "boolean",
      onClick: "() => void",
      className: "string",
      style: "CSSProperties"
    }
  },

  InputMask: {
    category: "forms",
    keywords: ["mask", "input", "format", "pattern", "masked"],
    description: "Input with customizable mask patterns",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      mask: "string | (string | RegExp)[]",
      maskChar: "string",
      alwaysShowMask: "boolean",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      formatChars: "Record<string, string>",
      beforeMaskedValueChange: "(newState: object, oldState: object, userInput: string) => object",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: string) => void",
      onComplete: "(value: string) => void"
    }
  },

  CurrencyInput: {
    category: "forms",
    keywords: ["currency", "money", "dollar", "price", "amount", "financial"],
    description: "Currency input with formatting and symbol support",
    props: {
      label: "string",
      placeholder: "string",
      value: "number | string",
      defaultValue: "number | string",
      currency: "string",
      locale: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      min: "number",
      max: "number",
      precision: "number",
      allowNegative: "boolean",
      showCurrencySymbol: "boolean",
      symbolPosition: "'prefix' | 'suffix'",
      thousandSeparator: "string",
      decimalSeparator: "string",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: number) => void",
      onValueChange: "(values: { floatValue: number; formattedValue: string; value: string }) => void"
    }
  },

  PercentInput: {
    category: "forms",
    keywords: ["percent", "percentage", "ratio", "proportion"],
    description: "Percentage input with formatting",
    props: {
      label: "string",
      placeholder: "string",
      value: "number",
      defaultValue: "number",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      min: "number",
      max: "number",
      precision: "number",
      allowNegative: "boolean",
      showSymbol: "boolean",
      symbolPosition: "'prefix' | 'suffix'",
      normalizeOnBlur: "boolean",
      clampValueOnBlur: "boolean",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: number) => void"
    }
  },

  TagInput: {
    category: "forms",
    keywords: ["tag", "input", "chips", "tokens", "labels", "keywords"],
    description: "Input for creating and managing tags or chips",
    props: {
      label: "string",
      placeholder: "string",
      value: "string[]",
      defaultValue: "string[]",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      maxTags: "number",
      minTags: "number",
      allowDuplicates: "boolean",
      caseSensitive: "boolean",
      trimValue: "boolean",
      addOnBlur: "boolean",
      addOnPaste: "boolean",
      pasteSeparators: "string[]",
      addKeys: "string[]",
      removeKeys: "string[]",
      suggestions: "string[]",
      validateTag: "(tag: string) => boolean | string",
      tagVariant: "'filled' | 'outlined'",
      tagColor: "string",
      tagSize: "'sm' | 'md'",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(tags: string[]) => void",
      onAdd: "(tag: string) => void",
      onRemove: "(tag: string, index: number) => void"
    }
  },

  MentionInput: {
    category: "forms",
    keywords: ["mention", "at", "user", "reference", "tag", "autocomplete"],
    description: "Text input with @mention support and user suggestions",
    props: {
      label: "string",
      placeholder: "string",
      value: "string",
      defaultValue: "string",
      required: "boolean",
      disabled: "boolean",
      readOnly: "boolean",
      error: "string",
      helperText: "string",
      trigger: "string | string[]",
      suggestions: "{ id: string; display: string; avatar?: string }[]",
      mentionStyle: "CSSProperties",
      highlightClassName: "string",
      allowSpaceInQuery: "boolean",
      multiline: "boolean",
      rows: "number",
      maxLength: "number",
      loading: "boolean",
      notFoundContent: "ReactNode",
      placement: "'top' | 'bottom'",
      size: "'sm' | 'md' | 'lg'",
      variant: "'outlined' | 'filled' | 'underlined'",
      onChange: "(value: string) => void",
      onSearch: "(query: string, trigger: string) => void",
      onSelect: "(suggestion: object, trigger: string) => void",
      renderSuggestion: "(suggestion: object) => ReactNode"
    }
  },

  EmojiPicker: {
    category: "forms",
    keywords: ["emoji", "picker", "emoticon", "smiley", "icon", "expression"],
    description: "Emoji picker for selecting and inserting emojis",
    props: {
      value: "string",
      onSelect: "(emoji: object) => void",
      disabled: "boolean",
      showPreview: "boolean",
      showSearch: "boolean",
      searchPlaceholder: "string",
      showCategories: "boolean",
      categories: "string[]",
      includeRecent: "boolean",
      maxRecent: "number",
      skinTone: "1 | 2 | 3 | 4 | 5 | 6",
      showSkinTones: "boolean",
      emojiSize: "number",
      perLine: "number",
      maxHeight: "number | string",
      theme: "'light' | 'dark' | 'auto'",
      locale: "string",
      native: "boolean",
      set: "'apple' | 'google' | 'twitter' | 'facebook'",
      custom: "{ id: string; name: string; emojis: object[] }[]",
      exclude: "string[]",
      trigger: "ReactNode",
      placement: "'top' | 'bottom' | 'left' | 'right'",
      onOpen: "() => void",
      onClose: "() => void"
    }
  }
};
